### ISSUE TITLE
Image handling and file handling 

### ISSUE THREAD

**Issue by vrjgamer** [firebase/FirebaseUI-Android#100]
I would be great to have a image and file handling methods in firebaseUI for convertion of Actual image or file to BASE64 String and back , with faster and better UI in case the listview or recyclerview has images or file handling.

**Comment by puf** [comment]
The Firebase Database is a JSON database. While you can BASE64 encode images and store them in the database, it is not well-suited for this. Until Firebase adds native support for storing images and other file types, it makes little sense to add it to FirebaseUI.

**Comment by sivi29y** [comment]
why is it not recommended to use base64 on such database?

**Comment by abehaskins** [comment]
Well we designed Firebase for small, quickly changing data. Having 10mb strings in there just doesn't fit into this model and ends up causing a lot of performance issues down the road. 

Sadly, we wont be adding any file handling via base64 into FirebaseUI :(
