### ISSUE TITLE
Document user metadata

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1001]
Once we move to `11.6.0` we get this new class:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUserMetadata

This should help people with the formerly common question of distinguishing between new and returning users.

**Comment by samtstern** [comment]
Huh apparently you can also tell if a user is know from the metadata returned with an auth result:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/AdditionalUserInfo

**Comment by SUPERCILEX** [comment]
Hmmm, however it looks like it's per provider instead of per `FirebaseUser`. You're the Googler though, I'm only guessing in the dark! 😆

**Comment by samtstern** [comment]
This is fixed in version `3.1.1`.
