### ISSUE TITLE
Can i intergrate FirebaseUI - FirebaseListViewAdapter with Material Search Bar ?

### ISSUE THREAD

**Issue by edenleeee** [firebase/FirebaseUI-Android#1003]
* Android device: Redmi Note 4
  * Android OS version: 7.0
  * Google Play Services version: 11.4.2
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.1.0
  
Describe the problem:

How can i use MaterialSearchBar (https://github.com/mancj/MaterialSearchBar) to search for user or other things on Firebase Realtime Database ?

I have thought about using Firebase UI for Android to get Firebase ListView Adapter then BindViewHolder with ListView of Search Bar . Is it possible to do this way ?

Thank you

**Comment by SUPERCILEX** [comment]
This question should probably be posted on SO, but I'll give you a short answer here.

I've briefly looked at MSB's source code and it looks like they require you to extend their custom adapter. So basically, you can't use any of the Firebase adapters. Either way, I don't think search suggestion content needs to be realtime! 😆 Instead, just add a text watcher with some sort of time filter so you don't get too many events and queue up a query for each event. Then, just use MSB's `setSuggestions` with whatever the result of your query is.

**Comment by samtstern** [comment]
Thanks @SUPERCILEX for giving it a stab and yes @edenleeee this sort of thing should be posted on StackOverflow, so I'm going to close this issue.

We try to reserve github issues for potential library bugs or feature requests!
