### ISSUE TITLE
[Refactor] Move to GoogleSignInClient and CredentialsClient, remove GoogleApiClient

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1007]
These are new in `11.6.0`:
https://developers.google.com/android/reference/com/google/android/gms/auth/api/credentials/CredentialsClient
https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInClient

Moving to use these classes will allow better chaining (through `Task`) remove any `GoogleApiClient` helper classes and probably make things a lot simpler.

It's also worth nothing the one issue in the release:
"GoogleApi instances created with a Context in apps with targetSdkVersion 26 won't automatically prompt users to update Google Play services. Consider using GoogleApiAvailability.showErrorDialogFragment() under these conditions instead."

So we should make sure we have play services before starting the flow.  Not sure if we do that already.

**Comment by samtstern** [comment]
(this is the beginning of breaking #962 up into issues which we can tackle one at a time)

**Comment by samtstern** [comment]
@SUPERCILEX I'd like to take a crack at this but not sure how badly that would mess you up.

**Comment by SUPERCILEX** [comment]
@samtstern I was actually planning to already start that refactor after the cleanup PRs are merged. Since it looks like that might happen tomorrow, we could already get that going by Friday. I think if it doesn't happen over the weekend at the latest, then yeah, you could start doing it. (Though it definitely will destroy my stuff since I deleted all the original Smart Lock files. 😄)

**Comment by samtstern** [comment]
I don't want to do that, although I would like to find ways to contribute to this rewrite besides reviewing PRs.  This is one topic I understand particularly well, but maybe it's not the right place.

The breaking down of the rewrite is going well so far but it still kind of all has the shadow of the big rewrite PR hanging over it.  I wonder if we could break some of the tasks down into issues, agree on the APIs (even internal APIs) and then share the authoring load.

**Comment by SUPERCILEX** [comment]
@samtstern Yeah, I totally agree with you, it would be awesome to work together on this and improve on my original ideas. 😄 Once that last refactor PR goes through, I was planning on opening a small and basic setup PR and use it in a PR refactoring the password reset activity with our new architecture. The plan was to use the password reset PR to dip our feet in the water and let me show you how I had done the other refactors.

Do you think I should follow through with that plan and then start opening a bunch of issues once you've seen the refactor style, or do you want to open the issues first and then do a "dip your feet in the water" PR?

**Comment by samtstern** [comment]
@SUPERCILEX that sounds good, password is a pretty simple flow and will be a good demonstration.

**Comment by SUPERCILEX** [comment]
@samtstern Sweet! See #1048

**Comment by samtstern** [comment]
This was done in `3.2.0`
