### ISSUE TITLE
Ensure explicit check for Play Services availability

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1012]
Since we have moved (in `3.1.1-dev`) the play services dep to `11.6.0` we now need to deal with the one issue in the release notes for that version:

> "GoogleApi instances created with a Context in apps with targetSdkVersion 26 won't automatically prompt users to update Google Play services. Consider using GoogleApiAvailability.showErrorDialogFragment() under these conditions instead."

**Comment by SUPERCILEX** [comment]
Yep, but we've been doing that for a while (and I don't plan on removing it until that bug is fixed):
https://github.com/firebase/FirebaseUI-Android/blob/ba9167d80e5c749ac84782d395770c00faf59e1e/auth/src/main/java/com/firebase/ui/auth/KickoffActivity.java#L41-L57

**Comment by samtstern** [comment]
Ok great, I honestly was just too lazy to find out if we had already been doing that.  Thanks for checking!

**Comment by SUPERCILEX** [comment]
Haha, NP! 😄
