### ISSUE TITLE
how to display login elements without using ShowFirebaseLoginDialog 

### ISSUE THREAD

**Issue by ankitrampal** [firebase/FirebaseUI-Android#102]
How to display these Login options on the activity instead of opening a Dialog?

**Comment by fanky10** [comment]
+1 to this, I'm working on a public fragment to include the stuff

**Comment by arandilopez** [comment]
👍  I prefer a Login View rather than popups

**Comment by shrenuj** [comment]
This would save sooo much time!

**Comment by samtstern** [comment]
This references the old FirebaseUI Auth implementation, closing the issue as it's not relevant to the new code.
