### ISSUE TITLE
Add support for Hosted Domain on Google auth

### ISSUE THREAD

**Issue by guillermo-varela** [firebase/FirebaseUI-Android#1021]
Hi,

I'd like to request a new feature to support the "Hosted Domain" configuration when using the Google auth provider.

This could be useful when developing apps for companies using a Google Apps account and want that only its employees to be able to authenticate.

#### Relevant Code:
Checking the current code, I see that the class GoogleSignInOptions.Builder already has a method [setHostedDomain](https://developers.google.com/android/reference/com/google/android/gms/auth/api/signin/GoogleSignInOptions.Builder.html#setHostedDomain(java.lang.String))

And the GoogleSignInOptions is being built on [GoogleProvider.getSignInOptions()](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/provider/GoogleProvider.java#L76)

  ```
GoogleSignInOptions.Builder builder =
                new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                        .requestEmail()
                        .requestIdToken(clientId);
  ```

My suggestion is quite simple:
Just add a new param on the AuthUI.IdpConfig instance when setting the auth providers on the client app side:

  ```
Bundle params = Bundle();
params.putString(AuthUI.EXTRA_HOSTED_DOMAIN, "company.com")

AuthUI.getInstance()
        .createSignInIntentBuilder()
        .setAvailableProviders(Arrays.asList(AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER)
                .setParams(params)
                .build()))
        .build()
  ```

This way, on the Firebase-UI-Android code the param can be checked and used when building the GoogleSignInOptions.
  ```
private GoogleSignInOptions getSignInOptions(@Nullable String email) {
    String clientId = mActivity.getString(R.string.default_web_client_id);

    GoogleSignInOptions.Builder builder =
            new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                    .requestEmail()
                    .requestIdToken(clientId);

    // Add additional scopes
    for (String scopeString : mIdpConfig.getScopes()) {
        builder.requestScopes(new Scope(scopeString));
    }

    if (!TextUtils.isEmpty(email)) {
        builder.setAccountName(email);
    }
    
    // New code here
    if (mIdpConfig.getParams() != null && mIdpConfig.getParams().containsKey(AuthUI.EXTRA_HOSTED_DOMAIN)) {
        builder.setHostedDomain(mIdpConfig.getParams().getString(AuthUI.EXTRA_HOSTED_DOMAIN));
    }

    return builder.build();
}
  ```

Thanks.

**Comment by samtstern** [comment]
Now tracking this in #1022, thanks for the idea!
