### ISSUE TITLE
Allow passing full GoogleSignInOptions to auth

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1022]
Requested in #757 and #1021 

Would allow more flexibility than just scopes.

**Comment by samtstern** [comment]
Also related to #806

**Comment by guillermo-varela** [comment]
Hi,

Are you guys working on this or do you need a PR?

Thanks.

**Comment by samtstern** [comment]
@guillermo-varela we have not yet started working on this.  If you plan to submit a PR (which would be really cool!) could you show the proposed API here first?  As this would change the public API it needs a little more discussion than your average PR.

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.0`.
