### ISSUE TITLE
How to using firebaseArray ?

### ISSUE THREAD

**Issue by ghost** [firebase/FirebaseUI-Android#1031]
I am trying to using firebaseArray 

`FirebaseArray<test1> firebaseArray = new FirebaseArray<test1>(query,test1.class);`
But ` firebaseArray.size()`  is always 0.

**Comment by samtstern** [comment]
@ghost sorry that nobody every got back to you here!  Hopefully you figured this out in the last few years ... I am going to close this issue since it's very old but please feel free to open a new one if you have new questions.
