### ISSUE TITLE
Add AuthUI method to perform silent Smart Lock sign-in

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#1039]
This should be a piece of cake with the new GPS APIs. (Is there a better acronym than GPS? 😄)

### Background
The beauty of Google Smart Lock is that it's able to magically sign users in when the app starts. Currently, FirebaseUI requires a full blown activity and loading UI to do anything with Smart Lock.

### Proposal
We should provide a task based method in `AuthUI` (or another class?) to sign the user in if they have saved credentials. This would work really nicely with Instant Apps where you're supposed to do the magic sign-in stuff.

### Problems
What to do with IDP providers or phone auth? It wouldn't be good UX to randomly start activities... so I guess we're stuck with email auth?

@samtstern What do you think?

**Comment by samtstern** [comment]
Do you mean something that we'd expose in the 3P API or just a refactoring of our smartlock flow?

**Comment by SUPERCILEX** [comment]
Probably a dumb question: what does `3P` mean?

I was thinking of adding a completely new flow that's designed to be started automatically (without user input). Our current flow is based off of the assumption that the user started the request (or at least they see some sort of UI indicating a sign-in is happening). The point was basically to enable the seamless Smart Lock blue banner at the bottom without the user having to initiate a sign-in request. Does that make sense?

**Comment by samtstern** [comment]
3P == Third Party aka Public.  Sorry for the jargon.

Yes that does make sense, however it kind of strays from the core point of the library which is "make Firebase Auth easy" to "make SmartLock easy".  So I'd want to talk to some folks before jumping into this.

**Comment by SUPERCILEX** [comment]
Oh, K. No problemo.

Yeah, I do see your point. That method would of course include using Firebase Auth stuff since it has to do email sign-in, but yeah, that decision is up to you. 😄

**Comment by samtstern** [comment]
This has been fixed and released in `4.0.0`
