### ISSUE TITLE
Conflict with Google Play Services 11.6.2

### ISSUE THREAD

**Issue by bpappin** [firebase/FirebaseUI-Android#1042]
Conflict with Google Play Services 11.6.2

It might be a little easier for us to keep up to date using something like gitflow.
We could then automate the building of the develop branch while waiting for the library to catch up.

**Comment by ShaldonSwiidAppDesigns** [comment]
I am having an issue now with this. My project gives me a "Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex"

issue when I add 'com.firebaseui:firebase-ui-auth:3.1.0' to my build,gradle file

**Comment by bpappin** [comment]
@ShaldonSwiidAppDesigns I temporarily solved it be excluding the dependency. Its seems to be working without errors, but obviously use at your own risk.

```gradle
api('com.firebaseui:firebase-ui:3.1.0', {
        exclude group: 'com.google.android.gms', module: 'play-services'
    })
```

**Comment by samtstern** [comment]
@bpappin can you show your whole `build.gradle` file?

**Comment by ShaldonSwiidAppDesigns** [comment]
@bpappin Thank you for this temp work around, I temporarily dropped the GMS and the Firebase versions from 11.6.2 to 11.4.2 for now and it compiled fine without the error. However I would desperately like this issue to be fixed though.

**Comment by samtstern** [comment]
@ShaldonSwiidAppDesigns if you could show me your full `app/build.gradle` file to reproduce the issue that would be very helpful.

**Comment by bpappin** [comment]
@samtstern just set up a new dummy project, and include these dependencies:

```gradle
    api 'com.google.firebase:firebase-auth:11.6.2'
    api 'com.google.firebase:firebase-firestore:11.6.2'
    api 'com.google.firebase:firebase-core:11.6.2'
    api 'com.google.firebase:firebase-messaging:11.6.2'
    api 'com.google.android.gms:play-services:11.6.2'
    api 'com.firebaseui:firebase-ui:3.1.0'
```

I dont remember the exact version, but `firebase-ui` tries to import `com.google.android.gms:play-services:11.4.?` which Android Studio complains about.

The temporary fix I mentioned above work because it drops the dependency from `firebase-ui`, and uses the explicit version.

**Comment by bpappin** [comment]
@ShaldonSwiidAppDesigns yeah, I agree, I maintain my build at the latest version *always* to reduce maintenance overhead. I want to know early if I have a problem, and make sure the build fails fast.

**Comment by samtstern** [comment]
@bpappin there are a few notable things here:

1) You should *never* use this line:

```
api 'com.google.android.gms:play-services:11.6.2'
``

That brings in every single play services dependency into your app!  That's everything in [this table](https://developers.google.com/android/guides/setup) plus even more that aren't listed there.  You should always reference the specific libraries you need like `play-services-auth`, etc.

2) You probably don't want `api 'com.firebaseui:firebase-ui:3.1.0'`.  That's similar to the play services line above.  Instead you want to specifically use `firebase-ui-database`, `firebase-ui-firestore`, etc.  Of course it's possible you're using FirebaseUI for Auth, RTDB, Firestore, and Storage in your app so maybe this is intentional.

3) You have to be careful with play services and FirebaseUI as described by this section of the README:
https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries

So I would actually not expect your `build.gradle` to work.  If you want to use FirebaseUI `3.1.0` with play services `11.6.2` you will need at least the following:

```groovy
    // Required by firebase-ui-auth
    api 'com.google.firebase:firebase-auth:11.6.2'
    api 'com.google.firebase:play-services-auth:11.6.2'

    // Required by firebase-ui-database
    api 'com.google.firebase:firebase-database:11.6.2'
 
    // Required by firebase-ui-firestore
    api 'com.google.firebase:firebase-firestore:11.6.2'

    // Required by firebase-ui-storage
    api 'com.google.firebase:firebase-storage:11.6.2'

    api 'com.firebaseui:firebase-ui:3.1.0'
```

**Comment by ShaldonSwiidAppDesigns** [comment]
`apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "swiidappdesigns.haveasafetrip"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        multiDexEnabled true
        resConfigs "auto"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.google.android.gms:play-services-maps:11.6.2'
    implementation 'com.google.android.gms:play-services-places:11.6.2'
    implementation 'com.google.android.gms:play-services-location:11.6.2'
    implementation 'com.google.firebase:firebase-database:11.6.2'
    implementation 'com.google.firebase:firebase-auth:11.6.2'
    compile 'com.firebaseui:firebase-ui-auth:3.1.0'
    compile('com.facebook.android:facebook-android-sdk:4.27.0')
    compile("com.twitter.sdk.android:twitter-core:3.0.0@aar") { transitive = true }
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

}
apply plugin: 'com.google.gms.google-services'`

This throws Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

**Comment by samtstern** [comment]
@ShaldonSwiidAppDesigns as mentioned here:
https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries

Your issue will probably be resolved if you add:

```
implementation 'com.google.android.gms:play-services-auth:11.6.2'
```

**Comment by ShaldonSwiidAppDesigns** [comment]
@samtstern Perfect, that worked! Thank you so much for the help.

**Comment by samtstern** [comment]
Closing this issue as I believe everything is still working as expected.  @bpappin please chime in if things don't work for you.

**Comment by bpappin** [comment]
@samtstern  ok, global import aside, I actually do want `api` because of how my project is broken up into independent modules, and the dependencies are needed to support code across those modules. This is a little bit of a mess due to the recent change in how deps work, but like everything else, figuring it out, restructuring the project, and fixing it is going to have to wait, as its a non-breaking change. So, for the moment, in that case, `api`is what its going to remain.

However, your good advice aside, the problem is still that `firebase-ui` requiring a version of `play-services` that is out of date. The simplest solution is to keep it up to date.
Are you suggesting that parts of `firebase-ui` are up to date, and others are not?

@ShaldonSwiidAppDesigns note that `compile` is going to have a similar result as `api`, with `compile` being the legacy term.

**Comment by samtstern** [comment]
@bpappin I was not referring to `api`, you can use that as needed.  I was referring to the use of the global `play-services` rather than `play-services-{foo}`.  Same with `firebase-ui` and not `firebase-ui-{foo}`.

All parts of FirebaseUI are compiled against the same versions of Firebase / Play services.  We do not release new versions of FirebaseUI every time a new version of those dependencies comes out unless we have a reason to upgrade.

That's why we provide the instructions on how to make FirebaseUI work with newer versions, as I explained above.
