### ISSUE TITLE
Authorisation UI interface depends on the mobile phone language

### ISSUE THREAD

**Issue by NeringaB** [firebase/FirebaseUI-Android#1051]
Hello. I would like to inquire if it is possible to set a language of authentication UI? We are going to release our app in various countries, however, for now, our app is supposed to be only in English as it is international language. However, Firebase authentication UI adapts to the language of the user mobile phone, and if that language is not English, then the app is in two different languages. Is it possible to set Firebase authentication UI to English so that the text on the buttons would be in English as well as the dialog after clicking a button?
I will be looking forward for your answer. 
Thank you :)

**Comment by samtstern** [comment]
@NeringaB you can change your `build.gradle` to drop all non-English resources from your build, which will achieve what you want:

``` groovy
defaultConfig {
    // ...

    // Only English resources
    resConfigs "en"
}
```

**Comment by NeringaB** [comment]
Thank you for your answer :) I added this to my code, the text on buttons in the Firebase UI changed to English and when I click on "Sign in with Google", it is written "Loading" in English, however, when the dialog to choose Google account is showed everything is written in the language of the user mobile phone. Is it possible to change this dialog to English, too?

**Comment by samtstern** [comment]
@NeringaB that's not possible as far as I know, and it's outside of FirebaseUI.  That comes from the Google Sign In SDK.  Sorry!

**Comment by NeringaB** [comment]
Okay. Thank you for information :)
