### ISSUE TITLE
Problem in deleting items from database

### ISSUE THREAD

**Issue by RedLann** [firebase/FirebaseUI-Android#1053]
* Android device: Nexus 6P
  * Android OS version: 8.0
  * Google Play Services version: 3.1.0
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.1.0

Hello i have a problem while deleting items from FirebaseDatabase, in my app i have this situation:
Activity with 3 static fragments in a view, those fragments use the FirebaseRecyclerAdapter to list 3 different kind of objects in the db (3 different places).
When i receive the click on one item the app opens another fragment (visibility gone to the 3 static fragments) then i can use this new fragment to delete this item from the db, i delete it with removevalue on its ref and popbackstack then set visibility visible on the 3 static fragments. At this point the item is correctly removed from the database.

The unexpected problem i have is that after i do another replace (showing a fragment that doesn't touch the database at all) and pop the backstack to return to the 3 static fragments, the item which was deleted will be re-added to it. I even tried stopping the adapter from listening when i open the other fragment (the one for deleting) and starting it again when i popbackstack but still nothing.

I'm not sure why and would like to know if it could be the adapter's behaviour that is adding the items again.

**UPDATE** i noticed that if i wait for a while before opening another fragment there is no problem

**Comment by samtstern** [comment]
@RedLann this sounds like it's a complex question and has to do with your Fragment hierarchy.  I would suggest asking this on StackOverflow, as this issue tracker is meant for reports of bugs in the FirebaseUI libraries.

**Comment by RedLann** [comment]
Ok, i asked here because the fragments i have the adapter attached to are static and aren't subject to any state change (onPause, onStop ... etc) and i delete the items from outside the adapter, so i was guessing it was some sort of issue with the adapter not removing the object. I guess i will try on StackOverflow, thanks.

**Comment by samtstern** [comment]
@RedLann if you asked this on StackOverflow, feel free to post the link here and I'll take a look.  Gonna close it on this side though.

**Comment by RedLann** [comment]
After some investigation (until a week ago) i noticed that my problem was the name of the method saving the objects, i named the method "finalize" which was called instead of the finalize method in Object (called on object Garbage Collected) so every time the fragment was being collected it would call the finalize() method that saved my items.
