### ISSUE TITLE
Using custom layouts with FirebaseRecyclerAdapter returning error

### ISSUE THREAD

**Issue by jangerhard** [firebase/FirebaseUI-Android#106]
When I try to set a new adapter using a custom layout, I get this error: 

java.lang.RuntimeException: java.lang.NoSuchMethodException: <init> [class android.view.View]

There is a connection to the Firebase server, and I have successfully gotten other information from the server. I'm not sure if parsing the information to the custom class is the problem, but all fields are identical. 

![code1](https://cloud.githubusercontent.com/assets/6482205/14726428/36324d4c-07f0-11e6-8286-c0f22305e19e.PNG)
![error1](https://cloud.githubusercontent.com/assets/6482205/14726427/362fc5f4-07f0-11e6-809c-ba904e13fdb0.PNG)

**Comment by puf** [comment]
This means that the adapter is unable to instantiate your TutorViewHolder
class.

Most likely you've made it an inner class of your activity, in which case
you need to mark the class as static:

     `public static class TutorViewHolder`

**Comment by jangerhard** [comment]
I don't get the error anymore! Closing the issue.
