### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by navaneethsaj** [firebase/FirebaseUI-Android#1066]
Information:Gradle tasks [:app:generateDebugSources, :app:generateDebugAndroidTestSources, :app:mockableAndroidJar]
C:\Users\ASUS\.gradle\caches\transforms-1\files-1.1\design-27.0.2.aar\dc07802960ab4ff2cff138f788bb7a6e\res\values-v26\values-v26.xml
Error:(3, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\ASUS\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\6698c705a9379da4f31c22ac03fee569\res\values-v26\values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
C:\Users\ASUS\.gradle\caches\transforms-1\files-1.1\firebase-ui-auth-3.1.2.aar\df78ee7eff49cfd4d3d123973a306171\res\values-v26\values-v26.xml
Error:(7, 5) error: style attribute 'android:attr/autofillHints' not found.
Error:(11, 5) error: style attribute 'android:attr/autofillHints' not found.
Error:(15, 5) error: style attribute 'android:attr/autofillHints' not found.
C:\Users\ASUS\.gradle\caches\transforms-1\files-1.1\appcompat-v7-27.0.2.aar\6698c705a9379da4f31c22ac03fee569\res\values\values.xml
Error:(252, 5) error: resource android:attr/keyboardNavigationCluster not found.
Error:(252, 5) error: resource android:attr/fontStyle not found.
Error:(252, 5) error: resource android:attr/font not found.
Error:(252, 5) error: resource android:attr/fontWeight not found.
E:\MyApps\and-nd-firebase-1.00-starting-point\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values-v26\values-v26.xml
Error:(36) error: style attribute 'android:attr/autofillHints' not found.
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:(18) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:(24) style attribute 'android:attr/autofillHints' not found.
Error:(28) style attribute 'android:attr/autofillHints' not found.
Error:(32) style attribute 'android:attr/autofillHints' not found.
Error:(36) style attribute 'android:attr/autofillHints' not found.
E:\MyApps\and-nd-firebase-1.00-starting-point\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml
Error:(250) resource android:attr/keyboardNavigationCluster not found.
Error:(468) resource android:attr/fontStyle not found.
Error:(468) resource android:attr/font not found.
Error:(468) resource android:attr/fontWeight not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt
Information:BUILD FAILED in 10s
Information:29 errors
Information:0 warnings
Information:See complete output in console

**Comment by samtstern** [comment]
@navaneethsaj there is not enough information here to help you so I am going to close this issue.  Please follow the issue template when filing new issues.

If you're stuck and this is all you have, I suggest going to StackOverflow.

**Comment by sameersohi** [comment]
@samedson I am getting the same issue.
/Users/sameersohi/.gradle/caches/transforms-1/files-1.1/design-27.0.2.aar/b392834f3327d2110d02dd61b8528c1b/res/values-v26/values-v26.xml
Error:(3, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/Users/sameersohi/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/0d70f8b052e7195660b65f59739d898f/res/values-v26/values-v26.xml
Error:(9, 5) error: resource android:attr/colorError not found.
Error:(13, 5) error: resource android:attr/colorError not found.
Error:(17, 5) error: style attribute 'android:attr/keyboardNavigationCluster' not found.
/Users/sameersohi/.gradle/caches/transforms-1/files-1.1/firebase-ui-auth-3.2.2.aar/6cd16c208592046c2634e92f2243995a/res/values-v26/values-v26.xml
Error:(7, 5) error: style attribute 'android:attr/autofillHints' not found.
Error:(11, 5) error: style attribute 'android:attr/autofillHints' not found.
Error:(15, 5) error: style attribute 'android:attr/autofillHints' not found.
/Users/sameersohi/.gradle/caches/transforms-1/files-1.1/appcompat-v7-27.0.2.aar/0d70f8b052e7195660b65f59739d898f/res/values/values.xml
Error:(252, 5) error: resource android:attr/keyboardNavigationCluster not found.
Error:(252, 5) error: resource android:attr/fontStyle not found.
Error:(252, 5) error: resource android:attr/font not found.
Error:(252, 5) error: resource android:attr/fontWeight not found.
/Users/sameersohi/AndroidStudioProjects/and-nd-firebase/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values-v26/values-v26.xml
Error:(36) error: style attribute 'android:attr/autofillHints' not found.
Error:(7) resource android:attr/colorError not found.
Error:(11) resource android:attr/colorError not found.
Error:(15) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:(18) style attribute 'android:attr/keyboardNavigationCluster' not found.
Error:(24) style attribute 'android:attr/autofillHints' not found.
Error:(28) style attribute 'android:attr/autofillHints' not found.
Error:(32) style attribute 'android:attr/autofillHints' not found.
Error:(36) style attribute 'android:attr/autofillHints' not found.
/Users/sameersohi/AndroidStudioProjects/and-nd-firebase/app/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml
Error:(250) resource android:attr/keyboardNavigationCluster not found.
Error:(468) resource android:attr/fontStyle not found.
Error:(468) resource android:attr/font not found.
Error:(468) resource android:attr/fontWeight not found.
Error:failed linking references.
Error:java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details
Error:Execution failed for task ':app:processDebugResources'.
> Failed to execute aapt



Here is my build.gradle
apply plugin: 'com.android.application'

repositories {
    mavenLocal()
    flatDir {
        dirs 'libs'
    }
}

android {
    compileSdkVersion 25
    buildToolsVersion '26.0.2'

    defaultConfig {
        
        minSdkVersion 16
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        //resConfigs "auto"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE-FIREBASE.txt'
        exclude 'META-INF/NOTICE'
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support:appcompat-v7:25.3.1'
    // Displaying images
    compile 'com.github.bumptech.glide:glide:3.6.1'
    //Firebase core binaries
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.google.firebase:firebase-database:11.8.0'
    compile 'com.google.firebase:firebase-auth:11.8.0'

    compile 'com.firebaseui:firebase-ui-auth:3.2.2'
}

apply plugin: 'com.google.gms.google-services'


I was trying Firebase UI. With the same gradle i was able to integrate with the Database and store the message but I was not able to integrate the UI. I am not lokking forward to migrate to the OREO SDK version and some posts point upgrading the SDK to 26 to fix this issue. Let me know incase you need more details. I would keep on investigating and if I find any solution I would post it here again
