### ISSUE TITLE
StaggeredGridLayoutManager doesn't work

### ISSUE THREAD

**Issue by tarlanahad** [firebase/FirebaseUI-Android#1069]
There are very big gaps between rows.

You get more detailed information from my question in StackOverflow

[Question](https://stackoverflow.com/questions/47928660/firebase-recyclerview-with-staggeredgridlayoutmanager)

**Comment by samtstern** [comment]
@tarlanahad please do not double post, this is unlikely to be a library issue so leaving it for StackOverflow.
