### ISSUE TITLE
FirebaseRecyclerAdapter not calling onbindViewholder

### ISSUE THREAD

**Issue by kenshin171** [firebase/FirebaseUI-Android#107]
I noticed that quite consistently on first launch of an activity with a RecyclerView backed by a firebaseRecyclerViewAdapter implementation, notifyItemInserted(index) will quite consistently not trigger onBindViewholder to be called and thus not drawing the list items onto the recyclerView. A subsequent entry into the same activity usually fixes the issue.

I am able to reproduce the issue when i exit my app and swipe it away from the recent apps pane and then start the app again, the issue will occur. I discovered that onBindViewHolder was not being called after FirebaseArray.OnChangedListener is called after detecting snapshot change and calling notifyItemInserted(index);

I used the firebaseRecyclerViewAdapter source and inputted some log statements to discover this.

Firebase these configs set in application class
``
Firebase.setAndroidContext(this);
Firebase.getDefaultConfig().setPersistenceEnabled(true); 
``

firebase ref has keep synced set to true
``         
ref.keepSynced(true);
``

Tested on android 6.0.1 and 4.3 
Using Support Library 23.3.0

**Comment by kr05** [comment]
I actually have this exact problem. RecyclerView won't appear on first opening, but will display if I close and reopen app. Has anyone found any workarounds?

**Comment by jaychang0917** [comment]
I also have this issue. In my case, the data only binds to the recylerview only when a soft keyboard shows up.

**Comment by kenshin171** [comment]
is there any updates from the firebase UI team n this issue?

**Comment by kenshin171** [comment]
i may have identified the culprit. My recyclerView had a height of wrap_content which was causing onbindviewholder to not be called ofttenly. Changing it to match_parent solved the problem for me so far.

**Comment by puf** [comment]
Good news Kenneth. I've been unable to reproduce it, but my list/recycler
views are indeed set to match_parent.

**Comment by samtstern** [comment]
@kenshin171 it looks like you have worked this out.  I am going to close this issue.  If anyone else runs into it I will re-open.

**Comment by Ispoock** [comment]
@kr05 I'm with the same problem, did you solve it?

**Comment by goyal9314** [comment]
> 
> 
> i may have identified the culprit. My recyclerView had a height of wrap_content which was causing onbindviewholder to not be called ofttenly. Changing it to match_parent solved the problem for me so far.

this worked for me also

**Comment by Anatolf** [comment]
Work for me:

    @Override
    protected void onStart() {
        super.onStart();
        firebaseRecyclerAdapter.startListening();
    }
