### ISSUE TITLE
IdpToken null after signing in with phone provider

### ISSUE THREAD

**Issue by rulamardawi** [firebase/FirebaseUI-Android#1072]
* Android device: Samsung Note3
  * Android OS version: 5.0
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 1.8.0
  * FirebaseUI version: 3.1.0
  

#### Observed Results:
onActivityResult after signingin
idpResponse.getIdpToken() is null
idpResponse has only the phone number and errorCode -1
all other fields are null
  
#### Relevant Code:
```java
   public void onClick(View v) {
                FirebaseAuth auth = FirebaseAuth.getInstance();
                if (auth.getCurrentUser() != null) {
                    if (BuildConfig.DEBUG) Log.i(TAG, "onClick: already signed in");
                    // already signed in
                } else {
                    // not signed in
                    startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setAvailableProviders(Collections.singletonList(
                                            new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()
                                    ))
                                    .build(),
                            RC_SIGN_IN);
                }
            }
```

```java
   public void onActivityResult(int requestCode, int resultCode, final Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        // digits/Firebase-auth
        if (requestCode == RC_SIGN_IN && resultCode == Activity.RESULT_OK) {
            final IdpResponse idpResponse = IdpResponse.fromResultIntent(data);
            if (idpResponse != null)
                if (BuildConfig.DEBUG) Log.i(TAG, "onActivityResult: idpResponse token = " + idpResponse.getIdpToken());
            return;
        }
```

**Comment by samtstern** [comment]
@rulamardawi this is working as expected, this field contains the token from the identity provider such as the Facebook or Google access token, when available.

There is no such token for Phone Number authentication.

**Comment by parthanjaria** [comment]
For phone-number auth do we ever get any unique token?(we used to get a token when we used Facebook account kit) or it will only return the phone number?

**Comment by samtstern** [comment]
@parthanjaria you can get an ID token for any Firebase Auth user using this method:
https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#getIdToken(boolean)

However it's not the same as a Facebook/Google access token.  It's a JWT you can use to send the user's authentication securely to your own server.  It expires every hour.
