### ISSUE TITLE
FirebaseRecyclerAdapter is not showing results

### ISSUE THREAD

**Issue by kurcano** [firebase/FirebaseUI-Android#1073]
I have tried everything, take a look at this link, i really dont know what is happening, since we now need to use FirebaseRecyclerOptions , i think there is a bug that dont let me see the results !

https://stackoverflow.com/questions/47979018/how-firebaserecycleradapter-knows-what-data-to-query/

**Comment by kurcano** [comment]
https://stackoverflow.com/questions/47979018/how-firebaserecycleradapter-knows-what-data-to-query/47979530?noredirect=1#comment82928112_47979530

**Comment by samtstern** [comment]
@kurcano please do not double post.  This looks like it is best solved on StackOverflow, so closing it here.
