### ISSUE TITLE
Change Signin with email button color

### ISSUE THREAD

**Issue by jauniuse** [firebase/FirebaseUI-Android#1075]
Is it possible to change Signin with email button background color? By default it's a very sharp red.

![image](https://user-images.githubusercontent.com/24221399/34414866-03d7a6f8-ebec-11e7-9855-707f2228be07.png)

I cannot seem to be able to customize it through theme.

**Comment by SUPERCILEX** [comment]
Not officially, but you can override our resources:
```xml
<color name="fui_bgEmail">#D0021B</color>
```

_Friendly warning: we may break you at any time since that's not public API._

**Comment by jauniuse** [comment]
thanks
