### ISSUE TITLE
API Key and Secret Key are too easy to grab

### ISSUE THREAD

**Issue by dscoppelletti** [firebase/FirebaseUI-Android#1084]
I would like to use FirebaseUI to sign-in with different providers, but API Key and Secret Key are too easy to grab if they are stored as string resources.  
Maybe you can use the params Bundle in the `AuthUI.IdpConfig.Builder` for setting API Key and Secret Key for any provider in order to make me free to handle the secret keys in the way I want.

**Comment by samtstern** [comment]
@dscoppelletti are you referring to the keys for Twitter?

**Comment by dscoppelletti** [comment]
Yes, I am developing and App with Twitter integration, but I think the problem is the same with the other providers.

**Comment by samtstern** [comment]
@dscoppelletti none of the other providers require any "secret" keys.

You can see our original discussion of the situation here: https://github.com/firebase/FirebaseUI-Android/issues/269

**Comment by dscoppelletti** [comment]
Sorry, I used only Facebook some years ago and it required the secret key.
Anyway I think that `params` Bundle in `AuthUI.IdpConfig.Builder` is good to set some parameters specific for a provider.

**Comment by samtstern** [comment]
This will be fixed in version `6.2.0` because @lsirac has changed the implementation of Twitter Sign In to use the new Generic IDP functionality.

**Comment by samtstern** [comment]
Version `6.2.0` has been released.
