### ISSUE TITLE
A network error keeps showing lower android versions

### ISSUE THREAD

**Issue by mikekaranja** [firebase/FirebaseUI-Android#1085]
Welcome to FirebaseUI and thanks for submitting an issue!

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: 5.1, 4.4, 4.4.2, 7.0
  * Google Play Services version: 11.6.2
  * Firebase/Play Services SDK version: 11.6.2
  * FirebaseUI version: 3.1.0, 3.1.2
  
### Step 3: Describe the problem:
The phone number auth does not work for some android versions 5.1, 4.4, 4.4.2. It keeps showing users the error message dialog A network error has occurred. I thought it was a one off event but it has occurred on too many phones running those OS versions.

#### Steps to reproduce:
Add these libraries to the project and run as usual.

compile 'com.android.support:appcompat-v7:27.0.2'
compile 'com.android.support:support-v4:27.0.2'
compile 'com.android.support:design:27.0.2'
compile 'com.android.support:customtabs:27.0.2'
compile 'com.android.support:cardview-v7:27.0.2'
compile 'com.android.support:recyclerview-v7:27.0.2'
compile 'com.google.android.gms:play-services-gcm:11.6.2'
compile 'com.google.firebase:firebase-core:11.6.2'
compile 'com.google.firebase:firebase-messaging:11.6.2'
compile 'com.google.firebase:firebase-auth:11.6.2'
compile 'com.firebaseui:firebase-ui-auth:3.1.2'
  
#### Observed Results:

Error message on some of the android OS's i mentioned.
  
#### Expected Results:

To authenticate phone number.
![26638352_791733294346164_72529121_n](https://user-images.githubusercontent.com/12885216/34496731-b98c6498-f00b-11e7-933d-01cb0f8791c8.png)

**Comment by samtstern** [comment]
@mikekaranja apologies for the late response but normally this error just means you actually have an unreliable network connection.  Could you try making a request to Firebase without FirebaseUI and see if you get a different result?

**Comment by lollipierre** [comment]
Hi, we have the same issue. It's been happening for a few days; and happens with or without FirebaseUI

**Comment by samtstern** [comment]
@mikekaranja can you provide logcat output from the device for the ~1m before you see the network error?

**Comment by samtstern** [comment]
Given that @lollipierre says this happens with/without FirebaseUI and we don't have any logs to debug, I am going to close this issue for now.
