### ISSUE TITLE
[STORAGE] Can't get transferred bytes with "getStream" way in FirebaseImageLoader

### ISSUE THREAD

**Issue by wonsuc** [firebase/FirebaseUI-Android#1093]
`Glide` with `FirebaseImageLoader` is really cool.  

However, Firebase never let's me know **downloading progress** if I use the `StorageReference.getStream()` method.

Most people would want to use the downloading progress feature with [Glide](https://github.com/bumptech/glide/issues/232). Our app also needs this feature but there's no way to integrate this feature if I use `FirebaseImageLoader`.  

I tried the code below and I can only know `getTotalByteCount()` but not `getBytesTransferred()`.

    imageRef.getStream().addOnProgressListener(new OnProgressListener<StreamDownloadTask.TaskSnapshot>() {
        @Override
        public void onProgress(StreamDownloadTask.TaskSnapshot taskSnapshot) {
            Log.i(TAG, "onProgress:" +
                    "bytesTransferred:" + taskSnapshot.getBytesTransferred() +
                    "|totalByteCount:" + taskSnapshot.getTotalByteCount());
        }
    });

Please let me know if I'm missing something or if I should use `url` to get **downloading progress** instead of `FirebaseUI`?

**Comment by wonsuc** [comment]
Ok. I confused the proper usage of `getStream()` method at the first time.  
I struggled for a day and resolved with my solution.  
I'm sharing the [gist](https://gist.github.com/wonsuc/7724258a760701eb3622c9afd42db971).  
I have no guarantees with this codes and I'm not sure if it's best way.  

![firebase_ui_progress_bar.gif](https://gist.githubusercontent.com/wonsuc/61de91cf99f16199d7c5cf9f4867ca48/raw/5108e37edd58e13b7a6e9735182e402fb8d95321/firebase_ui_progress_bar.gif)

**Comment by samtstern** [comment]
@wonsuc thanks for following up and sharing your solution, that's awesome! I assume I can close this issue now.

**Comment by lwinmoehaindadada** [comment]
Thanks for sharing
