### ISSUE TITLE
Refactor welcome back password flow use new architecture

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1095]
@SUPERCILEX I am going to take a stab at one of these refactors.

**Comment by samtstern** [comment]
Note that this also means I will be converting `SaveSmartLock` which should be a fun challenge.

**Comment by samtstern** [comment]
This will also encompass #1007

**Comment by SUPERCILEX** [comment]
@samtstern awesome, can't wait to see how you solve this! I'll keep my fork up to date with the new changes so we can pool ideas. 💡

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.0`.
