### ISSUE TITLE
FirebaseAuth.getInstance().getCurrentUser() never return null

### ISSUE THREAD

**Issue by herberthobregon** [firebase/FirebaseUI-Android#1112]
* Android device: Oneplus One, and all phones
  * Android OS version: 5.0 - 8.1
  * Google Play Services version: 11.9.51
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.1.3
  
### Step 3: Describe the problem:

When I start it all goes well but when I signOut with

FirebaseAuth.getInstance ().signOut ();

then I close the app and reopen the application, currentUser is not null
FirebaseAuth.getInstance ().getCurrentUser () == Null --> false

when I would expect that
FirebaseAuth.getInstance ().getCurrentUser () == null --> true

#### Steps to reproduce:

  1. FirebaseAuth.getInstance().signInWithEmailAndPassword(email,pass)
  2. FirebaseAuth.getInstance ().signOut ()
  3. close the app
  4. reopen app
  5. FirebaseAuth.getInstance ().getCurrentUser () == null --> **false**
I would expect that
FirebaseAuth.getInstance ().getCurrentUser () == null --> **true**
  
#### Observed Results:

None
  
#### Expected Results:
I would expect that
FirebaseAuth.getInstance ().getCurrentUser () == null --> true
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by SUPERCILEX** [comment]
`signInWithEmailAndPassword` is an async callback so it finishes _after_ you call `signOut`.

**Comment by dariushm2** [comment]
You should really be calling this too:

```
mGoogleSignInClient.signOut().addOnCompleteListener(this, task -> {
                       // UI update
                    });
```
I believe the documentation is bit misleading about this. I myself spent an hour finding out this piece of information.
