### ISSUE TITLE
"Resend Code" button(turned blue i.e. enabled) in Phone Auth not working in 3.1.3

### ISSUE THREAD

**Issue by kshivang** [firebase/FirebaseUI-Android#1113]
* Android device: MI4W (Problem is common for all devices)
  * Android OS version: 8.1.0
  * Google Play Services version: 3.1.1
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.1.3
  
#### Steps to reproduce:

  1. Integrate signIn via phone authentication
  2. Fill your phone no and continue
  3. If you get OTP within 20 sec no problem but for some reason if you not receive OTP within 20 sec Resend Code button will turn to blue (from grey) but remain still unclickable.

#### Observed Results:

  * After updating from FirebaseUI version from 3.1.2(FirebaseVersion 11.6.2) to 3.1.3(FirebaseVersion 11.8.0), I noticed this error that "Resend Code" button turns blue(i.e. Enabled) but not working. In 3.1.2 on clicking "Resend Code" a dialog opens momentarily with message "OTP sent" and time counter reset  to 20 sec but in version 3.1.3 on clicking "Resend Code" button (enabled) nothing happens.
  
#### Relevant Code:

Code I used to integrate PhoneAuth

  ```
 startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(
                                Collections.singletonList(new AuthUI.IdpConfig
                                        .Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()))
                        .setTheme(R.style.FirebaseUITheme)
                        .build(),
                RC_SIGN_IN);
  ```

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.0`.
