### ISSUE TITLE
High crash rate (NPE) com.firebase.ui.auth.ui.phone.PhoneActivity.dismissLoadingDialog

### ISSUE THREAD

**Issue by RuiVarela** [firebase/FirebaseUI-Android#1127]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment
  * Android device: several
  * Android OS version: 4,5,6,7
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.0
  
### Step 3: Describe the problem:
Hi All,
we have been experiencing an high crash rate for this issue since november,
while connecting with phone (we only use fb for phone) we have erratically this NPE in production

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.p android.support.v4.app.l.a()' on a null object reference
       at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:200)
       at android.support.v4.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:181)
       at com.firebase.ui.auth.ui.phone.PhoneActivity.dismissLoadingDialog(PhoneActivity.java:398)
       at com.firebase.ui.auth.ui.phone.PhoneActivity.access$000(PhoneActivity.java:55)
       at com.firebase.ui.auth.ui.phone.PhoneActivity$4$1.run(PhoneActivity.java:330)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6816)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)
```
we have released a version with the ui locked to portrait to try mitigating this issue, but no luck

here is the more detailed info from crashlitics
http://crashes.to/s/558e77a34fd
any advice, or workaround for this?

**Comment by samtstern** [comment]
@baole thanks for adding your details!  I believe that #1253 will address this indirectly by removing most of the state-based errors from the flow.  We had similar problems with dialog dismissals in the other parts of FirebaseUI and our refactoring has removed them.

**Comment by samtstern** [comment]
This will be fixed by #1253 because we won't have any more progress dialogs at that point.

**Comment by SUPERCILEX** [comment]
@samtstern This can be marked as `fix-implemented`.

**Comment by samtstern** [comment]
This has been released in version `4.1.0`

**Comment by KaluKhan** [comment]
Hi, I am getting a similar crash. The crash occurring on firebase phone auth screen. Though the crash is occurring on a few devices. I am using firebase versions as `firebaseVersion = '16+'` and
    `firebaseUIAuthVersion = '4.0.0' `. Please help me to sort out the crash. Crash log-

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference
>        at android.support.v4.app.DialogFragment.dismissInternal(DialogFragment.java:219)
>        at android.support.v4.app.DialogFragment.dismissAllowingStateLoss(DialogFragment.java:201)
>        at com.firebase.ui.auth.ui.phone.PhoneActivity.dismissLoadingDialog(PhoneActivity.java:405)
>        at com.firebase.ui.auth.ui.phone.PhoneActivity.access$000(PhoneActivity.java:56)
>        at com.firebase.ui.auth.ui.phone.PhoneActivity$1.run(PhoneActivity.java:203)
>        at android.os.Handler.handleCallback(Handler.java:815)
>        at android.os.Handler.dispatchMessage(Handler.java:104)
>        at android.os.Looper.loop(Looper.java:207)
>        at android.app.ActivityThread.main(ActivityThread.java:5765)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by samtstern** [comment]
@KaluKhan as you can see above, you are using `firebaseUIAuthVersion = '4.0.0'` but you need to be using `4.1.0` or greater.
