### ISSUE TITLE
Retrieve phone number

### ISSUE THREAD

**Issue by rroslan** [firebase/FirebaseUI-Android#1128]
How do I retrieve phone number to insert in firebase database during phone authentication. I cannot find the solution in search. I am sorry if this is not the place for question.

**Comment by SUPERCILEX** [comment]
Use `IdpResponse#getPhoneNumber()`

**Comment by rroslan** [comment]
I am sorry, I am new to android.
IdpResponse response = IdpResponse.fromResultIntent(data).getPhoneNumber(); cause error incompatible
type.  Recquired com.firebase.ui.auth.IdpResponse which is already imported.

**Comment by samtstern** [comment]
@rroslan this sounds like something wrong with your personal setup, I suggest posting on StackOverflow.

**Comment by rroslan** [comment]
String user_id = mAuth.getCurrentUser().getPhoneNumber();
                //String user_phone = mAuth.getCurrentUser().getPhoneNumber();
                DatabaseReference current_user_db = FirebaseDatabase.getInstance().getReference().child("Users").child("Customers").child(user_id);
                current_user_db.setValue(FirebaseAuth.getInstance().getCurrentUser().getPhoneNumber()).addOnCompleteListener(new OnCompleteListener<Void>() {
                    @Override
                    public void onComplete(@NonNull Task<Void> task) {
                        Log.d(TAG, "onComplete: " + task.isSuccessful());
                    }
                });
This work

**Comment by bineeshtvr** [comment]
Thanks rroslan, that gave some light.
