### ISSUE TITLE
Alert dialog showing out of focus

### ISSUE THREAD

**Issue by GuanacoDevs** [firebase/FirebaseUI-Android#1133]
Environment:

  * Android device: XZ5P 25 & Emulators
  * Android OS version: 19+
  * Google Play Services version: Any
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.1
  
#### Steps to reproduce:

  1. Add the `implementation 'com.firebaseui:firebase-ui-auth:3.2.1'`
  
#### Observed Results:

I'm Building a Trivia Game in full inmersive mode, after adding FirebaseUI implementation my custom alert dialogs won't show(I believe is displaced out of the screen) in my phisical device XZ5P, and on several emulators will appear displaced to the upper right without focus, although I can see a button the `onClick` won't trigger, since the AlertDialog is `cancelable(false)` the dialog can't get dissmissed. This behaviour is exhibed only when adding the de implementation.
  
#### Expected Results:

Since I thought had nothing to do with FirebaseUI took me some time to undo my changes until I removed the dependency and my app worked as expected. Nothing relevant appears on the LogCat.
  
#### Relevant Code:

This is how I build my Custom Alert Dialogs, (note I'm not using a Custom Class, but a Builder); I'm calling this dialog from within a Fragment, also call another AlertDialog from within the hosting activity via Interfaces with the same result:

```
    private void launchAlertDialog(int assistanceName, int assistanceDescription, final int flagCode) {
        soundEffectsManager.playDialogOpen();
        timedOutFlag = true;
        questionTimer.cancel();
        questionTimer.onFinish();
        timedOutFlag = false;
        View dialogView = View.inflate(getActivity(), R.layout.dialog_custom_messages, null);
        TextView dialogTitle = dialogView.findViewById(R.id.dialog_title);
        TextView dialogMessage = dialogView.findViewById(R.id.dialog_message);
        TextView dialogOkButton = dialogView.findViewById(R.id.dialog_button_ok);
        TextView dialogCancelButton = dialogView.findViewById(R.id.dialog_button_cancel);
        dialogCancelButton.setVisibility(View.GONE);
        dialogTitle.setText(getString(assistanceName));
        dialogMessage.setText(getText(assistanceDescription));
        dialogOkButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                assistanceDialog.dismiss();
            }
        });
        AlertDialog.Builder builder = new AlertDialog.Builder(getActivity(), R.style.DOKMessageDialog);
        builder
                .setCancelable(false)
                .setView(dialogView);
        assistanceDialog = builder.create();
        assistanceDialog.getWindow().setFlags(WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE, WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE);
        assistanceDialog.show();
        assistanceDialog.getWindow().getDecorView().setSystemUiVisibility(getActivity().getWindow().getDecorView().getSystemUiVisibility());
        assistanceDialog.getWindow().clearFlags(WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE);
    }
```
And I call this method in `OnResume()` to set the activity Inmersive Mode:

```
    private void setInmersive() {
//            logBlue(TAG + "Set Inmersive");
        int flags = View.SYSTEM_UI_FLAG_LAYOUT_STABLE
                | View.SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_LAYOUT_FULLSCREEN
                | View.SYSTEM_UI_FLAG_HIDE_NAVIGATION
                | View.SYSTEM_UI_FLAG_FULLSCREEN;
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.KITKAT) {
            flags = flags | View.SYSTEM_UI_FLAG_IMMERSIVE_STICKY;
        }
        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            getWindow().getDecorView().setSystemUiVisibility(flags);
            final View decorView = getWindow().getDecorView();
            final int finalFlags = flags;
            decorView.setOnSystemUiVisibilityChangeListener(new View.OnSystemUiVisibilityChangeListener() {
                @Override
                public void onSystemUiVisibilityChange(int visibility) {
                    if ((visibility & View.SYSTEM_UI_FLAG_FULLSCREEN) == 0) {
                        decorView.setSystemUiVisibility(finalFlags);
                    }
                }
            });
        }
    }
```

**Comment by samtstern** [comment]
@GuanacoDevs apologies for the late response here, can you show a screenshot of this behavior so I can better understand it?

**Comment by GuanacoDevs** [comment]
@samtstern Hi Sam, I have moved on, to keep working on my app removed the dependency. Added it today to take the screenshots only and at the end I'm posting my `build.gradle`.
I have a Xperia XZ5P API25 that shows the same as Nexus 5X API24.
All three are Emulators, first one is the expected behavior, before and after, all of them have the implementation added(working fine on API26):
Galaxy Nexus API26:
Working as expected.
![galaxy nexus api26 before](https://user-images.githubusercontent.com/32036535/35841725-209ab8fc-0ac3-11e8-897e-923ea40f85ff.png)
![galaxy nexus api26 after](https://user-images.githubusercontent.com/32036535/35841726-234d74d6-0ac3-11e8-97d5-afd5746b32f3.png)
Nexus 5X API24:
Dialog not shown, I believe is being drawn off screen.
![nexus 5x api24 before](https://user-images.githubusercontent.com/32036535/35841745-3a3c4b90-0ac3-11e8-9c6a-076300c2c215.png)
![nexus 5x api24 after](https://user-images.githubusercontent.com/32036535/35841748-3ce7f682-0ac3-11e8-8695-204c758d6948.png)
Pixel 2 API19:
Dialog showing half in the right upper corner
![pixel 2 api19 before](https://user-images.githubusercontent.com/32036535/35841760-5030e636-0ac3-11e8-936c-be123bbfa0e7.png)
![pixel 2 api19 after](https://user-images.githubusercontent.com/32036535/35841762-51da49a0-0ac3-11e8-8777-2789867db707.png)






This is my build.gradle(perhaps I messed up?):

```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.guanacodevs.ultimatetriviacontest"
        minSdkVersion 16
        targetSdkVersion 26
        versionCode 30
        versionName "alpha30.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        resConfigs "auto"
        vectorDrawables.useSupportLibrary = true
    }
    buildTypes {
        release {
            shrinkResources false
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:animated-vector-drawable:27.0.2'
    implementation 'com.android.support:appcompat-v7:27.0.2'
    implementation 'com.android.support:cardview-v7:27.0.2'
    implementation 'com.android.support:recyclerview-v7:27.0.2'
//    implementation 'com.android.support:support-fragment:27.0.2'
    implementation 'com.android.support:support-v4:27.0.2'
    implementation 'com.android.support:design:27.0.2'
    implementation 'com.android.support:customtabs:27.0.2'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
//    implementation 'com.google.android.gms:play-services-auth:11.6.2'
    implementation 'com.google.firebase:firebase-database:11.8.0'
    implementation 'com.google.firebase:firebase-auth:11.8.0'
    implementation 'com.google.firebase:firebase-core:11.8.0'
    implementation 'com.google.firebase:firebase-ads:11.8.0'
    implementation 'com.google.firebase:firebase-storage:11.8.0'
//
    implementation 'com.firebaseui:firebase-ui-auth:3.2.1'
//
    implementation 'com.facebook.android:facebook-login:4.27.0'
    implementation 'io.supercharge:shimmerlayout:1.1.0'
//    implementation("com.twitter.sdk.android:twitter-core:3.0.0@aar") { transitive = true }
//    implementation 'com.github.bumptech.glide:glide:4.3.1'
    implementation 'com.github.PhilJay:MPAndroidChart:v3.0.3'
//
    implementation 'com.github.d-max:spots-dialog:0.7@aar'
//    annotationProcessor 'com.github.bumptech.glide:compiler:4.3.1'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

}



apply plugin: 'com.google.gms.google-services'
```
Best Regards

**Comment by samtstern** [comment]
@GuanacoDevs it's possible that some themes you have defined are conflicting with some themes defined in FirebaseUI.  However from that screenshot it does not look like FirebaseUI is functioning improperly, the dialog that's off-center and blurry is part of your application.

We can't troubleshoot that here as it's too specific to your app, please try StackOverflow to get more help on this issue.  Good luck!
