### ISSUE TITLE
Error when cancelling login

### ISSUE THREAD

**Issue by afaucogney** [firebase/FirebaseUI-Android#114]
When I tried to login with Facebook provider, the connect user didn't own right to connect (app not released, and user not a tester). So I just click on the back button (android 5), and the app crashed. This happen with other failed or cancelled login process I didn't record.

> java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=64206, result=-1, data=Intent { (has extras) }} to activity {fr.xxx.app.aaa/fr.xxx.app.aaa.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.View android.view.View.findViewById(int)' on a null object reference

```
    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {
        Log.e("FB Prov", firebaseLoginError.toString());
        resetFirebaseLoginPrompt();
    }
```

**Comment by samtstern** [comment]
Closing because the 0.4.0 version uses different logic, please open a new issue if the new version does not fit your needs for a situation like this.
