### ISSUE TITLE
How to set addSnapshotListener and remove in populateViewHolder in RecyclerView Item.

### ISSUE THREAD

**Issue by PankajSavaliyaGit** [firebase/FirebaseUI-Android#1142]
I have implement RecyclerView with FirebaseUI-Android library.  
  *My RecyclerView realtime data change well once i use that **FirebaseRecyclerAdapter** .
  *In Collection that data document have field type as [Boolean , Integer, Reference](https://firebase.google.com/docs/firestore/manage-data/data-types?authuser=0).
  *I want use that **Reference** to get data in populateViewHolder with addSnapshotListener.

Help me!

**Comment by samtstern** [comment]
@PankajSavaliyaGit this doesn't sound like an issue with FirebaseUI, it sounds like a general question about how to program your application.  Please ask it on StackOverflow, I'd suggest also adding code snippets to your question  to make it easier to answer.
