### ISSUE TITLE
Firebase Email Authentication verification Email not sent

### ISSUE THREAD

**Issue by asimdogar** [firebase/FirebaseUI-Android#1145]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: yes
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
### Step 3: Describe the problem:
I'm using Email Authentication.but on signup did not get verification email.
#### Steps to reproduce:

  1. _____Select Email Authenticaion
  2. _____Signup Completed
  3. _____Did not get verification Email
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
    Signed In successfully without  verification.No errors on logcat.
  
#### Expected Results:

  * What did you expect to happen?
   Verification Email should be received on email.
  
#### Relevant Code:
  AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setIsSmartLockEnabled(false)
                                    .setAvailableProviders(Arrays.asList(
                                            new AuthUI.IdpConfig.EmailBuilder().build())
  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@asimdogar I believe this is working as intended, FirebaseUI does not trigger email verification emails on sign up.  

You can use the Firebase authentication APIs to do this yourself, if you want to.

**Comment by Kurt29** [comment]
@samtstern 
Relating to this:
Wouldn't it be useful to have a "Verify your email screen" in FireBaseUI if you want to have emails verified? For me, email verification is one of the core features of FireBase.

**Comment by samtstern** [comment]
@Kurt29 I agree this could be a useful feature, I believe we're tracking it here:
https://github.com/firebase/FirebaseUI-Android/issues/312

**Comment by Kurt29** [comment]
Wow, that feels like a long time ago =D
