### ISSUE TITLE
Indonesian Translation for this repository

### ISSUE THREAD

**Issue by iqbalhood** [firebase/FirebaseUI-Android#1155]
I want to create Translation for this repository. Is it  possible . And How to contribute?

**Comment by samtstern** [comment]
@iqbalhood thanks for filing this issue!  We would really love to accept your translation, but we can't for a few reasons:

  * **Verification** - we don't speak the language, so I don't know how I'd actually review your pull request :confused: 
  * **Future Scalability** - as we change the UI we'd need to keep the translation up to date, but we don't have any Idonesian language speakers on the team who can help with this.

That said, it should be really easy for your to add your own translation if you want to, just mirror one of the other languages here:
https://github.com/firebase/FirebaseUI-Android/tree/master/auth/src/main/res

Again I hate to reject any offer like this but I hope you understand.  Thank you for taking the time to file the issue!
