### ISSUE TITLE
FirebaseUser.getPhotoURL() - Parameterize photo dimensions

### ISSUE THREAD

**Issue by makcakaya** [firebase/FirebaseUI-Android#1159]
`FirebaseUser.getPhotoURL()` method should take an optional parameter specifying the height (and width too, maybe) of the picture we expect. 
 
For Facebook, currently an image of size 100x100px is returned by Graph request default.

It is possible to specify the image size for Facebook through Graph request. I don't know about other providers (Google, Twitter and Github).

An example would be:
```
user.getPhotoURL(200); // For 200x200px photo, or maybe 200px height photo. It depends.
```
FirebaseUI version: 3.1.0

-- Edit 1

For Google provider, it seems **possible** to get the picture with specified size and how to do it is explained [here](https://stackoverflow.com/a/36980705/1275489).

**Comment by samtstern** [comment]
@makcakaya thanks for this feature request!  I agree with you, however this is something that we'd want to change in the Firebase Auth SDK and not in FirebaseUI.

The best place to file this feedback, in that case, is here:
https://firebase.google.com/support/contact/bugs-features/

If you wouldn't mind filing an Feature Request there, it will get to the right place.  Thanks!
