### ISSUE TITLE
Is it possible to Cache images?

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-Android#116]
When moving between activities a stored image in firebase is re-downloaded. Is there a way to store the image locally to save on bandwidth, reuse the image when the activity reopens and delete once the app closes?

**Comment by puf** [comment]
Hey Joe,

There probably is a way to cache images, although it depends on how (and from where) you load them. But the solution is likely unrelated to FirebaseUI.

I suggest that you open a question on StackOverflow for this. Be sure to include a minimal piece of code that shows how you now load and display the images, and a representative snippet of your JSON (as text, not as a screenshot). With that others can suggest improvements based on what you've shown.

**Comment by Hishmad** [comment]
Hello Joe,

Check out Picasso by Square, or Glide by Bumtech, both does the image
caching, with one line of code.

Frank,
Thank you very much for everything.

Regards
Hishmad

**Comment by joemerritt** [comment]
Puf and Hishmad,

Thank you both for your answers. I appreciate the help! Hishmad I will look into Picaso and Glide and see if they can do what I'm after!

Cheers Gents

Joe

**Comment by thom7kick** [comment]
@joemerritt where you able to solve this . . .

**Comment by joemerritt** [comment]
Yes I did, I used Glide to load the images after converting them back from a String from the Firebase server.

Works a charm

**Comment by thom7kick** [comment]
can you share the code please..............
here is what i have now 

>                 Picasso.with(getContext()).load(model.getImage()).into(viewHolder.picture);

**Comment by joemerritt** [comment]
go to https://github.com/bumptech/glide

I used  Glide.with(getcontext()).load(picture).into(viewHolder.picture);

Very similar, but Glide worked for me..... Remember to use this after you convert the string back to a byte array.

ie.

String pictureString = pojo.getimagestring();
byte[] picture = Base64.decode(pictureString.getBytes(), Base64.DEFAULT);
Glide.with(getcontext()).load(picture).into(viewHolder.picture);

let me know if this works for you

**Comment by joemerritt** [comment]
Good to hear! @thom7kick ... happy coding

**Comment by BrunoGiubilei** [comment]
what you guys say in relation a Cache API? Can use it instead Picaso or Glide?

refered link:
[https://davidwalsh.name/cache](url)

**Comment by samtstern** [comment]
For those interested in using Firebase Storage with Glide, this gist may be helpful to you:
https://gist.github.com/samtstern/2e3870ed7896eb73d21c95a4c2e7fa25

To be honest I am not sure if Glide would cache by `getId()` but if anyone has ideas on how to extend that to have the desired caching behavior I'd love to hear it.

**Comment by samtstern** [comment]
Just to follow up here, Glide *does* cache by `getId()` so the implementation in the gist should give you free caching!
