### ISSUE TITLE
[Auth] No response for google and facebook login

### ISSUE THREAD

**Issue by eldi059** [firebase/FirebaseUI-Android#1160]
I downloaded the source from the github, and tested.  

I have made no change but...
  - facebook ID update in config.xml of app module and auth module
  - google-services.json has been inserted

Login with email works very well.  The problem is...
  - the app, onActivityResult in com.firebase.uidemo.auth.AuthUiActivity, **gets no result when I tried google login or facebook login.**

As I said I didn't change the gradle file and the information I used is like below...
  * Android device: LG-F700L
  * Android OS version: 7.0
  * Google Play Services version: ??? [When should I refer to get the information?]
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.1

Please teach me how to handle this problem.  Any advice or tip would be highly appreciated.

Also, it would be appreciated if you could teach me how to add label to issue.
I referred [https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/](url)
but, I couldn't find the checkbox which the page mentions in the third step.

**Comment by abdulwasae** [comment]
I believe i am having the same problem. 
I am using phone auth. The phone number gets verified, and the verification activity closes. The calling activity either does not get called, or is not getting the same supplied request code.

We faced this issue in prod on an Android 7.0 device (Samsung galaxy S7). I'll leave this info here, and meanwhile try to get my hands on a device with matching configs to test.

**Comment by samtstern** [comment]
@eldi059 do you get a response when you do email authentication or phone authentication?

(Also you can't label issues as an outside contributor so that's why you can't see the box)

**Comment by eldi059** [comment]
@samtstern 
Thanks for reply. I don't get response when trying phone authentication, and I do for email authentication.
I am developing the module not based on the example app in this repository but based on firebase documentation.  And just a minute ago I succeeded to login via google account.  Actually the documentation is quite good and it is easy to follow.
I will close the issue.
Thanks again.
(How can I become a contributor? I am a kind of novice in adroid app development, but want to contribute to this site. ;))

**Comment by samtstern** [comment]
@eldi059 thanks for letting us know you figured it out, I will close this issue.

We love to have contributors!  The best thing to do is to read issues and join the discussion, proposing solutions that may work.  FirebaseUI-Android may not be the best place to start if you're a beginner since it's an advanced codebase but you're always welcome to try and contribute to any Firebase repository.
