### ISSUE TITLE
[Auth] Ability to sign out outside of activity

### ISSUE THREAD

**Issue by sp00ne** [firebase/FirebaseUI-Android#1161]
Hi there!

In your sign out examples you utilise `activity` as a parameter for `signOut`. I know there has been a discussion previously for using `context` instead but I can't see that code anywhere (should have been included in your `3.1.1` release)

Is it possible to get a context-related method call rather than activity? In order to call this outside of activity context #

**Comment by samtstern** [comment]
@sp00ne the `AuthUI.signOut()` method currently takes a `Context` parameter:
https://github.com/firebase/FirebaseUI-Android/blob/63572c57e1ba39903b85060d64efb775a7ccef34/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L269

Are you having some trouble with this?  Can you try using the latest version?
