### ISSUE TITLE
NullPointerException on AuthUI.getInsatance()

### ISSUE THREAD

**Issue by gaurav-m** [firebase/FirebaseUI-Android#1170]
Hi, I am getting the said exception.
Dont know what can cause this issue.
Even if this is a bug, please tell me if I can do something to avoid this until this is fixed.

Here is the 

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.tasks.e com.google.android.gms.common.api.c.b(com.google.android.gms.common.api.internal.by)' on a null object reference
       at com.google.android.gms.internal.zzdvv.zzb(Unknown Source)
       at com.google.android.gms.internal.zzdwc.zza(Unknown Source)
       at com.google.firebase.auth.FirebaseAuth.signInAnonymously(Unknown Source)
       at com.firebase.ui.auth.AuthUI.(AuthUI.java:208)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:244)
       at com.firebase.ui.auth.AuthUI.getInstance(AuthUI.java:232)

```

**Comment by samtstern** [comment]
@gaurav-m please see #1104

**Comment by gaurav-m** [comment]
thanks a ton @samtstern

**Comment by BrownEli** [comment]
Im also getting this error in version 3.1.3
this is my crash log from crashlytics

`Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
com.google.android.gms.internal.zzdza.zzb (Unknown Source)
com.google.android.gms.internal.zzdzh.zza (Unknown Source)
com.google.firebase.auth.FirebaseAuth.setFirebaseUIVersion (Unknown Source)
arrow_right
com.firebase.ui.auth.AuthUI.getInstance (AuthUI.java:192)
com.firebase.ui.auth.AuthUI.getInstance (AuthUI.java:179)`

Please let me know if there is any way to avoid this.. Thanks
