### ISSUE TITLE
Firebase. Not get sms for users with migrate phone numbers

### ISSUE THREAD

**Issue by lmdic** [firebase/FirebaseUI-Android#1179]
In my **app/build.gradle**:

```
compile 'com.firebaseui:firebase-ui-auth:2.3.0'
compile 'com.google.firebase:firebase-auth:11.0.4'
```

In my fragment when click my custom button I call Firebase authentication screen for SMS authentication

```
button.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {                   
                FirebaseAuth.getInstance().signOut();
                FirebaseAuth.getInstance().addAuthStateListener(((MainApp) getActivity().getApplication()).firebaseCallback);

                startActivityForResult(
                        AuthUI.getInstance()
                                .createSignInIntentBuilder()
                                .setTheme(R.style.SG_Firebase_Theme)
                                .setAvailableProviders(
                                        Collections.singletonList(new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build())
                                )
                                .build(),
                        RC_SIGN_IN);
            }
        });
```
Steps:

1.After click my button show Firbase screen
2.I input phone number
3.Forward to second Firebase screen
4.Success get SMS code
5.Input SMS
6.Success verify SMS

Nice. It's work fine... with one exception.

In our country we have 3 mobile operators. And any user can migrate from one operator to another **WITHOUT** change it's phone number. It is very convenient for users.

And if this kind of users input it's phone number in first Firebase screen and click button "Confirm phone number", they **NEVER** get SMS confirm code.

But the user that not mirgate to another mobile operator **SUCCESS** get sms.

Why?

**Comment by samtstern** [comment]
@lmdic thanks for this report.

Unfortunately I can't help you here.  If you're having issues with SMS delivery please try Firebase Support:
firebase.google.com/support

Hope you get it figured out!
