### ISSUE TITLE
Handle empty state for recycleview

### ISSUE THREAD

**Issue by ismaelaarab10** [firebase/FirebaseUI-Android#118]
Is there a way for passing a different view if there is no data? Or does this require a second data check up outside de adapter

**Comment by samtstern** [comment]
@ismaelaarab this is a good feature request and something that I have implemented in my own apps many times on top of FirebaseUI.  It would most likely take the form of a simplified AdapterDataObserver that works with Firebase.

I will put this on the Enhancements list and target it for a future release.  If you have a good solution, always feel free to send a PR.

**Comment by zsweigart** [comment]
I am also running into needing this for my application.  I think a simple solution would be just to make an interface for onDataChanged and call it at the end of mSnapshot's data change listener

**Comment by winstonma** [comment]
Agree on this one.

The LoaderManager.LoaderCallbacks.onLoadFinished listener would be very useful.

**Comment by Sottti** [comment]
This is exactly what is holding me back right now. Basically there's a few scenarios that are common to a lot of my lists: Empty (size 0) and Error(impossible to get any data from network or cache.) I'd be really really happy to see this implemented. In my case I hide the recyclerView to show something else.

**Comment by samtstern** [comment]
@Sottti @winstonma Here's a trick you could use in the meantime.  If you attach a `ValueEventListener` to the same `DatabaseReference` that you're passing into the RecyclerView you can use it as an indication of when the load is done.  You'll get the `onDataChange` callback in the `ValueEventListener` and this is guaranteed to happen **after** all of the child events have been propagated to the RecyclerView.  So if you get `onDataChange` and the RecyclerView still has 0 items you can show your "no items" message or do something similar while being confident that the initial load is complete.

**Comment by winstonma** [comment]
Thanks @samtstern 

I saw many workarounds and it works. But I agree that it would be great if the features like `EmptyView` and `OnLoadFinished` is implemented so no one need to StackOverflow and make apps easier to build.

Thanks for the effort. In the meantime I will stick with your solution.

**Comment by samtstern** [comment]
@winstonma agree that some sort of `OnLoadFinished` callback would be a good feature.  Hopefully we will get to it in a coming release.

**Comment by samtstern** [comment]
A fix for this issue has been released in version `1.1.0`

**Comment by winstonma** [comment]
Thanks appreciated

**Comment by cutiko** [comment]
Greetings.

I was waiting for this, is great thanks! Can I suggest adding it in the docs, took me awhile to find it in the demo app.

Thanks.

**Comment by dri94** [comment]
I dont understand hwo this works if the firebase adapter is not a nested class

**Comment by cutiko** [comment]
@dri94 

`public class MyAdapter extends FirebaseRecyclerAdapter<MyHolder, MyModel> {}`

You can create the `holder` as a nested class inside the `MyAdapter` class or as another class on its own file, anyway: the adapter needs the holder so **always start for creating the holder**.

After you extend your class `alt+enter` on anything red and should suggest you the missing methods and constructor to make it work.
