### ISSUE TITLE
Couldn't get FireStore adapter example to work (lifecycle events not running) 

### ISSUE THREAD

**Issue by nebular** [firebase/FirebaseUI-Android#1186]
Been mad all this night upgrading support libraries, build version, arch components ... because the provided example did not work for me. After some debugging, I realized that LifeCycle events were never called, and specifically, the field **mOwner** was always null.

In the example in the README (in this repo), the **FirestoreRecyclerOptions** are created like this:

```
new FirestoreRecyclerOptions.Builder<S>()
				.setQuery(COLLECTION, MODEL)
				.build();

```
However, if I do this, everything works:
```

new FirestoreRecyclerOptions.Builder<S>()
				.setQuery(COLLECTION, MODEL)
				.setLifecycleOwner(context)
				.build();
```

Is the example wrong? Or is there yet another issue with support versions / gradle / arch plugins ...

Thanks in advance ! Nice Adapter !

**Comment by SUPERCILEX** [comment]
@nebular That's correct, check out our docs on the lifecycle events: https://github.com/firebase/FirebaseUI-Android/blob/master/database/README.md#firebaserecycleradapter-lifecycle

**Comment by SUPERCILEX** [comment]
@samtstern I believe this issue can be closed since it's expected behavior.

**Comment by SUPERCILEX** [comment]
@samtstern I believe this issue can be closed since it's expected behavior.
