### ISSUE TITLE
FirebaseAuth UI country code selection scrollbar not implemented right. 

### ISSUE THREAD

**Issue by srujanb** [firebase/FirebaseUI-Android#1192]
### Step 2: Describe your environment

  * Android device: OnePlus
  * Android OS version: 8.0
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.1
  
### Step 3: Describe the problem:

The scrollbar should not go beyond the screen when scrolling happens on the dialog box. See the **scrollbar** in the video below. 

https://youtu.be/t2xaA-M0t-E

#### Steps to reproduce:

1.  Implement firebaseUI auth. 
2.  Include SMS auth builder
3.  Click on the list of countries to select country code.
4.  Scroll 
5.  Get annoyed with the scrollbar going all the way to the bottom, out of the screen. 
  
#### Observed Results:

See the **Scrollbar** in the video.

https://youtu.be/t2xaA-M0t-E
  
#### Expected Results:

  Scrollbar not going beyond screen
  
#### Relevant Code:

None.

**Comment by samtstern** [comment]
This has been fixed and released in version `4.2.1`.
