### ISSUE TITLE
add a salt to passwords

### ISSUE THREAD

**Issue by j2emanue** [firebase/FirebaseUI-Android#1194]
the issue i am facing is that i am required to add a salt to the users Email provider password. basically if the user enters password as "1234" and my salt is "myapp_secret" then the true password will be a hash of: **myapp_secret1234**

How can i add this extra string to users password. i dont see a method for this.  this is common practice sometimes to better security.

**Comment by SUPERCILEX** [comment]
You don't get direct access to the user's passwords. Instead, they are stored securely in Google's data centers where you don't have to worry about any of that. All you'll need is the `FirebaseUser#getUid()` to be able to uniquely identify your users in a database or wherever else you need it.

PS: I'm pretty sure that you _can_ get a dump of your users' passwords in plaintext if absolutely necessary by contacting Firebase support.

**Comment by j2emanue** [comment]
So what's happening is that we are using the password  salt as a key for something else. System was made like this unfortunately. Anyway, do you know of anyway to do this from the firebase console then ? It's the same salt all the time. Constant.

**Comment by samtstern** [comment]
@j2emanue sorry this is not something that's supported in Firebase Authentication, so we won't support it in Firebase UI.

If you had hashed / salted passwords from another application you could import them into Firebase:
https://firebase.google.com/docs/cli/auth

If you really need to interact with your old system that has different password requirements, you could also use Custom Auth:
https://firebase.google.com/docs/auth/admin/create-custom-tokens

Thanks for your offer of a pull request, I hope you understand why we won't add this feature though!
