### ISSUE TITLE
firebaseUI as fragment not activity

### ISSUE THREAD

**Issue by j2emanue** [firebase/FirebaseUI-Android#1198]
Can you make the login buttons appear in a fragment instead of an activity.  The reason is i want to add other log in options that are not apart of firebase authentication.  For example, in asia we have login with Line ID as another provider but not a firebase provider.  so i could if firebaseUI was a fragment i could split the screen and show other providers on the same screen. i did not see an option for this, could you comment ?

**Comment by SUPERCILEX** [comment]
Hi there,
No, unfortunately, this isn't possible. Line isn't one of the default Firebase providers so that means using custom auth which FirebaseUI doesn't support. You're totally welcome to fork FirebaseUI and add support for Line yourself though! 😊
