### ISSUE TITLE
Support for joins

### ISSUE THREAD

**Issue by ginovva320** [firebase/FirebaseUI-Android#12]
Will there be any support here for joins across multiple Firebase paths, similar to what firebase-util offers for Javascript? All of my data is denormalized, so creating a ListView just based on one path would not be sufficient. If not, do you have any recommendations?

**Comment by puf** [comment]
While it is technically possible (and an interesting challenge) to joins two lists together, it comes with all kinds of nasty edge cases and performance implications that are often better prevented by duplicating data. I'll leave your report open as an enhancement, but it is not on the list of features we intend to work on in the immediate feature. It might also fit better in a separate project, similar to how firebase-util is separate from AngularFire.

**Comment by z-nut** [comment]
Check out my fork. I have tweaked the code to accept multiple firebase paths and then load them pretty much seamlessly into the same view holder. This is of course, a work in progress. 

https://github.com/z-nut/FirebaseUI-Android

**Comment by samtstern** [comment]
I believe this was fixed a while ago in #276 but this issue was never closed.  Closing it now, please open a new issue if the new implementation does not meet your needs.
