### ISSUE TITLE
NoClassDefFoundErrors logcat spam for optional providers

### ISSUE THREAD

**Issue by wojtek-kalicinski** [firebase/FirebaseUI-Android#1200]
* Android device: Pixel 2
  * Android OS version: P
  * Google Play Services version: 
  * Firebase/Play Services SDK version: 
  * FirebaseUI version: 3.2.2
  
### Step 3: Describe the problem:
ART verification spams the logcat with NoClassDefFoundErrors, because it needs to resolve superclasses of TwitterProvider and FacebookProvider, which don't exist if you're not using these SDKs. 

Instead of extending/implementing Callbacks from the SDKs directly, these classes should have inner classes for callbacks, that will not be eagerly verified.

#### Steps to reproduce:

  1. Don't include Facebook and Twitter SDKs
  2. Try to sign in using Firebase Auth
  
#### Observed Results:

NoClassDefFoundErrors in logcat
  
#### Expected Results:

No errors

**Comment by samtstern** [comment]
@SUPERCILEX integrated your suggestions into #1189

**Comment by samtstern** [comment]
This issue has been fixed and released in `3.3.0`.
