### ISSUE TITLE
FirestoreRecyclerAdapter no virtual method getDocument

### ISSUE THREAD

**Issue by jvergers** [firebase/FirebaseUI-Android#1210]
I am currently converting my Firebase UI components to Firestore UI components. When building the `FirestoreRecyclerAdapter` and manually call the `adapter.startListening()` or initialize it via `new FirestoreRecyclerOptions.Builder().setLifeCycleOwner()` I stumble on the following fatal exception.

    FATAL EXCEPTION: main
    Process: packagename, PID: 3129
    java.lang.NoSuchMethodError: No virtual method getDocument()Lcom/google/firebase/firestore/DocumentSnapshot; in class Lcom/google/firebase/firestore/DocumentChange; or its super classes (declaration of 'com.google.firebase.firestore.DocumentChange' appears in /data/app/packagename-yHh4aIRPAZwxxRYgunJivQ==/split_lib_dependencies_apk.apk)
    at com.firebase.ui.firestore.FirestoreArray.onDocumentAdded(FirestoreArray.java:98)
    at com.firebase.ui.firestore.FirestoreArray.onEvent(FirestoreArray.java:83)
    at com.firebase.ui.firestore.FirestoreArray.onEvent(FirestoreArray.java:21)
    at com.google.firebase.firestore.zzi.onEvent(Unknown Source:17)
    at com.google.android.gms.internal.zzeyn.zza(Unknown Source:6)
    at com.google.android.gms.internal.zzeyo.run(Unknown Source:6)
    at android.os.Handler.handleCallback(Handler.java:789)
    at android.os.Handler.dispatchMessage(Handler.java:98)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6809)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

The error states that the class `DocumentSnapshot` doesn't contain a method `getDocument` which after checking is correct. However this is also how the docs states this implementation.

The adapter with query

    mRecyclerView = (RecyclerView) view;
                mRecyclerView.setLayoutManager(new LinearLayoutManager(context));
    
                Query query = mFirestore.collection("spots");
                FirestoreRecyclerOptions<SpotModel> options = new FirestoreRecyclerOptions.Builder<SpotModel>().setQuery(query, SpotModel.class).setLifecycleOwner(this).build();
    
                mAdapter = new FirestoreRecyclerAdapter<SpotModel, SpotHolder>(options) {
                    @Override
                    public SpotHolder onCreateViewHolder(ViewGroup parent, int viewType) {
                        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.card_spot, parent, false);
    
                        return new SpotHolder(view);
                    }
    
                    @Override
                    protected void onBindViewHolder(@NonNull SpotHolder holder, int position, @NonNull SpotModel model) {
                        holder.bind(model);
                    }
                };
    
                mRecyclerView.setAdapter(mAdapter);

FirebaseUI dependencies

    implementation 'com.firebaseui:firebase-ui-auth:3.2.2'
    implementation 'com.firebaseui:firebase-ui-database:3.2.2'
    implementation 'com.firebaseui:firebase-ui-firestore:3.2.2'

The adapter is being initialized in the `onCreateView` method of a fragment.

**Comment by SUPERCILEX** [comment]
Could post the output of `./gradlew dependencies`?

**Comment by jvergers** [comment]
Full output:


`Configure project :app
Could not find google-services.json while looking in [src/nullnull/debug, src/debug/nullnull, src/nullnull, src/debug, src/nullnullDebug]
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)
Could not find google-services.json while looking in [src/nullnull/release, src/release/nullnull, src/nullnull, src/release, src/nullnullRelease]
registerResGeneratingTask is deprecated, use registerGeneratedFolders(FileCollection)

> Task :dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations


BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed`

Double checked if google-services.json is missing but it's placed in the projects app folder.

**Comment by SUPERCILEX** [comment]
Oh, my B. Could you run `./gradlew app:dependencies`? Thanks!

**Comment by jvergers** [comment]
Attached in textfile since its a pretty big output.

[gradeOutput.txt](https://github.com/firebase/FirebaseUI-Android/files/1845610/gradeOutput.txt)

**Comment by SUPERCILEX** [comment]
Huh, your dependencies look good to me. Are you using multidex?

**Comment by jvergers** [comment]
Multidex is not enabled.

**Comment by samtstern** [comment]
@jvergers thank you for this report, I got someone who mentioned this to me directly via email so it appears this is a real issue.

With the other report, it seems the problem comes from mixing Firebase dependencies `12.0.0` and FirebaseUI `3.2.2`.  You can solve this temporarily by downgrading to `11.8.0`.  We have a version `12.0.1` coming out in the next few days to fix some packaging issues with `12.0.0` that I hope will resolve this.

**Comment by samtstern** [comment]
The more I look at it, I also think this could be related to the newly added `QueryDocumentSnapshot` class in `12.0.0` which is meant to use the type system to signal to the developer that `.exists()` will always be true for `DocumentSnapshot` returned from a `QuerySnapshot` whereas that's not the case if you just call `get()` on a random `DocumentReference`

**Comment by jvergers** [comment]
Downgrading Firebase to `11.8.0` worked as a temporarily work around, will keep an eye on the update. Thanks a million!

**Comment by samtstern** [comment]
@jvergers I have #1216 to double-fix this issue :-)

I also suspect this is just due to some gradle build caching not being happy when you upgraded from 11.8.0 to 12.0.0, but it should be fixed in a few days either way.

**Comment by PankajSavaliyaGit** [comment]
This issue generated by **proguard-rules**. need to proguard-rules for that issue.

**Comment by samtstern** [comment]
This issue has been fixed and released in `3.3.0`.
