### ISSUE TITLE
Remove or change resConfigs "auto" from the suggested optimization

### ISSUE THREAD

**Issue by matpag** [firebase/FirebaseUI-Android#1217]
When updating to Android Studio 3.1, one of the first warning provided by the IDE is to remove the `resConfigs "auto"` property from defaultConfig and from flavors (if present), which is the opposite suggested in the current configuration guide [here](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#configuration)
![image](https://user-images.githubusercontent.com/4432213/37935044-8e4c4682-3150-11e8-9c7c-61fedaf2b985.png)

Refer to the note specified in the plugin documentation:
https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.ProductFlavor.html#com.android.build.gradle.internal.dsl.ProductFlavor:resConfigs(java.lang.String[])

**Comment by SUPERCILEX** [comment]
`auto` is meant as a placeholder. You're supposed to replace it with the languages you support, but I totally see how this is confusing. Will fix.

**Comment by samtstern** [comment]
Damn it's pretty lame they're removing "auto".  It actually was not a placeholder, it did 'the right' thing. But thanks for the PR.

**Comment by SUPERCILEX** [comment]
Huh, I always thought auto was the default. Guess not! 😮 Apparently it's because of multi-module project bugs. Now I'm disappointed too! 😭😂

**Comment by matpag** [comment]
You were super fast, thank you @SUPERCILEX 👍

**Comment by AlexanderLS** [comment]
@SUPERCILEX @samtstern  Question on the Stackoverflow - ['ProductFlavor.resConfigs' has a value 'auto' which is obsolete and has not been replaced](https://stackoverflow.com/questions/49498491/productflavor-resconfigs-has-a-value-auto-which-is-obsolete-and-has-not-been)

**Comment by samtstern** [comment]
@matpag thanks for the great answer on StackOverflow, also cc @SUPERCILEX 

![image](https://user-images.githubusercontent.com/8466666/37976401-47c9192e-3196-11e8-90f8-6a096d9e448e.png)

**Comment by matpag** [comment]
Was a pleasure 😉, you are doing a great jobs guys 👍
