### ISSUE TITLE
Compatability with new Firebase major release

### ISSUE THREAD

**Issue by Webzites-nl** [firebase/FirebaseUI-Android#122]
Hey, I am wondering when this library is expected to be compatible with the new Firebase version (com.google.firebase:firebase-database:9.0.0) released at Google IO this week.

**Comment by samtstern** [comment]
The new 0.4.0 version of Firebase UI is compatible with the 9.0.0 versions
of the Firebase libraries.

If you are asking specifically about Database, then you'll want to use
'com.firebaseui: firebase-ui-database:0.4.0' in your app.

Check out the README file in the database folder for some more information.

**Comment by Webzites-nl** [comment]
Perfect! That solves my issue exactly.
