### ISSUE TITLE
Firebase author ui requires update for supporting 12.0.0 dependencies

### ISSUE THREAD

**Issue by shivamsonu23** [firebase/FirebaseUI-Android#1220]
Firebase ui auth needs to be updated as 3.2.2 does not support 12.0.0 dependencies. It supports 11.8.1. Also not able to use play services api of version 12.0.0.

**Comment by shivamsonu23** [comment]
Sorry for mistyping. It's Firebase ui auth in title.

**Comment by krisu7** [comment]
@shivamsonu23 as per PR #1203, @samtstern is waiting for play services 12.0.1 since 12.0.0 has broken ProGuard.

**Comment by krisu7** [comment]
@shivamsonu23 check out [https://developers.google.com/android/guides/releases#march_20_2018_-_version_1200](https://developers.google.com/android/guides/releases#march_20_2018_-_version_1200)

**Comment by samtstern** [comment]
@shivamsonu23 we are waiting for `12.0.1` (and you should too!).  

However it's always possible to use FirebaseUI with a newer version of Play services dependencies:
https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies
