### ISSUE TITLE
Internal: bintray publishing broken

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1225]
This happened during `3.2.2` as well as `3.3.0` but I fixed it manually in each case.  Which is kind of a huge pain, so need to fix this before `3.3.1`.

Right now when I upgrade the artifacts to Bintray I get a lot of `unspecified` junk:

![image](https://user-images.githubusercontent.com/8466666/38053791-dfc2680e-3289-11e8-8f81-c671557d591c.png)

![image](https://user-images.githubusercontent.com/8466666/38053820-ef965ace-3289-11e8-9352-7c3c57228565.png)

**Comment by SUPERCILEX** [comment]
@samtstern Also on the subject of broken builds, all of [mine](https://travis-ci.org/SUPERCILEX/FirebaseUI-Android/builds/359588507) are passing, but the offical one's aren't happy because of bintray or something. Maybe clean the cache?

**Comment by samtstern** [comment]
Yeah i tried cleaning the cache .... gonna wait a few hours and try again.
jCenter had a known incident today.

**Comment by SUPERCILEX** [comment]
Oh, gotya, SGTM! 👍

**Comment by samtstern** [comment]
Fixed in #1257
