### ISSUE TITLE
Program type already present: com.google.android.gms.internal.zzcce

### ISSUE THREAD

**Issue by hiddeneyes02** [firebase/FirebaseUI-Android#1230]
> Program type already present: com.google.android.gms.internal.zzcce
Message{kind=ERROR, text=Program type already present: com.google.android.gms.internal.zzcce, sources=[Unknown source file], tool name=Optional.of(D8)}

This is my gradle:

```groovy
apply plugin: 'com.android.application'

android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.garishat.altahir"
        minSdkVersion 17
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:27.1.0'
    implementation 'com.android.support:support-v4:27.1.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
}

apply plugin: 'com.google.gms.google-services'
```

And project level:
```groovy
buildscript {

    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.0'
        classpath 'com.google.gms:google-services:3.2.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

Please help, I spent all the morning from one problem to another...

**Comment by samtstern** [comment]
@hiddeneyes02 what version of Android Studio are you using?  Could you try adding the following lines to your `gradle.properties` file and seeing if anything changes?

```
android.enableR8 = false
android.enableD8 = false
```

**Comment by hiddeneyes02** [comment]
I am using Android Studio 3.1, lastest

This is what I get with that:

> The option 'android.enableD8' is deprecated and should not be used anymore.
 Use 'android.enableD8=true' to remove this warning.
 It will be removed in AGP version 3.3.

The same original error if I remove android.enableD8 = false or set it to true

**Comment by samtstern** [comment]
@hiddeneyes02 what about FirebaseUI `3.2.2`?

**Comment by samtstern** [comment]
@hiddeneyes02 are you working offline?

Can you try running from the command line:
`./gradlew clean cleanBuildCache :app:assembleDebug`

**Comment by hiddeneyes02** [comment]
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\0.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\1.jar, D:\Fahed\LocalProjects\Android\Garishat\app\buil
d\intermediates\transforms\dexBuilder\debug\2.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\3.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\4.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\d
ebug\5.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\6.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\7.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\8.jar, D:\Fahed\LocalProjects\Andr
oid\Garishat\app\build\intermediates\transforms\dexBuilder\debug\9.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\10.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\12.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\
transforms\dexBuilder\debug\13.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\14.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\15.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\16.jar,
D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\17.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\18.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\19.jar, D:\Fahed\LocalProjects\Android\Garis
hat\app\build\intermediates\transforms\dexBuilder\debug\20.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\22.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\23.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transfor
ms\dexBuilder\debug\24.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\25.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\26.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\27.jar, D:\Fahed
\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\28.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\29.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\30.jar, D:\Fahed\LocalProjects\Android\Garishat\app\
build\intermediates\transforms\dexBuilder\debug\31.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\32.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\33.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBu
ilder\debug\34.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\35.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\36.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\37.jar, D:\Fahed\LocalPr
ojects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\38.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\39.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\40.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\in
termediates\transforms\dexBuilder\debug\41.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\42.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\43.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\de
bug\44.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\45.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\46.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\48.jar, D:\Fahed\LocalProjects\A
ndroid\Garishat\app\build\intermediates\transforms\dexBuilder\debug\50.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\52.jar, D:\Fahed\LocalProjects\Android\Garishat\app\build\intermediates\transforms\dexBuilder\debug\53.jar
```

With the same error. I should tell you the error occurs when trying to run the app, not when synchronizing gradle.

**Comment by samtstern** [comment]
@hiddeneyes02 I am a bit stumped here, and I think it's very strange that I have not seen this same error from any other users.

**Comment by samtstern** [comment]
@hiddeneyes02 I just recreated your exact project and here's how you can fix it:

Replace this:
```
classpath 'com.google.gms:google-services:3.2.0'
```

With this:
```
classpath 'com.google.gms:google-services:3.2.1'
```

**Comment by CraftedPvP** [comment]
@samtstern This doesn't solve it. My problem is exactly similar to his but my classpath is already

```
classpath 'com.android.tools.build:gradle:3.1.0'
classpath 'com.google.gms:google-services:3.2.1'
```

**Comment by hiddeneyes02** [comment]
It does do it for me neither, same error is appearing.

**Comment by mars885** [comment]
Hello everyone! I have the same problem as @hiddeneyes02 has described. Did you find a solution?

**Comment by hiddeneyes02** [comment]
@mars885 No unfortunately... I didn't use this library because I needed to finish my project. I used Facebook and Google Signin separately.

**Comment by sunilson** [comment]
I don't know if it was the same error but my problem was that I added Firebase UI Auth and Firebase Auth in Gradle, but Firebase Auth already comes with Firebase UI Auth. So after I removed the Firebase Auth SDK it worked again

**Comment by marvin68** [comment]
Tried creating a fresh project and only importing google services + Firebase UI auth and the same error happens.

**Comment by Diae-dm1303866** [comment]
Same error is happening to me as well! :( 
I have tried every single thing, but noting seems to work! :(

**Comment by Diae-dm1303866** [comment]
UPDATE:
I updated my firebase dependency from 3.2.0 to 3.3.0 and it started working! 
Try it and see if that will work for you! 

This is my gradle.module:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "iotapp.senior.seniorappdesign"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            useProguard false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
    //noinspection GradleCompatible
    compile 'com.google.firebase:firebase-core:12.0.1'
    **_compile 'com.firebaseui:firebase-ui-auth:3.3.0'_**

    implementation 'com.android.support:cardview-v7:26.1.0'
}
apply plugin: 'com.google.gms.google-services'
configurations.all { exclude group: 'com.android.support', module: 'support-v13' }

**Comment by hiddeneyes02** [comment]
I used @Diae-dm1303866  configuration, and it worked. Then I started tracking the source of problem, and I found that this lines solved it:

```
/....../
dependencies {
    /....../
    implementation 'com.google.firebase:firebase-core:12.0.1'
    implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
    implementation 'com.android.support:cardview-v7:27.1.0'
}
/....../
```

Thank you :)

**Comment by marvin68** [comment]
Seems to work after adding this line to app gradle 
    implementation 'com.google.firebase:firebase-core:12.0.1'

**Comment by wirmanto** [comment]
i have my solution by change this:
implementation 'com.android.support:appcompat-v7:27.0.0'
to
implementation 'com.android.support:appcompat-v7:26.0.0'

**Comment by JayRichrd** [comment]
@samtstern because I am compling a sdk for customer with support-v4， and the customer only accept to use my sdk via jar rather aar.

**Comment by huse** [comment]
I have similar problem cause by updating android studio. None of these solutions worked for me.

**Comment by lionello** [comment]
I'm running into this since upgrading `com.android.tools.build:gradle` to 3.1.0. I've managed to fix the issue by downgrading to 3.0.1 in my project's `build.gradle`:

```
-        classpath 'com.android.tools.build:gradle:3.1.0'
+        classpath 'com.android.tools.build:gradle:3.0.1'
```
@huse Try.

**Comment by huse** [comment]
@lionello 
Thank you very much, the "adding android.enableD8=false to gradle.properties" solved the problem.
Android returned:
WARNING: The option 'android.enableD8' is deprecated and should not be used anymore.
but I can move forward. :smiley:

**Comment by samtstern** [comment]
Thanks @lionello and @huse for those pointers!

**Comment by stwasant** [comment]
I have the same error after updating the gradle version to 4.4 and android plugin 3.1.2. I can't found the solution for this. Anybody can found how to fix this error?

> Code
**# > Build.gradle project**

`apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
}
android {
    compileSdkVersion 27
    defaultConfig {
        applicationId "com.pkg_app.sharing.sharing_app"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    signingConfigs {
        debug {
            storeFile file(project.projectDir.absolutePath + '/certs/debug.keystore')
            storePassword 'changeit'
            keyAlias 'android'
            keyPassword 'changeit'
        }

        release {
            storeFile file(project.projectDir.absolutePath + '/certs/release.jks')
            storePassword 'changeit'
            keyAlias 'android'
            keyPassword 'changeit'
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.debug
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-core:15.0.0'
    implementation 'com.google.firebase:firebase-database:15.0.0'
    implementation 'com.google.firebase:firebase-messaging:15.0.0'
    implementation 'com.firebaseui:firebase-ui-database:3.3.0'
    implementation 'com.google.firebase:firebase-auth:15.0.0'
    implementation 'com.facebook.android:facebook-android-sdk:4.32.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.google.android.gms:play-services-auth:15.0.0'
    implementation 'com.google.android.gms:play-services-places:15.0.0'
    implementation 'com.google.android.gms:play-services-cast:15.0.0'
    implementation 'com.google.android.gms:play-services-location:15.0.0'
    implementation 'com.google.android.gms:play-services-plus:15.0.0'
    implementation 'com.github.clans:fab:1.6.4'
    implementation 'com.thomashaertel:multispinner:0.1.1'
    implementation('com.crashlytics.sdk.android:crashlytics:2.6.7@aar') {
        transitive = true;
    }
    // ShowCase View
    //implementation 'com.github.mreram:ShowCaseView:1.0.5' // Agregado por Stiwart Antunez 01-05-2018
    implementation project(':library')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

// Plugin para login con Gmail Firebase 17-12-206
apply plugin: 'com.google.gms.google-services'`


**# > Build.gradle project**

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }

        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'io.fabric.tools:gradle:1.22.1'
        // Dependencia para Firebase - Login Gmail 17-12-2016
        classpath 'com.google.gms:google-services:3.0.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()

        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}


Thank you!

**Comment by heliomartins** [comment]
I was working just fine, and suddenly I got this same error.

Apparently, Firebase had just released a new version **15.0.2** to some of their libraries.
I was using 15.0.0 and updated to the latest and my project worked again.

Hope this helps.

**Comment by qbait** [comment]
After updating to `15.0.2` I'm getting
`Failed to resolve: com.google.android.gms:play-services-auth:15.0.2`
...

**Comment by heliomartins** [comment]
Thanks for the feedback @qbait, would you mind having a look at this link?

https://firebase.google.com/support/release-notes/android

Apparently, for **auth** you should use the `com.google.firebase:firebase-auth:15.1.0`. Would you mind trying it again!?

**Comment by Madonahs** [comment]
I will support @heliomartins  after i updated my error did disappear.  @stwasant  Hope it works for you too. Happy coding.

**Comment by stwasant** [comment]
@Madonahs  Thank you I hope too.

**Comment by Edison4mobile** [comment]
I have updated firebase messaging, storage, core and crash version as 15.0.2.
And this is disappeared.

**Comment by fetching** [comment]
Thank you @heliomartins !   I was also getting the "Program type already present" error. Following your advice of the [Firebase Release Notes](https://firebase.google.com/support/release-notes/android) pertaining to a release yesterday I upgraded some Firebase libraries and the error went away.

For reference here are the versions I'm using and my app compiles and deploys again.

App Gradle:

    implementation 'com.google.firebase:firebase-database:15.0.0'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-auth:15.1.0'
    implementation 'com.google.firebase:firebase-messaging:15.0.2'
    implementation 'com.google.firebase:firebase-storage:15.0.2'
    implementation 'com.firebaseui:firebase-ui-database:3.3.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'

Project Gradle:

    classpath 'com.android.tools.build:gradle:3.1.2'
    classpath 'com.google.gms:google-services:3.2.1'

**Comment by stwasant** [comment]
Thank you everybody I upgrade my firebase version and Google services like @fetching  and work. :)

Here my last version code:
# Final Code
## Build Gradle Project

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public'

        }
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
        classpath 'io.fabric.tools:gradle:1.22.1'
        // Dependencia para Firebase - Login Gmail 17-12-2016
        classpath 'com.google.gms:google-services:3.2.1'

        classpath 'com.github.dcendents:android-maven-gradle-plugin:2.0'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
        jcenter()
        google()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

## Build Gradle App
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'

repositories {
    maven { url 'https://maven.fabric.io/public' }
   }
android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'
    defaultConfig {
        applicationId "com.pkg_app.sharing.sharing_app"
        minSdkVersion 19
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        vectorDrawables.useSupportLibrary = true
        multiDexEnabled true
    }
    signingConfigs {
        debug {
            storeFile file(project.projectDir.absolutePath + '/certs/debug.keystore')
            storePassword 'changeit'
            keyAlias 'android'
            keyPassword 'changeit'
        }

        release {
            storeFile file(project.projectDir.absolutePath + '/certs/release.jks')
            storePassword 'changeit'
            keyAlias 'android'
            keyPassword 'changeit'
        }
    }
    buildTypes {
        debug {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.debug
        }

        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'

            signingConfig signingConfigs.release
        }
    }
    productFlavors {
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:support-v4:27.1.1'
    implementation 'com.android.support:support-vector-drawable:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.0'
    implementation 'com.android.support:multidex:1.0.3'
    implementation 'com.google.firebase:firebase-core:15.0.2'
    implementation 'com.google.firebase:firebase-database:15.0.1'
    implementation 'com.google.firebase:firebase-messaging:15.0.2'
    implementation 'com.firebaseui:firebase-ui-database:3.3.0'
    implementation 'com.google.firebase:firebase-auth:15.1.0'
    implementation 'com.facebook.android:facebook-android-sdk:4.32.0'
    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.google.android.gms:play-services-auth:15.0.1'
    implementation 'com.google.android.gms:play-services-places:15.0.1'
    implementation 'com.google.android.gms:play-services-cast:15.0.1'
    implementation 'com.google.android.gms:play-services-location:15.0.1'
    implementation 'com.google.android.gms:play-services-plus:15.0.1'
    implementation 'com.github.clans:fab:1.6.4'
    implementation 'com.thomashaertel:multispinner:0.1.1'
    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true;
    }
    // ShowCase View
    implementation 'com.github.mreram:ShowCaseView:1.0.5' // Agregado por Stiwart Antunez 01-05-2018
    implementation project(':library')
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

// Plugin para login con Gmail Firebase 17-12-206
apply plugin: 'com.google.gms.google-services'

### No Errors but show a Warning "Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {
" and looking now what meen this messages. :)

**Comment by stwasant** [comment]
I found how to fix the warning messages "Warning: The rule `-keep public class *extends java.lang.annotation.Annotation {"

In my Graddle App:
Commented this line:
//multiDexEnabled true

Reference link: [https://stackoverflow.com/questions/49518115/android-studio-3-1-warning-the-rule-keep-public-class-extends-java-lang-anno](url)

**Comment by kpamansoor** [comment]
I updated implementation 'com.google.firebase:firebase-messaging:15.0.0'
to implementation 'com.google.firebase:firebase-messaging:15.0.2'.

So it is worked.!!!

**Comment by shree-vastava** [comment]
@JayRichrd 
I am facing an exactly same issue.
Volley aar in app module
Volley aar in library module

app module uses library module

Were you able to fix it by any chance?

**Comment by hiteshcla00** [comment]
i got this error plz help
Program type already present: android.support.v4.app.LoaderManager |  
null |  
java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\CLA\IGText\app\build\intermediates\transforms\dexBuilder\debug\1.jar,
com.android.tools.r8.CompilationFailedException: Compilation failed to complete |  
com.android.tools.r8.utils.AbortException |

**Comment by saurabhdtu** [comment]
I agree with @tajchert ... 16.0.4 works perfectly fine... I hope the new update comes with this fix.

**Comment by GuanacoDevs** [comment]
Gradle warns that there is a new update for `firebase-core:16.0.4` (`16.0.5`), it's been more than a week already, when you make the change you get the error. The solution as pointed by @tajchert is to revert to `16.0.4` it is strange because if you check the [firebase](https://firebase.google.com/support/release-notes/android) release notes `16.0.5` is not there yet while any other update warn from Gradle about firebase works just fine but `core`

**Comment by NarendraSingh88** [comment]
> @hiddeneyes02 what version of Android Studio are you using? Could you try adding the following lines to your `gradle.properties` file and seeing if anything changes?
> 
> ```
> android.enableR8 = false
> android.enableD8 = false
> ```

Warning:The option 'android.enableD8' is deprecated and should not be used anymore.

**Comment by Vedkh** [comment]
if someone still has that issue, next build.gradle lines will help:
```
implementation ("com.google.firebase:firebase-database:18.0.1"){
   exclude group: "com.android.support"
}
```
