### ISSUE TITLE
Enable 'passwordless' sign-in flow

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1231]
The `12.0.0` release of `firebase-auth` enabled passwordless sign in flows where the user gets an link in his/her email and clicking the link deep links back into the app to complete the flow (using a one-time code).

We plan to add support for this to FirebaseUI in the future as it's a UI-heavy flow, although we of course need iOS support as well as some mocks from UX as to how this should look/flow.

Filing just to keep track.

**Comment by IchordeDionysos** [comment]
Any updateS on thiS?

**Comment by IchordeDionysos** [comment]
Oh and let me Share Some ideaS on how to improve the proeSS even more.

SlaCk doeS a pretty good job on thiS paSSwordleSS auth.
SlaCk preSentS you with the option to open your email app direCtly from the app and So the email iS only a few CliCk away.

See the SCreenShot below.

Oh and Sorry for the upperCaSe S and C :) Github won't allow me to type them and even thinkS I want to open a new iSSue when typing a C...

**Comment by IchordeDionysos** [comment]
https://cl.ly/1000291w2a0O

**Comment by mislav** [comment]
> Oh and Sorry for the upperCaSe S and C :) Github won't allow me to type them and even thinkS I want to open a new iSSue when typing a C...

This doesn't sound right 😕 If this keeps happening, please reach out to support@github.com and tell them your exact browser version and any browser extensions that you have installed!

**Comment by ganeshub** [comment]
Optionally If there is a option to get Fullname from user it will be useful.

**Comment by samtstern** [comment]
This has been released in version `4.3.0`.
