### ISSUE TITLE
Retrieve Credentials for Automatic Sign In & Smart Lock

### ISSUE THREAD

**Issue by GuanacoDevs** [firebase/FirebaseUI-Android#1232]
Is there any method in `AuthUI` that will allow me to request saved credentials for automatic Sign In or do I have to build it myself.
My flow is:
Splash Screen: If user is logged in already, opens the `Main Activity`, else will Sign In 'Anonymous' and then open the` Main Activity`, in the `Main Activity` the user may choose to sign in or not. The `AuthUI` Sign In happens in `Main Activity`, so if the user chooses to Sign Out, next time another Anonymous user will be created, I have already worked out the account upgrade and anonymous user deletion.
So what I'd like to do is in the` Splash Activity`, check if is Signed In already if not, check if it has saved credentials and Sign In or request to choose an account if there is no credentials just sign in Anonymously.
What would be my best approach in this matter or is there a way to do it with `AuthUI` already, that I have missed?

Best Regards
Ne0R@Cu

**Comment by SUPERCILEX** [comment]
Are you looking for something like [this](https://github.com/firebase/FirebaseUI-Android/pull/1212)? It sounds very close to what you're trying to do.

**Comment by GuanacoDevs** [comment]
@SUPERCILEX Yep, I have been following that thread, I'm eager for the release and to know how is it going to work. I started writing code to retrieve the credentials last week, but I was getting too many warnings "This method call is internal and not meant to be call by the app..." and then read that 12.0.0 had some bugs and to wait for 12.0.1.
Since my sign in flow starts as anonymous in the splash screen I just wonder if there will be methods to make it easier on my own(something to check for saved credentials and signin with them), or I'll have to write it myself.
You've already made it prettry easy.

**Comment by SUPERCILEX** [comment]
Have you seen the [docs](https://github.com/firebase/FirebaseUI-Android/pull/1212/files#diff-46b10a690795758a8db6b0f86c9afddc)? They describe exactly what you're looking for. If you want, I can also provide a dependency with that PR already merged...

**Comment by GuanacoDevs** [comment]
I was following exactly that when I was writing my code, but the amount of warnings turn me down, now with 12.0.1 I'll try again.
I opened this hopping that you might include something like AuthUI.getInstance().getSavedCredentials(). You already done the whole job, I know, since I'm using a Splash Screen to login anonymously and AuthUI in the Main Activity the sign in flow is a bit differen from most apps.
I think I'll wait for 3.4.0 to see how to work it out.
@SUPERCILEX 

Best Regards
