### ISSUE TITLE
Launching auth UI gives misleading and unhelpful message when the device is offline

### ISSUE THREAD

**Issue by CodingDoug** [firebase/FirebaseUI-Android#1234]
* Android device: Nexus 5X
  * Android OS version: 8.1
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.2.2

#### Steps to reproduce:

1. Take device offline, no internet
2. Invoke Google auth login via AuthUI
  
#### Observed Results:

Logcat says: "Sign in error 1"
Snackbar says: "Not signed in"
  
#### Expected Results:

More accurate and helpful snackbar and logcat message, for both the developer and the end user.  "Not signed in" doesn't give the user actionable steps to take.  If we know the device is offline, the messaging should at least indicate as much.  Logcat could be more helpful as well.

**Comment by samtstern** [comment]
@CodingDoug I cannot reproduce this with your steps.

**Scenario 1**
If I have the device completely offline _before_ entering the FirebaseUI flow then I see no UI, I get an immediate `onActivityResult` with the network error code and (at least for the sample app in this repo) I see a snackbar that says "No internet connection"

**Scenario 2**
If I enable network long enough to reach the FirebaseUI "NASCAR" screen (with all the login buttons), then disable internet while on that screen and then click "Sign in with Google" I see an account picker followed by a toast that says "an unknown error has occurred"

Note that I did this testing with version `3.3.0`, the latest.

**Comment by samtstern** [comment]
Closing due to stale-ness, sorry doug!
