### ISSUE TITLE
Dismiss loading dialog on authentication method picker when authentication fails

### ISSUE THREAD

**Issue by iainmcgin** [firebase/FirebaseUI-Android#124]
We do not correctly dismiss the loading dialog on the authentiation method picker screen if a chosen authentication method fails, [here](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/idp/AuthMethodPickerActivity.java#L226). Ensure that on failure the dialog is dismissed, the pertinent details of the failure are logged, and that the user is notified via a toast / snackbar what happened.

**Comment by iainmcgin** [comment]
Fixed by b605f0c6cc7b1db1808bb59c5c3cc20d90d0a209

**Comment by samtstern** [comment]
This issue is now fixed in version 0.4.1, please update your dependencies and thanks for the patience!
