### ISSUE TITLE
Does Firebase Auth uses Facebook Graph API?

### ISSUE THREAD

**Issue by Queskr** [firebase/FirebaseUI-Android#1241]
I've got a notice by Facebook to upgrade our API due to the use of an old Graph API version (v2.5).

**Comment by samtstern** [comment]
We use `com.facebook.android:facebook-login:4.31.0` so I don't believe we should have any issues, but I will look into it.

**Comment by samtstern** [comment]
Ok as far as I can tell, we are good to go.

You should try using the [API Upgrade Tool](https://developers.facebook.com/tools/api_versioning) on your app.  If you don't see any Graph API <= 2.5 calls then you won't have any problems.

**Comment by j2emanue** [comment]
if a facebook user has an non-email account, (for example uses phone number as user name instead of email ) will firebaseUI-ath ask the user to provide a email address or is that an implementation detail for the developer ?

**Comment by samtstern** [comment]
You can see here where we do the profile request:
https://github.com/firebase/FirebaseUI-Android/blob/6a86d992b8a4596924038d5724e05162d9cdefd6/auth/src/main/java/com/firebase/ui/auth/data/remote/FacebookSignInHandler.java#L138

We don't prompt the user if they don't have an email, that's something currently left to the developer.  If you could try using FirebaseUI with a non-email account and give me some feedback on it I'd be happy to consider some future changes to the behavior.
