### ISSUE TITLE
Expose isNewUser information in IDPResponse

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1242]
See:
https://github.com/firebase/FirebaseUI-Android/issues/1209#issuecomment-378708048

Currently we tell developers to rely on the created / signed in timestamps when checking to see if a `FirebaseUser` is new or not.  However these timestamps have some limitations that make them occasionally unreliable.

If we could expose this information in the response we provide at the end of the AuthUI flow, that would help developers launch follow-up flows.

**Comment by curiousily** [comment]
Is there any **reliable way** to workaround this using the current version of the library?

**Comment by samtstern** [comment]
@curiousily the timestamps are reliable with the edge case issue that if a new user signs up, signs out, and signs in within two minutes they will still look "new" because the timestamps wont change.

**Comment by j2emanue** [comment]
you guys can also send a flag in onActivityResult intent. like a boolean to represent if its new or existing.

**Comment by j2emanue** [comment]
guys, its me again. so i noticed one strange thing.  my business has both website and app but use same firebase authentication table.   so i signed up for a new account on our website as an email provider.  checked firebase console and saw the account there as email provider. waited almost 2 hours..... then logged into app with email provider, but to my surprise it found it as a new signup.  so i checked and the following was true, why ?

**metadata.creationTimestamp == metadata.lastSignInTimestamp**

after waiting almost 2 hours should this not be false.  is this check only local to the mobile application ?

**Comment by curiousily** [comment]
Hey @samtstern,

Any progress on this issue? This really degrades the experience for our users.

**Comment by samtstern** [comment]
This has been released in version `4.1.0`

**Comment by AndrazP** [comment]
Hi @samtstern 
I found this old issue after noticing that comparing timestamps
`metadata.getCreationTimestamp() == metadata.getLastSignInTimestamp()`
is not reliable. `isNewUser` seems to fix it.
Are there any drawbacks of using this method? Why is comparing timestamps still recommended in README?

**Comment by samtstern** [comment]
@AndrazP I think I just forgot to update the README!  `isNewUser` is preferred.   Want to send a PR and fix the README?
