### ISSUE TITLE
Kotlin App Build Issue

### ISSUE THREAD

**Issue by JitenderSha** [firebase/FirebaseUI-Android#1248]
I am developing the app using Kotlin and found error while using the com.firebaseui:firebase-ui-auth:3.3.0

### Describe your environment
  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  * FirebaseUI version: 3.3.0
  
### Step 3: Describe the problem:
* Not able to use the FirebaseUI with Kotlin

#### Steps to reproduce:

  1. Add FirebaseUI version 3.3.0
  2. Build the App
  3. Error occured
  
#### Observed Results:
  *Error in Gradle Console
* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex
 
  
#### Relevant Code:

  ```
implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
  ```

**Comment by btrautmann** [comment]
Have you checked to ensure you've not hit dex limit?

**Comment by samtstern** [comment]
Yes I believe @btrautmann is right.  @JitenderSha please see: https://developer.android.com/studio/build/multidex.html
