### ISSUE TITLE
Twitter Provider

### ISSUE THREAD

**Issue by squm** [firebase/FirebaseUI-Android#1251]
### Step 2: Describe your environment

  * Android OS version: 27
  * Firebase/Play Services SDK version: 12.0.1
  * FirebaseUI version: 3.2.2
  
### Step 3: Describe the problem:

Warning: com.firebase.ui.auth.provider.TwitterProvider: can't find referenced class retrofit2.Call
Warning: com.firebase.ui.auth.provider.TwitterProvider: can't find referenced class retrofit2.Call

#### Relevant Code:
  ```
	implementation 'com.google.firebase:firebase-core:12.0.1'
	implementation 'com.google.firebase:firebase-auth:12.0.1'
	implementation 'com.firebaseui:firebase-ui-auth:3.2.2'
  ```

**Comment by SUPERCILEX** [comment]
Yup, this was fixed in 3.3. 👍
