### ISSUE TITLE
 Execution failed for task ':app:processDebugManifest'. > Manifest merger failed 

### ISSUE THREAD

**Issue by bilal-kathia** [firebase/FirebaseUI-Android#1255]
**Error:**
	Attribute meta-data#com.facebook.sdk.ApplicationId@value value=(@string/FACEBOOK_APP_ID) from AndroidManifest.xml:39:13-52
	is also present at [com.firebaseui:firebase-ui-auth:3.3.0] AndroidManifest.xml:21:13-60 value=(@string/facebook_application_id).
	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:37:9-39:54 to override.
FAILURE: Build failed with an exception.

"I am attaching AndroidManifest.xml as well. Kindly, find error.

**Thanks!**
![fb_id](https://user-images.githubusercontent.com/30662760/38759309-b2c75280-3f8e-11e8-99dc-2ee738a4b6cd.png)
![fb_id](https://user-images.githubusercontent.com/30662760/38759328-c848fe56-3f8e-11e8-903b-ed83de72b446.png)

**Comment by SUPERCILEX** [comment]
Simply remove the `ApplicationId` meta data.

**Comment by samtstern** [comment]
@SUPERCILEX is right.  Also questions like this are normally better suited for StackOverflow as it's just a config error (with a solution in the error message).

**Comment by bilal-kathia** [comment]
@SUPERCILEX 
That is attached to account kit SDK. I can't remove that meta data tag :(

**Comment by bilal-kathia** [comment]
@samtstern Yeah you're right but i couldn't get any help from there!

**Comment by SUPERCILEX** [comment]
You can remove it because FUI handles it for you.
