### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException Attempt to invoke virtual method 'android.support.v4.app.FragmentTransaction android.support.v4.app.FragmentManager.beginTransaction()' on a null object reference

### ISSUE THREAD

**Issue by RAHUL-SADHU** [firebase/FirebaseUI-Android#1261]
android.support.v4.app.DialogFragment.dismissInternal (DialogFragment.java:218)
--
 android.support.v4.app.DialogFragment.dismissAllowingStateLoss (DialogFragment.java:200)
com.firebase.ui.auth.ui.phone.PhoneActivity.dismissLoadingDialog (PhoneActivity.java:400)
com.firebase.ui.auth.ui.phone.PhoneActivity.showLoadingDialog (PhoneActivity.java:389)
com.firebase.ui.auth.ui.phone.PhoneActivity.submitConfirmationCode (PhoneActivity.java:173) com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment.submitConfirmationCode (SubmitConfirmationCodeFragment.java:177) com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment.access$400 (SubmitConfirmationCdeFragment.java:45)
com.firebase.ui.auth.ui.phone.SubmitConfirmationCodeFragment$2.onClick (SubmitConfirmationCodeFragment.java:171)
android.view.View.performClick (View.java:5612)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)

**Comment by venkataseshaiahudatha** [comment]
do we have solution for this issue
