### ISSUE TITLE
Query order and limit in the Firestore FirebaseUI chat app

### ISSUE THREAD

**Issue by b-fg** [firebase/FirebaseUI-Android#1267]
I am trying to implement a chat app using the FirebaseUI for Firestore in an Android device. Specifically, I am looking at [these classes](https://github.com/firebase/FirebaseUI-Android/tree/master/app/src/main/java/com/firebase/uidemo/database/firestore).

The issue arises with the default query to get the last 50 messages ordered by their timestamp:
`Query sChatQuery = sChatCollection.orderBy("timestamp").limit(50);`
This query orders the messages by timestamp (from old to new) and gets the 50 first messages. Hence, when the limit is exceeded the newest messages are not retrieved. Is this behaviour expected?
The only way I have been able to retrieve the last 50 messages is by:
`Query sChatQuery = sChatCollection.orderBy("timestamp", Query.Direction.DESCENDING).limit(50);`
However, they are retrieved in the wrong order (from new to old) and I cannot locally reverse them since the data array is somewhere hidden in the FirebaseUI library and I cannot find it.

I have also opened [this question](https://stackoverflow.com/questions/50032569/firestore-chat-app-using-firebaseui-android) in stackoverflow.com regarding this issues.

Thanks.

**Comment by samtstern** [comment]
@b-fg that's a good point!  I am fixing this in the demo app in #1268.  Check out the code there for the solution you want.

**Comment by b-fg** [comment]
Thanks, that was precisely the solution I was already using.
