### ISSUE TITLE
Incomplete documentation for firebase-ui-auth

### ISSUE THREAD

**Issue by brezinajn** [firebase/FirebaseUI-Android#127]
There are few neat features in new release. Unfortunately there seems to be no documentation available (at least I weren't able to find one :D) . For example the new sign up feature is awesome, but I need to create few fields for each registered user. Or (different case) I'd like to be able to disable the sign up feature. How would one go about that?

Keep up the awesome work :+1:

**Comment by samtstern** [comment]
@brezinajn thanks for trying the library. We are definitely working on expanding the documentation to cover the whole API surface.

If you have specific questions about the API I'm happy to answer them here.

**Comment by brezinajn** [comment]
I'd like to know if there is possibility to disable the sign up.

**Comment by sathe-aditya** [comment]
Hello! I had an issue with firebase. For dummy users, I was providing 3-4 lettered passwords, but firebase needs at least 6 characters. Could I modify the documentation accordingly? :)

**Comment by samtstern** [comment]
@sathe-aditya did the UI not tell you to use a 6 character password?  When I try to use a short password I see the error on screen "Strong passwords have at least 6 characters and a mix of letters and numbers".

**Comment by samtstern** [comment]
I am going to close this issue as it's pretty old and not specific enough to address.  @brezinajn @sathe-aditya if you see anything in the documentation that you want to change, please send over a PR!
