### ISSUE TITLE
Error:Execution failed for task ':app:preDebugAndroidTestBuild'. > Conflict with dependency 'com.android.support:support-annotations' in project ':app'. Resolved versions for app (26.1.0) and test app (27.1.1) differ. See https://d.android.com/r/tools/test-apk-dependency-conflicts.html for details.

### ISSUE THREAD

**Issue by royal008** [firebase/FirebaseUI-Android#1272]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@royal008 please fill out the issue template when filing an issue.  As I can see from the issue title, this is not a FirebaseUI issue but a normal dependency issue.  If you need help solving it please try StackOverflow.

**Comment by CUET-sajib10** [comment]
I solved this problem by changing in app.gradle as following -
Replacing 
implementation 'com.android.support:appcompat-v7:26.0.1' 
wihth
implementation 'com.android.support:appcompat-v7:27.1.1'

**Comment by abhilashasurmount** [comment]
Replace 
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
with 
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

**Comment by SubhamKuswa** [comment]
implementation 'com.android.support:appcompat-v7:26.0.1'
with
implementation 'com.android.support:appcompat-v7:27.1.

> **This solution is working only for one project when i create new project same issue is occuring
> i know i can replace these line in every project but i  want to know why it is happenning**

**Comment by abhilashasurmount** [comment]
implementation 'com.android.support:appcompat-v7:26.0.1'
with
implementation 'com.android.support:appcompat-v7:27.1.
This solution is working only for one project when i create new project same issue is occuring i know i can replace these line in every project but i want to know why it is happening.

This happens because while creating project you are not setting correct **compileSdkVersion**, **minSdkVersion** & **targetSdkVersion**. Make sure these three values matches the required version.

@SubhamKuswa

**Comment by SubhamKuswa** [comment]
thank you i will try it..

**Comment by rajbhalala** [comment]
@SubhamKuswa did you able to solve this problem ? because i am facing the same problem
