### ISSUE TITLE
 Could not find method getCompileConfiguration() for arguments []

### ISSUE THREAD

**Issue by anuj-njoshi** [firebase/FirebaseUI-Android#1277]
I am getting following error when building  app.
Could not find method getCompileConfiguration() for arguments [] on object of type com.android.build.gradle.internal.api.ApplicationVariantImpl
I am working on ionic 1  android app development.
When i faced firebase conflict version issue  i did following changes in project.Properties

```
target=android-26
android.library.reference.1=CordovaLib
cordova.system.library.1=com.android.support:support-v4:+
cordova.system.library.2=com.google.firebase:firebase-core:11.4.2
cordova.system.library.3=com.google.firebase:firebase-messaging:11.4.2
cordova.gradle.include.1=cordova-plugin-fcm/app-FCMPlugin.gradle
cordova.gradle.include.2=com-sarriaroman-photoviewer/app-photoviewer.gradle
cordova.system.library.4=com.android.support:support-v4:26.+
cordova.system.library.5=com.android.support:appcompat-v7:26.+
cordova.system.library.6=com.android.support:support-v4:+
cordova.system.library.7=com.google.android.gms:play-services-location:11.4.2
cordova.system.library.8=com.google.android.gms:play-services-analytics:11.4.2
```

 dependencies {
        classpath 'com.android.tools.build:gradle:+'
        classpath 'com.google.gms:google-services:+'
    }
and 
 maven {
        url "https://maven.google.com" // Google's Maven repository
    } in build.gradle

**Comment by samtstern** [comment]
@anuj-njoshi sorry I don't know anything about Cordova or Ionic, we don't officially support those platforms when using FirebaseUI for Android since the error surface is so large.  Please try asking this question on StackOverflow, good luck!

**Comment by aqeelmashkraft16** [comment]
change this line
classpath 'com.google.gms:google-services:+'
to
classpath 'com.google.gms:google-services:3.2.1'
in file  android-FCMPlugin.gradle
is worked for me

**Comment by iamsudz** [comment]
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApkCopy'.
   > Could not find com.google.firebase:firebase-core:11.4.2.
     Required by:
         FIRENOTIFY:app:unspecified




my app name is FIRENOTIFY

**Comment by SafeSoft-tlt** [comment]
Is worked for me!
