### ISSUE TITLE
Proguard breaks on the latest update.

### ISSUE THREAD

**Issue by gelodgreat** [firebase/FirebaseUI-Android#1281]
![image](https://user-images.githubusercontent.com/20021423/39561363-b510f0ca-4ed7-11e8-9678-6c6e23124544.png)

**Comment by SUPERCILEX** [comment]
We don't support 16.0.0 yet, sorry. Speaking of, @samtstern do we want to break compatability too in 3.4 or bump up to 4.0? And do we want to keep unified versions (I'm in favor since it's a relatively simple project)?

**Comment by gelodgreat** [comment]
so should i downgrade to 15.0.0?

**Comment by SUPERCILEX** [comment]
Yes, it's going to crash at runtime anyway.

**Comment by samtstern** [comment]
@gelodgreat as @SUPERCILEX said, we have some work to do before `16.0.0` will work with FirebaseUI.
