### ISSUE TITLE
Grammar issue on FirebaseUI docs

### ISSUE THREAD

**Issue by Feramance** [firebase/FirebaseUI-Android#1282]
There's a grammar mistake in the bullet point letting users know where to report an issue:

If you find **AND** issue in FirebaseUI and would like to report it, use the GitHub issue tracker.

That and is meant to be an **AN**

Regards, 
Feramance

**Comment by SUPERCILEX** [comment]
In what file is this?

**Comment by Feramance** [comment]
It’s in the following link at the bottom of the page under next steps: https://firebase.google.com/docs/auth/android/firebaseui

Regards,
Shaun Agius

**Comment by samtstern** [comment]
@Feramance thanks, I'll get that fixed over there.
