### ISSUE TITLE
[Discuss] New Firebase / Play services SDK versioning

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1283]
@SUPERCILEX opening this issue as a discussion thread.

Starting with version `15.0.0`, the various Firebase / Play services SDKs have been decoupled and are now free to have their own, semantic version numbers.  This can be seen in the release on 5/2/2018 where some modules went to `15.0.2`, some to `15.1.0`, and some to `16.0.0` depending on the changes they were shipping.

Some big changes due to this:

- The dependency tree is now encoded properly in the Maven `pom.xml` files.  However we know that Gradle has some strange dependency resolution tactics.  In the old system if you had a build error with one of these libraries the solution was to make sure that all of them were the same version (incl your transitive dependencies).  Now that advice is more complicated, but we hope to make the `google-services` gradle plugin able to diagnose these errors and suggest fixes.
- Rather than being ProGuarded and released all together, the libraries are now divided into smaller groups that have inter-library dependencies.  Some libraries that have no dependencies are in their own group.
- We should see more frequent releases as one library group can't hold another library group back.  The previous release schedule was sort of on a least-common-denominator speed.
- Most libraries will continue to have very infrequent breaking changes, as developers generally don't appreciate them.  However some libraries, like Cloud Firestore, that have "beta" status may break more frequently.  We can see this in `16.0.0`.
- In the event that a meaningful change is made to a foundational library (something like `Tasks`) it may require an old-school style release where all the libraries bump their versions together.

What it means for FirebaseUI:

- To support Firestore's breaking changes, we probably need to move to `4.0.0`.  We should use this as an opportunity to clean up any long-deprecated pieces of the API as well and take on any other breaking proposals (within reason).
- We'll have to update the documentation about dependencies.
- Expect new and exciting error messages in the Github issue tracker.

**Comment by SUPERCILEX** [comment]
@samtstern Wow, thanks for the super detailed explanation! I'm assuming this will be explained in an I/O too, but I'm all for getting the early scoop. 😉

Looks like we're on the same page! I was also thinking it's time to get rid of all the deprecated auth stuff so 4.0 sounds great. Do you think we should turn 3.4 into 4.0? That makes sense to me since we'd be shipping the paging stuff, making the release sound cooler. 😁 (Also, maybe 1.0 will be out by then.)

> Expect new and exciting error messages in the Github issue tracker.

🤣

**Comment by samtstern** [comment]
Yeah I am thinking `3.4.0` can become `4.0.0` since one of the major features is paging and it seems silly to release a new Firestore feature against an old major version SDK.

Also don't expect much noise about this at I/O since it's a pretty niche topic, but here's a blog post explaining some more:
https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html

**Comment by samtstern** [comment]
This has been fixed and released in `4.0.0`
