### ISSUE TITLE
Lock orientation to portrait when signing using Facebook

### ISSUE THREAD

**Issue by curiousily** [firebase/FirebaseUI-Android#1294]
FirebaseUI merges it's manifest with that of your app (which supports only portrait mode). During login the users can rotate the device and enter our app in landscape mode. Is it possible to force the Facebook login to be only in portrait mode? How about Google+?

**Comment by samtstern** [comment]
@curiousily I apologize for not responding earlier but I don't think there is anything we can/should do here.  The best thing may be to try and detect the device orientation when the sign-in flow completes and make the user rotate (or do it for them) if they are somehow in landscape.
