### ISSUE TITLE
Reconsider an RTDB paging adapter

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1296]
Based on the compromises we made for Firestore, I think we could make an RTDB paging adapter with equivalent functionality.  Previous discussions focused on the difficulty of managing realtime listeners but that's not a concern at the moment.

(Related #17)

**Comment by rosariopfernandes** [comment]
Is this issue still relevant? It seems like our RTDB paging adapter already has the same functionality as the firestore one.

**Comment by samtstern** [comment]
@rosariopfernandes good call!

**Comment by rosariopfernandes** [comment]
@samtstern However, we could replace the current `singleValueEventListener` with the new `Task<DataSnapshot> get()` to avoid getting stale results from cache as [puf explains here](https://stackoverflow.com/a/66072472/5861618). I believe that would make it more consistent with Firestore?

**Comment by samtstern** [comment]
@rosariopfernandes I think that's a good idea!
