### ISSUE TITLE
Firebase reading and writing works on one phone but not on another

### ISSUE THREAD

**Issue by brownninjaturtle** [firebase/FirebaseUI-Android#1305]
I have an app where I read and write from the firebase database (currently using 15.0.0). Everything works fine with a nexus phone but when using a different phone (moto g5), I am unable to read or write to the database. I have tried upgrading the dependency version to the latest with no success. I have had success with database communication using android 7.0 emulated and 8.0 on an actual device (nexus). Is there some firewall or privacy issue that I am missing that is preventing the moto g5 phone to not work when communicating with the database?

**Comment by samtstern** [comment]
@brownninjaturtle sorry for the late response but I am going to close this issue because there is no evidence provided that it has to do with FirebaseUI.  Please try a more general forum (like StackOverflow) to get help with this.
