### ISSUE TITLE
NullPointerException when calling `FirebaseUser.linkWithCredential`

### ISSUE THREAD

**Issue by islamassi** [firebase/FirebaseUI-Android#1307]
* Android device: different devices
  * Android OS version: 5-8
  * Google Play Services version: 3.2.1
  * Firebase/Play Services SDK version: 12.0.1
  * FirebaseUI version: none
  
  
#### Problem

Crash when calling `FirebaseUser.linkWithCredintials(credential)` inside the `CompleteListener` of `FirebaseAuth.signInAnonymously()`.

#### Observed Results:

`
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'com.google.android.gms.tasks.Task com.google.android.gms.common.api.GoogleApi.zzb(com.google.android.gms.common.api.internal.zzde)' on a null object reference
com.google.android.gms.internal.zzdza.zzb (Unknown Source)
com.google.android.gms.internal.zzdzh.zzd (Unknown Source)
com.google.firebase.auth.FirebaseAuth.zzc (Unknown Source)
com.google.firebase.auth.FirebaseUser.linkWithCredential (Unknown Source)
arrow_right
yamsafer.yamsafer.me.Managers.FirebaseUserManager.lambda$anonymousFirebaseLogin$140$FirebaseUserManager (FirebaseUserManager.java:269)
yamsafer.yamsafer.me.Managers.FirebaseUserManager$$Lambda$4.onComplete (Unknown Source)
com.google.android.gms.tasks.zzf.run (Unknown Source)
android.os.Handler.handleCallback (Handler.java:751)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6682)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1520)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1410)
`

**## Fabric link:**  . [http://crashes.to/s/e1459e8ebb1](url)

#### Other logs:
`
1
6:02:59 AM
D/CrashlyticsCore start_app

2
6:02:59 AM
D/CrashlyticsCore activity SplashActivity onCreate() critic.Mem:false

3
6:02:59 AM
D/CrashlyticsCore activity SplashActivity onResume() critic.Mem:false

4
6:03:01 AM
D/CrashlyticsCore GMS_CRASH: credential Not null, provider: password , signInMethod: password ,currentActivity:Activitys.SplashActivity
`

**Comment by samtstern** [comment]
@islamassi since you said "FirebaseUI version: none" it doesn't seem like you have filed this in the right place.  Maybe you want to try reaching out to Firebase support?
