### ISSUE TITLE
No resource found that matches the given name

### ISSUE THREAD

**Issue by ahaverty** [firebase/FirebaseUI-Android#1317]
* FirebaseUI version: 4.0.0
  
### Step 3: Describe the problem:
Unable to build firebase ui v4.0.0

#### Steps to reproduce:
Attempt to build with v4.0.0
  
#### Observed Results:

`No resource found that matches the given name (at 'layout_constraintBottom_toTopOf' with value '@id/main_tos_and_pp').`

**Comment by ahaverty** [comment]
It's this ID that's giving me build issues
https://github.com/firebase/FirebaseUI-Android/blame/7d7a1fcd7ac9b012f2c9dd8d4f17eb979449e22d/auth/src/main/res/layout/fui_auth_method_picker_layout.xml#L36

**Comment by SUPERCILEX** [comment]
@ahaverty What Android Gradle Plugin version are you using? Pre 3.0? Did you disable AAPT2?

@samtstern Looks like our lint check is broken. 😢 It was supposed to ensure we `@+id`ed stuff, right?

**Comment by samtstern** [comment]
Huh yeah I also think the lint check is broken it is spitting a bunch of
Kotlin nonsense.

**Comment by Beb3r** [comment]
yupe got the same with:
classpath 'com.android.tools.build:gradle:3.1.2'
implementation 'com.google.firebase:firebase-core:16.0.0'
    implementation 'com.google.firebase:firebase-messaging:17.0.0'
    implementation 'com.google.firebase:firebase-database:16.0.1'
    implementation 'com.google.firebase:firebase-storage:16.0.1'
    implementation 'com.google.firebase:firebase-auth:16.0.1'
    implementation 'com.firebaseui:firebase-ui-auth:4.0.0'

**Comment by SUPERCILEX** [comment]
#1321 inadvertently solves this by upgrading lint.

**Comment by samtstern** [comment]
This has been fixed and released in `4.0.1`
