### ISSUE TITLE
AuthUi null pointer exception

### ISSUE THREAD

**Issue by plugie** [firebase/FirebaseUI-Android#1319]
Info related crash can be found at: http://crashes.to/s/b69fd713da6

Steps to reproduce:
Login in using Firebase Auth Ui
This crash is rarely happen.

  ```
  // TODO(you): code here to reproduce the problem
  My code in MainActivity.java
startActivityForResult(
                            AuthUI.getInstance()
                                    .createSignInIntentBuilder()
                                    .setTheme(R.style.AppTheme)
                                    .setAvailableProviders(
                                            Arrays.asList(
                                                    new AuthUI.IdpConfig.GoogleBuilder().build(),
                                                    new AuthUI.IdpConfig.FacebookBuilder().build()))
                                    .build(),
                            RC_SIGN_IN);

**Comment by plugie** [comment]
I am using FirebaseUi version 3.3.0

Below is my dependencies :

`dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'


    implementation 'com.android.support:support-v13:27.1.1'
    implementation 'com.android.support:customtabs:27.1.1'
    implementation 'com.android.support:design:27.1.1'
    //implementation 'com.android.support:palette-v7:27.0.2'
    implementation 'com.android.support:animated-vector-drawable:27.1.1'
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support:recyclerview-v7:27.1.1'
    implementation 'com.android.support:cardview-v7:27.1.1'

    implementation 'de.greenrobot:eventbus:2.4.0'
    implementation 'com.commonsware.cwac:provider:0.3.0'

    implementation 'com.google.android.gms:play-services-vision:12.0.1'
    implementation 'com.google.firebase:firebase-ads:12.0.1'

    implementation 'com.google.firebase:firebase-messaging:12.0.1'
    implementation 'com.google.firebase:firebase-database:12.0.1'
    implementation 'com.firebaseui:firebase-ui-auth:3.3.0'
    implementation 'com.facebook.android:facebook-android-sdk:4.31.0'

    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.9.0'

    implementation 'com.andrognito.pinlockview:pinlockview:2.1.0'

    implementation('com.crashlytics.sdk.android:crashlytics:2.9.1@aar') {
        transitive = true;
    }
}`

**Comment by samtstern** [comment]
@plugie please update to the newest version of FirebaseUI if you can (version `4.0.0`).

**Comment by samtstern** [comment]
Closing due to outdated lib and lack of response.
