### ISSUE TITLE
Landscape Auth Picker

### ISSUE THREAD

**Issue by GuanacoDevs** [firebase/FirebaseUI-Android#1333]
Is it possible to lock the FUI Auth Picker to a orientation.
Any chance to redesign the landscape layout, now with TOS & PP, doesn't look good, see attached
Thank You
![screenshot_20180531-180636](https://user-images.githubusercontent.com/32036535/40820553-709a28fa-651e-11e8-87fd-34f12ee65dcb.png)

**Comment by SUPERCILEX** [comment]
Yup, the fix is already targeted for 4.1. A snapshot build might be available tomorrow depending on how things go.
