### ISSUE TITLE
Facebook "Firebase login unsuccessful"

### ISSUE THREAD

**Issue by ryanzor** [firebase/FirebaseUI-Android#134]
When I'm using Facebook login I see the permission dialog.  After accepting I am brought to the screen with the login options, a progress dialog is displayed, the dialog can not be dismissed.

The log says:

05-22 10:54:49.417 30725-30725/com.ryanzor.thegang W/AuthMethodPicker: Firebase login unsuccessful

**Comment by iainmcgin** [comment]
If you are using the same test device, this is likely related to #133 - if the firebase auth library is not functional on the device, none of the authentication methods will work.
