### ISSUE TITLE
Android studio does not recognize the project as android project

### ISSUE THREAD

**Issue by abdurahmanadilovic** [firebase/FirebaseUI-Android#1349]
I cloned the repository and I tried to open it with Android studio and got nowhere, what is a proper way to open this project with android studio 3.1.3?

**Comment by samtstern** [comment]
@abdurahmanadilovic I am also using Studio `3.1.x` but (obviously) I can't see the same problem.  Please provide more information, otherwise I think this is an issue with your machine/configuration.

**Comment by abdurahmanadilovic** [comment]
I tried to clone the project then open the cloned folder in the android studio and also I tried to clone the repo through the Android studio, using the create new project from source control option and I am unable to build the project with both methods.

In the project explorer if I select android nothing shows up if I select Project view [this is only what appears in the explorer](https://imgur.com/a/jQmc8wI)

I guess the build.gradle.kts might cause this issues since android studio is looking for build.gradle without the .kts extension?

**Comment by SUPERCILEX** [comment]
Oh, that's because you didn't import it from Gradle properly. `Ctrl + E` to get to the Gradle sidebar. Then click the + button to add the root module and start a sync. If that doesn't work, close the project and delete the `.idea` folder. Then choose import from existing sources and go through the Gradle flow.

**Comment by abdurahmanadilovic** [comment]
So [this happens if](https://imgur.com/a/bJe0n6K) I try to import a gradle project. It detects multiple android / java modules and none of them are runnable. If I understood you correctly I should select import project then select gradle, instead of "Open an existing Android Studio project"?

**Comment by SUPERCILEX** [comment]
In the second step, you should have clicked the `Import project from external model` option. Be sure to delete the `.idea` folder again before importing.

**Comment by abdurahmanadilovic** [comment]
I managed to build the project by selecting "import project from external model", now everything works, thanks for helping me out.

**Comment by sushihangover** [comment]
FYI: I am using AS 3.2C18 and since there is an existing repo-based file within .idea:

* .idea/codeStyleSettings.xml

Importing via Gradle fails to import the project properly. 

Deleting the `.idea` directory and re-importing from external model works fine.

**Comment by sugoireed** [comment]
What worked for me was 

On Android Studio 

Open the settings.gradle file

include your project

include ':myproject'

**Comment by ashomokdev** [comment]
To open the project you need to have Gradle installed on your PC. Then 
Download repo FirebaseUI-Android from github. 
In your Android Studio File -> New -> Import Project -> FirebaseUI-Android-master Path -> Import project from external model -> Gradle (!) -> Use local gradle distribution

If it not helps, add **local.properties** file to the root of FirebaseUI-Android-master with next line (edited for you) sdk.dir=/home/yuliia/Android/Sdk

**Comment by AdamSHurwitz** [comment]
Thanks for the recent update @ashomokdev ! I've followed your steps and am unfortunately running into the following build [error](https://docs.google.com/document/d/137Vs8EYba5aw8Nl_3svJrZDYN42U07EBu5r0KWC0IvA/edit?usp=sharing).

#Implementation

1. `git clone git@github.com:firebase/FirebaseUI-Android.git`
2. Android Studio: **File > New > Import Project > _FirebaseUI-Android_ path > _Import project from external model_ > _Gradle_ > _Use local gradle distribution_ > Select _Yes_ to override existing _.Idea_ file > Select _Configure_ when _Android framework is detected_ dialog is displayed.**
3. Once I received the build error above, I followed your advice and  added the **local.properties** file to the root _FirebaseUI-Android_ directory. I found the Android SDK path in terminal and used the `pwd` command to retrieve the path: `sdk.dir=/Users/adamhurwitz/Library/Android/sdk`
4. I attempted re-importing after adding the _local.properties_ file with the same build error.

#Attempted Solutions
I've also attempted the following variations in the import process:

- All of the below variations were tested with both file paths 1) **File > New > Import Project > _FirebaseUI-Android_ path > ...** and 2) **File > New > Import Project > _app_ path  > ...**. 
- **File > New > Import Project > _FirebaseUI-Android_ path > _Create project from existing sources_ > ...**
- **File > New > Import Project > _FirebaseUI-Android_ path > _Import project from external model_ > _Android Gradle_ > ...** ([different build error message](https://docs.google.com/document/d/1LNjOvDJvkubFsXDjnJ6qqAhkSY9teeors4mx8IVIhJo/edit?usp=sharing)).

**Comment by IMasood** [comment]
Error occurring after importing project
I have explained all these details overhere https://stackoverflow.com/questions/55333262/after-importing-project-in-android-studio-there-are-some-errors-in-xml-file-like?noredirect=1#comment97393690_55333262

**Comment by IshuDeve** [comment]
Hi I have a problem when i connect Firebase to android It always occurred some error

**Comment by rachittt** [comment]
Doing a simple 'sync with gradle' solved my problem :D

**Comment by jhonatansabadi** [comment]
Close your project on Android Studio, then delete .idea folder, then open open your project.

**Comment by albertocapired** [comment]
Same problem: lost gradle, github is useful to me about interesting code here, but the projects implementation and cloning is very complicate, I see this in multpipe github blogs like this, sorry Microsoft

**Comment by yogesh-sirsat** [comment]
> What worked for me was
> 
> On Android Studio
> 
> Open the settings.gradle file
> 
> include your project
> 
> include ':myproject'

also worked for me, thanks man

**Comment by mohitkumarsoni** [comment]
in my case i downloaded zip file from telegram desktop & unzipped in same folder so i got this problem,

save your unzipped project at other location like desktop & than open project will solve your problem, good luck
