### ISSUE TITLE
FirebaseRecyclerAdapter view filter

### ISSUE THREAD

**Issue by sivai2i** [firebase/FirebaseUI-Android#135]
I need to filter the data in client side from FirebaseRecyclerAdapter. Is there any way to do it without removing the data in firebase database?

**Comment by puf** [comment]
At the moment, server-side filtering is your best option. We're considering adding client-side filtering (#15), but it's not a very natural fit with the realtime nature of the Firebase Database.

**Comment by sivai2i** [comment]
Then is there any options to filter not equal to any specific value in query.?

**Comment by puf** [comment]
The query model of the Firebase Database does not support a "not equal"
filter.

But performing such a filter client-side would in that case also not be a
good solution, since you'd be pulling down more data than needed.

A better option would be to model your data in a way that allows this query
For example if you put all the items that have the "not equal" condition
under a common node, you won't need a query at all. This sort of custom
indexing is quite common with Firebase and NoSQL databases in general.

**Comment by sivai2i** [comment]
But I couldn't have a model like that.  Let me tell the scenario which i am facing now. I am developing a chat application where i need to show the list of registered users. All users are under the same node "user". I am fetching all the users from this node so, I need to filter current user from the list of users.

**Comment by jishincreo** [comment]
**Exact same issue that I'm facing.** Can anyone help us one this one?

 @sivai2i , A temporary solution for this would be to let the `FirebaseRecyclerViewAdapter` work the way it works, but in your `ViewHolder`, you just show the current user as the current user("You") and disable the click event or any other action in general to the `RecyclerView`.

**Comment by Aki58** [comment]
same problem here

**Comment by magdini** [comment]
I have same problem too. I want to show a list of users except the current user

**Comment by eth0izzle** [comment]
In your populateViewHolder() call do something like:

                if (user.id.equalsIgnoreCase(application.getUser().id))
                    return;

and override getItemCount() to return count - 1 (you want to handle instances where count will be 0, etc).

**Comment by tango4567** [comment]
![device](https://user-images.githubusercontent.com/2922986/29684338-3960ba5a-892f-11e7-98d1-b6c5f2a28573.jpeg)

**Comment by samtstern** [comment]
@sivai2i are you maybe using `INVISIBLE` when you should be using `GONE` to hide views?

**Comment by Kishanjvaghela** [comment]
I have created custom FirebaseRecyclerAdapter that support the Filterable feature.
[Custom Filterable FirebaseRecyclerAdapter](https://gist.github.com/Kishanjvaghela/67c42f8f32efaa2fadb682bc980e9280)

**Comment by Ananthusubramanian** [comment]
Is there any way to stop accessing a particular child from a node using firebase rules? So this problem can be solved easily?
