### ISSUE TITLE
Create a publicly usable lint module

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1351]
See #1340 which implements new lint checks but is not yet exposed because it's in `internal`.

**Comment by samtstern** [comment]
cc @pavlospt

One possible roadblock here: the lint checks are written in Kotlin and we have not yet shipped any Kotlin to developers.  I am not sure how this will impact their builds...

**Comment by pavlospt** [comment]
Isn't just a jar shipped as a dependency for Lint modules? Would this also bring the whole Kotlin stdlib in?

**Comment by samtstern** [comment]
This was fixed and released in version `4.2.0`
