### ISSUE TITLE
Google Auth token 

### ISSUE THREAD

**Issue by YogeshTripathi5** [firebase/FirebaseUI-Android#1359]
Want to get the google sign in auth token while signing in via google.Is their any way out while using firebase ui

**Comment by samtstern** [comment]
@YogeshTripathi5 we don't provide this information directly from FirebaseUI, but if your user has recently signed in successfully with Google through FirebaseUI then you should be able to use the Google Sign In `silentSignIn` method to quickly get the access token in the background.
