### ISSUE TITLE
Twitter login does not work anylonger since June and I can't seem to fix it in anyway.

### ISSUE THREAD

**Issue by devingDev** [firebase/FirebaseUI-Android#1360]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Emulator Nexus 5X API 27 x86 
  * Android OS version: 8.1.0
  * Google Play Services version: 12.5.21 (on device)
  * Firebase/Play Services SDK version:  :firebase-core:16.0.1  / :play-services-auth:15.0.1.1 / :google-services:4.0.1
  * FirebaseUI version: :firebase-ui-auth:4.0.1.1
  
### Step 3: Describe the problem:
Problem is that since June Twitter seems to enforce something called callback locking which never worked so I had it always disabled.
I set up the callback url just like I was told from the firebase project page and it did work before but now with the locking it does not anylonger.
Relevant Twitter url : https://twittercommunity.com/t/action-required-sign-in-with-twitter-users-must-whitelist-callback-urls/105342

So what I did is update to these versions above but sadly it did not fix anything.

#### Steps to reproduce:

  1. Setup Firebase / Firebase Auth UI with Twitter 
  2. Set callback url in Twitter Development App site as shown in firebase
  3. Use Firebase Auth UI to login with twitter and get error before even getting to the username / password screen while its loading.

  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
https://hastebin.com/xexesujisi.rb
  
#### Expected Results:

  * What did you expect to happen?
No errors, logging in like some weeks ago.   

#### Relevant Code:

Well the code is basically the same as in Firebase Auth UI example : 

in androids onCreate : 
```
twitterprovider = Arrays.asList( new AuthUI.IdpConfig.TwitterBuilder().build());
```  

Now calling this to show twitter login (which worked like 2-3 weeks ago) :

```
AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(twitterprovider )
                        .setTosUrl("https://somurl.com/terms-of-service.html")
                        .setPrivacyPolicyUrl("https://somurl.com/privacy-policy.html")
                        .build(),
                RC_SIGN_IN);
  ```

I used this : implementation 'com.twitter.sdk.android:twitter-core:3.1.1'

Maybe also relevant : https://github.com/twitter/twitter-kit-android/issues/134

**Comment by devingDev** [comment]
https://github.com/twitter/twitter-kit-android/issues/135

Added "twittersdk://" without the quotation marks as a callback url in twitter app settings (nothing else just twittersdk://   !! )

now it works. Not sure why you have to do that even though its their own sdk lol.

Anyway this is fixed

**Comment by samtstern** [comment]
@devingDev thanks for following up on your own issue!  I just ran into this with @lsirac and you saved us.

**Comment by devingDev** [comment]
you probably could find it after some research but no problem. just hate having solved issues without any solution mentioned. have fun

**Comment by rahul-rahul1** [comment]
in firebase:Just use Comback_Url twittersdk://,It is working Fine both firbase authentication and twitter Login.

**Comment by devingDev** [comment]
where in firebase do you set that url?

**Comment by samtstern** [comment]
@devingDev you have to set that URL in the Twitter console, no change needed in Firebase.

**Comment by devingDev** [comment]
Helps when people read what is some comments above... anyway I'm out this is solved for me.
