### ISSUE TITLE
Firebase Phone Verification OTP works for some numbers for other it does not send any OTP.

### ISSUE THREAD

**Issue by goyalish** [firebase/FirebaseUI-Android#1378]
I am able to receive OTP on JIO number. However I am not getting OTP on my other number.
I have tested with two vodafone prepaid numers out of which it worked for one for other I never received any OTP. Then I tested on JIO number and it worked. Then I tested on my friends numbers for some it works for others it does not. Please look into this. If this is going to be the firebase auth behaviour , I am afraid that I am going to use it. Need a reliable service for my app.

**Comment by samtstern** [comment]
@goyalish when dealing with SMS delivery issues please contact [Firebase support](https://firebase.google.com/support/).  They are best at debugging this.

**Comment by 9061169702** [comment]
Request to firebase for getting otp is working ,after that  callback  verification failed is working
can any one please help me
