### ISSUE TITLE
Can't run sample app

### ISSUE THREAD

**Issue by agnunezv** [firebase/FirebaseUI-Android#138]
Everytime that I tried to run the sample app it's showing me:
```
Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/andresnunez/AndroidstudioProjects/FirebaseUI-Android/app/src/debug/google-services.json
  /Users/andresnunez/AndroidstudioProjects/FirebaseUI-Android/app/google-services.json
```

And if I take the `google-services.json` from the `library` module and replace the empty space from `package_name` with `com.firebase.uidemo` and copy that file into the `app` module the sample app starts but once I tap on the `Auth UI demo` option the app crashes.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.firebase.uidemo/com.firebase.uidemo.auth.AuthUiActivity}: java.lang.IllegalStateException: FirebaseApp with name [DEFAULT] doesn't exist. 
```

What I'm doing wrong?

Thank you very much.

**Comment by samtstern** [comment]
Try going to the Firebase Console (https://console.firebase.google.com) and
following the steps to add an Android app.  Use the package name of the
sample app here and your own keystore SHA1.  Then you'll get the right json
file.

**Comment by agnunezv** [comment]
@samtstern That was it. Thank you very much.
