### ISSUE TITLE
Allow linking accounts when logging in

### ISSUE THREAD

**Issue by wli** [firebase/FirebaseUI-Android#139]
If you logged in with Facebook first, and then tried to log in with Google later, there should be an option to combine the credentials into one account. Right now, it forces you to log in with the original login method if it detects a duplicate email. There appears to be an API to handle this.

https://firebase.google.com/docs/auth/android/account-linking#link-auth-provider-credentials-to-a-user-account

**Comment by iainmcgin** [comment]
The flow actually does link the two accounts - we force the user to sign in with the previous authentication method to prove ownership of the existing account, and then link the new authentication method to the account. See here:

https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/account_link/WelcomeBackIDPPrompt.java#L165
