### ISSUE TITLE
DexArchiveMergerException: Unable to merge dex

### ISSUE THREAD

**Issue by mrjaypatel** [firebase/FirebaseUI-Android#1391]
Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

I got above error after adding this dependency!
compile 'com.firebaseui:firebase-ui:0.4.2'

I also tried compile 'com.firebaseui:firebase-ui:0.4.3' version but the problem comes in both version!
give me some solution!

**Comment by SUPERCILEX** [comment]
You're probably meaning to use version `4.1.0`. 😉

**Comment by frapeti** [comment]
I'm also getting this error with 4.1.0

Error: Program type already present: android.arch.core.util.Function

**Comment by samtstern** [comment]
@frapeti see https://github.com/firebase/FirebaseUI-Android/issues/1357

@mrjaypatel see that issue, also make sure you're using the latest version!  `0.4.x` is from many many years ago.
