### ISSUE TITLE
Update: androidx from support. android.support.constraint.BuildConfig duplicate type

### ISSUE THREAD

**Issue by ersin-ertan** [firebase/FirebaseUI-Android#1394]
### Step 2: Describe your environment
  * Compile sdk version API 28: Android 8.+ (P)
  * compileSdkVersion 28
  * Firebase/Play Services SDK version:    com.google.firebase:firebase-core:16.0.1
  * FirebaseUI version: com.firebaseui:firebase-ui-auth:4.0.0
  
### Step 3: Describe the problem:
`com.android.support.constraint:constraint-layout:1.1.0`
is being used but after updating to `androidx.constraintlayout:constraintlayout:1.1.2`
you get a `Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: android.support.constraint.BuildConfig`

Excluding seemed to work:
```
    implementation('com.firebaseui:firebase-ui-auth:4.0.0') {
        exclude group: 'com.android.support.constraint', module: 'constraint-layout'
        exclude group: 'com.android.support.constraint', module: 'constraint-layout-solver'
    }
```

**Comment by samtstern** [comment]
@ersin-ertan I haven't had any problems myself using AndroidX + FirebaseUI (I am using the latest, 4.1.0).

Do you have Jetifier enabled?  You'll want to make sure you're using Android Studio `3.3.x` and have the following in your `gradle.properties` file:

```
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by SUPERCILEX** [comment]
Same here, it works with 3.2 beta04 as well.

**Comment by ersin-ertan** [comment]
I was in mid manual transition until I found the Refactor -> Migrate to AndroidX button, while enabling jetifier and useAndroidX. All is working correctly with Android Studio 3.3 canary 3
