### ISSUE TITLE
Unable to Merge Dex - Android Studio 3.0

### ISSUE THREAD

**Issue by mrjaypatel** [firebase/FirebaseUI-Android#1397]
```
dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    testImplementation 'junit:junit:4.12'
    //noinspection GradleCompatible
    implementation 'com.android.support:appcompat-v7:27.1.1'
    implementation 'com.android.support.constraint:constraint-layout:1.1.2'
    implementation 'com.android.support:support-v4:27.1.1'

    //noinspection GradleCompatible
    implementation 'com.google.firebase:firebase-storage:9.2.0'
    implementation 'com.google.firebase:firebase-database:9.2.0'
    implementation 'com.google.firebase:firebase-auth:9.2.0'
    compile 'com.firebaseui:firebase-ui-database:0.4.0'
    compile 'com.firebaseui:firebase-ui-auth:0.4.0'

//    compile 'com.firebaseui:firebase-ui:0.4.3'

    compile 'com.firebase:firebase-client-android:2.3.1'

    compile 'com.android.support:recyclerview-v7:27.1.1'
    compile 'com.android.support:cardview-v7:27.1.1'
    implementation 'com.squareup.picasso:picasso:2.71828'

/**
 *  androidTestImplementation 'com.android.support.test:runner:1.0.2'
 *  androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
 * */
}
```

Hear is my app:gradle dependency so someone please give me some solution!

**Comment by samtstern** [comment]
@mrjaypatel this is not enough information to help you, you'd be much better off asking on StackOverflow for this kind of debugging help as there's nothing here to suggest FirebaseUI is your problem.

However, I'll give you some scattered advice before closing this issue:

- `'com.google.firebase:firebase-storage:9.2.0'` --> this is really old!  The latest version is [16.0.1](https://firebase.google.com/support/release-notes/android).  Many of your other libraries are out of date, you'll want to update.
- `compile 'com.firebaseui:firebase-ui-auth:0.4.0'` --> FirebaseUI is on version `4.1.x` now, this is super super old.  Also don't mix `compile` and `implementation` unless you have to.
- `compile 'com.firebase:firebase-client-android:2.3.1'` --> this is the old, pre-Google Firebase client.  It *does* go with version `4.1.0` of FirebaseUI but you should ideally remove this an update.
