### ISSUE TITLE
Phone Authentication: Change display name sending the code to verify the phone number

### ISSUE THREAD

**Issue by Domztabz** [firebase/FirebaseUI-Android#1400]
Is there a way to change the display  name of the sender sending the code to verify phone number.? I want to change it from 'Phone Code' to the name of my company.

**Comment by samtstern** [comment]
@Domztabz the best answer to your question is here from @puf:
https://stackoverflow.com/questions/44879218/how-to-change-the-sms-verification-template-in-firebase-phone-auth

Basically, if we allowed customization of the text of the SMS it could be abused which may result in some legitimate Firebase SMS messages being marked as spam.  So for now, you can't customize the text at all.

**Comment by aytunch** [comment]
For the time being the body of the SMS is filled with our app'sname taken from App stores. I think this is a very smart way and avoids spam. So why don't you allow the sender name to be the app's name using the same conditions?
User can not edit the sender name but it will automatically be taken from app stores.

**Comment by Kajol115** [comment]
> For the time being the body of the SMS is filled with our app'sname taken from App stores. I think this is a very smart way and avoids spam. So why don't you allow the sender name to be the app's name using the same conditions? User can not edit the sender name but it will automatically be taken from app stores.

**Comment by Kajol115** [comment]
> For the time being the body of the SMS is filled with our app'sname taken from App stores. I think this is a very smart way and avoids spam. So why don't you allow the sender name to be the app's name using the same conditions? User can not edit the sender name but it will automatically be taken from app stores.

I agree with you @aytunch

**Comment by ritobratadeepneura** [comment]
is it possible without firebase??
