### ISSUE TITLE
"Read-only & non-realtime mode activated to improve browser performance" makes every recyclerview slower

### ISSUE THREAD

**Issue by JagarYousef** [firebase/FirebaseUI-Android#1409]
### Step 1: Are you in the right place?
I believe so

### Step 2: Describe your environment

  * Android device: All
  * Android OS version:All
  * FirebaseUI version: 3.1.0
  
### Step 3: Describe the problem:
I only had few dozens of nodes in my "REAL TIME" firebase database, it is for a chat android app. I suddenly found a message says : Read-only & non-realtime mode activated to improve browser performance
Now the app is extremely slow in updating all my Firebase recycler view. I don't know what to do or should I trust in this unstable database.

**Comment by JagarYousef** [comment]
Thanks @samsterm 
I just knew the reason that was a function that was creating an infinite loop of database nodes so it made the updating slower.

**Comment by samtstern** [comment]
@JagarYousef glad you solved it!
