### ISSUE TITLE
error can't separate operations in search advanced ? Angular Firestore 

### ISSUE THREAD

**Issue by Omar-Qalei** [firebase/FirebaseUI-Android#1414]
How to create Advanced Search filter Angularfirestore using Typescript ?

```
search = this.afs.collection('City');
search.ref.where('areaList', '==', this.data.area[_i])
.where('price', '>=', this.data.minPrice)
.where('price', '<=', this.data.maxPrice)
```
If I use only one input give me error need to fill other inputs, I wanna separate between operations and use as needed .

All data was saved in firestore.

**Comment by samtstern** [comment]
@Omar-Qalei this is not the right repo for AngularFire.  See here:
https://github.com/angular/angularfire2
