### ISSUE TITLE
Touch area issue on some UI elements (38dp -> 48dp)

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#1415]
* Android device: all
  * Android OS version: all
  * FirebaseUI version: 4.1.0
  
#### Steps to reproduce:

After uploading the app to Google Play, the automatically created pre-launch reports state that some clickable parts of the Firebase UI have a too small size (38dp, should be 48dp).
  
#### Observed Results:

![firebase_ui_toucharea](https://user-images.githubusercontent.com/1724223/44546471-53b19200-a718-11e8-9195-df2dca234dcb.png)
  
#### Expected Results:

Firebase-UI should not give any problems in the pre-launch reports of Google Play.

**Comment by samtstern** [comment]
This has been fixed and released in version `4.2.1`.
