### ISSUE TITLE
This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]

### ISSUE THREAD

**Issue by deekshithp45** [firebase/FirebaseUI-Android#1418]
This app is not authorized to use Firebase Authentication. Please verifythat the correct package name and SHA-1 are configured in the Firebase Console. [ App validation failed ]

**Comment by samtstern** [comment]
@deekshithp45 the solution is right there in the error message.  You need to configure the SHA1 for all of your certificates in the console!

Also please fill out the issue template when filing issues.
