### ISSUE TITLE
Show brand logo on firebase sign in UI

### ISSUE THREAD

**Issue by mufaddalgulshan** [firebase/FirebaseUI-Android#142]
As of now, there is provision to customize the colors and typography of the Firebase login UI (AuthMethodPickerActivity) as shown below

![loginui](https://cloud.githubusercontent.com/assets/9861299/15534812/6945c526-2288-11e6-8463-dcd9d3aab7e3.png)

Is there any way to display the brand's logo above the sign in buttons?

**Comment by samtstern** [comment]
@mufaddalgulshan thanks for the feature request, definitely would be a nice feature to fill up that empty space.  We will look into it.

**Comment by iainmcgin** [comment]
This was discussed prior to launch, we just didn't have time to implement it. It's on the list for a future version, along with other customization options :)

**Comment by samtstern** [comment]
@mufaddalgulshan this has been implemented and will be included in the next release.  If you follow the instructions on building locally you can try this out now.

**Comment by mufaddalgulshan** [comment]
@samtstern thanks a lot for such a quick resolution. Will definitely try it out. When can we expect the 4.1 release to be out?

**Comment by samtstern** [comment]
@mufaddalgulshan no hard timeline right now, there are a few bugs that are still not fixed that we want to be in the same release.

**Comment by samtstern** [comment]
This issue is now fixed in version 0.4.1, please update your dependencies and thanks for the patience!
