### ISSUE TITLE
FirebaseRecyclerAdapter  with   compile 'com.firebaseui:firebase-ui-database:0.4.0'

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-Android#143]
I am trying to use the FirebaseRecyclerAdapter with the  compile 'com.firebaseui:firebase-ui-database:0.4.0' dependency. However, it does not recognise it. 
I've tried to add compile 'com.firebaseui:firebase-ui:0.4.0' however, it won't sync saying "could not find com.firebaseui:database:0.4.0 event though I have it as a dependency.

Going back to compile 'com.firebaseui:firebase-ui:0.3.1' requires the constructor found with the old firebase.

any suggestions?

**Comment by puf** [comment]
The dependency is `compile 'com.firebaseui:firebase-ui-database:0.4.0'`

**Comment by joemerritt** [comment]
Good Morning Puf, Thanks for the response. I'm using that dependency however it's not implementing FirebaseRecyclerAdapter. Only when I include the old 'com.firebaseui:firebase-ui:0.3.1 will it implement it

**Comment by puf** [comment]
It does implement the adapter. I added to another project yesterday.

The only tricky bit was that Android Studio refused to auto-import the
FirebaseRecyclerAdapter
until I removed the old import. If your problem is the same, *remove* this
line:

import com.firebase.ui.FirebaseRecyclerAdapter;

Or change it to:

import com.firebase.ui.database.FirebaseRecyclerAdapter;

**Comment by joemerritt** [comment]
that was exactly the problem... cheers Puf! good help as always!

**Comment by puf** [comment]
I drove me nuts for a good five minutes yesterday. Android Studio so often
does the exactly right thing, that I didn't realize why it was giving me a
hard time here. :-)

**Comment by joemerritt** [comment]
I hear what you're saying... i just wish it took me 5 min to figure out! hahaha.... more like 2hrs (or until you go online! thanks again

**Comment by Inzimam-Tariq** [comment]
@puf, I have upgraded my build tool version and target version to API 28 Pie. And now `FirebaseRecyclerAdapter` asking me to extend my `ViewHolder` class from android.support.v7`. Check below

Type parameter 'com.domain_name.app_name.FriendsFragment.FindFriendsViewHolder' is not within its bound; should extend 'android.support.v7.widget.RecyclerView.ViewHolder'

I'm extending `ViewHolder` from API 28 with the below import
`androidx.recyclerview.widget.RecyclerView;`

**Comment by samtstern** [comment]
In your `gradle.properties` file add:

```
android.useAndroidX=true
android.enableJetifier=true
```

**Comment by Inzimam-Tariq** [comment]
> In your `gradle.properties` file add:
> 
> ```
> android.useAndroidX=true
> android.enableJetifier=true
> ```

Now android studio do not recognize `onCreateViewHolder` and says its never used

**Comment by kingdoom0** [comment]
i need help to make book library with firebase to read pdf files
