### ISSUE TITLE
FirebaseUI not adjusted according to the rotation and numbers of providers

### ISSUE THREAD

**Issue by JitenderSha** [firebase/FirebaseUI-Android#1434]
### Describe your environment

  * Android device:  Nexus 5
  * Android OS version: 6
  * Google Play Services version: 12.8.74
  * Firebase/Play Services SDK version: firebase-auth:16.0.3, play-services-location:15.0.1
  * FirebaseUI version: 4.1.0
  
### Step 3: Describe the problem:

1. In Portrait mode 
      As in screenshot 1, the blank space is leaved if used two providers.

2. In Landscape mode
     As in screenshot 2, the blank space is leaved at the bottom of the logo and logo is not in vertical center.

#### Steps to reproduce:

  1. Use FirebaseUI using
startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setLogo(R.mipmap.tb_logo)      // Set logo drawable
                        .setTheme(R.style.AppTheme)      // Set theme
                        .build(),
                RC_SIGN_IN);
  2. Run the app
  3. See in both orientations
  
#### Observed Results:

  * All is in screenshots
  
#### Expected Results:

  * What did you expect to happen?
In Portrait mode, if two providers are used the space should evenly distributed between the logo and buttons.

In Landscape mode, the logo should be placed in vertical center of the screen.
  
#### Relevant Code:
Just copy paste the following :

  // Choose authentication providers
       
       List<AuthUI.IdpConfig> providers = Arrays.asList(
                new AuthUI.IdpConfig.PhoneBuilder().build(),
                new AuthUI.IdpConfig.FacebookBuilder().build());

        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setLogo(R.mipmap.tb_logo)      // Set logo drawable
                        .setTheme(R.style.AppTheme)      // Set theme
                        .build(),
                RC_SIGN_IN);

![screenshot_1](https://user-images.githubusercontent.com/38163139/45026564-4ff90600-b05c-11e8-8fd4-c54e1d072f6a.png)
![screenshot_2](https://user-images.githubusercontent.com/38163139/45026577-56877d80-b05c-11e8-8167-9de1ed06a4da.png)

**Comment by samtstern** [comment]
@JitenderSha thanks for reporting.  What is the bug in portrait mode?  That looks correct to me.

Also you say this is "Android version 6" but from the look of the screenshots that device is running Android 4.x ... can you provide a screenshot from a device running Lollipop, Marshmallow, or higher?  I just want to see if this is Android version specific.

**Comment by Fxghlu** [comment]
@samtstern I have the same issue, in horizontal mode the layout looks wrong. Looks identical to @JitenderSha pictures, Logo off center and login buttons stuck to the very right. I am using Android API 28

**Comment by samtstern** [comment]
#1457 shows this issue on a modern device, which is the confirmation I need.

**Comment by Fxghlu** [comment]
@samtstern any idea of a rough eta til fixed?

**Comment by SUPERCILEX** [comment]
@JitenderSha Probably 4.2.1 😊

**Comment by samtstern** [comment]
This has been fixed and released in version `4.2.1`.
