### ISSUE TITLE
Getting java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by programmorem** [firebase/FirebaseUI-Android#1436]
* Android device:  Sony Xperia Z5
  * Android OS version: 7.1.1
  * Google Play Services version: 12.8.74
  * Firebase/Play Services SDK version: 15.0.0
  * FirebaseUI version: 3.3.0
  
Hey,  
my Problem is that I get this error sometimes:   

```
09-05 21:59:51.720 26100-26124/? E/ActivityThread: Failed to find provider info for com.tencent.ig.TPUSH_PROVIDER
09-05 21:59:51.720 10211-10211/com.test.test.testE/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.test.test.test, PID: 10211
    java.lang.ArrayIndexOutOfBoundsException: length=10; index=-1
        at java.util.ArrayList.get(ArrayList.java:413)
        at com.firebase.ui.common.BaseObservableSnapshotArray.getSnapshot(BaseObservableSnapshotArray.java:70)
        at com.test.test.test.adapter.NoteListAdapter$NoteViewHolder$1.onClick(NoteListAdapter.java:101)
        at android.view.View.performClick(View.java:5685)
        at android.view.View$PerformClick.run(View.java:22481)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6274)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
````

The specific error line is this here:  
```
DocumentSnapshot snapshot = getSnapshots().getSnapshot(getAdapterPosition());
```

I use this when you click at an Item in RecyclerView:  
```
view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    DocumentSnapshot snapshot = getSnapshots().getSnapshot(getAdapterPosition());
                    Note note = snapshot.toObject(Note.class);
                    String id = getSnapshots().getSnapshot(getAdapterPosition()).getId();
                    MainActivity.updateNote(id, note);
                }
            });
```

**Comment by samtstern** [comment]
Looking at this line:
```
java.lang.ArrayIndexOutOfBoundsException: length=10; index=
```

I would say that it means `getAdapterPosition()` is returning `-1` inside your click listener.

Could you show more code around where you call `view.setOnClickListener`?

**Comment by programmorem** [comment]
I call it in my ViewHolder:  
`public class NoteViewHolder extends RecyclerView.ViewHolder {

        public TextView title, content;
        public ImageView bg_note_image;
        public RelativeLayout viewBackground, viewForeground;

        public NoteViewHolder(View view) {
            super(view);
            title = view.findViewById(R.id.tvTitle);
            content = view.findViewById(R.id.tvContent);
            bg_note_image = view.findViewById(R.id.note_image_view);
            viewBackground = view.findViewById(R.id.view_background);
            viewForeground = view.findViewById(R.id.view_foreground);

            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {
                    DocumentSnapshot snapshot = getSnapshots().getSnapshot(getAdapterPosition());
                    Note note = snapshot.toObject(Note.class);
                    String id = getSnapshots().getSnapshot(getAdapterPosition()).getId();
                    MainActivity.updateNote(id, note);
                }
            });
        }
    }`

**Comment by samtstern** [comment]
@programmorem look at the docs for `getAdapterPosition`:
https://developer.android.com/reference/android/support/v7/widget/RecyclerView.ViewHolder#getadapterposition

> Note that if you've called notifyDataSetChanged(), until the next layout pass, the return value of this method will be NO_POSITION.

The value of [`NO_POSITION`](https://developer.android.com/reference/android/support/v7/widget/RecyclerView#NO_POSITION) is `-1` which is what you are seeing.

I think the best thing to do is add this in your `onClick` to protect against this case:

```java
if (getAdapterPosition() == RecyclerView.NO_POSITION) {
  return;
}
```

**Comment by programmorem** [comment]
@samtstern But instead of the error, I can't click at my items. So how to solve it that I can click at my Items and that the App does not crash? How is this solved by professional Apps?

**Comment by samtstern** [comment]
If `getAdapterPosition()` is returning -1 there is something wrong with how you're adding/displaying your view holders.

Maybe there's a problem in your `onCreateViewHolder` code?  I closed the issue because there is nothing to suggest this is a problem with FirebaseUI

**Comment by programmorem** [comment]
@samtstern I don't think that I have written something wrong in my code. But it would be great if you could have a look at my code: https://stackoverflow.com/questions/52210840/getting-arrayindexoutofboundsexception-in-adapter
