### ISSUE TITLE
nullpointerexception on signinwithemailandpassword Firebase Authentication 

### ISSUE THREAD

**Issue by gulzi619** [firebase/FirebaseUI-Android#1448]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device:google nexus 5 _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
### Step 3: Describe the problem:
i've been getting null pointer exception error and i'm unable to solve this. help please 
cant figure out whats wrong .

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:
My code is as follows: 

```
 private EditText AdminID;
    private EditText Password;
    private Button Login;
    Administrator info;
    String Adminid;
    String Pass;
    private ProgressDialog verifylogin;
    private FirebaseAuth mAuth;
    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        requestWindowFeature(Window.FEATURE_NO_TITLE);
        setContentView(R.layout.activity_login);
        mAuth = FirebaseAuth.getInstance();
        refids();
        verifylogin = new ProgressDialog(this);
        info = new Administrator();
        Login.setOnClickListener(this);
    }
    @Override
    public void onStart() {
        super.onStart();
        // Check if user is signed in (non-null) and update UI accordingly.
        FirebaseUser currentUser = mAuth.getCurrentUser();
    }

    @Override
    public void onClick(View view)
    {
        validate();

    }

    public void validate()
    {

        Adminid = AdminID.getText().toString();
        Pass=Password.getText().toString();

       if(Pass.isEmpty() || Pass.contains(" "))
       {
           Password.setError("Invalid Password");
       }
       else if(Adminid.isEmpty() || Adminid.contains(" ") || !Adminid.contains("@"))
       {
           AdminID.setError("Invalid Admin ID");
       }
       else
       {
           validateUser();
       }
    }

    public void refids()
    {
        AdminID = findViewById(R.id.Admin_ID);
        Password = findViewById(R.id.Password);
        Login = findViewById(R.id.Login);
    }

    private void validateUser()
    {
        verifylogin.setMessage("Verifying, Please Wait");
        verifylogin.show();
            mAuth.createUserWithEmailAndPassword(Adminid, Pass)
                    .addOnCompleteListener(new OnCompleteListener<AuthResult>() {
                        @Override
                        public void onComplete(@NonNull Task<AuthResult> task) {
                            if (task.isSuccessful()) {
                                // Sign in success, update UI with the signed-in user's information
                                Log.d(TAG, "signInWithEmail:success");
                                FirebaseUser user = mAuth.getCurrentUser();
                            } else {
                                // If sign in fails, display a message to the user.
                                Log.w(TAG, "signInWithEmail:failure", task.getException());
                                Toast.makeText(LoginActivity.this, "Authentication failed.",
                                        Toast.LENGTH_SHORT).show();
                            }


                        }
                    });
        }
```

**Comment by samtstern** [comment]
@gulzi619 can you show the stack trace of the exception?  It's hard to debug from just posting all of your code without knowing what happens and what you expect to happen.

**Comment by samtstern** [comment]
Since this issue did not follow the template and there has been no response in ~8 days, closing it.  @gulzi619 I would recommend finding help on StackOverflow!
