### ISSUE TITLE
Rotation on startActivityForResult produces UI that looking wrong.

### ISSUE THREAD

**Issue by Fxghlu** [firebase/FirebaseUI-Android#1457]
* Android device: 
    Nexus 5x

  * Android OS version: 
    API 28

  * Google Play Services version: 
    16.0.0

  * Firebase/Play Services SDK version: 
    implementation 'com.google.firebase:firebase-core:16.0.3'
    implementation 'com.google.firebase:firebase-auth:16.0.3'
    implementation 'com.google.firebase:firebase-database:16.0.2'

  * FirebaseUI version: 
    implementation 'com.firebaseui:firebase-ui:4.1.0'
    implementation 'com.firebaseui:firebase-ui-auth:4.1.0'
    implementation 'com.firebaseui:firebase-ui-database:4.1.0'
  
#### Steps to reproduce:

Code:
 1. startActivityForResult(AuthUI.getInstance()
                    .createSignInIntentBuilder()
                    .setTheme(R.style.GreenTheme)
                    .setLogo(R.drawable.logo)
                    .setIsSmartLockEnabled(false, true)
                    .setAvailableProviders(Arrays.asList(
                            new AuthUI.IdpConfig.FacebookBuilder().build(),
                            new AuthUI.IdpConfig.EmailBuilder().build(),
                            new AuthUI.IdpConfig.GoogleBuilder().build()))
                    .build(), RC_SIGN_IN);
  
2. Run the app and upon login screen rotate the phone to landscape. 
  
#### Observed Results:

  The logo isn't centered, it just looks wrong, I have 3 builders in place as seen from code above but if you use two builders it looks even more wrong.
  
#### Expected Results:

  Logo be centered as well as buttons for logging in.
  
#### Screenshot

Portrait Looks perfect:
![potrait](https://user-images.githubusercontent.com/17144570/45959153-1e4add80-c011-11e8-9d55-7ff662e20761.PNG)

Landcape looks wrong:
![lands](https://user-images.githubusercontent.com/17144570/45959157-24d95500-c011-11e8-9eb9-1e05fdff8e44.PNG)

**Comment by samtstern** [comment]
@Fxghlu thanks for this!  This looks the same as #1434 so closing as a duplicate.  We can address it there.
