### ISSUE TITLE
AAPT2 error while building auth-release.aar

### ISSUE THREAD

**Issue by lazyFloyd** [firebase/FirebaseUI-Android#1459]
I'm having issues when I try to build FirebaseUI **auth** module as **.aar** in a simple Android project (I was using "Create Android Project" wizard). What I only added in build.gradle was following:

`implementation(name: "auth-release", ext: "aar")`

After I click on "Sync Now" I get the following error:

<img width="1553" alt="screen shot 2018-09-25 at 17 44 55" src="https://user-images.githubusercontent.com/23117238/46027300-cb932380-c0ed-11e8-9a38-d46a278c4e3c.png">

I checked out branch **version-4.2.0** and generated auth-release.aar. Does anybody know what could be the problem?

**Comment by samtstern** [comment]
@lazyFloyd are you trying to _use_ FirebaseUI in your app or are you trying to contribute to (or fork) the library?

**Comment by lazyFloyd** [comment]
Hi Sam,

I actually forked FirebaseUI library (without any custom changes at the
moment) and trying to use auth as the .aar library in my app.

**Comment by samtstern** [comment]
I can see what's missing is `mpb_` attributes, which I bet come from the MaterialProgressBar library which is a dependency of the `auth` library.

I think something about the way you are trying to use your fork is not bringing in all the dependencies you need.

How are you making `auth-release.aar`?  I'd recommend installing your fork into your local maven repository using the guide here:
https://github.com/firebase/FirebaseUI-Android#installing-locally

**Comment by SUPERCILEX** [comment]
Yeah, that won't work because Gradle doesn't know that the aar needs extra dependencies. Please use the standard maven local. (It worked before because you already had all the dependencies, but that can change at any time if we update any of them)

**Comment by samtstern** [comment]
Yeah unfortunately we can't support the "drag and drop aar" model.  Once you publish into maven local, you should add `mavenLocal()` to your `repositories{}` block and depend on it from there.

Good luck!
