### ISSUE TITLE
Wrong result code after password reset flow

### ISSUE THREAD

**Issue by itaihanski** [firebase/FirebaseUI-Android#146]
When returning from the password reset flow, whether after sending a reset email or pressing back, the return code received is `RESULT_OK` even though the user is not signed in at that point.

This renders this example code snippet false:

    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_SIGN_IN) {
            if (resultCode == RESULT_OK) {
                // user is signed in!    <-- Not true in this case
            } else {
                // user is not signed in. Maybe just wait for the user to press
                // "sign in" again, or show a message
            }
        }
    }

Recreate:

1. Sign in with an email and a password / create a user via the console.
2. Sign out / clear data
3. Click the "sign in with email" button and provide that email address
4. Click on "trouble signing in"
5. Press back / Reset the password
6. `onActivityResult` is called with `RESULT_OK`

**Comment by amandle** [comment]
This should be fixed with pull request https://github.com/firebase/FirebaseUI-Android/pull/149

**Comment by itaihanski** [comment]
Thanks :)
