### ISSUE TITLE
Twitter sign in possible with no email

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1469]
### Step 2: Describe your environment

  * Android device: Pixel 2
  * Android OS version: 8.x
  * FirebaseUI version: 4.2.0 (`master`)
  
#### Steps to reproduce:

  1. Sign in with Google account (samsterntest@gmail.com)
  2. Sign out
  3. Sign in with Twitter account (samsterntest@gmail.com)
  
#### Observed Results:

Signed in as a user with no email:
![device-2018-10-03-104444](https://user-images.githubusercontent.com/8466666/46429113-8331c200-c6fa-11e8-9908-c81d165384db.png)

Console shows user with no identifier:
![image](https://user-images.githubusercontent.com/8466666/46429125-888f0c80-c6fa-11e8-81d7-f09f65d4ddf1.png)

 
#### Expected Results:

Expected to be asked to link my Twitter account to Google.
  
#### Relevant Code:

N/A

**Comment by samtstern** [comment]
In these lines of `TwitterSignInHandler`

```java
           TwitterCore.getInstance()
                    .getApiClient()
                    .getAccountService()
                    .verifyCredentials(false, false, true)
                    .enqueue(new Callback<com.twitter.sdk.android.core.models.User>() {
                        @Override
                        public void success(Result<com.twitter.sdk.android.core.models.User> result) {
                            com.twitter.sdk.android.core.models.User user = result.data;
```

`user.email` is `null` ...

**Comment by samtstern** [comment]
Likely relevant: my email address on Twitter was not confirmed.

**Comment by samtstern** [comment]
@SUPERCILEX I forget: did we consciously decide to allow users with no email to exist?  Or this is a bug?

**Comment by SUPERCILEX** [comment]
Didn't we allow that so Twitter users with only phone numbers can sign in? Pretty you were even the one to test that! 😂

**Comment by samtstern** [comment]
Yeah that's true, although the Twitter account I was signed in with has neither an email nor a phone number.  So it just has "no identifier" in the Firebase console.

Also it doesn't look like we would propagate the phone number from Twitter, even if we got it.

**Comment by SUPERCILEX** [comment]
Huh, I just checked and the Twitter user profile object doesn't include a phone number field... so we're kinda stuck. I guess that makes this issue intended behavior?

**Comment by samtstern** [comment]
Yeah I think it is intended behavior.  The behavior with an unverified email was really bad, but I think that situation is not very common (linking with unverified) so there's no need to worry about it.
