### ISSUE TITLE
Response Code:16 message:16 when login google

### ISSUE THREAD

**Issue by Thien658jjh** [firebase/FirebaseUI-Android#1471]
I used FireBaseUI login to my project.
When I build debug, it worked perfectly by when I build `release `and upload to` google store`. It did not work any more and only showed toast with response: `code: 16 message: 16 ` ???
Do I need something else to release ?

**Comment by Thien658jjh** [comment]
help me

**Comment by samtstern** [comment]
There's not enough information here, but sounds like you didn't properly register your SHA1 for your production build with the Firebase console.  That is a common issue for people using Google Sign In.  If you're using the Play Store's app signing feature, then you need to get the SHA1 of the actual production signing key!
