### ISSUE TITLE
exitFreeformMode: You can only go fullscreen from freeform

### ISSUE THREAD

**Issue by Midhilaj** [firebase/FirebaseUI-Android#1473]
when we run this code app is crashing and if I remove this code app work without any problem why this is happening? what is wrong here?

 ```
mAuth=FirebaseAuth.getInstance();
    //_FirebaseImageUploader m_FirebaseImageUploader;
    if(mAuth!=null?mAuth.getCurrentUser()!=null?true:false:false){

    }
    else{
        List<AuthUI.IdpConfig> providers = Arrays.asList(
                new AuthUI.IdpConfig.EmailBuilder().build(),
                new AuthUI.IdpConfig.PhoneBuilder().build(),
                new AuthUI.IdpConfig.GoogleBuilder().build());// Create and launch sign-in intent
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .build(),
                RC_SIGN_IN);
    }
```

**Comment by samtstern** [comment]
@Midhilaj there's not really enough information here to help.  I see you [also posted this question](https://stackoverflow.com/questions/52676737/exitfreeformmode-you-can-only-go-fullscreen-from-freeform) on StackOverflow.  Given that there's no indication here that there's a bug in FirebaseUI (seems like something to do with your application) I am going to close this issue, StackOverflow is the right place to debug app issues!
