### ISSUE TITLE
 .enableAnonymousUsersAutoUpgrade() problem for phone auth

### ISSUE THREAD

**Issue by zafersnger** [firebase/FirebaseUI-Android#1475]
The environment

  * Android device: Galaxy Note 5
  * Android OS version: 7.0
  * Google Play Services version: 14.3.66
  * Firebase/Play Services SDK version: 16.0.4
  * FirebaseUI version: 4.2.0
  
the problem:
When enable .enableAnonymousUsersAutoUpgrade() in AuthUI.getInstance(). onActivityResult() isn't called.  When I disable .enableAnonymousUsersAutoUpgrade(), I can sign in successfully.  But in that case, Anonymous User's session ID isn't merged with the user's session ID .  This only occurs for already signed phone numbers.

#### Steps to reproduce:

1. Sign in with phone number
1. Clear data
3. Open the  app
4. Sign in anonymously
5. Sign in with phone number
  
#### Observed Results:
onActivityResult() isn't called.

  com.firebase.ui.auth.FirebaseAuthAnonymousUpgradeException: User account merge conflict
        at com.firebase.ui.auth.viewmodel.SignInViewModelBase.handleMergeFailure(SignInViewModelBase.java:35)
        at com.firebase.ui.auth.data.remote.SignInKickstarter.onActivityResult(SignInKickstarter.java:189)
        at com.firebase.ui.auth.KickoffActivity.onActivityResult(KickoffActivity.java:81)
        at android.app.Activity.dispatchActivityResult(Activity.java:7256)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
        at android.app.ActivityThread.-wrap22(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
  
#### Expected Results:

onActivityResult() should be called and anonymous session and authenticated user sessions should be merged.

**Comment by samtstern** [comment]
@zafersnger I just tried to reproduce this using the Anonymous Auth account linking activity in the sample app in this repository and was not able to reproduce the issue.  The account linking process returned the errors correctly and I was able to merge.

**Comment by zafersnger** [comment]
@samtstern I don't see phone authentication in the sample app in this repository. If I am wrong, I am sorry.

**Comment by samtstern** [comment]
@zafersnger it's definitely in the sample!

**Step 1 - Go to the Auth UI Demo**
<img height="400" src="https://user-images.githubusercontent.com/8466666/46687624-29287500-cbb0-11e8-8861-d45c1ae72f01.png"></img>

**Step 2 - Sign in with Phone**
(see the Phone checkbox is checked, then click Start)
<img height="400" src="https://user-images.githubusercontent.com/8466666/46687654-3ba2ae80-cbb0-11e8-92db-1995dbe1aed7.png"></img>

Once you have done that you can sign out, then go back to the screen in "Step 1" and instead click on the Anonymous Upgrade demo.  You can use that to try out account linking with the phone account you created.

**Comment by samtstern** [comment]
@zafersnger that's intentional.  The main sample doesn't support the anonymous upgrade flow because it's complex and we wanted to show it elsewhere.  That's why you should open the **FirebaseUI Anonymous Account Linking** sample.  This does support phone auth, and seems to work as expected.

**Comment by zafersnger** [comment]
@samtstern so how will anonymous authentication will be upgraded to use authentication in real life apps. I think that   com.firebase.ui.auth.FirebaseAuthAnonymousUpgradeException: User account merge conflict in a bug when .enableAnonymousUsersAutoUpgrade() into AuthUI.getInstance().createSignInIntentBuilder()

**Comment by samtstern** [comment]
@zafersnger the included example shows how you can do the upgrade in real apps.  Have you tried it?  Does it work for you?

**Comment by samtstern** [comment]
Since there hasn't been a response in a week and I was never able to reproduce this issue, I am going to close.

If you can find reproduction steps in the sample app let me know and I will re-open and investigate more!
