### ISSUE TITLE
Proposal: Allow fully customized XML layouts for the AuthMethodPickerActivity

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1477]
## Proposal
Allow developers to pass their own XML resource for the main login screen:

```java
AuthUI.getInstance().createSignInIntentBuilder()
    // ...
    .setTheme(...)
    .setMainLayout(R.xml.my_custom_layout) // If not provided, default used
    .build()
```

We would define an implicit public API specifying which resource IDs need to be present in that XML screen in order for us to add controls to it, such as:

- A `ViewGroup` for us to add the sign-in provider buttons
- A `TextView` for the Terms of Service and Privacy Policy disclosure
- A `ProgressBar` to show loading operations
- An option to use your own sign-in buttons and just let us add click listeners. 

Note that this proposal **only** affects the first screen.  The rest would still be governed by the `setTheme()` attribute.  There are too many other screens, and their functionality is too complex, to allow for full user customization of every one.  

## Rationale

We have gotten many requests to be able to customize the main UI more such as:
#1383, #753, #619, #266, #236, #229 

When looking at popular Android apps, the sign-in method selection screen is often a showcase for the brand and the UI varies from app to app.  There's no way to add more "options" to our system to encompass all use cases.

Here are some examples of screens from other apps that I like and would like to enable.  While we can't enable every single feature shown in these screenshots, we can at least allow developers to get most of the way there and create an immersive look and feel without writing anything besides XML.

<img height="400" src="https://user-images.githubusercontent.com/8466666/46692528-61ce4b80-cbbc-11e8-9554-d87651658e70.png"></img>
<img height="400" src="https://user-images.githubusercontent.com/8466666/46692536-67c42c80-cbbc-11e8-9add-cab9a60f1213.png"></img>
<img height="400" src="https://user-images.githubusercontent.com/8466666/46692545-6bf04a00-cbbc-11e8-837d-8b7909c2b9cb.png"></img>
<img height="400" src="https://user-images.githubusercontent.com/8466666/46692555-74e11b80-cbbc-11e8-8e8c-9a5d21d0467e.png"></img>

cc @bojeil-google @morganchen12 @lsirac @SUPERCILEX

**Comment by SUPERCILEX** [comment]
I think you're right. The main issue I see is that all those screenshots have data which would probably be downloaded dynamically. If we _really_ wanted to support as many use cases as possible, we'd probably have to create a service which gives devs access to the view hierarchy so they can do animations, dynamic stuff, whatever. I'm using a service for the full account linking PR and I've been wanting to do something similar for the email sign-up page to allow custom field add/removal and validation.

In any case, this seems like a step in the right direction to me. 👍

**Comment by cutiko** [comment]
Greetings

I think this is a great improvement, is what I would expect as customization. I would like to suggest something about this:

> which resource IDs need to be present in that XML 

That seems prompt to human error, a formal structure that represents the layout could be useful:

```
public class AuthLayout {
       @LayoutRes
        private int layout;
        @IdRes
        private int facebookBtn, googleBtn, emailBtn;
        //Constructors, getters and setters...
}
```

This way we have to only be careful to have one id for each provider

**Comment by dimipaun** [comment]
In addition to this, we should export the building blocks of this screen so that users can easily recreate it -- this would solve all these problems and more!

For example, we want to add additional login buttons (e.g. Login with XYZ) which is basically impossible to do right now as the building blocks of this page are not public.

**Comment by samtstern** [comment]
@cutiko that's a good idea!  It would avoid having XML as an implicit API and use something more explicit.

@dimipaun we'd love to do something like that but right now it's really hard because we're managing a whole stack of Activities.  Without owning the root activity, there are some things we can't do.  It may be possible to define an interface so that anyone could make their own root activity, but that's a non-goal right now.

**Comment by samtstern** [comment]
@iamyaoxi has started working on this using the suggestions of everyone here.

**Comment by iamyaoxi** [comment]
Yes! And thanks everyone for those great ideas! And if possible, please review the PR and give your opinion on it.

**Comment by samtstern** [comment]
Just merged the initial implementation for this by @iamyaoxi, so this should be ready to go for `4.3.0`

**Comment by cutiko** [comment]
Greetings

I have a doubt, what if someone does something like this:

```
 <FrameLayout>

     <Button
        text="Facebook"/>

    <fragment
      id="coolFragment"
      name="com.package.project.CoolFragment"/>

</FrameLayout>
```

We can pass a `Fragment` and then in `onActivityCreated` access to whatever we want. I can think of plenty cool things I would like to do, but, can this create a conflict in anyhow?

**Comment by samtstern** [comment]
@cutiko that's actually a pretty interesting idea!  There's nothing that will break right away (that I can think of off the top of my head), however we're not going to make any guarantees about the Activity lifecycle or what other Fragments may be present so make sure to do a lot of testing if you go down that road.

**Comment by cutiko** [comment]
Greetings

I'm working on this basing my self [on this](https://github.com/firebase/FirebaseUI-Android/blob/version-4.3.0-dev/app/src/main/java/com/firebase/uidemo/auth/AuthUiActivity.java). 

- Builder seems intuitive
- I wouldn't mind about highlighting the mismatch between providers, the log seems fairly obvious

I'm having some problems as well:

 - If smart lock is not disable `.setIsSmartLockEnabled(false)` then the Google account chooser dialog is showed before seen the kickoff activity
 - if there is only  Email sign-in method, then the kickoff activity is skipped, going directly to the specific method activity
 - If only Google is available and the smart lock is disabled, then nothing happens

**Comment by cutiko** [comment]
```
repositories {
    maven { url "https://oss.jfrog.org/artifactory/oss-snapshot-local" }
}

dependencies {
    ...
    implementation 'com.firebaseui:firebase-ui-auth:4.3.0-SNAPSHOT'
    ...
}
```

Screenshot as requested
![SCREENSHOT](https://github.com/cutiko/FirebaseUiAuth/blob/ui-auth/app/src/main/res/raw/error_dialog_google_photo.png?raw=true)

![SCREENSHOT](https://github.com/cutiko/FirebaseUiAuth/blob/ui-auth/app/src/main/res/raw/error_dialog_google_photo.png?raw=true)

[Video can be seen here](https://github.com/cutiko/FirebaseUiAuth/blob/ui-auth/app/src/main/res/raw/error_dialog_google_video.webm)


Ok, that fixes a lot, sorry was not aware of the method.

Couldn't find anything relevant on the logs [this is the current repo branch](https://github.com/cutiko/FirebaseUiAuth/tree/ui-auth)

**Comment by samtstern** [comment]
@cutiko glad that helped!  I will look into the thing about SmartLock exiting, that's a bug.

**Comment by samtstern** [comment]
@cutiko hmm once I dismiss the SmartLock dialog I get this (the Google sign in dialog):
<img width="379" alt="screen shot 2018-11-20 at 4 31 21 pm" src="https://user-images.githubusercontent.com/8466666/48804109-c2839480-ece1-11e8-8997-82f7bf1f7ba7.png">

So I am a little stuck on how to reproduce your error.  But I will keep trying!

**Comment by cutiko** [comment]
@samtstern can you take a look at [this file](https://github.com/cutiko/FirebaseUiAuth/blob/bug/app/src/main/java/cl/cutiko/firebaseuiauth/SplashActivity.kt) found something on the `logcat` is commented there.

Google is enabled on the console, SHA is set on the project settings...

I think I found something else:

 - If the account is created the problem is presented only sometimes :/
 - If the account is created and `.setAlwaysShowSignInMethodScreen(true)` closing smart-lock move to the next activity
 - If the account is not created closing smart-lock prompt the account selector
 - If the account is not created and `.setAlwaysShowSignInMethodScreen(true)` closing smart-lock move to the next activity

I'm confused, I was able to reproduce the error, then deleting the account and trying to reproducing it again and I can't.

I'm afraid it could be me doing something wrong, but someone else on [SO](https://stackoverflow.com/questions/52517730/firebase-ui-auth-sign-in-error-api-exception) had the same problem

**Comment by cutiko** [comment]
I think is working, you can see the first version of the demo here

[SEE VIDEO](https://www.youtube.com/watch?v=awDbJ4QrdoI)

In case anyone wants to take a look more closely, [this is the repo](https://github.com/cutiko/FirebaseUiAuth/tree/ui-auth)

For the moment I want to make a dirty demo just trying to push the layout customization to the max. I'm planning to clean up the code and add some others later, I want to see what happens with a service binding and more than one fragment and using broadcast. All of that should end up being a *juicy* example of how far this new release can be pushed. 

In my regards, I only have kind words to everyone who works on this project, this next release is going to completely blow everyone mind **Thanks everybody this is awesome**

**Comment by samtstern** [comment]
@cutiko that's so cool!  I am gonna share that with the whole team.  And hopefully we can get to the bottom of your SmartLock/Google issues.

**Comment by samtstern** [comment]
This has been released in version `4.3.0`.

**Comment by sipersso** [comment]
@samtstern Is it possible to have a separate theme for the AuthMethodPickerActivity and the rest of the screens. I am using the customization, which is great, but I don't want the toolbar och the AuthMethodPicker. If I remove it using the them, it will also remove the toolbar from all other activities, like the email sign in flow, where the toolbars are actually useful. 

Is there any way to achieve this?

**Comment by sipersso** [comment]
@samtstern thank you! As you said, very hacky, but I think it might work. I'll give that a try.

**Comment by sipersso** [comment]
@samtstern works perfectly. Thank you!

**Comment by nathanvogel** [comment]
Hacky but works :) Here's the full code for the lazy ones like me:

```
class DisableActionBarFragment : Fragment() {
    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        return inflater.inflate(R.layout.empty, container, false)
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        activity?.actionBar?.hide()
        (activity as? AppCompatActivity)?.supportActionBar?.hide()
    }
}
```

**Comment by thestch** [comment]
@samtstern Hi, is it possible to register listeners into the UI elements of the layout used by AuthMethodPickerLayout? The reason is that while I'm using a custom layout, I would also need to register listeners to EditText etc. to get other user details such as their name, instead of launching a new activity to let them enter it.

**Comment by samtstern** [comment]
Sorry that is not possible.  You'll have to fork the library if you want to
do something that advanced.

**Comment by cutiko** [comment]
@thestch take a look at this you might find a hack arround
https://github.com/cutiko/FirebaseUiAuth
Is old but worth the try

**Comment by MangeshGhotage** [comment]
I am trying to create a UI similar to what is shown in the last screenshot (TikTok) by OP. In my case FirebaseUI is not showing transparent background. How to achieve that UI?
PS: [Here](https://stackoverflow.com/q/61413868/3273962) is my detailed SO post
