### ISSUE TITLE
Initialize firebase reference 

### ISSUE THREAD

**Issue by mg25071998** [firebase/FirebaseUI-Android#1478]
I have firebase db structure as 
State->city->district->date 

So my dbref=fbdb.getInstance().getref().child(state).child(city).city(district);

In recycler view i am receving empty recycler view item with key as delhi and no other value fetched 
But key is supposed to the date 
So how do i reference it to date using firebase Ui

**Comment by samtstern** [comment]
I apologize for not getting to this earlier, but this issue does not have enough information to debug (or any indication that there's a bug in FirebaseUI) so I am going to close it.

For general questions about how to use Firebase, try StackOverflow.
