### ISSUE TITLE
Filter the Display in FirebaseRecyclerView using spinner

### ISSUE THREAD

**Issue by Dranzen** [firebase/FirebaseUI-Android#1479]
Hello i can't filter the display in FirebaseRecyclerView using spinner. I have spinner to select a category then to filter the Display in FirebaseRecyclerView.

**Comment by samtstern** [comment]
@Dranzen this doesn't sound like a bug in FirebaseUI and you have not really provided enough information to go any further.  I'd suggest going to StackOverflow for general coding help and advice.
