### ISSUE TITLE
LICENSE: missing copyrights

### ISSUE THREAD

**Issue by magdini** [firebase/FirebaseUI-Android#1484]
LICENSE file is missing copyright info in the end, right now it just says:
Copyright [yyyy] [name of copyright owner]

instead of actually having a year and a name.

**Comment by rosariopfernandes** [comment]
That's just an appendix, explaining how to apply the license. If you check the source code (the [AuthUI](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/AuthUI.java) class for example) you'll see the license with the year and owner name.

**Comment by magdini** [comment]
Found it, thanks for the quick answer! :)

**Comment by samtstern** [comment]
Thanks @rosariopfernandes
