### ISSUE TITLE
The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1.

### ISSUE THREAD

**Issue by Akramhussain4** [firebase/FirebaseUI-Android#1487]
I'm trying to implement authentication using firebase auth UI but the build is failing everytime. I'm using firebase-UI-auth:4.1.0 and I also tried 4.2.0. but no luck it fails with this error.

> The library com.google.android.gms:play-services-basement is being requested by various other libraries at [[15.0.1,15.0.1]], but resolves to 16.0.1. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.

I think it's because the firebase-ui-auth library is still using 16.0.1 version of firebase-auth and 15.0.1 of the play-services-auth. It should be the latest version's for the successful build that's what I have came to know after researching on the internet. Please provide a fix for it.

**Comment by Akramhussain4** [comment]
Well..I just found out this from the Firebase UI docs. I will do a more thorough research form next time before opening an issue and explicitly adding updated firebase-auth and play-services-auth dependencies resolved the issue. 

> If you would like to use a newer version of one of FirebaseUI's transitive dependencies, such as Firebase, Play services, or the Android support libraries, you need to add explicit implementation declarations in your build.gradle for all of FirebaseUI's dependencies at the version you want to use

**Comment by nSpider** [comment]
This actually helped me... thanks !!
