### ISSUE TITLE
Problems with multiple Google accounts login & SmartLock feature.

### ISSUE THREAD

**Issue by burekas7** [firebase/FirebaseUI-Android#1490]
* Android device: Samsung Galaxy S8
  * Android OS version: 8.1
  * Google Play Services version: 4.1.0
  * Firebase/Play Services SDK version: 28
  * FirebaseUI version: 4.2.0
  
### Step 3: Describe the problem:

1) In case that I have multiple Google accounts (or even Facebook accounts - I haven't checked it yet):
Why does after a first login with Google, the Google accounts selection dialog shown up, **but** after the first login, when trying to log out and log in again in order to login with another account, this dialog isn't shown up anymore, so it keeps connecting to the last Google account which was connected by default.
- How can I fix it, so the google accounts dialog will be shown up on each time after logout-login procedure?

2) How can I disable this Google SmartLock feature?
After login with a Google account, when I'm trying to open the providers screen in order to make a login with Facebook (or other provider), it keeps log in with the last Google account, and in the bottom of the screen it shows that Google SmartLock is responsible to that (Maybe I set by mistake)

Thanks for your help.

**Comment by SUPERCILEX** [comment]
Please use `AuthUI#signOut` instead of the Firebase auth version. We handle the bug you described for you.

**Comment by samtstern** [comment]
@SUPERCILEX is right.  Also make sure you wait for the `Task<>` returned by `AuthUI.signOut()` to complete before considering yourself signed out!

**Comment by burekas7** [comment]
Thanks, now it's ok.

It's well explained here:
https://firebase.google.com/docs/auth/android/firebaseui

I added it in addition to the FirebaseAuth.signout() and it's working good.

By the way, regarding the "delete" method, does it totally delete the user from firebase users?

**Comment by samtstern** [comment]
Yes, it totally deletes them from Firebase.

**Comment by richjhart** [comment]
This still isn't working for me - I've switch over to using AuthUI.getInstance().signOut(), but it still just automatically logs me in again instead of giving me the account list.
