### ISSUE TITLE
Cannot resolve symbols in project

### ISSUE THREAD

**Issue by iamyaoxi** [firebase/FirebaseUI-Android#1492]
Is anyone facing similar issue with me? I make sure the code is up-to-date with `master`, and it compiles, and `:library:prepareArtifacts` task is working.

But, whenever I want to work on the code, the IDE can't recognise other classes within the same module.

For example:

`com.firebase.ui.auth.AuthUI` cannot resolve imports on `com.firebase.ui.auth.data.model.FlowParameters`. Is it related to `@RestrictTo(RestrictTo.Scope.LIBRARY_GROUP)` annotations?

**Comment by iamyaoxi** [comment]
Hmm. Somehow the issue solved when I use IntelliJ and not Android Studio...

**Comment by samtstern** [comment]
That's strange!  I am using Android Studio 3.2.1 stable, for what it's worth.
