### ISSUE TITLE
Implement Email link sign in phase 2

### ISSUE THREAD

**Issue by lsirac** [firebase/FirebaseUI-Android#1496]
Phase 2 allows using email link sign in across different devices.  

Also need to fix the following issues with phase 1:
1. Pressing the back button from TroubleSigningInFragment should return you to the EmailLinkFragment
2. Add a picture

**Comment by samtstern** [comment]
My personal vote is to wait to let phase 1 soak in a public release before
continuing here.  We'll get feedback and it will be easier to fix before
we've layered more complexity on top.
