### ISSUE TITLE
Code:12500 when using 'Sign in with Google'

### ISSUE THREAD

**Issue by avyx7** [firebase/FirebaseUI-Android#1504]
hello guys,
The app is running on my mobile device. While pressing 'Sign in with Google' it gives a toast message 'Code:12500'

**Comment by irwinOT** [comment]
so?

**Comment by MoacirSchmidt** [comment]
Usually this error is related to missing google-services plugin for gradle. see https://developers.google.com/android/guides/google-services-plugin

**Comment by twiceyuan** [comment]
There is another possible reason: you did not enable the Google sign-in option in the Firebase Console
