### ISSUE TITLE
Error: Program type already present: com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Type$1

### ISSUE THREAD

**Issue by dimitrileite** [firebase/FirebaseUI-Android#1511]
Describe your environment

  * Android device: Motorola G5
  * Android OS version: Android 8.1.1
  * Google Play Services version: 4.1.0
  * Firebase/Play Services SDK version: 16.0.4/16.0.1
  * FirebaseUI version: 4.2.1
  
Describe the problem:

After upgrading to FirebaseUI 4.2.1 this error came:
Error: Program type already present: com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Type$1
I have downgraded to 4.2.0, 4.1.0, 4.0.1 but the problem is persistent.

#### Steps to reproduce:

  1. _____ have these on the buildgradle:

Project:

```groov
buildscript {
    ext.kotlin_version = '1.2.71'
    ext.android_plugin_version = '3.2.1'
    ext.google_play_services = '4.1.0'

    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath "com.android.tools.build:gradle:3.2.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.2.71"
        // classpath "io.fabric.tools:gradle:1.25.4"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath "com.google.gms:google-services:4.1.0"
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://maven.fabric.io/public' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

App:

```groovy
    // Support lib
    implementation "com.android.support:appcompat-v7:27.1.1"
    implementation "com.android.support:cardview-v7:27.1.1"
    implementation "com.android.support:customtabs:27.1.1"
    implementation "com.android.support:design:27.1.1"
    implementation "com.android.support:palette-v7:27.1.1"
    implementation "com.android.support:recyclerview-v7:27.1.1"
    implementation "com.android.support:support-v4:27.1.1"

    implementation "com.android.support.constraint:constraint-layout:1.1.3"

    // Firebase
    implementation "com.google.firebase:firebase-analytics:16.0.4"
    implementation "com.google.firebase:firebase-appindexing:16.0.2"
    implementation "com.google.firebase:firebase-auth:16.0.5"
    implementation "com.google.firebase:firebase-config:16.1.0"
    implementation "com.google.firebase:firebase-core:16.0.4"
    implementation "com.google.firebase:firebase-crash:16.2.1"
    implementation "com.google.firebase:firebase-database:16.0.4"
    implementation "com.google.firebase:firebase-firestore:17.1.2"
    implementation "com.google.firebase:firebase-messaging:17.3.4"
    implementation "com.google.firebase:firebase-storage:16.0.4"

    //Crashlytics
    implementation "com.crashlytics.sdk.android:crashlytics:2.9.5"

    // FirebaseUI for Firebase UI
    implementation "com.firebaseui:firebase-ui-auth:$firebaseUI"
    implementation "com.firebaseui:firebase-ui-database:$firebaseUI"
    implementation "com.firebaseui:firebase-ui-firestore:$firebaseUI"
    implementation "com.firebaseui:firebase-ui-storage:$firebaseUI"

    // Google Play Services
    implementation "com.google.android.gms:play-services-auth:16.0.1"
    implementation "com.google.android.gms:play-services-basement:16.1.0"
    implementation "com.google.android.gms:play-services-location:16.0.0"
    implementation "com.google.android.gms:play-services-places:16.0.0"
    implementation "com.google.android.gms:play-services-ads:17.0.0"
    implementation "com.google.android.gms:play-services-appinvite:16.0.4"
    implementation "com.google.android.gms:play-services-maps:16.0.0"
 ```

#### Observed Results:

```
Error: Program type already present: com.google.protobuf.DescriptorProtos$1
```
  
#### Expected Results:
Compile and deploy

**Comment by samtstern** [comment]
@dimitrileite what's the latest version of FirebaseUI that doesn't have this issue?

**Comment by dimitrileite** [comment]
It worked just now but I needed to roll back to 3.3.1.

**Comment by SMH17** [comment]
After the update of Firebase libs I have the same problem with all my projects and they don't compile unless I downgrade libs to previous version or I remove 'com.google.firebase:firebase-core:16.0.5'. The previous 16.0.4 version works.

**Comment by dimitrileite** [comment]
Anyone knows how to upgrade to 4.2.1 without having this issue?
Error: Program type already present: com.google.protobuf.DescriptorProtos$FieldDescriptorProto$Type$1

**Comment by dimitrileite** [comment]
It looks like someone has answered something that can help fix this issue in this [link](https://stackoverflow.com/questions/46949761/unable-to-merge-dex-android-studio-3-0/46971548#46971548).

**Comment by samtstern** [comment]
On StackOverflow the answer says to add an explicit dependency on the right version of `com.google.android.gms:play-services-auth`.  Did that help?

**Comment by dimitrileite** [comment]
FOUND the error: 
I found that FirebaseUI has Glide as a dependency.
So I just needed to comment this line:
// kapt 'com.github.bumptech.glide:compiler:4.8.0'
and now I`m using FirebaseUI 4.2.1!!!!!
Thanks Jesus!

**Comment by dimitrileite** [comment]
Once again I tried to see what was going on but I came up with using both versions together until we have some update on firebaseUI.firestore:

Using FirebaseUI version 4.2.1 but firestore 3.3.1.

ext {
    firebaseUI = '4.2.1'
    firebaseUIold = '3.3.1'
}
implementation "com.firebaseui:firebase-ui-auth:$firebaseUI"
implementation "com.firebaseui:firebase-ui-database:$firebaseUI"
implementation "com.firebaseui:firebase-ui-firestore:**$firebaseUIold**"
implementation "com.firebaseui:firebase-ui-storage:$firebaseUI"

Working 75%

**Comment by dimitrileite** [comment]
Now I have the full answer. 
I discovered that the library 
> api  'com.theartofdev.edmodo:android-image-cropper:2.8.0' 
was having ##a transitive dependency##. 
Following this [link](https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html) I changed to:
> implementation ("com.theartofdev.edmodo:android-image-cropper:2.8.0") {
>       exclude group: 'com.google.protobuf', module: 'protobuf-lite'
>  }
Now 100% of the FirebaseUI is implemented in my project.
Thanks Jesus! ... and there were 12 days. 👍 :-)
