### ISSUE TITLE
Broken phone country dialog after rotation

### ISSUE THREAD

**Issue by ryanjohn1** [firebase/FirebaseUI-Android#1518]
After rotating the phone on the phone number entry screen, the country code picker dialog no longer works 

  * Android device: Samsung S8 and Samsung S4
  * Android OS version: 8.0 and 5.0
  * Google Play Services version: 16.0.4
  * Firebase/Play Services SDK version: 16.0.4
  * FirebaseUI version: 4.2.1

#### Steps to reproduce:

  1. Choose "Sign in with phone" auth option
  2. Rotate device while on the enter phone number screen
  3. Tap country code picker
  
#### Observed Results:

  * A white rectangle appears on screen as a dialog
  
#### Expected Results:

  * A dialog with a list of country codes appears

**Comment by samtstern** [comment]
Fix implemented, will be in version `4.3.0`

**Comment by samtstern** [comment]
This has been released in version `4.3.0`.
