### ISSUE TITLE
Exception:  No provider even though we received a FirebaseAuthUserCollisionException

### ISSUE THREAD

**Issue by j2emanue** [firebase/FirebaseUI-Android#1519]
the class StartWelcomeBackFlow a very very small percentage of users are getting this error: 

in StartWelcomeBackFlow:

Fatal Exception: java.lang.IllegalStateException
No provider even though we received a FirebaseAuthUserCollisionException
com.firebase.ui.auth.viewmodel.idp.SocialProviderResponseHandler$StartWelcomeBackFlow.onSuccess

when i check the code i see that firebase UI auth library itself is throwing this error:

from SocialProviderResponseHandler.java:

  @AuthUI.SupportedProvider String provider = ProviderUtils.getLastUsedProvider(result);
            if (provider == null) {
                throw new IllegalStateException(
                        "No provider even though we received a FirebaseAuthUserCollisionException");
            }

so seems if there is no providers in the list after a collision occurs this can happen. how does this occur ?  How can i reproduce this issue or what do you recommend to fix this. the app should not crash.

**Comment by samtstern** [comment]
Reproduced, and definitely my fault

**Comment by j2emanue** [comment]
can you give me the fix for it.  i will fork and apply the fix. or tell me how to reproduce it.

**Comment by Jemshi101** [comment]
Is this issue fixed? I just got hit by this

**Comment by rjbx** [comment]
I reproduce this bug on attempting to authenticate with the email address associated with a 'FirebaseUser' prior to a successful call to 'changeEmail'.  The same response is generated after both a successful call to 'signOut' with the same 'FirebaseUser' as well as deleting and re-installing the application.

**Comment by samtstern** [comment]
I have no idea what I did on "Nov 5, 2018" to reproduce this (I feel dumb for not writing it down) and since @rjbx has provided a very clear and actionable path to reproduction I am going to assume that's the core issue and mark this as a duplicate of #1644, which I will try to fix in the next release.
