### ISSUE TITLE
Refreshing blink on resume, Firestore

### ISSUE THREAD

**Issue by dovahkiin98** [firebase/FirebaseUI-Android#1523]
When I open the recent apps and come back to my app (Pause the app), the list refreshes itself. That is probably because `stopListening()` is called in `onStop()`.
I wonder if this is intended, or if there a way to fix this refreshing blink when coming back to the app.

**Comment by dovahkiin98** [comment]
I managed to remove the blink by moving `stopListening` to `onDestroy`. So far this doesn't seem to be crashing.

**Comment by SUPERCILEX** [comment]
See https://github.com/firebase/FirebaseUI-Android/issues/947. I'm almost ready to publish a guide demoing how to keep track of your state.

**Comment by samtstern** [comment]
Yeah let's talk about this issue on #947.

@SUPERCILEX excited to see this guide!  Also if you have any changes you think we should make in FirebaseUI to accommodate this, let me know.

**Comment by SUPERCILEX** [comment]
@samtstern ❤️. I've tried multiple times to come up with a nice API, but it never worked out nice. 😭
