### ISSUE TITLE
Terms of Service/Privacy Policy links are clickable beyond their text

### ISSUE THREAD

**Issue by lsirac** [firebase/FirebaseUI-Android#1525]
If you tap around, not on, the Tos/Pp links you'll be redirected.

**Comment by samtstern** [comment]
I was only able to observe this when clicking slightly to the left of the words "Terms of Service" on the `AuthMethodPickerActivity` screen but I think that's actually how AppCompatTextView implements selection in a multi-line situation and not something we can control / can worry about.
