### ISSUE TITLE
Improve phone auth UX

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#1526]
I've used several other phone auth systems and found a few improvements we can do:
- If the user is typing, automatically start the auth process once all numbers have been typed
   - We'll probably have to update the ToS text
- In `onResume` check the clipboard and automatically start the auth process if a 6 digit number is present

**Comment by samtstern** [comment]
Both are good suggestions!

**Comment by SUPERCILEX** [comment]
Oooooh, even cooler: https://developers.google.com/identity/sms-retriever/request. Totally gonna build this just so I can drool at how sleek the whole experience will be. 🤤😍😁

**Comment by samtstern** [comment]
The SMS Retriever API is supposed to already be built in to Firebase Auth,
that's one way auto verification can work.

Although I don't remember ever seeing it work haha...

**Comment by SUPERCILEX** [comment]
Aw, really 😭? Well it sounds cool in principle. 😉

**Comment by samtstern** [comment]
@SUPERCILEX jut FYI I was finally able to see both forms of auto-fill work:

  * The first time I tried the sample app on my new personal phone I got an SMS and it used the SMS-retriever API to fill the code.
  * I did phone auth again and then I was able to see the completely invisible "auto verification" take place where the sms never even was delivered, Google already knew this was my phone and what number it had.

**Comment by samtstern** [comment]
Also here's a UX issue I noticed in the above:

  * Start phone sign in
  * SMS is sent
  * SMS retriever API picks up the number automatically
  * Sign in completes

What happens here is I am suddenly presented with the SmartLock save dialog on top of `CheckPhoneNumberFragment` even though the fragment still shows empty number entry.  I think we need to show the number auto-entered for clarity (as if a robot filled out the UI).

**Comment by SUPERCILEX** [comment]
Sorry for the delay. 😳

The auto verification stuff suddenly started working for me too, though I'm not sure why. (Just in case you need to [disable it](https://stackoverflow.com/a/54176372/4548500).) I actually didn't change anything there though, so 🤷‍♂️. The new UX I added is where a copied number is automatically pasted into the code field (not sure if you saw that 🤔) + the auto submit stuff (which you saw 👍).

Totally agree about the blank field being weird, will fix. 👍

**Comment by samtstern** [comment]
This has been fixed and released in version `4.3.2`
