### ISSUE TITLE
Failed to resolve: com.firebaseui:firebase-ui-auth-github:4.2.1

### ISSUE THREAD

**Issue by MartinXPN** [firebase/FirebaseUI-Android#1533]
Seems like the ui for github authentication cannot be added to the project. When adding it to the gradle file like this:
  ```
    // ...
    implementation 'com.firebaseui:firebase-ui-auth:4.2.1'
    implementation 'com.firebaseui:firebase-ui-auth-github:4.2.1'
    // ...
  ```

The gradle build fails with the following error:
  `Failed to resolve: com.firebaseui:firebase-ui-auth-github:4.2.1`

**Comment by samtstern** [comment]
@MartinXPN good catch!  I never actually mirrored that package to jCenter.  Doing that now.

It's a little sad that you're the first to mention it, clearly we don't have enough people using GitHub auth!

**Comment by samtstern** [comment]
This has been fixed.
