### ISSUE TITLE
Obtaining A Facebook Friends List

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#1535]
If a user signs in and authenticates via Facebook, does the app gain access to that user's friends? I ask as I am interested in potentially having users invite friends and share via Facebook.

**Comment by samtstern** [comment]
@troy21688 not by default, but you can add any scopes you want:
https://github.com/firebase/FirebaseUI-Android/tree/master/auth#oauth-scope-customization

So you could ask for the Facebook friends scope (I don't know it off the top of my head) and then after the FirebaseUI sign in completes you can use the Facebook Android SDK to retrieve the friends.
