### ISSUE TITLE
Login Buttons

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#1536]
Is it possible at all to move them up? Also, is the image/logo size limited?

**Comment by samtstern** [comment]
@troy21688 right now the answer is "no" to most customization questions.  However in version `4.3.0` we are launching the ability to provide a fully custom layout on the main sign-in screen which will allow you to better match the style of your app:

See #1477 for the ideas and #1513  for an example of what you can do with it!
