### ISSUE TITLE
"Code: 8 Message: 8" error when double tapping "Sign In" button

### ISSUE THREAD

**Issue by hendrep** [firebase/FirebaseUI-Android#1538]
### Step 2: Describe your environment

  * Android device:  Samsung A3 and Xiaomi A1 (not tested on other devices yet)
  * Android OS version: 7 and 8.1
  * Google Play Services version: 4.0.1
  * Firebase/Play Services SDK version: 16.04
  * FirebaseUI version: 4.2.1
  
### Step 3: Describe the problem:
FirebaseUI reverts to main screen with toast: "Code: 8 Message: 8" when "Sign-In" button is tapped twice on the "You already have an account screen"

#### Steps to reproduce:

  1. Sign up with Google account
  2. Sign in with email option
  3. On "You already have an account" screen, tap sign in button twice

Sometimes there is a bit of a delay and user thinks that they did not tap the button, resulting in this behaviour.
  
#### Observed Results:
Code: 8, Message: 8 toast is displayed and UI reverts to main screen.
  
#### Expected Results:

User should not be able to double tap the sign-in button.

**Comment by samtstern** [comment]
@hendrep thanks for this!  I was able to reproduce the bug.

**Comment by samtstern** [comment]
Fixing this in #1541

**Comment by samtstern** [comment]
This has been released in version `4.3.0`.
