### ISSUE TITLE
Firebase RecyclerView Adapter don't get refreshed

### ISSUE THREAD

**Issue by rajjejosefsson** [firebase/FirebaseUI-Android#154]
Is it me doing wrong or is it Firebase RecyclerView Adapter that doesn't work with notifying a change.
I want to change the query based on what item is selected from a spinner.

Please check repo here.

http://stackoverflow.com/questions/37515383/does-anyone-know-if-firebase-can-notify-the-adapter-against-a-query

**Comment by samtstern** [comment]
Answering on StackOverflow, closing here.
