### ISSUE TITLE
FirebaseImageLoader.FirebaseStorageKey doesn't implement hashCode() and equals()

### ISSUE THREAD

**Issue by lahiruchandima** [firebase/FirebaseUI-Android#1543]
`FirebaseImageLoader.FirebaseStorageKey` implements Key interface of glide.

The documentation at `Key` interface mentions that it is necessary for the implementations to implement `hashCode()` and `equals()` methods. But `FirebaseImageLoader.FirebaseStorageKey` doesn't implement them.

I sometimes observe an issue where glide is loading the same image multiple times from firebase, without looking in the cache. It may be happening due to this.

**Comment by samtstern** [comment]
@lahiruchandima nice catch!  We'll get this fixed in the next release.

**Comment by samtstern** [comment]
This has been released in version `4.3.0`.
