### ISSUE TITLE
Resize images on the server to the requested dimensions with FirebaseImageLoader

### ISSUE THREAD

**Issue by carloshwa** [firebase/FirebaseUI-Android#1545]
If I have a 1000x1000 image in Firebase Storage and would like to download it using `FirebaseImageLoader` into a 100x100 `ImageView`, resize the image on the server to the requested dimensions before downloading to conserve bandwidth and memory use.

I'm not sure if Firebase Storage even provides this capability on the server-side, but it would be very useful!

**Comment by samtstern** [comment]
@carloshwa thanks for the feedback!  I am going to close this issue since there's nothing we can do in FirebaseUI to get the server to do the resizing but I agree it's a great idea.

You can go here to submit your feature request to the backend team:
https://firebase.google.com/support/
