### ISSUE TITLE
issue with support libraries in main project

### ISSUE THREAD

**Issue by devingDev** [firebase/FirebaseUI-Android#1546]
So my project uses sdk 28 and that support library version too.
FirebaseUI (auth) uses 27 for some of the stuff like customTabs 

I saw the readme.md and it say "add explicit implementation declarations" , does that mean I have to pull the whole project of firebaseUI , change the lines to make it use api 28 ?
and then?

I tried just copying and pasting auth folder (which is the only thing I am using) but it uses build.gradle.kts and had lots of errors when I looked into it, no idea how to fix it to work in my normal java android project with gradle.
My plan was to add the auth project in settings.gradle in the root and then do the implementation project(':auth') in build.gradle but because of that build.gradle.kts file I am confused.

**Comment by devingDev** [comment]
I tried cloning the whole thing then changed some lines in Config.kt 
like object Support {
            private const val version = "28.0.0"
and 
object SdkVersions {
        const val compile = 28
        const val target = 28
        const val min = 16
    }

but when I do buildNeeded gradle task it errors with this message which I can not fix :  
`C:\Users\user1\Desktop\FirebaseUI-Android-master\auth: Error: All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 28.0.0, 27.0.2. Examples include com.android.support:animated-vector-drawable:28.0.0 and com.android.support:support-media-compat:27.0.2 [GradleCompatible]
  
`

i cant find the support-media-compat anywhere, neither can I find the 27.0.2 anywhere.

**Comment by devingDev** [comment]
Oh now I see what you have to do. I just have to add the implementation lines to my app build.gradle , right?

**Comment by samtstern** [comment]
@devingDev yeah you just need to add the `implementation` lines to your app's `build.gradle`.  You don't need to download or modify the FirebaseUI source.

**Comment by samtstern** [comment]
@devingDev we have released version `4.3.0` which depends on support lib v28 so your issue should be solved.
