### ISSUE TITLE
Adding logo in phone auth screen

### ISSUE THREAD

**Issue by hkchakladar** [firebase/FirebaseUI-Android#1551]
I'm only using Phone auth and while launching app, it directly shows the phoneauth screen, which is okay.

But it doesn't look good. I want to add logo in the top, as we do on provider selection page.

This is what it looks like now:
![phone-auth-page](https://user-images.githubusercontent.com/7250906/50041991-577c7200-0083-11e9-8d60-4f09cb465c06.jpg)

**Comment by samtstern** [comment]
@hkchakladar thanks for the suggestion!  We don't have any plans to add more logos throughout the flow.  If this is critical to you, this may be a good reason to fork the library.
