### ISSUE TITLE
AuthMethodPickerLayout class and setAuthMethodPickerLayout(AuthMethodPickerLayout layout) method couldn't find

### ISSUE THREAD

**Issue by engineerchef** [firebase/FirebaseUI-Android#1556]
More info "Auth method picker layout" section at https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#custom-layout

I also wrote an issue at https://issuetracker.google.com/issues/122001983

![2018-12-26 182612](https://user-images.githubusercontent.com/4135858/50453001-be850b00-094e-11e9-9ff2-952c55f4b125.jpg)

**Comment by engineerchef** [comment]
I found solution as below;

1. Open `app/build.gradle` file
2. implement firebase-ui-auth library as `implementation 'com.firebaseui:firebase-ui-auth:4.3.0'` into dependencies
3. Build project again
4. Done!

**Comment by samtstern** [comment]
@engineerchef thanks for following up with your own solution!
