### ISSUE TITLE
Add your own Authentication provider to FirebaseUI-Android

### ISSUE THREAD

**Issue by wtb2015** [firebase/FirebaseUI-Android#1557]
There is a need to modify the Authprovider screen to allow other Authentication providers such as Line, Odnoklassniki, VKontakte, etc. 

From the StackOverflow entry:
https://stackoverflow.com/questions/51491812/is-it-possible-to-add-a-line-login-button-to-firebaseui-so-that-it-will-be-displ/51500852

Is this a possible feature enhancement ?

Update: 
We are trying to implement the custom lay-out 
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#custom-layout

However we receive an error when we implement two 
new AuthUI.IdpConfig.AnonymousBuilder().build()
the error states we can only implement one.

Therefore I am forking/cloning the repository and will try to add the other Authproviders specifically into my fork of FirebaseUI.

**Comment by samtstern** [comment]
@wtb2015 thanks for the feedback!  We have heard this before and it would definitely be a nice feature, bit it's very complex to do correctly and right now we don't plan to add it to FirebaseUI.

Forking and adding your own support is the right way to go for now.
