### ISSUE TITLE
AuthUI.EMAIL_PROVIDER value

### ISSUE THREAD

**Issue by consp1racy** [firebase/FirebaseUI-Android#156]
Current state:

    AuthUI.EMAIL_PROVIDER = "email"

Desired state:

    AuthUI.EMAIL_PROVIDER = "password"

Why:

1) Consistency. The provider is called "password" within Firebase.
2) Utility. The following code currently does not filter out email provider

        val auth = FirebaseAuth.getInstance();
        val allProviders = listOf(
                AuthUI.EMAIL_PROVIDER,
                AuthUI.GOOGLE_PROVIDER,
                AuthUI.FACEBOOK_PROVIDER)
        val currentUser = auth.currentUser
        if (currentUser != null) {
            // already signed in
            val providers = allProviders.filterNot { currentUser.providers!!.contains(it) }.toTypedArray()
            startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setProviders(*providers)
                            .build(),
                    1);
        }

`auth.currentUser.providers` returns `"password"` as provided by Firebase instead of `"email"` as used with AuthUI.

**Comment by consp1racy** [comment]
And "google.com" instead of "google".
And similar for facebook.

And after finding this out maybe it best be kept decoupled...

**Comment by samtstern** [comment]
@amandle what do you think about this?  Should the constants be the same as the Firebase SDK?

**Comment by amandle** [comment]
We originally made them different because they mean two different things.  One is a configuration setting for the UI, and the other is an identity provider.  I can see how it is confusing though, since currently each configuration option is a one-to-one mapping to identity provider. I personally think they should remain different but I don't feel too strongly about it.

**Comment by samtstern** [comment]
Ok if you think they should remain different I am inclined to leave them as-is unless it starts causing major problems.
