### ISSUE TITLE
Single unified link for parallelized test runs

### ISSUE THREAD

**Issue by niranjani23** [firebase/FirebaseUI-Android#1566]
Am using Flank test runner to parallelize my test runs and execute them on Firebase and finally report test results on our slack channel. Since I started parallelizing test runs, there are separate instances for each test run and there is no single unified link that I can report stating for example as "Smoke test run link". Would be super useful to have a single link for parallel test runs. 

Not sure if this is the right place for adding feature requests. Feel free to move it to the relevant location.

**Comment by samtstern** [comment]
I don't think this issue has anything to do with the FirebaseUI library so I am going to close it.  Please see this link for better ways to provide feedback:
https://firebase.google.com/support/
