### ISSUE TITLE
Twitter Provider

### ISSUE THREAD

**Issue by raulperez** [firebase/FirebaseUI-Android#157]
Doesn't the last version include the twitter provider?

**Comment by samtstern** [comment]
Firebase Auth does support Twitter login, however we have not yet implemented the UI flow in FirebaseUI.

If you want to use Twitter login with Firebase you can follow [this example](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/TwitterLoginActivity.java) to implement the UI yourself.

**Comment by raulperez** [comment]
Thank you Sam.

It will be implemented later on?

**Comment by samtstern** [comment]
@raulperez yes we hope to support all providers eventually, but the priority now is fixing bugs in the Facebook/Google/Email implementation so that there is a solid base for that future work.

**Comment by dazza5000** [comment]
:+1:

**Comment by mockitoo** [comment]
![image](https://cloud.githubusercontent.com/assets/16718247/16340587/a73a2df2-3a31-11e6-9239-e9c3fa378115.png)

**Comment by Chris-crisur** [comment]
@samtstern I have managed to implement Twitter login a while ago; would you like me to extend this library's UI flow to include it?
The recent(ish) Firebase upgrades have also meant Firebase Twitter auth works with Digits too now; but Firebase can give a `User has already been linked to the given provider` error if the user tries to login with Twitter AND Digits. One solution is to log them out of the old provider (e.g. Twitter) and auth again with the new provider (e.g. Digits).

**Comment by Chris-crisur** [comment]
if this gets enough 'like's and the moderators (cough @samtstern cough) approve; I will work to implement it.
Moderators, would you like me to create a new issue with the proposed change (Twitter integration) as per your contribution steps?

**Comment by samtstern** [comment]
I think amandle@ is already working on this, we know it's an important
feature for everyone and it's at the top of our list too.

**Comment by Chris-crisur** [comment]
Awesome!
@amandle let me know if you need help.
Would also be keen to implement Digits, which would piggy back off Twitter.

**Comment by dazza5000** [comment]
Looking forward to this!

**Comment by dazza5000** [comment]
THANK YOU!
