### ISSUE TITLE
firebaseUI-database 4.3.1 give errors (Failed to resolve: support-v4 / Failed to resolve: recyclerview-v7/Failed to resolve: viewmodel) with sdk 28

### ISSUE THREAD

**Issue by adam9200394** [firebase/FirebaseUI-Android#1570]
this are dependencies  i'm using:

```groovy
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0-alpha'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'

    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation ('com.android.support.test.espresso:espresso-core:3.0.2',{
        exclude group: 'com.android.support' , module: 'support-annotations'
    })
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-database:16.0.5'
    implementation 'com.google.firebase:firebase-storage:16.0.5'

    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'de.hdodenhof:circleimageview:3.0.0'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'
    implementation 'com.firebaseui:firebase-ui-database:4.3.1'


    implementation 'com.squareup.picasso:picasso:2.5.2'
    implementation 'com.theartofdev.edmodo:android-image-cropper:2.4.+'
```

**Comment by samtstern** [comment]
@adam9200394 sorry for my slow response here.  This isn't quite enough information to debug.  What are you doing to get those errors?  And can you paste the full error log here?

**Comment by adam9200394** [comment]
i'm using appcompat-v7:28.0.0 and the firebase libraries firebase-core:16.0.6 and 
firebase-auth:16.1.0 and firebase-database:16.0.5 and when adding the firebaseUI library 
firebase-ui-database:4.3.1 it gave me three errors:
cannot resolve support-v4
cannot resolve recyclerview-v7
cannot resolve viewmodel

but when i use appcompat-v7:28.0.0-rc01 it works fine when i use firebase-ui-database:3.2.1 and it's the only version that work i tried all of them with all of the appcompat-v7 versions trying to solve this problem for two days now please help        

[build gradle.txt](https://github.com/firebase/FirebaseUI-Android/files/2776088/build.gradle.txt)

**Comment by adam9200394** [comment]
@samtstern also my android studio IDE version is 3.3 the latest version but firebase-ui-database:4.3.1 says it require android version 4.3.1 help me solve this issue to see if it related to the updated version

**Comment by samtstern** [comment]
When you say:

> it gave me three errors:
> cannot resolve support-v4
> cannot resolve recyclerview-v7
> cannot resolve viewmodel

Can you provide some screenshot or copy-paste of the exact error you're getting?

Also what happens if you change:

```
    implementation 'com.android.support:appcompat-v7:28.0.0-rc01'
    implementation 'com.android.support:design:28.0.0-rc01'
```

to 

```
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
```

**Comment by adam9200394** [comment]
thanks the problem solved i upgraded my IDE from 3.2 to 3.3 and upgraded the gradle form 3.3 to 4.10

**Comment by RahmanPurwanto** [comment]
@Override
    protected void onStart() {
        super.onStart();
        FirebaseRecyclerAdapter<Users, UsersViewHolder> firebaseRecyclerAdapter = new FirebaseRecyclerAdapter<Users, UsersViewHolder>(
                Users.class,
                R.layout.users_single_layout,
                UsersViewHolder.class,
                mUserDatabase
        ) {
            @Override
            protected void populateViewHolder(UsersViewHolder usersViewHolder, Users users, int position) {
                usersViewHolder.setName(users.getName());
            }
        };
        mUsersList.setAdapter(firebaseRecyclerAdapter);
    }

**Comment by RahmanPurwanto** [comment]
help please.. this is my error.. i cant use firebaseRecyclerView maybe because my dependencies update  

implementation 'com.firebaseui:firebase-ui-database:4.3.1'

**Comment by adam9200394** [comment]
`the method  populateViewHolder() is redundant create your viewHolder class  then use FirebaseRecyclerAdapter like this``

**Comment by adam9200394** [comment]
FirebaseRecyclerOpation  opation  = new FirebaseRecyclerOpation.Builder<yourClass>().setQuery(FirebaseReference, yourClass.class).build();

 FirebaseRecyclerAdapter<Chats, ChatsViewHolder> adapter =
                new FirebaseRecyclerAdapter<Chats, ChatsViewHolder>(options) {

                    @Override
                    protected void onBindViewHolder(@NonNull final ViewHolder holder, final int 
                     position, @NonNull yourClass  model)
                    {  
                     return yourViewHolder
                    }
                     @NonNull
                    @Override
                    public ViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int i) {
                        return viewHolder;
                    }

**Comment by RahmanPurwanto** [comment]
@adam9200394 
Cok Matane, sek ga kenek ngene.
Translate : Wow Man, its work thanks for your help 👍

**Comment by farhat6745646** [comment]
Failed to resolve: com.firebaseui:firbase-ui-databse:4.3.1
there is resovle error is not slove kindly tell me how resolve this error

**Comment by farhat6745646** [comment]
implementation 'com.google.firebase:firebase-messaging:17.3.4'

    implementation 'com.google.firebase:firebase-database:16.0.6'
    implementation 'com.google.firebase:firebase-core:16.0.7'
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support:design:28.0.0'
    implementation 'com.karumi:dexter:5.0.0'
    implementation 'com.firebaseui:firbase-ui-databse:4.3.1'
    implementation 'com.firebaseui:firbase-ui-auth:4.3.1'
    implementation 'com.github.d-max:spots-dialog:1.1@aar'
    implementation 'com.google.android.gms:play-services-location:16.0.0'
    implementation 'com.github.mancj:MaterialSearchBar:0.8.2'

    //RxJava2
    implementation 'io.reactivex.rxjava2:rxandroid:2.0.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.1.7'

    //Retrofit2
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
