### ISSUE TITLE
State changing in RecyclerAdapter

### ISSUE THREAD

**Issue by dovahkiin98** [firebase/FirebaseUI-Android#1578]
* Android device: Emulator
  * Android OS version: 8.0.0
  * Google Play Services version: latest
  * Firebase/Play Services SDK version: latest
  * FirebaseUI version: 4.3.1

When using RecyclerAdapter, any operation on the data is automatically saved offline, and therefore shown on the adapter.

I have this case where :
A message's state is 0 (sending), until the message has reached the server, in which the state becomes 1 (sent). 
If I quickly set the state to 1, the adapter will already use the new state, even when using WriteBatch.
And sending another update after the message has been sent is risky, as the other update might happen much later than the sending.

Is there any way I can solve this? Maybe stop the Adapter from saving the state offline or something?

**Comment by samtstern** [comment]
@dovahkiin98 I'm sorry I don't full understand the question.  Could you show some code snippets that cause the behavior you're seeing and explain the desired behavior?

**Comment by dovahkiin98** [comment]
This is what I'm trying to do, send a message, but also change the state of the message after it is sent.

```kotlin
FirebaseFirestore.getInstance().batch()
    .set(newMessage, message)
    .update(chat.parent!!, mapOf(
        "lastMessage" to message.text
    ))
    .update(newMessage, mapOf(
        "state" to 1
    )).commit()
```
The adapter quickly jumps to the last state, where the message is sent. Where as, I want the message to change its' state AFTER it has reached the server.

**Comment by samtstern** [comment]
@dovahkiin98 ah ok.  Unfortunately there is no way to completely ignore local updates in the adapter.

However you should be able to do this yourself.  When you get the `DocumentSnapshot` you can call `getMetadata()` to get a `SnapshotMetadata` object:
https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/SnapshotMetadata

Then you can call `hasPendingWrites()` to see if the snapshot has some state that has not yet been written to the server.  You can make your UI consider these messages unsent, or sending.

If you're sorting on `state` however, then the Adapter will continue to jump.
