### ISSUE TITLE
Crash on Meizu devices

### ISSUE THREAD

**Issue by baole** [firebase/FirebaseUI-Android#1581]
### Step 1: Are you in the right place?
yes

### Step 2: Describe your environment

  * Android device: Meizu M5s
  * Android OS version: 6
  * Google Play Services version: N/A
  * Firebase/Play Services SDK version: N/A
  * FirebaseUI version: 4.3.1
  
### Step 3: Describe the problem:

App crash when launches Firebase login UI/ Phone authen.

#### Observed Results:

http://crashes.to/s/3620e0e34ad

This is an known issue on Meizu devices that android.support.design.widget.TextInputLayout is crashed. There are a work-around described at https://stackoverflow.com/questions/51891415/nullpointerexception-on-meizu-devices-in-editor-updatecursorpositionmz
  
#### Expected Results:

No crash
  

Can we avoid using android.support.design.widget.TextInputLayout / com.google.android.material.textfield.TextInputLayout or adopt above workaround for phone login?

**Comment by samtstern** [comment]
@baole thanks for reporting this, and special thanks for linking to a proposed solution.  I am not sure if we should implement device-specific workarounds here when they require doing things that are otherwise not best practice (like specifically referencing appcompat views in XML).

But I will look into it!

**Comment by osipovaleks** [comment]
I have the same bug

**Comment by Nebneb** [comment]
Hello there, I'm still having this issue on Meizu devices and I don't see anything related to this issue in 5.0.0 release. Is there anything new about it or should we implement this workaround on each of our forks ?

**Comment by samtstern** [comment]
There's no update on this issue right now.

**Comment by samtstern** [comment]
Looks like this is going to be fixed by the material components library, which we now use:
https://github.com/material-components/material-components-android/pull/358
