### ISSUE TITLE
Github enterprise

### ISSUE THREAD

**Issue by alorma** [firebase/FirebaseUI-Android#1588]
Is there any option to login into Github Enterprise?

**Comment by samtstern** [comment]
@alorma that's not supported at the moment and I'm not really familiar with the difference.  I assume you tried it and it didn't work?

**Comment by alorma** [comment]
No I've not tried yet

Thing is that enterprise uses a different endpoint to do auth (or it did when i used years ago)

Also, I've not seen any option to configure github enterprise url

**Comment by samtstern** [comment]
@alorma got it, if it uses a different endpoint we don't support it right now.  Firebase Auth may eventually launch support for generic OAuth login and in that case we could handle it.  But it could be a while!

**Comment by alorma** [comment]
@samtstern

Are you open to PR? As both endpoints (if different) return the same responses, it would be easily (hope so) to implement, and i want to give a try on it

**Comment by samtstern** [comment]
I think this would require work outside of FirebaseUI, in the Firebase Auth service and the core SDK.

**Comment by samtstern** [comment]
@alorma I am doing some issue cleanup / consolidation and I am going to consider this a sub-request of #979 which is to support generalized custom OAuth providers.

The good news is that some of the work needed with the Firebase Auth SDK has been done (see `OAuthProvider`) so this may actually be possible in the future.
