### ISSUE TITLE
FirebaseUI RecyclerView Query problem

### ISSUE THREAD

**Issue by sbotev5** [firebase/FirebaseUI-Android#1589]
Hi all,

I am using FirebaseUI for Cloud Firestore. I have two root collections, _users_  and _tenancies_.

A single tenancy document has a few fields - two of them are **name** (type String) and **landlordID** (type Reference).

I want to leverage this amazing library and populate a recyclerview of tenancy for a landlord. I have created a Tenancy class (landlordID is a DocumentReference type and name is String) and a TenancyAdapter as per the README guide.

So the query should look like this:

` String userId = mAuth.getCurrentUser().getUid();
Query query = db.collection("tenancies").whereEqualTo("landlordID", "/users/" + userId);`

From where I continue with _ FirestoreRecyclerOptions<Tenancy>_ etc.

However, nothing gets populated and no errors are given. So I tried this instead:

`Query query = db.collection("tenancies").whereEqualTo("name", "test_harcoded");`

And it works ! It returns the doc that matches. So IDK what I have missed, either from this library or FireStore, but I can't put my finger on why _whereEqualTo_  would fail querying by a different field type.

Thanks in advance.

Kind Regards,

sbotev5

**Comment by sbotev5** [comment]
Adding Tenancy class  and a screen of the Firestore might be of help, the rest is just like the README.

`public class Tenancy {
    private String name;
    private String address;
    private String postCode;
    private String city;
    private String startDate;
    private String endDate;
    private DocumentReference landlordID;
    private List<DocumentReference> tenants;

    public Tenancy(String name, String address, String postCode,
                   String city, String startDate, String endDate,
                   DocumentReference landlordID, List<DocumentReference> tenants) {

        this.name = name;
        this.address = address;
        this.postCode = postCode;
        this.city = city;
        this.startDate = startDate;
        this.endDate = endDate;
        this.landlordID = landlordID;
        this.tenants = tenants;
    }

    public Tenancy(){

    }

//Getters and setters omitted.
`
![image](https://user-images.githubusercontent.com/27702185/53467889-e3315800-3a4f-11e9-951f-1c4eeaac7a4c.png)

**Comment by sbotev5** [comment]
Queries for Reference fields need to be defined in the query.

`Query query = db.collection("some_collection").whereEqualTo("field_name", db.collection("document_collection").document(document_ID));`

**Comment by samtstern** [comment]
Yep @sbotev5 has it right, a string and a Document reference are not the same so the query is returning no results because the types don't match.
