### ISSUE TITLE
Couldn't retrive profile photo url

### ISSUE THREAD

**Issue by Fax3D** [firebase/FirebaseUI-Android#159]
When i try to read getPhotoUrl() on a FirebaseAuth.getInstance().getCurrentUser() on a google account with a valid profile image (during auth ui flow i can see the photo in the account chooser), i always get null.

**Comment by samtstern** [comment]
@Fax3D does this happen on all devices and all accounts?  Also for what it's worth many Google accounts do not have a valid profile picture so you should structure your application to properly handle `null` in this case.

**Comment by Fax3D** [comment]
@samtstern yes on all devices (i have 3 test device with different Android version), and it happens on my personal account. I'm sure profile picture is valid because using google plus api, i can retrive the photourl in the right way. The problem isn't in handling the null (i know there are many account without photo), but it's the impossibility to retrieve the profile picture even when it does.

Thanks.

**Comment by byte-artisan** [comment]
To retrieve user profile from google provider use GIDSignIn class instead, like this:
let googleUser = GIDSignIn.sharedInstance().currentUser
let photoURL = googleUser?.profile.imageURLWithDimension(200)

**Comment by runia1** [comment]
I am also having this issue.  I know the profile photo is there as I can retrieve it from my personal google account using the js api.  Also strangely when I did the "FriendlyChat" demo I was able to retrieve it.  This is my code:

```
private void onLoggedIn() {
        authButton.setOnClickListener(logoutListener);
        authButton.setText(R.string.action_logout);

        //must re-init these to avoid java.lang.NullPointerException when grabbing username, etc,.
        //this happens if user is not logged when onCreate() is called initially.
        mFirebaseAuth = FirebaseAuth.getInstance();
        mFirebaseUser = mFirebaseAuth.getCurrentUser();

        //grab the user's info
        try {
            mUserid = mFirebaseUser.getUid();
            mUsername = mFirebaseUser.getDisplayName();
            mUserprofileUrl = mFirebaseUser.getPhotoUrl().toString();
            Log.i(TAG, "Username: "+mUsername+" Userid: "+mUserid+" profileUrl: "+mUserprofileUrl);
        } catch(Exception e) {
            Log.e(TAG, "Problem fetching user's info from mFirebaseUser, some info may be missing.");
        }

        //use it to set up ui
        usernameView.setText(mUsername);
        if (mUserprofileUrl == null) {
            userProfileView.setImageDrawable(ContextCompat.getDrawable(MainActivity.this, R.drawable.ic_account_circle));
        } else {
            Glide.with(MainActivity.this).load(mUserprofileUrl).into(userProfileView);
        }
        userProfileView.setVisibility(View.VISIBLE);
    }
```

**Comment by alfongj** [comment]
This does not seem to be related to FirebaseUI per se. Could you please reach out via StackOverflow or other support channels for the main Firebase SDKs?

Thank you :)
