### ISSUE TITLE
The app module is using emoji characters outside of UTF-8 set.

### ISSUE THREAD

**Issue by gubo** [firebase/FirebaseUI-Android#161]
the app module is using emojji characters outside of UTF-8 set:

    @see https://code.google.com/p/android/issues/detail?id=64892

    Nexus 4, Android 5.1.1 LMY48T

    app/res/values/strings.xml:
        <string name="sign_in_cancelled">Sign in cancelled 😔</string>
        <string name="delete_account_failed">Delete account failed 😨</string>
        Unsupported characters for the charset 'UTF-8'

at com.firebase.uidemo.auth.AuthUiActivity.showSnackbar(AuthUiActivity.java:228)

06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xf0
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]     string: 'Sign in cancelled 😔'
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]     in call to NewStringUTF
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]     from java.lang.String android.content.res.StringBlock.nativeGetString(long, int)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65] "main" prio=5 tid=1 Runnable
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   | group="main" sCount=0 dsCount=0 obj=0x730c4000 self=0xb8137408
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   | sysTid=23718 nice=0 cgrp=default sched=0/0 handle=0xb6fdbbec
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   | state=R schedstat=( 0 0 0 ) utm=99 stm=21 core=2 HZ=100
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   | stack=0xbe53c000-0xbe53e000 stackSize=8MB
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   | held mutexes= "mutator lock"(shared held)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #00 pc 00004e64  /system/lib/libbacktrace_libc++.so (UnwindCurrent::Unwind(unsigned int, ucontext*)+23)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #01 pc 00003665  /system/lib/libbacktrace_libc++.so (Backtrace::Unwind(unsigned int, ucontext*)+8)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #02 pc 00256401  /system/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, int, char const*, art::mirror::ArtMethod*)+84)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #03 pc 00238fbf  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+158)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #04 pc 000b199b  /system/lib/libart.so (art::JniAbort(char const*, char const*)+610)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #05 pc 000b20d5  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+68)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #06 pc 000b468f  /system/lib/libart.so (art::ScopedCheck::Check(bool, char const*, ...) (.constprop.129)+922)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #07 pc 000be1bd  /system/lib/libart.so (art::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+44)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #08 pc 00089e1f  /system/lib/libandroid_runtime.so (???)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   native: #09 pc 00263393  /data/dalvik-cache/arm/system@framework@boot.oat (Java_android_content_res_StringBlock_nativeGetString__JI+102)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.nativeGetString(Native method)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.content.res.StringBlock.get(StringBlock.java:82)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   - locked <0x183bf025> (a android.content.res.StringBlock)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.content.res.AssetManager.getResourceText(AssetManager.java:154)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   - locked <0x364eb5fa> (a android.content.res.AssetManager)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.content.res.Resources.getText(Resources.java:295)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.support.design.widget.Snackbar.make(Snackbar.java:240)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at com.firebase.uidemo.auth.AuthUiActivity.showSnackbar(AuthUiActivity.java:228)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at com.firebase.uidemo.auth.AuthUiActivity.handleSignInResponse(AuthUiActivity.java:154)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at com.firebase.uidemo.auth.AuthUiActivity.onActivityResult(AuthUiActivity.java:138)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.Activity.dispatchActivityResult(Activity.java:6192)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.access$1300(ActivityThread.java:151)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.os.Handler.dispatchMessage(Handler.java:102)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.os.Looper.loop(Looper.java:135)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at android.app.ActivityThread.main(ActivityThread.java:5254)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke!(Native method)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at java.lang.reflect.Method.invoke(Method.java:372)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
06-02 09:33:19.750 23718-23718/com.firebase.uidemo A/art: art/runtime/check_jni.cc:65]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by samtstern** [comment]
@gubo thanks for the report.  I am surprised to see this crash but it's probably best to just take the characters out.  Would you mind submitting a Pull Request to remove the emojis?  If you'd rather not, I can do it.
