### ISSUE TITLE
FirebaseUI Auth activity hangs when account is disabled

### ISSUE THREAD

**Issue by daerimin** [firebase/FirebaseUI-Android#1611]
1.) Disable test account in Firebase Console
2.) Attempt to log in using that account through Firebase UI pre-made activity
3.) Wait animation begins at the top of the screen, translucent overlay appears
4.) Activity hangs and never completes.  No output or errors of any kind.

**Comment by samtstern** [comment]
@daerimin thanks for reporting this, I will put this on the next milestone for investigation.

Are you trying this with email/password accounts?  And what would your ideal behavior be?

**Comment by daerimin** [comment]
The test was done with an account linked to both Google and FB.  I have not tested other types - I'll be happy to if you'd like.

IMHO, the ideal behavior would be for the FirebaseUI activity to finish with a RESULT_CANCELED code, and for the intent to contain a specific error code so that we would know the account was disabled, and it wasn't just a general failure - that way we could display an appropriate message to the user.

Thanks for your help!!

**Comment by felipe-gouveia** [comment]
Hi @daerimin I can take a look into it today. Are you already close to a fix or can I start?

**Comment by daerimin** [comment]
This particular issue didn't seem to be something I could work around, so I've been hoping for some help from your side. :)

Thank you!


________________________________

**Comment by felipe-gouveia** [comment]
Hi @daerimin I have created the PR https://github.com/firebase/FirebaseUI-Android/pull/1632 with the fix to this issue.

**Comment by samtstern** [comment]
This has been fixed and released in `5.0.0`
