### ISSUE TITLE
How to use multiple queries(Compound queries) with Firestore paging adapter

### ISSUE THREAD

**Issue by dolphylimitinf** [firebase/FirebaseUI-Android#1617]
How to use multiple queries(Compound Queries) with FirestoreRecycleviewAdapter or with FirestorePagingAdapter. 

For example :-
Query query = collectionref.whereEqualTo("field","value").whereEqualTo("field","value")..orderBy("field", Query.Direction.DESCENDING)

Please revert back asap.

**Comment by samtstern** [comment]
@dolphylimitinf when you create the `FirestorePagingOptions` you can pass any valid Firestore query, including the one you posted.  See here:
https://github.com/firebase/FirebaseUI-Android/tree/master/firestore#using-the-firestorepagingadapter

**Comment by dolphylimitinf** [comment]
Thank you, Sir, for your response. But the query I posted to your
repository was not working. Can You please elaborate? As I am unable to
fetch data with the query I am using.
Query query =
collectionref.whereEqualTo("field","value").whereEqualTo("field","value")..orderBy("field",
Query.Direction.DESCENDING)//not working.

Thankyou!!

**Comment by samtstern** [comment]
@dolphylimitinf you're probably missing the index you need, if a certain query is not working that's not related to FirebaseUI.  Check to see if there are any errors in your logs.  Or you could so a simple `get()` on that same query and then print the error in the failure listener.

**Comment by dolphylimitinf** [comment]
Sir but after creating index too its not fetching data.

Thankyou!!

**Comment by sabeehshah** [comment]
How to pass two queries such as GreaterThan and LessThan to accomplish the not-equals query? I am using FirebasePagingAdapter, really need this functionality to combine queries.
