### ISSUE TITLE
Error in Italian strings

### ISSUE THREAD

**Issue by crpalmisano** [firebase/FirebaseUI-Android#1618]
Hi @samtstern,
there are two errors in the Italian string resource file:

1. 

`<string name="fui_tos_and_pp">Se continui, accetti le nostre %1$s e i nostri %2$s.</string>`

should be:

`<string name="fui_tos_and_pp">Se continui, accetti i nostri %1$s e le nostre %2$s.</string>`

2. 

`<string name="fui_sms_terms_of_service_and_privacy_policy_extended">Se tocchi “%1$s”, accetti le nostre %2$s e i nostri %3$s. È possibile che venga inviato un SMS. Potrebbero essere applicate le tariffe per l\'invio dei messaggi e per il traffico dati.</string>`

should be:

`<string name="fui_sms_terms_of_service_and_privacy_policy_extended">Se tocchi “%1$s”, accetti i nostri %2$s e le nostre %3$s. È possibile che venga inviato un SMS. Potrebbero essere applicate le tariffe per l\'invio dei messaggi e per il traffico dati.</string>`

Basically, the translator inverted feminine and masculine in that strings...

Thanks

**Comment by samtstern** [comment]
@crpalmisano thank you for reporting this!  I will include this fix in the next release.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `6.2.1`
