### ISSUE TITLE
FirestorePagingAdapter - Ability to get DocumentReference

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/FirebaseUI-Android#1619]
Can we add `getReference()` method in `FirestorePagingAdapter` so that we can get the `DocumentReference` of a child populated during onBindViewHolder.
Here is what I want to say...

We can add a method as below...
```java
    @NonNull
    public DocumentReference getReference(int position) {
        return getItem(position).getReference();
    }
```

And we will use this as...

```java
    @Override
    protected void onBindViewHolder(@NonNull ItemViewHolder holder,
                                    int position,
                                    @NonNull Item model) {
        DocumentReference itemRef = getReference(position);
        //Futher process...
    }
```

Is it useful?

**Comment by samtstern** [comment]
@PatilShreyas I think since you can already do `getItem(position).getReference();` we don't need to expand the API to support this any further.  But thank you for the suggestion!

**Comment by PatilShreyas** [comment]
@samtstern Yes. Right!
Thanks.
