### ISSUE TITLE
Thumbnail instead of Full resolution Profile Picture

### ISSUE THREAD

**Issue by vptcr** [firebase/FirebaseUI-Android#162]
When I try to do something like:-
`Glide.with(this)
                    .load(FirebaseAuth.getInstance().getCurrentUser().getPhotoUrl())
                    .centerCrop()
                    .placeholder(R.drawable.ic_profile)
                    .crossFade()
                    .into(mainAvatar);
`
The displayed picture is actually a low resolution thumbnail. 
In the previous API, invoking something like:-
`        Glide.with(this).load((String) mAuthData.getProviderData().get("profileImageURL")).into(avatar);
`
always resulted in a high resolution profile picture. 

PLUS, in the previous API, if there was no Profile Image available for user, a placeholder Gravatar image used to arrive as well. That's gone as well.

Kindly consider fixing.

**Comment by puf** [comment]
I agree that it would be great if the Firebase Auth API provided a higher resolution profile picture. 
But this issue is not related to FirebaseUI, so it doesn't belong here.
