### ISSUE TITLE
How to manage the access of the same user on multiple devices

### ISSUE THREAD

**Issue by maneletorres** [firebase/FirebaseUI-Android#1620]
### Step 1: Are you in the right place?
Yes, or at least I think so.

### Step 2: Describe your environment
  * Android device: BQ Aquaris U2
  * Android OS version: 8.1.0
  * Google Play Services version: N/A
  * Firebase/Play Services SDK version: N/A
  * FirebaseUI version: 4.3.1
  
### Step 3: Describe the problem:
I am developing an application in **Android Studio** that uses **Firebase Authentication** (**Google**, **Facebook**, **Twitter** and **Email/password**) and **Firebase Databas**e.

The authentication works perfectly and in the database the different registered users are stored, consisting of a key ('**firebaseUser.getUid()**') and a value consisting of: a list of allergies (in ArrayList format), a displayName ('**firebaseUser.getDisplayName()**' in String format) and an email (in String format).

Example image for a user who has logged in and has been registered in the database:
![image](https://user-images.githubusercontent.com/33102786/56097510-87366c00-5ef5-11e9-933f-b5c7eda4d4eb.png)

On the other hand, in a certain section of my application I have a button with the following associated business logic that is responsible for deleting the user in question from the database and closing the current session (to see the code go to the 'Relevant Code' section).

#### Steps to reproduce:
  1. Open the application and log in to FirebaseAuth in any of the access options with device 1 and user 1.
  2. Open the application and log in to FirebaseAuth in any of the access options with device 2 and user 1.
  3. In the device 1 (although it also works if we take the device 2 as a reference), we click on the button that is responsible for deleting the current user of the Firebase Realtime Database where it is registered.
  
#### Observed Results:
The two devices return to the main screen for authentication, but when I click on either button on the login button (regardless of the option chosen), this initial page reloads again without taking the user's pulse into account. In addition, the log is filled with messages such as "permission denied" or "you are not the owner" and they start to give up.
  
#### Expected Results:
The expected result would be either to limit the access to a single device per user simultaneously or to establish simultaneity mechanisms to allow the connection of two devices through the same user, taking into account that when the user is erased, proceed accordingly efficiently.

Therefore, my question is: what is the best practice to efficiently manage the login of a single user for various devices?
  
#### Relevant Code:
```
userDatabaseReference.removeValue (); // This variable points to FirebaseDatabase.getInstance (). getReference ("users"). child (sUID));
AuthUI.getInstance().signOu (this).addOnCompleteListener(task -> {
Intent intent = new Intent(PreferenceActivity.this, AuthActivity.class); 
startActivity (intent); finish ();});
```

**Comment by samtstern** [comment]
Hi @maneletorres,

Thanks for the detailed issue.  This doesn't seem like it's a bug or issue with FirebaseUI at all, so I would suggest taking your question to StackOverflow.

The issue here is that you have two different user "sessions":
  * One based on Firebase Auth
  * Another based on an entry in the Firebase Database

So when you remove the entry in the database, users may still be signed in via Firebase Auth on another device.  What I would probably suggest is adding a global Database listener to the user record so you can react across devices when this record changes.
