### ISSUE TITLE
Cant connect to Firebase neither using FirebaseUI or Firebase Standard Auth methods

### ISSUE THREAD

**Issue by ricardolousada** [firebase/FirebaseUI-Android#1625]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Emulator - Nexus 5 API 28
  * Android OS version: 9
  * Google Play Services version: 49
  * Firebase/Play Services SDK version: 16.0.8
  * FirebaseUI version: 4.3.2
  
### Step 3: Describe the problem:
I create a fisrt project in the console and tried to connect to my app using standard auth methods. Not only the last step of the app set-up did not finneshed because connection was never made and whem i invoque signInWithEmailAndPassword I always get the following error message: sign is falilure com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted

It's strange because i have made it in the past....I'm also having problems with ruby gems due to certificates, can this be a certificate issue or something?

I tried with another project, a course in Udacity for building an App Chat and I tried to use the Firebase UI, the result is the same, after entering the e-mail it takes a long time doing nothing and then in the log cat i see the following error:
2019-04-29 21:28:38.141 30303-30422/? E/PlayCommon: [1591] com.google.android.play.b.g.a(860): Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com": No address associated with hostname
2019-04-29 21:28:58.157 29991-30054/? E/PlayCommon: [1553] com.google.android.play.b.g.a(860): Failed to connect to server: java.net.UnknownHostException: Unable to resolve host "play.googleapis.com":

and also this one :
2019-04-29 21:33:29.040 1202-1237/com.google.firebase.udacity.friendlychat E/FirebaseInstanceId: Token retrieval failed: AUTHENTICATION_FAILED

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  Already explained above
  
#### Expected Results:

  I was expecting to be able to coonect to Firebase and use the autentication services for my app
  
#### Relevant Code:

I don't think its a code issue, as mentioned above in either the projects the new app setups ends with sucess because connection is never established.

**Comment by samtstern** [comment]
You have a lot of issues like this one:
> Unable to resolve host "play.googleapis.com": No address associated with hostname

Have you tried this on either a real device or one of the emulators that has the Google Play Store on it?  Also what country are you in?  Sounds like your network is blocking google services.

**Comment by samtstern** [comment]
@ricardolousada I am going to close this issue because it does not have anything to do with FirebaseUI.  I would suggest doing a few things:

  * Make sure you're using one of the emulator images with the Play store
  * Open the Play store and sign in, try to download an app
  * Make sure your emulator has a network connection and that you can load "google.com" in the browser

**Comment by ricardolousada** [comment]
@samtstern  Thanks that was the issue :) I can run it on the real device, now i just need to discover how to get my emulator accessing the Internet
PS - From Portugal and running a MAC
Cheers.

**Comment by samtstern** [comment]
@ricardolousada glad it was solved!
