### ISSUE TITLE
I can not use the Query whereEqualTo option with FirestorePagingAdapter

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1629]
When I try to use whereEqualTo in the **FirestorePagingAdapter** query I do not get the data, it does not load anything in the **RecyclerView**, but I do _remove this from the Query_ if it shows the data.

This is the code of the Database that I obtain:
`mPostDB = FirebaseFirestore.getInstance().collection("Publications");`

This database has documents with random ID's. Each document has a **"type"** value of type **number**.

This is the code of the query that I try to use:
`Query mPostWithMethodsQuery = mPostDB.whereEqualTo("type", 4).limit(30).orderBy("date", Query.Direction.DESCENDING);`

Could anyone help me please? I can not continue with my project if I have this problem.

**Comment by samtstern** [comment]
This query:
```
Query mBinsWithMethodsQuery = mPostDB.whereEqualTo("type", 4).limit(30).orderBy("date", Query.Direction.DESCENDING);
```

Requires a compound index on `type` (ASCENDING) and `date` (DESCENDING).  If you create that in the console, I bet you will see some data.

**Comment by itzThiefz-exe** [comment]
Could you give me an example, sir? Sure, if it's not too much trouble.

**Comment by samtstern** [comment]
In the Firebase console under Firestore in the Indexes section:

![image](https://user-images.githubusercontent.com/8466666/57001036-6b74cc00-6b6b-11e9-95b5-b94a6f50ab58.png)

Also make sure `limit` is at the end of your query:

```
// yes
mPostDB.whereEqualTo("type", 4).orderBy("date", Query.Direction.DESCENDING).limit(30);

// no
mPostDB.whereEqualTo("type", 4).limit(30).orderBy("date", Query.Direction.DESCENDING);
```
