### ISSUE TITLE
setIsSmartLockEnabled should verify Google Play services permissions before calling APIs

### ISSUE THREAD

**Issue by delta9** [firebase/FirebaseUI-Android#1634]
### Step 2: Describe your environment

  * Android device: Pixel XL
  * Android OS version: 9
  * Google Play Services version: 17.1.22
  * Firebase/Play Services SDK version: 17.0.0 / 4.2.0
  * FirebaseUI version: 4.3.2
  
#### Steps to reproduce:

  1. Disable Google Play services `Phone` permission ([Screenshot](https://i.imgur.com/SUIURzP.jpg))
  2. Create a SignInIntent with `setIsSmartLockEnabled(true)`
  3. Watch as `onActivityResult` is never called and the progress bar spins forever.
  
#### Observed Results:

  * `setIsSmartLockEnabled(true)` requires permission `READ_PHONE_STATE` even if an app only uses Email/Password as a sign-in provider.
  
#### Expected Results:

  * I expected the library to verify permissions before calling the Google Play services API. Also, an Email/Password only sign-in shouldn't require `READ_PHONE_STATE`.
  
#### Relevant Code:

  ```
  AuthUI.getInstance()
 .createSignInIntentBuilder()
 .setIsSmartLockEnabled(true)
 .setAvailableProviders(arrayListOf(AuthUI.IdpConfig.EmailBuilder().build()))
 .build()
  ```

#### Short Term Fix:

```
    private fun hasReadPhoneStatePermission(context: Activity): Boolean {
        val googleApiAvailability = GoogleApiAvailability.getInstance()
        val googlePlayServices = googleApiAvailability.isGooglePlayServicesAvailable(context)
        val hasPermission = packageManager.checkPermission(Manifest.permission.READ_PHONE_STATE, "com.google.android.gms") == PackageManager.PERMISSION_GRANTED
        return googlePlayServices == ConnectionResult.SUCCESS && hasPermission
    }

  // .setIsSmartLockEnabled(hasReadPhoneStatePermission(context))

```

Many thanks,
Melvin

**Comment by samtstern** [comment]
@delta9 sorry for my super slow response here!  Have been traveling.

How did you get into a place where Google Play services has partially revoked permissions?  This is not something we should have to handle normally, and I don't think any app or library should be in the business of checking `com.google.android.gms` permissions manually.

**Comment by delta9** [comment]
Hey @samtstern no worries, thanks for the reply!

We've had a user complain about our login not working and after a bit of back and forth came to the conclusion that they've disabled some Google Play runtime permissions - a rare edge-case but I thought I'd let you know and for anyone searching, this was the error code:

`GoogleApiAvailability: Unexpected error code 19`

**Comment by samtstern** [comment]
@delta9 thanks for following up!  I agree that this is a rare edge-case, and I appreciate the heads up anyway.
