### ISSUE TITLE
How do you get the document Id using FirebaseFirestoreAdapter Ui?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1638]
I'm trying to get the ID of the view document, but I can not find a way to do it. Somebody could help me?

**Comment by PatilShreyas** [comment]
Try calling below method of Adapter

```java
String docRef = getItem(position).getId();
```

**Comment by samtstern** [comment]
Thanks @PatilShreyas for answering

**Comment by Okami-x-Senpai** [comment]
It does not work, it tells me that getKey () can not be solved.

What I find strange is that after writing getItem (). I see the objects of my model.

**Comment by PatilShreyas** [comment]
Oh yes... I see It's because its return type is T i.e. data model.

**Comment by Okami-x-Senpai** [comment]
I understand, but what can I do to get the ID of the document?

**Comment by PatilShreyas** [comment]
@samtstern I think there should be a method like `getRef(position)` same as exists in Realtime Database adapter.

**Comment by Okami-x-Senpai** [comment]
@PatilShreyas Will that method be sufficient to obtain the Id of the document?

**Comment by PatilShreyas** [comment]
@Okami-x-Senpai yes. Because the same method exists in Realtime Database adapter which returns`DataSnapshot`. 
Here this method will return `DocumentSnapshot` and then we can call `getId()` method to obtain it's ID.

**Comment by Okami-x-Senpai** [comment]
You tell me to use the code:
```
getItem (position) .getId
```

Because that code throws me an error because the getItem does not recognize me getID or getKey.

**Comment by PatilShreyas** [comment]
@Okami-x-Senpai hmmm... I was wrong there... Because in `FirestorePagingAdapter` this same method exists to get DocumentSnapshot.

**Comment by Okami-x-Senpai** [comment]
I understand, but the problem is that in FirestorePagingAdapter if I can get the document ID easily, but with FirestoreAdapter I can not do it.

**Comment by PatilShreyas** [comment]
@Okami-x-Senpai I think this issue should be reopened.

**Comment by samtstern** [comment]
What about:
```
getSnapshots().getSnapshot(index).getId()
```

**Comment by PatilShreyas** [comment]
@samtstern It's good!
