### ISSUE TITLE
How can I make my adapter using FirestoreRecyclerAdapter go to the end of everything?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1639]
I'm trying to make a conversation room, the problem is that when entering the activity the messages appear to me from the beginning, when I should have an automatic scroll until the end. How can I get an automatic scroll when they enter the activity? until the last message sent (final)?

**Comment by samtstern** [comment]
@Okami-x-Senpai sorry for the slow response here, but this type of question is better suited for StackOverflow or another forum since it's not a bug in the library or a feature request.
