### ISSUE TITLE
Header Firebase Recycler Adapter

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-Android#1642]
Hi All, I've been wracking my brains for a couple of days now. I'm trying to implement a header on the FirebaseUI recycler adapter. 

Can anyone point me in the right direction to get this done.

Thank you .

Joe

**Comment by samtstern** [comment]
@joemerritt this issue tracker is really only meant for bugs / feature requests in the FirebaseUI library.  For a question like yours "How do I ... ?" I would suggest StackOverflow.

As a pointer, you're probably going to need to create your own class that extends `FirebaseRecyclerAdapter` and overrides things in the `0` position to create a header.

**Comment by adityagangasagar** [comment]
package com.example.myfoodorder;

import android.os.Bundle;

import com.example.myfoodorder.Common.Common;
import com.example.myfoodorder.Interface.ItemClickListener;
import com.example.myfoodorder.Model.Category;
import com.example.myfoodorder.ViewHolder.MenuViewHolder;
import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.firebase.ui.database.FirebaseRecyclerOptions;
import com.google.android.material.floatingactionbutton.FloatingActionButton;
import com.google.android.material.snackbar.Snackbar;

import android.view.View;

import androidx.annotation.NonNull;
import androidx.core.view.GravityCompat;
import androidx.appcompat.app.ActionBarDrawerToggle;

import android.view.MenuItem;

import com.google.android.material.navigation.NavigationView;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.squareup.picasso.Picasso;

import androidx.drawerlayout.widget.DrawerLayout;

import androidx.appcompat.app.AppCompatActivity;
import androidx.appcompat.widget.Toolbar;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.view.Menu;
import android.view.ViewGroup;
import android.widget.TextView;
import android.widget.Toast;

public class Home extends AppCompatActivity
        implements NavigationView.OnNavigationItemSelectedListener {

    FirebaseDatabase database;
    DatabaseReference category;
    TextView txtFullName;
    RecyclerView recycler_Menu;
    RecyclerView.LayoutManager layoutManager;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_home);

        Toolbar toolbar = findViewById(R.id.toolbar);
        toolbar.setTitle("Menu");

        //Init FireBase

        database = FirebaseDatabase.getInstance();
        category = database.getReference("category");

        setSupportActionBar(toolbar);
        FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Snackbar.make(view, "Replace with your own action", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
            }
        });
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        NavigationView navigationView = findViewById(R.id.nav_view);
        ActionBarDrawerToggle toggle = new ActionBarDrawerToggle(
                this, drawer, toolbar, R.string.navigation_drawer_open, R.string.navigation_drawer_close);
        drawer.addDrawerListener(toggle);
        toggle.syncState();
        navigationView.setNavigationItemSelectedListener(this);

        //Set Name For User

        View headerview = navigationView.getHeaderView(0);
        txtFullName = (TextView)headerview.findViewById(R.id.txtFullName);
        txtFullName.setText(Common.currentUser.getName());

        //Load Menu

        recycler_Menu = (RecyclerView)findViewById(R.id.recyler_menu);
        recycler_Menu.setHasFixedSize(true);
        layoutManager = new LinearLayoutManager(this);
        recycler_Menu.setLayoutManager(layoutManager);

        loadMenu();

    }


    private void loadMenu() {

        FirebaseRecyclerAdapter<Category,MenuViewHolder> adapter = new FirebaseRecyclerAdapter<Category, MenuViewHolder>
****(Category.class,R.layout.menu_item,MenuViewHolder.class,category)**** {
            @Override
            protected void onBindViewHolder( MenuViewHolder menuViewHolder, int i, @NonNull Category category) {

                menuViewHolder.txtMenuName.setText(category.getName());
                Picasso .with(getBaseContext()).load(category.getImage())
                        .into(menuViewHolder.imageView);

                final Category clickItem = category;
                menuViewHolder.setItemClickListener(new ItemClickListener() {
                    @Override
                    public void onClick(View view, int position, boolean isLongClick) {
                        Toast.makeText(Home.this, "" + clickItem.getName(), Toast.LENGTH_SHORT).show();
                    }
                });
            }

            @NonNull
            @Override
            public MenuViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                return null;
            }


        };

    }

    @Override
    public void onBackPressed() {
        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        if (drawer.isDrawerOpen(GravityCompat.START)) {
            drawer.closeDrawer(GravityCompat.START);
        } else {
            super.onBackPressed();
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.home, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
         return super.onOptionsItemSelected(item);
    }

    @SuppressWarnings("StatementWithEmptyBody")
    @Override
    public boolean onNavigationItemSelected(MenuItem item) {
        // Handle navigation view item clicks here.
        int id = item.getItemId();

        if (id == R.id.nav_menu) {
            // Handle the camera action
        } else if (id == R.id.nav_cart) {

        } else if (id == R.id.nav_orders) {

        } else if (id == R.id.nav_logout) {

        }

        DrawerLayout drawer = findViewById(R.id.drawer_layout);
        drawer.closeDrawer(GravityCompat.START);
        return true;
    }
}

**Comment by PatilShreyas** [comment]
@adityagangasagar refer [this](https://stackoverflow.com/questions/50420505/how-to-create-sticky-headers-in-firebaserecycleradapter/50420807).
