### ISSUE TITLE
App Crashes during  Phone Authentication 

### ISSUE THREAD

**Issue by SaumyaSingh1** [firebase/FirebaseUI-Android#1645]
* For issues or feature requests related to the code https://github.com/SaumyaSingh1/ProjectMudra   file a GitHub issue.

  * Android device: _Redmi Note4____
  * Android OS version: ___7 NRD__
  * Google Play Services version:  4.0.0_____
  * Firebase/Play Services SDK version: __17.0.0___
  * FirebaseUI version: __4.1.0__
  
###  Describe the problem:
After the splash screen , i coded for the firebase phone authentication in main activity . The app is crashed immediately after the splash screen .

Reach the code :
https://github.com/SaumyaSingh1/ProjectMudra

**Comment by samtstern** [comment]
@SaumyaSingh1 we can't really take the time to read your whole project and find the bug, please post the stack trace of the crash here and any other information that we will need.

**Comment by SaumyaSingh1** [comment]
@samtstern  Issue Resolved on updating google services version to 4.0.1
Thanks for your quick response :)

**Comment by samtstern** [comment]
@SaumyaSingh1 glaf you solved it!
