### ISSUE TITLE
Activity leak.

### ISSUE THREAD

**Issue by gubo** [firebase/FirebaseUI-Android#165]
AuthMethodPickerActivity, in populateIdpList(...) creates an instance of GoogleProvider, with 'this' for
the Activty parameter:
`mIdpProviders.add(new GoogleProvider(this, providerParcel));`

Then GoogleProvider constructor creates a GoogleApiCient on that context:
`mGoogleApiClient = new GoogleApiClient.Builder(activity)`

But, it is not auto-managed, and disconnect() is never called.
Therefore, when AuthMethodPickerActivity is destroyed, GC can not reclaim because
GoogleApiClient has a reference.

Suggest:

**1.** change to:
`mGoogleApiClient = new GoogleApiClient.Builder( activity.getApplicationContext() )`

**2.** add method to GoogleProvider:
```
public void disconnect() {
    if ( mGoogleApiClient != null ) {
        mGoogleApiClient.disconnect();
        mGoogleApiClient = null;
    }
}
```

**3.** override AuthMethodPickerActivity.onDestroy:
```
@Override
protected void onDestroy() {
    super.onDestroy();
    if ( mIdpProviders != null ) {
        for ( final IDPProvider provider: mIdpProviders ) {
            if ( GoogleProvider.class.isInstance( provider ) ) {
                ( ( GoogleProvider)provider).disconnect();
            }
        }
    }
}
```

Ref:
https://developers.google.com/android/reference/com/google/android/gms/common/api/GoogleApiClient
https://developers.google.com/android/guides/api-client#start_an_automatically_managed_connection

-Jeff

**Comment by iainmcgin** [comment]
Thanks for the feedback, Jeff! We're working to clean up all of our GoogleApiClient handling behind a simpler interface so mistakes like this are avoided.
