### ISSUE TITLE
FirestorePagingAdapter does not log errors by default

### ISSUE THREAD

**Issue by sanisloandras** [firebase/FirebaseUI-Android#1652]
Hello!

Recently I discovered that FirestorePagingAdapter does not log errors by default, while FirestoreRecylcerAdapter does.
I think it should save developers some time. I lost some time while debugging why my FirestorePagingAdapter didn't not display any data. I simply forgot to create an index, but I didn't get the warning log about that, because FirestorePagingAdapter's onError method body is empty.

FirestoreRecyclerAdapter:
`@Override
    public void onError(@NonNull FirebaseFirestoreException e) {
        Log.w(TAG, "onError", e);
    }`

FirestorePagingAdapter:
`protected void onError(@NonNull Exception e) {
        // For overriding
    }`

**Comment by samtstern** [comment]
@sanisloandras I think this is a great idea, would you like to submit a PR with this change?

**Comment by samtstern** [comment]
This has been released in FirebaseUI `6.1.0`
