### ISSUE TITLE
In some version will it be possible to obtain the real-time data of new documents when using FirestorePagingAdapter?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1653]
I think it would be good if they implemented the function that when using `FirestorePagingAdapter` the Adapter can **get new documents added to the Firestore database**. I have seen that _only new documents can be displayed if the Adapter is recharged_. It would be a good idea, as I said before, for the **adapter to obtain and draw the data of the new documents in the design without having to reload the entire adapter to see the new documents**.

Something similar when using `FirestoreRecyclerAdapter`.

**Comment by samtstern** [comment]
@Okami-x-Senpai thanks for the question.  We're not currently working on this as it's very hard to do efficiently with the current versions of the Firestore SDK.  We may be able to change this in the future, but for now you would have to build your own.
