### ISSUE TITLE
I have a problem using .limit(long) in a Query using FirestorePagingAdapter

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1655]
I want to **show only 1 document** from **my collection in Firestore**, but my problem is that **FirestorePagingAdapter shows me all the documents**, in a few words, it is _ignoring my condition of .limit(1)_.

This is the code that I try to use:
`Query mChangelogQuery = mAdminDB.document("announcements").collection("Changelog").orderBy("date").limit(1);`

Could you help me?

**Comment by samtstern** [comment]
@Okami-x-Senpai the paging adapter does ignore limits, that's part of the design because it sets its own limits to do paging.  You should use the non-paging version of the adapter if you just want to show one document.
