### ISSUE TITLE
DatabasePagingOptions setIndexedQuery

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#1656]
Hello, Is it possible to use `DatabasePagingOptions` with `IndexedQuery`?
`DatabasePagingOptions.Builder` has only regular `.setQuery()`

I'm migrating from `FirebaseRecyclerOptions.Builder` which contains `setIndexedQuery` api.
Have someone already faced with this issue? Is there any workaround I can use?

**Comment by samtstern** [comment]
@stasbar no it is not possible to use an indexed query with pagination right now.  The total complexity for that kind of adapter would be really high, so we did not implement that.  If you need this feature your best bet is to fork the library and attempt to subclass the adapter yourself to add indexed query support.
