### ISSUE TITLE
How to hide an item using FirestorePagingAdapter?

### ISSUE THREAD

**Issue by Okami-x-Senpai** [firebase/FirebaseUI-Android#1657]
I want to **hide an item when a button is pressed**  but _I do not know how to do it using FirestorePagingAdapter_.

**Could someone give me an example?**

**Comment by samtstern** [comment]
@Okami-x-Senpai sorry for the late response here but hiding an item is something you would do outside of this library in your `Adapter` subclass.  If you need help learning about how to use a RecyclerView adapter please ask on StackOverflow.
