### ISSUE TITLE
How to add two filters to firebase paging recyclerviee

### ISSUE THREAD

**Issue by adfaous** [firebase/FirebaseUI-Android#1664]
I have two spinner Containers which one sort a post by date/popularity and other by tags. I tried the below code, but it keeps loading for life. Please help me with how to use 2 filter method.

  ```
  Query mQuery = dataB.collection("forum").orderBy("postDate", Query.Direction. DESCENDING).whereArrayContains("postTag", by_type);
  ```

**Comment by samtstern** [comment]
@adfaous do you have the compound index that is needed for that query?  Check your error logs to see if there is an index link.

**Comment by adfaous** [comment]
I got no error, it just keep loading on my phone. 
What is compound index? Please refer me to a docs that explain that sir.  
And please don't close the issue to soon.

**Comment by samtstern** [comment]
@adfaous here's some information about indexes:
https://firebase.google.com/docs/firestore/query-data/indexing

If you add this to your adapter you should get an error about the index in your logcat:
```
   @Override
    protected void onError(@NonNull Exception e) {
      Log.w("PagingAdapter", "onError", e);
    }
```

**Comment by adfaous** [comment]
Thanks I'm able to resolve it with compound index. 
I sorted both spinner fields manually on firebase console, one by ascending and other by arrays. 
Thanks
