### ISSUE TITLE
When can I show the loading spinner in firestoreRecyclerAdapter?

### ISSUE THREAD

**Issue by loveprotocol** [firebase/FirebaseUI-Android#1666]
Hello

I am using firestoreRecyclerAdapter.
When new data is added or updated, I want to use the loading spinner in case it takes a long time.
I saw a comment to use onDataChanged to hide the loading spinner. 
When does the data change begin? I want to know when I can show the loading spinner.

please answer about my question. Thank you.

**Comment by PatilShreyas** [comment]
If you have set life-cycle owner as activity then You can start showing animation after setting an adapter otherwise you can start if after calling `startListening()`

**Comment by samtstern** [comment]
Thanks @PatilShreyas for providing the answer.  That's correct, you should show the spinner as soon as you start listening for data.

**Comment by loveprotocol** [comment]
Thanks for the quick response. @PatilShreyas @samtstern 
Okay. I know when I first start LIstening, but what can I do when it is updated in real time? Is it better not to use the spinner when it is updated?

**Comment by samtstern** [comment]
@loveprotocol if you are using the normal (non-paging adapter) there is no reason to show the spinner or any other loading indicator for real-time updates.  By the time you are notified there's no more loading to be done.

The paging adapter will fire a load start and load end event for each "page" and you may want to show the spinner there.
