### ISSUE TITLE
FirebaseUI GridView Adapter 

### ISSUE THREAD

**Issue by sjabiulla** [firebase/FirebaseUI-Android#1669]
Currently there is no Adapter provided by FirebaseUI for Android GridView. It would be great If you could provide an inbuilt FireBase adapter for GridView too

**Comment by PatilShreyas** [comment]
There is no need to use special adapter for Grid. You can achieve it by setting layoutManager as a GridLayoutManager to the RecyclerView.

**Comment by PatilShreyas** [comment]
Refer [this](https://stackoverflow.com/questions/40587168/simple-android-grid-example-using-recyclerview-with-gridlayoutmanager-like-the)

**Comment by sjabiulla** [comment]
thanks for the suggestion @PatilShreyas . I will try using RecyclerView instead of GridView

**Comment by samtstern** [comment]
Thanks for the answer @PatilShreyas !
