### ISSUE TITLE
6.0.0 missing FirestoreRecyclerOptions?

### ISSUE THREAD

**Issue by achuinard** [firebase/FirebaseUI-Android#1676]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * FirebaseUI version: 6.0.0
  
### Step 3: Describe the problem:

App will not compile, says FirestoreRecyclerOptions doesn't exist as a class.

#### Steps to reproduce:

Upgrade to 6.0.0 in your build.gradle.

#### Observed Results:

It doesn't compile.
  
#### Expected Results:

I wanted the app to compile.

**Comment by willgurht** [comment]
I see the same, some files are missing from the downloaded .aar
<img width="510" alt="missingfiles" src="https://user-images.githubusercontent.com/2734652/64879892-42a32e00-d657-11e9-9c8d-36528ed8abe0.png">

**Comment by samtstern** [comment]
@achuinard @willgurht thank you for reporting!  This is ... not good.  I will have to take a look.

**Comment by samtstern** [comment]
OK I used [dex-member-list](https://github.com/JakeWharton/dex-member-list) to analyze the members of firestore 5.1.0 vs 6.0.0 and this is the diff:
http://www.mergely.com/NlVBQrgZ/

There are a lot of missing classes (`FirestoreArray`, `FirestoreRecyclerOptions`) but also some very suspicious missing methods like `FirestoreRecyclerAdapter.updateOptions` ... I have no idea what's going on here but it's definitely a real issue!

**Comment by samtstern** [comment]
Working on this in #1678, once it's merged we will have a `SNAPSHOT` build for you to test.

**Comment by samtstern** [comment]
Ok this has been fixed in `6.0.1`.  Let me know if you see any issues!

**Comment by achuinard** [comment]
Thanks @samtstern. Just waiting on 6.0.2 first though...

**Comment by samtstern** [comment]
That's coming today, thanks for your patience!
