### ISSUE TITLE
Method to update Options in Paging Adapters

### ISSUE THREAD

**Issue by PatilShreyas** [firebase/FirebaseUI-Android#1677]
@samtstern Recently we developed and released method `updateOptions()` to update options in Adapters. But this isn't available in Paging adapters yet. If we again work on this again, it'll be helpful to update options at runtime without changing adapters. Should we work on this again?

If we work on this, `final` modifier from  `LiveData<>` fields should be removed. Because, while changing options `LiveData<>` fields should again re-initialised.

Is it Okay?

**Comment by samtstern** [comment]
@PatilShreyas I think this is a good idea but a few things:

1) We'll have to see if the underlying paging library supports this
2) I am going to be super busy until the Firebase Summit on September 26th so let's hold off on any feature development until after that.

Thanks for always contributing your thoughts and code to this project!

**Comment by PatilShreyas** [comment]
Yeah sure! We will discuss on it later. Thank you!

**Comment by mateusdias** [comment]
Dears, sorry ask this, but how can i change the query object and "restart" all process to bind recyclerview etc? 
Let me explain: If you have an activity and filter dialog. So... when user interact on filter dialog i factory one custom query to perform on firestore (after activity load default query and setup options, adapter, etc). 
So, how can I change the query, update options and notify adapter to "refresh the new results of the new query?"

**Comment by PatilShreyas** [comment]
@mateusdias Which adapter you're using? Are you using `FirestoreRecyclerAdapter` or `FirestorePagingAdapter`?
Please let me know about this.

**Comment by mateusdias** [comment]
@PatilShreyas Thanks for reply! 
I am using FirestorePagingAdapter. By the way, I implemented exactly as in your example tutorial in the medium, here: https://medium.com/firebase-developers/firestore-pagination-in-android-using-firebaseui-library-1d7fe1a75704

As I said, in this activity I have a filter that processes user search preferences and dynamically builds new queries. So every time the user applies the filter it's like I literally need to reload everything from scratch, starting a new pagination with a new query. What I found most interesting is that even trying "RE INSTANTIATE everything... Adapter, RecyclerView etc" doesn't work. The result is blank. To make sure the problem wasn't with queries, I simply forced a query object to see what happened and didn't bring up the results.

II tried to control the state of the adapter manually too, but it didn't work.

Its important clarify, i'm using RecyclerView from androidx library: import androidx.recyclerview.widget.RecyclerView;

**Comment by PatilShreyas** [comment]
@mateusdias Hmmm. Paging adapters currently not having the ability to replace queries at runtime. That's why I issued it.

I understood what problem you're facing. Have you set `LifecycleOwner` to options object?
If not, then have you called `startListening()` on adapter instance? Because adapter only listens to item updates after calling `startListening()`.

**Comment by PatilShreyas** [comment]
@samtstern should we start work on this?

**Comment by samtstern** [comment]
@PatilShreyas sure!  I'll be back in the office Monday for code review and stuff.  Let's start with just one of the adapters at first so we can get all the pieces fleshed out.

**Comment by PatilShreyas** [comment]
Yeah Okay!

**Comment by PatilShreyas** [comment]
@samtstern Code is ready. When and where (on which branch) to create PR?

**Comment by samtstern** [comment]
@PatilShreyas open a PR against `version-6.0.3-dev`

**Comment by PatilShreyas** [comment]
@samtstern We'll have to do same for RTDB Paging Adapter.

**Comment by samtstern** [comment]
This has been released in FirebaseUI `6.1.0`

**Comment by hkchakladar** [comment]
@samtstern, @PatilShreyas Since this has been implemented, but no example code is available in the documentation on how to update the query after user select some filter.

Can you please add some exmple code on how to update the query and refresh/reload the data, on some user action/click after the initial query is completed?

**Comment by PatilShreyas** [comment]
@hkchakladar Thanks for that. I'll start working for it soon.

**Comment by ebekerman** [comment]
Any updates on the example code or guideline for the refresh/reload query?

**Comment by hkchakladar** [comment]
@ebekerman I have figured it out. Check it out here https://github.com/firebase/FirebaseUI-Android/issues/1726#issuecomment-573033035.

**Comment by ramneekkashyap9** [comment]
@PatilShreyas Hey, Any Example on this issue yet? to paginate the query using FirestorePagingAdapter where the user applies filters to get the desired list in recyclerview?

**Comment by PatilShreyas** [comment]
Refer this article, this will help you.
Link: https://link.medium.com/lzYvTaZgj6

**Comment by ramneekkashyap9** [comment]
@PatilShreyas i went through the example but could not implement it due to lots of errors, please let me know where I can share you the code if you can help me

**Comment by PatilShreyas** [comment]
See this example implementation. This might help you!
https://github.com/PatilShreyas/FirebaseRecyclerUpdateQuery-Demo/blob/master/app/src/main/java/dev/shreyaspatil/firebase/recyclerqueryupdate/firestore/FirestorePagingActivity.kt
