### ISSUE TITLE
Migrate architecture components to AndroidX

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#1681]
This entire block needs to be moved over to `androidx` versions. (I think we should just have it be part of the `Androidx` block and get rid of `Arch` to unify everything.)

https://github.com/firebase/FirebaseUI-Android/blob/d953be7c218e7b9fad52b8ae190de9029dd89517/buildSrc/src/main/kotlin/Config.kt#L40-L51

**Comment by samtstern** [comment]
D'oh.  I honestly forgot that there was Arch before there was AndroidX.

**Comment by samtstern** [comment]
Fixed and released in version 6.0.2
