### ISSUE TITLE
Firebase Auth UI Crash

### ISSUE THREAD

**Issue by paulsUsername** [firebase/FirebaseUI-Android#1684]
### Step 1: Android device and Version

Android Version 7.1.1
Nexus 6

Android Version 7.1.1
Nexus 5x

Auth UI Version:
`'com.firebaseui:firebase-ui-auth:4.3.2'`
  
### Step 3: Describe the problem:

I am getting reports from multiple users on Crashalytics experiencing a crash android.content.res.Resources$NotFoundException that is being pinned down to:

com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onCreate (AuthMethodPickerActivity.java:117)
  

  
#### Expected Results:

User to login to firebase
  
#### Relevant Code:

```
Caused by android.content.res.Resources$NotFoundException
Resource ID #0x7f08017a
android.content.res.ResourcesImpl.getValue (ResourcesImpl.java:190)
android.content.res.Resources.getValue (Resources.java:1290)
androidx.appcompat.widget.ResourceManagerInternal.createDrawableIfNeeded (ResourceManagerInternal.java:176)
androidx.appcompat.widget.ResourceManagerInternal.getDrawable (ResourceManagerInternal.java:141)
androidx.appcompat.widget.ResourceManagerInternal.getDrawable (ResourceManagerInternal.java:132)
androidx.appcompat.content.res.AppCompatResources.getDrawable (AppCompatResources.java:104)
androidx.appcompat.widget.AppCompatImageHelper.setImageResource (AppCompatImageHelper.java:86)
androidx.appcompat.widget.AppCompatImageView.setImageResource (AppCompatImageView.java:94)
**com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onCreate** (AuthMethodPickerActivity.java:117)
android.app.Activity.performCreate (Activity.java:6679)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1118)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2618)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2726)
android.app.ActivityThread.-wrap12 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1477)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:154)
android.app.ActivityThread.main (ActivityThread.java:6119)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:886)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:776)
de.robv.android.xposed.XposedBridge.main (XposedBridge.java:107)
```

**Comment by samtstern** [comment]
@paulsUsername a few questions:

1. Have you been able to reproduce this yourself at all?  Also when you say "multiple users" how many is that?
2. Can you show the code you use to launch FirebaseUI?
3. I see `de.robv.android.xposed.XposedBridge.main (XposedBridge.java:107)` in the stack trace ... from what I remember Xposed is used by people with rooted/modded phones.  Is it possible this is caused by some user modification?

**Comment by paulsUsername** [comment]
Sorry I never for back to you. This issue seems to have resolved itself with the latest update.
