### ISSUE TITLE
Custom layout for phone authentication 

### ISSUE THREAD

**Issue by mostasim** [firebase/FirebaseUI-Android#1687]
How can i set my own custom layout for phone authentication work flow?

**Comment by 100rabhkr** [comment]
I have a very stupid work around for this:-

Create a custom layout for login with phone. One where you take the phone number of the user. 

Have a button which upon clicking does this:

`startActivityForResult(
        AuthUI.getInstance()
                .createSignInIntentBuilder()
                .setAvailableProviders(Arrays.asList(
                      new IdpConfig.PhoneBuilder()
        .setDefaultNumber("Entered phone number with ISD code")
        .build()  ))
                .build(),
        RC_SIGN_IN);`

Or maybe do this in a new activity passing the number between them. Then the user can proceed with verifying the number. NOTE: This might or might not work for your work case.

**Comment by samtstern** [comment]
@mostasim we only support custom layout for the very first screen.  After that you can provide themes but you can't change the layout.  FirebaseUI is meant to be a drop-in UI so customizing the whole thing somewhat defeats the point.

@100rabhkr thanks for sharing!  That will definitely work for some cases.
