### ISSUE TITLE
Misleading Logcat error when using custom layout for FirebaseUI Auth

### ISSUE THREAD

**Issue by AhmedAshour** [firebase/FirebaseUI-Android#1688]
* FirebaseUI version: 6.0.2
  
Problem Description:
When creating an `AuthMethodPickerLayout` object to make a custom layout for the login screen, 
you have to set button ids of the auth providers that you chose.
When you choose `EmailBuilder` as a provider but without providing a button id for it while creating the `AuthMethodPickerLayout` object the app crashes and shows this error in log cat:
`Caused by: java.lang.IllegalStateException: No button found for auth provider: password`

**So the problem here is the "password" word, it should say "email" or "EmailBuilder."**

I thought that this could be misleading to some people so I created this issue.

#### Steps to reproduce:

  1. Create an `AuthMethodPickerLayout `object to make a custom layout.
  2. Choose `EmailBuilder` as a provider but without providing a button id for it while creating the object.
  
#### Observed Results:

`Caused by: java.lang.IllegalStateException: No button found for auth provider: password`
  
#### Expected Results:

`Caused by: java.lang.IllegalStateException: No button found for auth provider: email`

**Comment by samtstern** [comment]
@AhmedAshour thanks for filing this!  That's a reasonable request, I'll look into it for the next version.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `6.2.1`
