### ISSUE TITLE
Project fails to build for Java 1.8 - doclint issue

### ISSUE THREAD

**Issue by Danm72** [firebase/FirebaseUI-Android#169]
It appears that building/publishing fails on 1.8 due to doc linting which was added in 1.8

We might be able to ignore it with:

`if (JavaVersion.current().isJava8Compatible()) {
    allprojects {
      tasks.withType(Javadoc) {
        options.addStringOption('Xdoclint:none', '-quiet')
      }
    }
  }
`

**Comment by samtstern** [comment]
@Danm72 thanks for the report and the potential workaround.  Will keep this open until it's resolved.

**Comment by Danm72** [comment]
No problem, could you reproduce it? Might be some weirdness around my environment!

**Comment by jirungaray** [comment]
I was able to reproduce. Let me do a quick test and send over a PR.

**Comment by jirungaray** [comment]
@Danm72 
Pull request #175 already up and awaiting approval.

**Comment by samtstern** [comment]
Fixed by #175
