### ISSUE TITLE
How to allow access to multiple users with different email address and signup or register with their email address using firebaseUI in Android Application

### ISSUE THREAD

**Issue by srk2k13** [firebase/FirebaseUI-Android#1693]
How to allow access to multiple users with different email address and signup or register with their email address using firebaseUI in Android Application.

I am getting the Error " The Email address is already used by another account"  and hence is not registering and not   entering into my App  etc.

Any Live Chat Suppot available     like  Social communities Whatsapp or facebook etc.

Thanks

Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@srk2k13 please use the issue template when filing issues, I can't understand the feature you're asking for based on the information provided.

**Comment by srk2k13** [comment]
Hi,
In Issue Template
It is asking for correct formatCode sample, links.
I am Unable to ask a question  ,I tried yesterday.

My query is "How to allow access to multiple users with different email address to register and use my firrbaseUI integrated Android App.
Please help me I am facing trouble in creating the database and storing the database and retrieving it back.

Thanks
Kumar


Sent from Yahoo Mail on Android 
 
  On Thu, 10 Oct 2019 at 9:50 PM, Sam Stern<notifications@github.com> wrote:   
@srk2k13 please use the issue template when filing issues, I can't understand the feature you're asking for based on the information provided.

**Comment by samtstern** [comment]
@srk2k13 for general questions we normally point people to StackOverflow.  FirebaseUI does not allow for multiple users to be signed in at one time, which I think is what you're asking for.  You have to sign out and sign back in with a new user each time.

**Comment by srk2k13** [comment]
How to allow access to multiple users with different email address and signup or register with their email address using firebaseUI in Android Application

My Android device: __Latest Smart Phone like Redmi Note 4, Real Me, OnePlus6 or New Android version

Android OS version: 8 to 10 any_ Google Play Services version: NA_ Firebase/Play Services SDK version:Update - September 26, 2019 Authentication version 19.1.0

FirebaseUI version: ___Update - September 26, 2019 Authentication version 19.1.0_

link for the version details https://firebase.google.com/support/release-notes/android#latest_sdk_versions

Steps to reproduce: 1)How to allow access to multiple users with different email address and signup or register with their email address using firebaseUI in Android Application

2)How to create the database for for users profile information and storing / saving in the database and retrieve them back when required.

Observed Results: When a user want to Sign in with the existing details with which he has registered, It is saying " Error " The Email Address is Already Used in another account"" and it is nit allowing to access the App.

What happened?

When a user want to Sign in with the existing login details with which he has registered, It is saying " Error " The Email Address is Already Used in another account"" and it is nit allowing to access the App.

Expected Results: It should allow access and further may ask to fill other data of the user profile inormation.

What did you expect to happen?

It should allow access and further may ask to fill other data of the user profile inormation.

Relevant Code:

I have the following procedure as mentioned in the below link

https://www.youtube.com/watchv=ylqOGRZNEKs&list=PLk7v1Z2rk4hhUCFBSnVTECda_MdTp3GnQ

https://www.youtube.com/watch?v=qVaBY92sOSI

**Comment by srk2k13** [comment]
Please Dont close this issue . I have not recieved any correct/ right solution for my query. I have reposted my query in the format you have asked.
