### ISSUE TITLE
In-app messaging popup(Android).java

### ISSUE THREAD

**Issue by chitra-bahadur** [firebase/FirebaseUI-Android#1699]
In this popup is always triggering in splash screen. I want it to trigger in main activity. How to do it?
@samtstern @Dnyaneshwar1926  have you guys found any solution? i tried log event also but event is not showing in firebase events.

**Comment by Dnyaneshwar1926** [comment]
@chitra-bahadur 
Try to trigger event for 10 to 15 times. Then check.

**Comment by chitra-bahadur** [comment]
@Dnyaneshwar1926  i did but its only working in first screen. i have 3 fragments in an activity. i put the code in activity.

**Comment by Dnyaneshwar1926** [comment]
Check this link

https://github.com/firebase/firebase-android-sdk/issues/378

**Comment by chitra-bahadur** [comment]
@Dnyaneshwar1926 which solution worked for you can you share the steps if possible?  i went through that link already and followed all the things.

**Comment by Dnyaneshwar1926** [comment]
Here is the solution:-
https://github.com/firebase/firebase-android-sdk/issues/378#issuecomment-511103616

**Comment by chitra-bahadur** [comment]
i have tried the log event . will try again and thanks for the help.

**Comment by samtstern** [comment]
Sorry I never responded here but this discussion does not belong on this repo.  If you have a bug in the Firebase Android SDK for In-App Messaging file it on the `firebase-android-sdk` repo.  For general questions and discussion use StackOverflow.
