### ISSUE TITLE
Large gap between phone number input field and verify button

### ISSUE THREAD

**Issue by hkchakladar** [firebase/FirebaseUI-Android#1704]
* Android device: Samsung J7 Prime
  * Android OS version: 8.1.0
  * Google Play Services version: 19.5.30
  * FirebaseUI version: 6.0.2
  
### Step 3: Describe the problem:

There is very large gap between the phone input field and the button. See here https://imgur.com/I3rAL3Y

**Comment by samtstern** [comment]
@hkchakladar thanks for this!  I can confirm it's not device specific:

![image](https://user-images.githubusercontent.com/8466666/68249629-0a272d00-ffd4-11e9-9994-e1437217679a.png)

**Comment by samtstern** [comment]
This change happened here, seems like it was an accident:
auth/src/main/res/layout/fui_phone_layout.xml

**Comment by samtstern** [comment]
This has been released in FirebaseUI `6.1.0`
