### ISSUE TITLE
Stop fetch when scroll upward.

### ISSUE THREAD

**Issue by BismeetSingh** [firebase/FirebaseUI-Android#1706]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device:Realme 3 pro
  * Android OS version:Pie
  * Google Play Services version: 4.3.2
  * Firebase/Play Services SDK version(Firestore):21.2.1
  * FirebaseUI version: 5.1.0
  
#### Steps to reproduce:

  1. Load the paginated data
  2. User likes a post.View updates to blue color
  3. Scroll upwards. Data is refreshed and view is reset.
  
#### Observed Results:

  * User feedback of liking the post is gone,
  
#### Expected Results:

  * View should not be refreshed when scroll upwards or for data that was already loaded.
  
#### Relevant Code:

```java
private void fetchPagingData(){
    Query postsQuery = FirebaseFirestore.getInstance().collectionGroup(Constants.POSTS)
            .orderBy(Constants.DATE, Query.Direction.DESCENDING);
    PagedList.Config config = new PagedList.Config.Builder()
            .setEnablePlaceholders(true)
            .setPrefetchDistance(5)
            .setPageSize(10)
            .build();
    String currentUserId = FirebaseAuth.getInstance().getCurrentUser().getUid();
    FirestorePagingOptions<PostsWrapper.Posts> options = new FirestorePagingOptions.Builder<PostsWrapper.Posts>()
            .setLifecycleOwner(this)
            .setQuery(postsQuery, config
                    , new SnapshotParser<PostsWrapper.Posts>() {
                        @NonNull
                        @Override
                        public PostsWrapper.Posts parseSnapshot(@NonNull DocumentSnapshot snapshot) {
                            PostsWrapper.Posts posts=snapshot.toObject(PostsWrapper.Posts.class);
                            posts.setDocumentId(snapshot.getId());
                            if (posts.getUserIds()!=null && posts.getUserIds().contains(currentUserId)){
                                posts.setPostLikedByCurrentUser(true);
                            }
                            return posts;
                        }
                    }
            ).build();
    postsPagingAdapter=new PostsPagingAdapter(options,this,this,this);
    fragmentHomeBinding.userFeeds.setAdapter(postsPagingAdapter);
}
```

**Comment by samtstern** [comment]
@BismeetSingh could you show:

  * Some images or a video of this behavior?
  * Could you show the code of your `PostsPagingAdapter`?

**Comment by BismeetSingh** [comment]
`



public class PostsPagingAdapter extends 
FirestorePagingAdapter<PostsWrapper.Posts,PostsPagingAdapter.CustomHolder> {
   
    private OnPostClickListener onPostClickListener;
    private OnSharePostListener onSharePostListener;
    private OnDataLoaded onDataLoaded;

    public PostsPagingAdapter(@NonNull FirestorePagingOptions<PostsWrapper.Posts> options,OnDataLoaded onDataLoaded, OnPostClickListener onPostClickListener, OnSharePostListener onSharePostListener) {
        super(options);
        this.onSharePostListener = onSharePostListener;
        this.onDataLoaded = onDataLoaded;
        this.onPostClickListener = onPostClickListener;
    }

    @Override
    protected void onBindViewHolder(@NonNull CustomHolder customHolder, int i, @NonNull PostsWrapper.Posts posts) {
        customHolder.bind(posts);

    }

    @Override
    public long getItemId(int position) {
        return position;
    }

    @NonNull
    @Override
    public CustomHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType)
    {
        ItemPosttimelineBinding itemNotificationBinding = ItemPosttimelineBinding.inflate(LayoutInflater.from(parent.getContext()),
                parent, false);

        return new PostsPagingAdapter.CustomHolder(itemNotificationBinding);
    }

    public class CustomHolder extends RecyclerView.ViewHolder {
        private ItemPosttimelineBinding itemPosttimelineBinding;
        public CustomHolder(@NonNull ItemPosttimelineBinding itemView) {
            super(itemView.getRoot());
            this.itemPosttimelineBinding=itemView;
        }

        public void bind(PostsWrapper.Posts posts) {
            itemPosttimelineBinding.setPosts(posts);
            posts.setDate(TimeAgoUtil.covertTimeToText(posts.getDate()));
            itemPosttimelineBinding.usernameProfile.setText(posts.getUsername());
            GlideApp.with(itemPosttimelineBinding.getRoot().getContext())
                    .load(posts.getImageThumbnail()).into(itemPosttimelineBinding.profilePhoto);
            if (posts.isPostLikedByCurrentUser()) {
                itemPosttimelineBinding.likeBtn.setColorFilter(ContextCompat.getColor(itemPosttimelineBinding.getRoot().getContext(), R.color.blue));
            } else {
                itemPosttimelineBinding.likeBtn.setColorFilter(ContextCompat.getColor(itemPosttimelineBinding.getRoot().getContext(), R.color.grey_40));
            }
            if (posts.getLikesCount() > 0) {
                itemPosttimelineBinding.likesCount.setText(String.valueOf(posts.getLikesCount()));
            }
            itemPosttimelineBinding.downloadBtn.setOnClickListener(v -> {
                Timber.d("Downloading");
                onDataLoaded.onDownload(posts);

            });
            itemPosttimelineBinding.shareLayout.setOnClickListener(v -> onSharePostListener.onPostShareClickListener(posts));

            itemPosttimelineBinding.titlePost.setText(posts.getTitle());

            itemPosttimelineBinding.likeBtn.setOnClickListener(v -> {
                if (!posts.isPostLikedByCurrentUser()) {
                    itemPosttimelineBinding.likeBtn.setColorFilter(ContextCompat.getColor(itemPosttimelineBinding.getRoot().getContext(), R.color.blue));
                    posts.setPostLikedByCurrentUser(true);
                    onDataLoaded.OnPostStatusChanged(posts.getUid(), posts.getDocumentId(), true);


                } else {
                    itemPosttimelineBinding.likeBtn.setColorFilter(ContextCompat.getColor(itemPosttimelineBinding.getRoot().getContext(), R.color.grey_40));
                    posts.setPostLikedByCurrentUser(false);
                    onDataLoaded.OnPostStatusChanged(posts.getUid(), posts.getDocumentId(), false);
                }
            });

            itemPosttimelineBinding.postContent.setOnClickListener(v -> {
                onPostClickListener.onPostItemContentClicked(posts.getTitle(),posts.getUsername(), posts.getImageThumbnail(), posts.getDate(), posts.getPostContent());
            });
            itemPosttimelineBinding.titlePost.setOnClickListener(v -> {
                onPostClickListener.onPostItemContentClicked(posts.getTitle(),posts.getUsername(), posts.getImageThumbnail(), posts.getDate(), posts.getPostContent());
            });
            itemPosttimelineBinding.userNameProfileClickLayout.setOnClickListener(v -> onPostClickListener.onPostClicked(posts.getUid()
                    , posts.getUsername(), posts.getImageThumbnail()));
        }



        }
    }
`

**Comment by samtstern** [comment]
@BismeetSingh can you show the code for `posts.setPostLikedByCurrentUser(...)`?  Does that actually write to the database somewhere? 

It's really not clear that there is any bug in FirebaseUI here, it looks more likely there is a bug in how you are storing the like values and how it interacts with a Recyclerview

**Comment by BismeetSingh** [comment]
`@Override
    public void OnPostStatusChanged(String uid, String postId, boolean isPostliked) {

        if (isPostliked) {
            DocumentReference postReference = FirebaseFirestore.getInstance().collection(Constants.USER).document(uid).collection(Constants.POSTS).document(postId);
            FirebaseFirestore.getInstance().runTransaction(transaction -> {
                transaction.update(postReference, USERIDS, FieldValue.arrayUnion(FirebaseAuth.getInstance().getCurrentUser().getUid()));
                transaction.update(postReference, LIKECOUNT, FieldValue.increment(1));
                return null;
            }).addOnFailureListener(Timber::d);


        } else {
            DocumentReference docRef = FirebaseFirestore.getInstance().collection(Constants.USER).document(uid).collection(Constants.POSTS).document(postId);
            FirebaseFirestore.getInstance().runTransaction(transaction -> {
                DocumentSnapshot posts = transaction.get(docRef);
                long count = posts.getLong(LIKECOUNT);
                if (count > 0) {
                    transaction.update(docRef, USERIDS, FieldValue.arrayRemove(FirebaseAuth.getInstance().getCurrentUser().getUid()));
                    transaction.update(docRef, LIKECOUNT, count - 1);
                }

                return null;
            }).addOnFailureListener(Timber::d);
        }


    }`

**Comment by samtstern** [comment]
@BismeetSingh since you're not waiting for your transactions to succeed this is likely a race condition of some kind between the transactions and your scrolling.

I don't see any evidence here of a bug in FirebaseUI, it really looks like you're just having some trouble with your app logic.  I would suggest StackOverflow for further debugging.

If you do find some indication that FirebaseUI is actually not behaving correctly, please let me know and I will re-open this issue.
