### ISSUE TITLE
Possible erratum at FirebaseUI-Android/database/README.md

### ISSUE THREAD

**Issue by Danoso89** [firebase/FirebaseUI-Android#172]
Under "Using FirebaseUI to Populate a RecyclerView", two steps are defined:

    lane 219 -> 1. Create a custom ViewHolder class
    lane 220 -> 2. Create a custom subclass FirebaseListAdapter

Shouldn't the second step be "2. Create a custom subclass _FirebaseRecyclerAdapter_"?

Later on, at lane 253 this part of the guide is developed, and the title is "Create a custom FirebaseRecyclerAdapter"

**Comment by samtstern** [comment]
@Danoso89 thanks for the catch!  Fixed.

**Comment by Danoso89** [comment]
You're welcome! :+1:
