### ISSUE TITLE
[Urgent] Facebook Automatic sign-in loop prevents user from switching accounts

### ISSUE THREAD

**Issue by babkouew** [firebase/FirebaseUI-Android#1720]
Hi, I have recently updated Facebook to the new 5.9 sdk. Everything still works fine for the email and google login options but for Facebook, I can no longer switch accounts after login for the first time. 

I tried to force a Facebook logout with "LoginManager.getInstance().logOut()" just prior to calling FirebaseUI's signout function but it did not change a thing.  I have smartlock set to false in my signinIntentBuilder to no effect.

Uninstalled the App, invalidated cache and restart but the sign-in loop persist. It does end only when I open the Facebook App and logout from there.

I have no idea how to solve this and my App is about to enter production please help!

I am using the latest dependencies:
implementation 'com.firebaseui:firebase-ui-auth:6.1.0'
implementation 'com.facebook.android:facebook-login:5.9.0'

**Comment by samtstern** [comment]
@babkouew are you sure this is a FirebaseUI issue?  It sounds like you're not able to log out of the Facebook SDK at all ... if it's a FirebaseUI can you describe where things are going wrong within the FirebaseUI flow?
