### ISSUE TITLE
[Feature Request] Firebase AuthUI not allowing account linking between Mobile Phone auth and other providers

### ISSUE THREAD

**Issue by Alimiel** [firebase/FirebaseUI-Android#1721]
At the moment there is no way to perform account linking between mobile number accounts and other provider type accounts. I understand that it might be connected with the way Firebase Auth stores user details, specifically identifiers. Would it be possible to add additional optional identifiers to account by which the linking could be performed?

For example:

1. The user signs up using mobile phone and the account is created in the Firebase Authentication - Users with identifier +44 12345 678908 and some UID.

2. Then, in the application flow I could ask the user to provide e-mail, which I would then update with the code:

`val user = FirebaseAuth.getInstance().currentUser`

`val profileUpdates = UserProfileChangeRequest.Builder()`
        `.setDisplayName("Jane Q. User")`
        `.setPhotoUri(Uri.parse("https://example.com/jane-q-user/profile.jpg"))`
        `.setOptionalEmailIdentifier("jane.q@email.com")`
        `.build()`

`user?.updateProfile(profileUpdates)`
        `?.addOnCompleteListener { task ->`
            `if (task.isSuccessful) {`
                `Log.d(TAG, "User profile updated.")`
            `}`
        `}`

3. Once the user tries to sign in using for example Facebook provider, two accounts can be automatically linked.

One problem with this is that e-mail address would have to be verified first somehow to prevent following scenario:

1. Jane Q signs in using mobile phone and provides optional e-mail identifier belonging to Joe Schmoe (joe.schmoe@email.com).
2. Joe Schmoe not having any account signs in using his Facebook account which provides e-mail joe.schmoe@email.com
3. Joe Schmoe Facebook account is then linked with Jane Q mobile phone account.

This is just example of how this could work. Would it be possible to implement mobile phone account linking with other providers by this or any other means?

**Comment by samtstern** [comment]
@Alimiel thanks for the feature request!  Unfortunately there is no way to make this work with Firebase Authentication.  Email and Phone Number are mutually exclusive unique identifiers for the account.  There is no way to say "this account is the unique owner of 555-123-4567 and foo@bar.com".

cc @lsirac who is on the Firebase Authentication team and relay this feature request.  But for now, nothing we can do in FirebaseUI.
