### ISSUE TITLE
Unable to share credentials for multi-project support with email provider type?

### ISSUE THREAD

**Issue by kermitdefroghere** [firebase/FirebaseUI-Android#1722]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _All____
  * Android OS version: __All___
  * Google Play Services version: __Current___
  * Firebase/Play Services SDK version: _Current____
  * FirebaseUI version: _6.1___
  
### Step 3: Describe the problem:

It appears that I am unable to connect to multiple Firebase projects when the user is signed in with email provider.
More specifically, I am unable to issue "FirebaseAuth.getInstance(secondaryApp).signInWithCredential(credential)" because:
1) I'm unable to manually  access and retain email provider credentials on initial login
2) I'm unable to retrieve the user's credentials later with EmailAuthProvider.getCredential(email, password) because I don't have access to the user's password 

Am I missing something or does FirebaseUI not support multi-projects with email provider at this time? If not, I'd like to request this feature be added as soon as possible.
Thanks

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@kermitdefroghere thanks for the feedback.  FirebaseUI is intended to make it super simple to drop in auth flows for basic auth use cases.  Authenticating across apps is out of scope for this mission, it's much more complicated than what 99% of our users are trying to do.  For this reason we're not going to add this feature, I hope you can understand.
