### ISSUE TITLE
Filter firestore paging adapter (update query)

### ISSUE THREAD

**Issue by hkchakladar** [firebase/FirebaseUI-Android#1726]
Do you have any sample code to `filter the firestore paging adapter` with updated firestore query based on user selection?

**Comment by samtstern** [comment]
@hkchakladar can you explain more about what you're trying to do?

**Comment by hkchakladar** [comment]
I was asking about the filter in the `Firestore paging adapter` using the recently added option to update the query.

So I'm using the the adapter to update the show `transactions history` and I have a button to show the filtered transactions history which have `status == success`.

Onbutton click, I'm apdating the adapter the following way:

```java
        baseQuery = firestore.collection("transactions")
                        .whereEqualTo("status", "success")
                        .orderBy("__name__", Query.Direction.DESCENDING);

        options = new FirestorePagingOptions.Builder<ItemTxn>()
                .setLifecycleOwner(this)
                .setQuery(baseQuery, config, ItemTxn.class)
                .build();

        adapter.updateOptions(options);
```

And it's woking.

I think it's the way to update the query and the adapter.

**Comment by samtstern** [comment]
@hkchakladar yes that's the right way to do it!

**Comment by ramneekkashyap9** [comment]
@hkchakladar Hi, can you show the example how to exactly implement with the Filters in recyclerview. I am not able to implement this yet.
