### ISSUE TITLE
Can't get getUid() in response of current after authenticated.

### ISSUE THREAD

**Issue by hardslk** [firebase/FirebaseUI-Android#1733]
I am using FirebaseUI-Android and auth method is phone and after authentication I can't get UId of User there is no method for getting Uid().

Can't get getUid() in response of current after authenticated.

Thanks in advance.

**Comment by samtstern** [comment]
@hardslk does this work for you?
```
FirebaseAuth.getInstance().getCurrentUser().getUid()
```
