### ISSUE TITLE
FirestoreRecyclerOptions. The query requires an index error, when no index needed. Only when I use orderBy

### ISSUE THREAD

**Issue by bermanapps** [firebase/FirebaseUI-Android#1739]
I'm using Firestore database, and FirebaseUI to load the results into a recycler view in android kotlin. I am experiencing something weird.

I understand the error "The query requires an index", when making too many different requests over different fields. However, I understand you can make many requests, whereEqualTo, together with one request orderBy. Now, when I make this request myself (not using FirestoreRecyclerOptions). I have no problem and it works great.

However when I use the request with FirestoreRecyclerOptions, for example like this:

 var querySearch = FirebaseFirestore.getInstance()
            .collection(DB_DEALS_COLLECTION).document(departureCountry.toString()).collection(DB_DEALS_SUB_COLLECTION)
            .whereEqualTo(FILTER_FIELD_APR, true)
            .whereEqualTo(FILTER_FIELD_AUG, true)
            .whereEqualTo(FILTER_FIELD_DEC, true)
            .orderBy(FILTER_FIELD_TIMESTAMP, Query.Direction.DESCENDING).limit(15)

        val options = FirestoreRecyclerOptions.Builder<Deal>().setQuery(querySearch, Deal::class.java).build()
I get this error:

[Firestore]: Listen for Query(target=Query(deals_collection/USA/deals where monthApr == true and monthAug == true and monthDec == true order by -timestamp, -__name__);limitType=LIMIT_TO_FIRST) failed: Status{code=FAILED_PRECONDITION, description=The query requires an index.

When I click on the link in the console to add the index, I get this message in the Firestore console to add: I have to make a composite index with these fields:

monthApr Ascending 
monthAug Ascending 
monthDec Ascending 
timestamp Descending
Now I never wanted these fields ascending, only the timestamp?

Note: This only happens when I include:

.orderBy(FILTER_FIELD_TIMESTAMP, 
Also in the console I see, limitType=LIMIT_TO_FIRST. Also i see, -__name__ . What are these, I never set them!

I hope my problem is clear, I'm a bit confused with all this.

Thanks!

**Comment by samtstern** [comment]
Since we're already talking on StackOverflow (https://stackoverflow.com/questions/60327219) I am going to close this here.
