### ISSUE TITLE
Customize Password Reset Link

### ISSUE THREAD

**Issue by kmcnellis** [firebase/FirebaseUI-Android#1746]
Firebase UI should allow devs to customize their password reset links, to allow them to create a custom handler using [email action links in the Admin SDK](https://firebase.google.com/docs/auth/admin/email-action-links).

This will allow them to customize the emails sent to give custom instructions and have branded styling.

We should add a builder setting for `.setPasswordResetLink(...)` or something similar

**Comment by kmcnellis** [comment]
https://github.com/firebase/FirebaseUI-iOS/issues/843

**Comment by samtstern** [comment]
This has been released in version `6.4.0`
