### ISSUE TITLE
different strings for password input hint

### ISSUE THREAD

**Issue by dan-drewes** [firebase/FirebaseUI-Android#1753]
### Step 2: Describe your environment

  * Android device: LG ThinQ (applies to all)
  * Android OS version: 9
  * Google Play Services version: 17.0.0
  * Firebase/Play Services SDK version: 17.0.0
  * FirebaseUI version: 19.3.0
  
### Step 3: Describe the problem:

It should be possible to set different strings as the password hint when the user is asked to create a new password and when he should enter an already existing one.

#### Steps to reproduce:

  1. Overwrite the string 'fui_password_hint' in strings.xml with a different value, e.g. 'Set new password'
  2. Register new email address and see the password hint
  3. Use an email address that has been registered before and see the password hint 
 

#### Observed Results:

  * The strings shown are the same. It is not possible to change one of them without changing the other one.
  
#### Expected Results:

  * When overwriting the string 'fui_password_hint' in strings.xml with for example value 'Set new password' I would expect only one string to change. In other words, it should be possible to set different strings as the password hint when the user is asked to create a new password and when he should enter an already existing one.
  
#### Relevant Code:

 `<string name="fui_password_hint" translation_description="Hint for password input field">Set new password</string>`

**Comment by samtstern** [comment]
@dan-drewes are your users confused by the sign-up screen?  If so I wonder if a change other than the hint text is the correct fix here, hint text is pretty subtle and I think `Password` should be enough if the overall context is clear.

**Comment by dan-drewes** [comment]
@samtstern indeed some users said they were unsure about whether they should enter a new password or an existing one when signing up. They referred explicitly to the hint as misleading them. 
Personally, I do not think the hint text is that subtle in this particular context as there is only very few other text on the sign up form.

**Comment by samtstern** [comment]
Ok thanks @dan-drewes, I have no objection to making a second string.  I am going to put this on the `6.3.0` milestone since requesting new translations takes a while and I don't want to block `6.2.1` on that.

**Comment by samtstern** [comment]
This issue is fixed and released in version `6.3.0`.
