### ISSUE TITLE
[Feature Request] please add an option to change the email intent ui! it is the only reason for me not to use the library.

### ISSUE THREAD

**Issue by netef** [firebase/FirebaseUI-Android#1766]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: all
  * Android OS version: all
  * Google Play Services version: all
  * Firebase/Play Services SDK version: all
  * FirebaseUI version: 6.2.1
  
### Step 3: Describe the problem:
i want to have a certain design in my app and i cant without the email intent not allowing me to change the design.
#### Steps to reproduce:

  1. allow me to change the design
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@netef what do you mean by "change the email intent ui"?  Please provide more information when filing an issue, it's really hard to help from just a title.

**Comment by netef** [comment]
hi, thank you for the comment :) i want to make a custom layout for the email activity and i cannot. i am bound to the default layout which is only edit texts and a button at the end and my app design does not look like that. i want to make it more appealing :)

**Comment by samtstern** [comment]
@netef sorry but FirebaseUI is not meant to match the custom style of every app.  We allow you to override the first screen and also change the theme of all following screens:

You can read about those here:
https://firebaseopensource.com/projects/firebase/firebaseui-android/auth/readme#ui_customization

Other than that you'll have to implement your own UI!

**Comment by netef** [comment]
i have my own ui but i cannot use your email implementation with it because it is unchangable,
i just want to change the location of the elements and the design not add or remove elements

**Comment by samtstern** [comment]
You can use the base Firebase SDK and build your own UI around it:
https://firebase.google.com/docs/auth/android/password-auth

**Comment by netef** [comment]
ok will try this :)

**Comment by netef** [comment]
but if i put 3 buttons for login one for google one for facebook and one for email how can i make the email icon go to another activity that will manage the auth as you said?
