### ISSUE TITLE
ClassNotFoundException: android.support.v7.app.AppCompatViewInflater

### ISSUE THREAD

**Issue by jorge-acosta-abstracta** [firebase/FirebaseUI-Android#1767]
* Android device: Android Emulator
  * Android OS version: Android version 10; Security Patch March 05, 2020
  * Google Play Services version: 20.06.16
  * Firebase/Play Services SDK version: 49
  * FirebaseUI version: com.firebaseui:firebase-ui-auth:6.2.1 
  
### Step 3: Describe the problem:

When calling our function firebaseUISDKLogin the following exception appears on the console at the same time the sign in screen is created.

> 2020-03-26 11:45:43.581 10093-10093/? I/AppCompatDelegate: Failed to instantiate custom view inflater android.support.v7.app.AppCompatViewInflater. Falling back to default.
>     java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
>         at java.lang.Class.classForName(Native Method)
>         at java.lang.Class.forName(Class.java:454)
>         at java.lang.Class.forName(Class.java:379)
>         at so.a(:com.google.android.gms@200616040@20.06.16 (120700-296104215):50)
>         at so.onCreateView(:com.google.android.gms@200616040@20.06.16 (120700-296104215):1)
>         at android.view.LayoutInflater.tryCreateView(LayoutInflater.java:1059)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:995)
>         at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
>         at android.view.LayoutInflater.inflate(LayoutInflater.java:479)
>         at com.android.internal.policy.DecorView.onResourcesLoaded(DecorView.java:2098)
>         at com.android.internal.policy.PhoneWindow.generateLayout(PhoneWindow.java:2642)
>         at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2705)
>         at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2105)
>         at so.A(:com.google.android.gms@200616040@20.06.16 (120700-296104215):9)
>         at so.c(:com.google.android.gms@200616040@20.06.16 (120700-296104215):5)
>         at dqz.setContentView(:com.google.android.gms@200616040@20.06.16 (120700-296104215):1)
>         at com.google.android.gms.auth.api.credentials.yolo.ui.CredentialPickerChimeraActivity.onCreate(:com.google.android.gms@200616040@20.06.16 (120700-296104215):33)
>         at com.google.android.chimera.ActivityBase.publicOnCreate(:com.google.android.gms@200616040@20.06.16 (120700-296104215):0)
>         at qmi.onCreate(:com.google.android.gms@200616040@20.06.16 (120700-296104215):7)
>         at android.app.Activity.performCreate(Activity.java:7990)
>         at android.app.Activity.performCreate(Activity.java:7979)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3477)
>         at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
>         at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
>         at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
>         at android.os.Handler.dispatchMessage(Handler.java:106)
>         at android.os.Looper.loop(Looper.java:216)
>         at android.app.ActivityThread.main(ActivityThread.java:7464)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
>      Caused by: java.lang.ClassNotFoundException: android.support.v7.app.AppCompatViewInflater
> 
> 

**The application crashes if the user presses the back button on the device**

```
2020-03-26 11:50:26.345 1848-1848/? E/servicemanager: Could not find android.hardware.power.IPower/default in the VINTF manifest.
2020-03-26 11:50:26.345 15594-15594/io.abstracta.mpos E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.abstracta.mpos, PID: 15594
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1986, result=0, data=null} to activity {io.abstracta.mpos/io.abstracta.mpos.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.ui.auth.FirebaseUiException com.firebase.ui.auth.IdpResponse.getError()' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4912)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4953)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2043)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7464)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.ui.auth.FirebaseUiException com.firebase.ui.auth.IdpResponse.getError()' on a null object reference
        at io.abstracta.mpos.MainActivity.onActivityResult(MainActivity.java:73)
        at android.app.Activity.dispatchActivityResult(Activity.java:8300)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4905)
```

#### Steps to reproduce:

  1. Configure build.gradle
  2. Call the startActivityForResult(AuthUI.getInstance() ...)
  3. The exception is logged.
  4. Stay on the login screen for 10 seconds press the back button on the device: the application crashes.
  
#### Observed Results:

On our app the user presses a sign in button that 
  
#### Expected Results:

  * No app crashes
  * No errors while calling the Firebase Auth UI Screen.
  
#### Relevant Code:

**Build.gradle (app):**

```
android {

    compileSdkVersion 29

    defaultConfig {
        applicationId "io.abstracta.mpos"
        minSdkVersion 22
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    implementation 'com.google.firebase:firebase-analytics:17.2.2'
    implementation 'com.google.firebase:firebase-auth:19.3.0'
    implementation 'com.google.firebase:firebase-functions:19.0.2'
    implementation 'com.google.firebase:firebase-database:19.2.1'
    //Firebase UI will not be used in production
    implementation 'com.firebaseui:firebase-ui-auth:6.2.1'

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
}
```

**Sign In Call:**

 ```

    public void firebaseUISDKLogin(View view) {
        // Choose authentication providers
        List<AuthUI.IdpConfig> providers = Arrays.asList(
                new AuthUI.IdpConfig.EmailBuilder().build());
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setLogo(R.drawable.glogo)
                        .setTheme(R.style.AppTheme)
                        .build(),
                RC_SIGN_IN);
    }

 //UI SDK Signin Result
    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_SIGN_IN) {
            if(data == null){
                //user abandoned sign in
                showToast("user abandoned the sign in process");
            }
            IdpResponse response = IdpResponse.fromResultIntent(data);
            if (resultCode == RESULT_OK) {
                // Successfully signed in
                FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
                showToast(user.getEmail() + " " + user.getUid());
            } else {
                // Sign in failed. If response is null the user canceled the
                // sign-in flow using the back button. Otherwise check
                // response.getError().getErrorCode() and handle the error.
                showToast(Integer.toString(response.getError().getErrorCode()));
            }
        }
    }
```

**Comment by samtstern** [comment]
@jorge-acosta-abstracta it looks like the crash is happening in your own code:
```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.firebase.ui.auth.FirebaseUiException com.firebase.ui.auth.IdpResponse.getError()' on a null object reference
        at io.abstracta.mpos.MainActivity.onActivityResult(MainActivity.java:73)
```

```
showToast(Integer.toString(response.getError().getErrorCode()));
```

So it looks like `response` is null there.  Could you add the following logging in your `onActivityResult` so I can see what's being returned:

```java
Log.d("FirebaseUI", "onActivityResult: " + requestCode + ", " + resultCode);
Log.d("FirebaseUI", "onActivityResult: " + data);
if (data != null) {
  Log.d("FirebaseUI", "onActivityResult: " + data.getExtras());
}
```

**Comment by samtstern** [comment]
Here is the code we use in the sample app in this repo, I would suggest you do something similar:

```java
        // Successfully signed in
        if (resultCode == RESULT_OK) {
            // ...
        } else {
            // Sign in failed
            if (response == null) {
                // User pressed back button
                showSnackbar(R.string.sign_in_cancelled);
                return;
            }

            if (response.getError().getErrorCode() == ErrorCodes.NO_NETWORK) {
                showSnackbar(R.string.no_internet_connection);
                return;
            }

            if (response.getError().getErrorCode() == ErrorCodes.ANONYMOUS_UPGRADE_MERGE_CONFLICT) {
                // ...
            }

            if (response.getError().getErrorCode() == ErrorCodes.ERROR_USER_DISABLED) {
                showSnackbar(R.string.account_disabled);
                return;
            }

            showSnackbar(R.string.unknown_error);
            Log.e(TAG, "Sign-in error: ", response.getError());
        }
```
