### ISSUE TITLE
open How to pass new query to FirestorePagedAdapter to refresh it 

### ISSUE THREAD

**Issue by josephkabba** [firebase/FirebaseUI-Android#1770]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@josephkabba please use the issue template when filing an issue, a title is not enough.

You should be able to use the `updateOptions` method to achieve what you're trying to do.

**Comment by josephkabba** [comment]
Thanks for your reply ....one other thing firestorePagedAdapter takes long
to load data


Thanks for the help generally the library is good and quick to setup and
use😊😊😊 let be it.  Hope that you are safe during this massive
outbreak....God bless you

**Comment by josephkabba** [comment]
I can't find the updateOptions method in FirestorePagedAdapter
