### ISSUE TITLE
recycler view not working

### ISSUE THREAD

**Issue by aayushmalviya2106** [firebase/FirebaseUI-Android#1782]
package com.example.chairlabs;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import android.view.View;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.firebase.ui.database.FirebaseRecyclerOptions;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import Model.Cart;
import Model.User;
import Prevalent.Prevalent;
import View_Holder.CartviewHolder;

public abstract class cartActivity extends AppCompatActivity {
    private RecyclerView recyclerView;
    private Button Next;
    private TextView txtTotalAmount;
    private RecyclerView.LayoutManager layoutManager;
    FirebaseRecyclerAdapter<Cart, CartviewHolder> adapter;
    DatabaseReference cartlistref;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cart);

        cartlistref = FirebaseDatabase.getInstance().getReference().child("Cart list").child("User View")
                .child(Prevalent.currentOnlineUSer.getNumber()).child("Products");

        Next = (Button) findViewById(R.id.next_cart);
        txtTotalAmount = (TextView) findViewById(R.id.total_price);
        Toast.makeText(cartActivity.this, "cart", Toast.LENGTH_SHORT).show();

        recyclerView = findViewById(R.id.cart_list_recycler);
        recyclerView.setHasFixedSize(true);
        layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);

    }

    protected void onStart() {
        super.onStart();

        Cart cart = new Cart();
        if (cart.getPname() != null) {
            Log.e("message ", "  ==>" + cart.getPname());  // Here I am getting null value

            Toast.makeText(cartActivity.this, (cart.getPname()), Toast.LENGTH_SHORT).show();
        }
        if (cart.getPrice() == null) {
            Log.e("message price ", "  ==>" + cart.getPrice());
            Toast.makeText(cartActivity.this, (cart.getPrice()), Toast.LENGTH_SHORT).show();
        }

        Toast.makeText(cartActivity.this, "onStart", Toast.LENGTH_SHORT).show();

        final DatabaseReference cartlistref = FirebaseDatabase.getInstance().getReference().child("Cart list");
        FirebaseRecyclerOptions<Cart> options = new FirebaseRecyclerOptions.Builder<Cart>()
                .setQuery(cartlistref.child("User View")
                                .child(Prevalent.currentOnlineUSer.getNumber()).child("Products")
                        , Cart.class)
                .build();
        Log.e("message ", "  ==>" + cartlistref.child("User View").child(Prevalent.currentOnlineUSer.getNumber()).child("Products").toString());
        Toast.makeText(cartActivity.this, options.toString(), Toast.LENGTH_SHORT).show();
        Log.e("message ", "  ==>" + options.toString());
        FirebaseRecyclerAdapter<Cart, CartviewHolder> adapter = new FirebaseRecyclerAdapter<Cart, CartviewHolder>(options) {

            @NonNull
            @Override
            public CartviewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                android.view.View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.cart_item_layout, parent, false);
                CartviewHolder holder = new CartviewHolder(v);
                Toast.makeText(cartActivity.this, "holder", Toast.LENGTH_SHORT).show();

                return holder;

            }

            @Override
            protected void onBindViewHolder(CartviewHolder cartviewHolder, int i, Cart cart) {
                if (cart.getQuantity() != null) {
                    Log.e("message qty ", "  ==>" + cart.getQuantity())
                    ;
                    cartviewHolder.setName(cart.getQuantity());//Cart.class,R.layout.cart_item_layout,CartviewHolder.class,cartlistref
                }
                if (cart.getPrice() != null) {
                    cartviewHolder.setprice(cart.getPrice());
                }
                if (cart.getPname() != null) {
                    cartviewHolder.txtProductName.setText(cart.getPname());
                }
                Log.e("tagline", cart.getPname().toString());
                Toast.makeText(cartActivity.this, "cartActivity", Toast.LENGTH_SHORT).show();
            }

          /*  protected void populateViewHolder(CartviewHolder cartviewHolder, Cart cart, int position) {
                cartviewHolder.setprice(cart.getPrice());
                cartviewHolder.setName(cart.getPname());
                cartviewHolder.setQuantity(cart.getQuantity());
            }*/
        };

        recyclerView.setAdapter(adapter);
        adapter.startListening();

    }
}

**Comment by aayushmalviya2106** [comment]
onBindView method and onCreate method is not executing

**Comment by aayushmalviya2106** [comment]
package com.example.chairlabs;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AlertDialog;
import androidx.appcompat.app.AppCompatActivity;
import androidx.recyclerview.widget.LinearLayoutManager;
import androidx.recyclerview.widget.RecyclerView;

import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import android.view.View;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.firebase.ui.database.FirebaseRecyclerOptions;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

import Model.Cart;
import Model.User;
import Prevalent.Prevalent;
import View_Holder.CartviewHolder;

public class cartActivity extends AppCompatActivity {
    private RecyclerView recyclerView;
    private Button Next;
    private TextView txtTotalAmount;
    private RecyclerView.LayoutManager layoutManager;
    private FirebaseRecyclerAdapter<Cart, CartviewHolder> adapter;
    DatabaseReference cartlistref;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_cart);

        cartlistref = FirebaseDatabase.getInstance().getReference().child("Cart list").child("User View")
                .child(Prevalent.currentOnlineUSer.getNumber()).child("Products");


        Next = (Button) findViewById(R.id.next_cart);
        txtTotalAmount = (TextView) findViewById(R.id.total_price);
        Toast.makeText(cartActivity.this, "cart", Toast.LENGTH_SHORT).show();


        recyclerView = findViewById(R.id.cart_list_recycler);
        recyclerView.setHasFixedSize(true);
        layoutManager = new LinearLayoutManager(this);
        recyclerView.setLayoutManager(layoutManager);


    }


    protected void onStart() {
        super.onStart();






        Cart cart = new Cart();
        if (cart.getPname() != null) {
            Log.e("message ", "  ==>" + cart.getPname());  // Here I am getting null value

            Toast.makeText(cartActivity.this, (cart.getPname()), Toast.LENGTH_SHORT).show();
        }
        assert cart.getPrice() != null;
        if (cart.getPrice() == null) {
            Log.e("message price ", "  ==>" + cart.getPrice());
            Toast.makeText(cartActivity.this, (cart.getPrice()), Toast.LENGTH_SHORT).show();
        }


        Toast.makeText(cartActivity.this, "onStart", Toast.LENGTH_SHORT).show();

        String user = Prevalent.currentOnlineUSer.getNumber().toString();
        final DatabaseReference cartlistref = FirebaseDatabase.getInstance().getReference().child("Cart list");
        FirebaseRecyclerOptions<Cart> options = new FirebaseRecyclerOptions.Builder<Cart>()
                .setQuery(cartlistref.child("User View")
                                .child(user).child("Products")
                        , Cart.class)
                .build();
        Log.e("message ", "  ==>" + cartlistref.child("User View").child(user).child("Products").toString());
        Toast.makeText(cartActivity.this, options.toString(), Toast.LENGTH_SHORT).show();
        Log.e("message ", "  ==>" + options.toString());

      //Cart cart = new Cart();
        assert cart.getPname() != null;
        if (cart.getPname() != null) {
            Log.e("message ", "  ==>" + cart.getPname());  // Here I am getting null value

            Toast.makeText(cartActivity.this, (cart.getPname()), Toast.LENGTH_SHORT).show();
        }
        assert cart.getPrice() != null;
        if (cart.getPrice() == null) {
            Log.e("message price ", "  ==>" + cart.getPrice());
            Toast.makeText(cartActivity.this, (cart.getPrice()), Toast.LENGTH_SHORT).show();
        }
        FirebaseRecyclerAdapter<Cart, CartviewHolder> adapter = new FirebaseRecyclerAdapter<Cart, CartviewHolder>(new FirebaseRecyclerOptions.Builder<Cart>()
                .setQuery(cartlistref.child("User View")
                                .child(user).child("Products")
                        , Cart.class)
                .build()) {


            @Override
            protected void onBindViewHolder(@NonNull CartviewHolder holder, int position, @NonNull Cart cart) {
                String use = cart.getQuantity();
                assert cart.getQuantity() != null;
                if (cart.getQuantity() != null) {
                    Log.e("message qty ", "  ==>" + cart.getQuantity())
                    ;
                    holder.setName(cart.getQuantity());//Cart.class,R.layout.cart_item_layout,CartviewHolder.class,cartlistref
                }
                assert cart.getPrice() != null;
                if (cart.getPrice() != null) {
                    holder.setprice(cart.getPrice());
                }
                assert cart.getPname() != null;
                if (cart.getPname() != null) {
                    holder.txtProductName.setText(cart.getPname());
                }
                Log.e("tagline", cart.getPname().toString());
                Toast.makeText(cartActivity.this, "cartActivity", Toast.LENGTH_SHORT).show();


            }


            @NonNull
            @Override
            public CartviewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                android.view.View v = LayoutInflater.from(parent.getContext()).inflate(R.layout.cart_item_layout, parent, false);
                CartviewHolder holder = new CartviewHolder(v);
                Toast.makeText(cartActivity.this, "holder", Toast.LENGTH_SHORT).show();

                return holder;
            }
        };

        recyclerView.setAdapter(adapter);
        adapter.startListening();





    }
}

**Comment by aayushmalviya2106** [comment]
unable to retrieve values from adapter

**Comment by samtstern** [comment]
@aayushmalviya2106 this issue does not follow the issue template.  For questions on how to debug your code, try StackOverflow.
