### ISSUE TITLE
[Auth] Can't set GithubLoginButtonID to AuthMethodPickerLayout

### ISSUE THREAD

**Issue by le-kamba** [firebase/FirebaseUI-Android#1783]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: any
  * Android OS version: any
  * Google Play Services version: `classpath 'com.google.gms:google-services:4.3.3'`
  * Firebase/Play Services SDK version: `implementation 'com.google.firebase:firebase-core:17.4.1'`
  * FirebaseUI version: `implementation 'com.firebaseui:firebase-ui-auth:6.2.1'`
  
#### Steps to reproduce:

  1. import `com.firebase.ui.auth.AuthMethodPickerLayout`
  2. create `AuthMethodPickerLayout` with `AuthMethodPickerLayout.Builder`
  3. use `setGithubButtonId` to set button id from custom layout file.
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

There is a merged PR at #1583, so I expected to using `setGithubButtonId `, but cannot compile with **Unresolved reference** error.

I checked source code here,
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/AuthMethodPickerLayout.java

and here,
https://github.com/firebase/FirebaseUI-Android/blob/version-6.2.1/auth/src/main/java/com/firebase/ui/auth/AuthMethodPickerLayout.java
  
I can't find `setGithubButtonId` method.

Is that removed for any reason?

#### Expected Results:

  * What did you expect to happen?

No compile error and build completes.
  
#### Relevant Code:

  ```
            val authLayout = AuthMethodPickerLayout.Builder(R.layout.layout_auth)
                .setEmailButtonId(R.id.email_button)
                .setFacebookButtonId(R.id.facebook_button)
                .setTwitterButtonId(R.id.twitter_button)
                .setGoogleButtonId(R.id.google_button)
                .setGithubButtonId(R.id.github_button)
                .build()
  ```

**Comment by samtstern** [comment]
This issue is fixed and released in version `6.3.0`.
