### ISSUE TITLE
FirestorePagingAdapter not can run getSnapshots method

### ISSUE THREAD

**Issue by LukeDaniel16** [firebase/FirebaseUI-Android#1784]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: J6 Plus
  * Android OS version: 9.0
  * Google Play Services version: Last Updated
  * Firebase/Play Services SDK version: Last Updated
  * FirebaseUI version: Last Updated
  
### Step 3: Describe the problem:

When using the RecyclerView adapter we can easily obtain snapshots using the getSnapshots method, which, using FirestorePagingAdapter, is not possible, as the method does not exist

#### Steps to reproduce:

  1. In the Holder class, you can create ListenerOnClick interface
  2. And in event clicks on Holder class, you can to do action
  3. In the Event OnClick you could to call getSnapshots(). But this method is not exist in FirebasePagining.
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

  There is no observable result if the method does not exist.

#### Expected Results:

  * What did you expect to happen?
  I hope to find some way to capture a specific document and keep it with me to use in other activities
#### Relevant Code:

```  @Override
                public void onClick(View v) {
                    int posicao = getAdapterPosition();
                    if(posicao != RecyclerView.NO_POSITION && listener != null){
                        // getSnapshots here...
                    }
                }```

**Comment by samtstern** [comment]
@LukeDaniel16 we can't provide `getSnapshots()` since this is a paged adapter and we don't have all the snapshots at once.

Maybe try this method, from the base AndroidX class:
https://developer.android.com/reference/androidx/paging/PagedListAdapter#getCurrentList()
