### ISSUE TITLE
com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner

### ISSUE THREAD

**Issue by colorgold** [firebase/FirebaseUI-Android#1787]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: __Nexus 5X___
  * Android OS version: _6.0.1____
  * Google Play Services version: 18.0.0_____
  * Firebase/Play Services SDK version: ___17.4.2__
  * FirebaseUI version: __6.2.1__
  
### Step 3: Describe the problem:
This is the error I received from Crashlytics
`Fatal Exception: java.lang.RuntimeException 
Unable to start activity ComponentInfo{app.myandroidhello.com.chatmurcianys/com.firebase.ui.auth.ui.phone.PhoneActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Set.isEmpty()' on a null object reference`
#### Steps to reproduce:

  1. _Initialize phone provider: `List<AuthUI.IdpConfig> phoneProvider = Collections.singletonList(
                new AuthUI.IdpConfig.PhoneBuilder().build());` ___
  2. _When the phone button is clicked: _`startActivityForResult(
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(phoneProvider)
                            .setTheme(R.style.BlankTheme)
                            .build(),REQUEST_SIGN_IN
            );`__

  
#### Observed Results:
I tried this out on a Nexus 5X API 28 Emulator and it worked as expected without any crashes. However, Crashlytics has detected 39 crashes affecting 15 users apparently all on Nexus 5x phones. I haven't really being able to reproduce this crash myself, but it bothers me that there's other users out there who are not able to register using their phone numbers.
  * What happened?  This could be a description, `logcat` output, etc.
  `com.firebase.ui.auth.ui.phone.CountryListSpinner.getCountriesToDisplayInSpinner (CountryListSpinner.java:93) `

`com.firebase.ui.auth.ui.phone.CountryListSpinner.init (CountryListSpinner.java:81) `

`com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.setupCountrySpinner (CheckPhoneNumberFragment.java:207) `

`com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.onViewCreated (CheckPhoneNumberFragment.java:104) `

`androidx.fragment.app.FragmentManagerImpl.moveToState (FragmentManagerImpl.java:892) `
#### Expected Results:

  * What did you expect to happen?
  I expected the emulator to crash, but it did not; I have not been able to fully understand where the problems begins.
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```List<AuthUI.IdpConfig> phoneProvider = Collections.singletonList(
                new AuthUI.IdpConfig.PhoneBuilder().build());
 ```startActivityForResult(
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(phoneProvider)
                            .setTheme(R.style.BlankTheme)
                            .build(),REQUEST_SIGN_IN
            );

**Comment by samtstern** [comment]
This is very similar to #1734 and #1738 but I can't really figure out how this is possible.  There is nowhere in the code where those `Set` objects could possibly be assigned to `null`!

**Comment by colorgold** [comment]
> This is very similar to #1734 and #1738 but I can't really figure out how this is possible. There is nowhere in the code where those `Set` objects could possibly be assigned to `null`!

yeah I have no idea what could be happening because I have tested on different android devices, including tablets, without any success of reproducing the problem.

**Comment by colorgold** [comment]
The error I get from Crashlytics seems to be referencing sets `mWhitelistedCountryIsos` and `mBlacklistedCountryIsos` as if they have not been initialized in lines 58 and 59 in the CountryListSpinner class. I've googled this issue, but usually the problems lies in people not initializing the lists (which does not seem to be the problem here). I don't know if checking that the 2 sets are not `null` before checking if they are empty could fix the problem.

**Comment by samtstern** [comment]
@colorgold if you want to try and fix this a PR is welcome!  I am not a fan of defensively coding without understanding the bug but this may be one of the cases where it's warranted.

Also every report of this crash I have seen is from the Nexus 5X which is not a popular device ...

**Comment by colorgold** [comment]
> fix this a PR is welcome

I know what you mean. It's frustrating not being able to find the root of the problem to be able to find the cure. I keep getting over 28 crashes every week on a Nexus 5X device attempting to register with their phone. I've never submitted a Pull Request, so I am a little confused as to how to do it. Nevertheless I will give it try.

**Comment by colorgold** [comment]
I am trying to understand the code for `CountryListSpinner.java` class a little better. Line 93 has this code:
``if (mWhitelistedCountryIsos.isEmpty() && mBlacklistedCountryIsos.isEmpty()) {
            this.mWhitelistedCountryIsos = new HashSet<>(countryInfoMap.keySet());
 }``

My question is: why is `mWhitelistedCountryIsos` used inside the `if` expression but `this.mWhitelistedCountryIsos` is used inside its body? I just don't see any local variable with the same name as the global one inside the function.

**Comment by samtstern** [comment]
@colorgold I think we just have an inconsistent use of `this` within our code.  It's optional when referring to a field if there's no local variable with the same name, which I believe is the case there.

**Comment by colorgold** [comment]
I have been receiving more crashes of this issue and just wanted to inform that the problem only seems to come from `rooted Nexus 5X LGE phones`

**Comment by samtstern** [comment]
@colorgold thanks for reporting.  I think there's some fishy Android device farms out there using Nexus 5X devices which do not represent real users.  I still don't know *how* they break this code but clearly they have runtime modifications.

Do you think we can close this issue since it seems to be out of our hands?

**Comment by colorgold** [comment]
@samtstern yes. I will close it. Thank you for taking the time to look through this.
