### ISSUE TITLE
how to query data on firebase database pagination 

### ISSUE THREAD

**Issue by deflexable** [firebase/FirebaseUI-Android#1792]
hi everyone, am having an issue integration firebase pagination to it full potential. i have followed the official firebaseUi database pagination. When I compiled and test my app everything is working well. But am building an e-commerce app which i will need to query products name from real-time database. i tried to query the data by using the startAt and endAt clause but unfortunately my app crashes. i went through the doc multiple times and found out that we should customize our model class with snapshot parser, so my question is this, is the right way and how can i query my data from firebase database with pagination. 

- so this is the line of code of the snapshot parser
![Screenshot_20200609-022031](https://user-images.githubusercontent.com/57331729/84096067-ce849380-a9f8-11ea-8873-e5e04bc6bf04.png)

i will be really glad and happy if any one can help me?

**Comment by samtstern** [comment]
@deflexable in order to help you we would need a lot more information about what code you've written and how it crashes (error logs, etc).

**Comment by deflexable** [comment]
@samtstern thanks for replying, am paginating a recycler view with firebase-ui-database and this is my activity class
`
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.biss_index);

        RecyclerView bissRecy = findViewById(R.id.recylBindex);
        GridLayoutManager layoutManager = new GridLayoutManager(this,2);
        bissRecy.setLayoutManager(layoutManager);
        bissRecy.setHasFixedSize(false);

        DatabaseReference productRef = FirebaseDatabase.getInstance().getReference().child("Products");
        productRef.keepSynced(true);

        PagedList.Config config = new PagedList.Config.Builder()
                .setEnablePlaceholders(false)
                .setPrefetchDistance(5)
                .setPageSize(6)
                .build();

        Query query = productRef.orderByChild("pName").startAt("olamide").endAt("olamide"+ "\uf8ff");

        //Initializing FirebasePagingOptions
        DatabasePagingOptions<Products> optionPaging = new DatabasePagingOptions.Builder<Products>()
                .setLifecycleOwner(this)
                .setQuery(query, config, Products.class)
                .build();

        adapter = new FirebaseRecyclerPagingAdapter<Products, BissIndexHolder>(optionPaging) {
            @Override
            protected void onBindViewHolder(@NonNull BissIndexHolder viewHolder, int position, @NonNull Products model) {
                viewHolder.setBisIndex(model.getpImage(),model.getpName());
            }

            @NonNull
            @Override
            public BissIndexHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                View oview= LayoutInflater.from(parent.getContext()).inflate(R.layout.biss_index_items,parent,false);
                return new BissIndexHolder(oview, BissIndex.this);
            }
        };
        bissRecy.setAdapter(adapter);
    }
`

and this is my recycler viewHolder

`
public class BissIndexHolder extends RecyclerView.ViewHolder {
    private Context dContext;
    private View dView;

    public BissIndexHolder(@NonNull View dItemView, Context context) {
        super(dItemView);
        dView = dItemView;
        dContext = context;
    }

    public void setBisIndex(String jobimage,String jobText){
        ImageButton jobImg = dView.findViewById(R.id.imgBtn);
        TextView jobTxt = dView.findViewById(R.id.careerTxt);
        Picasso.get().load(jobimage).into(jobImg);
        jobTxt.setText(jobText);
    }
}

` 
when i run the app it crashes and print this message to the logcat

![pagingLogcat](https://user-images.githubusercontent.com/57331729/84202987-86b94700-aaa0-11ea-9b48-229ba184815d.PNG)

but when I replace the query part use in binding the view with the productRef, it works but that doesn't query the data i need from firebase.

**Comment by deflexable** [comment]
thanks a lot for replying. I have added more info about my code at

https://github.com/firebase/FirebaseUI-Android/issues/1792

please follow the link above and i will really be glad if you can help me.

**Comment by samtstern** [comment]
Unfortunately we can't accept a query into the adapter that already has a `startAt` clause:

```
Query query = productRef.orderByChild("pName").startAt("olamide").endAt("olamide"+ "\uf8ff");
```

The adapter would work if you changed your query to:
```
Query query = productRef.orderByChild("pName")
```

We realize this is a tough limitation but the Realtime Database / Firestore SDKs don't give use any query inspection API we could use to work around it.

This is something you could probably solve by forking the library, but we won't be able to support it directly.

**Comment by deflexable** [comment]
@samtstern ok thanks 👌
