### ISSUE TITLE
Recycler view not loading second time

### ISSUE THREAD

**Issue by jay-ph** [firebase/FirebaseUI-Android#1794]
### Problem Description:
The recycler view shows items when starting the activity for the first time. But when I press the back button and re-open that activity the items are not displayed.
  
#### Observed Results:

  * I tried a solution I found on StackOverflow that worked for someone and it is to add the orderBy method. But no success.
What happened: in an activity, there is a recycler view that displays some items also using firestore recycler adapter and when I click on an item I go to an item details activity that contains some details about that item and in it, there is also a recycler view. That one is the one that is showing the item for the first time. When I press the back button or the toolbar home button, the activity is finished. If I click back the item and re-go to the details activity the recycler view doesn't show the items. It works only when closing the app from recent apps.
  
#### Expected Results:

  * RecyclerView showing the items every time not only once.
  
#### Relevant Code:

  ```
    Query query = document.collection("Items");

    FirestoreRecyclerOptions<Model> options = new FirestoreRecyclerOptions.Builder<Model>()
            .setLifecycleOwner(this)
            .setQuery(query, Model.class)
            .build();

    adapter = new ItemsRecyclerAdapter(options, this, this);

    recyclerView.setHasFixedSize(true);
    recyclerView.setLayoutManager(new LinearLayoutManager(this));
    recyclerView.setAdapter(adapter);
  ```

**Comment by samtstern** [comment]
@jay-ph this is not enough code or logs to properly debug your issue.  Where is the code above actually running?

Are you sure it executes?  Have you tried adding more logging to `ItemsRecyclerAdapter` to see if the data is loaded?

With the information available it's hard to say if this is a FirebaseUI issue or an issue in your app.

**Comment by jay-ph** [comment]
@samtstern 

This code is for loading the items in an item details activity. It is a private method which is called when loading the details loads. i.e: I load the item image, name, description, and its subitems using the recycler view.

And here's the adapter code I don't know if it useful:

`public class ItemsRecyclerAdapter extends FirestoreRecyclerAdapter<Model, ItemsRecyclerAdapter.ViewHolder> {

    Context context;
    ListItemButtonClick listItemButtonClick;

    public interface ListItemButtonClick {
        void onClick(String id);
    }

    public ItemsRecyclerAdapter(@NonNull FirestoreRecyclerOptions<Model> options, Context context, ListItemButtonClick listItemButtonClick) {
        super(options);
        this.context = context;
        this.listItemButtonClick = listItemButtonClick;
    }

    @NonNull
    @Override
    public ItemsRecyclerAdapter.ViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {

        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.list_item, parent, false);
        context = parent.getContext();
        return new ViewHolder(view);

    }

    @Override
    protected void onBindViewHolder(@NonNull final ItemsRecyclerAdapter.ViewHolder holder, int position, @NonNull Model model) {

        // retrieving and applying here
      

    }

    public class ViewHolder extends RecyclerView.ViewHolder {

        ImageView image;
        TextView name,

        public ViewHolder(@NonNull View itemView) {
            super(itemView);

            image = itemView.findViewById(R.id.image);
            name = itemView.findViewById(R.id.name);
            

        }

    }

}
`

**Comment by samtstern** [comment]
@jay-ph where do you call these lines:
```java
  adapter = new ItemsRecyclerAdapter(options, this, this);

  recyclerView.setHasFixedSize(true);
  recyclerView.setLayoutManager(new LinearLayoutManager(this));
  recyclerView.setAdapter(adapter);
```

**Comment by jay-ph** [comment]
@samtstern In onCreate there is a method to retrieve the details such as image, name... from firestore document and in that method there is a method for above code

**Comment by samtstern** [comment]
@jay-ph I agree that sounds simple but it's not possible to debug this just by thinking about what your code may be doing.

Are you sure that...

- `onCreate` executes when you return to the activity?
- The "method to retrieve the details" is called each time and succeeds?
- Within that method the code to make the adapter is called each time and succeeds?

I would suggest adding logging or attaching a debugger until you are sure of these things.

**Comment by jay-ph** [comment]
@samtstern 
Yes, I already said that it works fine from the first run. If the app is completely closed and I run it the recyclerview is showing the items fine but if I go back and then return to that activity it simply doesn't.

Is it possible to send you a screen recording of it?

**Comment by samtstern** [comment]
No a screen recording doesn’t help.  I believe you’re having this issue but you’re not really helping when it comes to debugging.

The Android activity lifecycle is complex.  I suspect that onCreate is not running when you think it is.  

If you’re not willing to try and confirm or deny that then we can’t really proceed here.

**Comment by jay-ph** [comment]
How it doesn't help? It is just to show you what I'm trying to describe just so you get the idea.
I tried debugging but it didn't help

But the onCreate is working. Only the recyclerview is not displaying the items from the first time until I close the app completely. It is the first time it happens. I also tried adding the code for setting the adapter directly in onCreate and removing everything. So I'm just retrieving the recyclerview items. And still having the same issue.

**Comment by samtstern** [comment]
I'm sorry I don't think we're speaking the same language here.  There have been no logs presented or any or other type of debugging information that will help to pinpoint the source of the problem.  A video would only confirm that this is happening, which I obviously believe.  However we need to figure out what makes your app different from the thousands of others that have implemented FirebaseUI without this issue.

Without any evidence that there is a bug in FirebaseUI I have to close this issue.  I would suggest StackOverflow as a more productive venue.

**Comment by jay-ph** [comment]
@samtstern i tried stackoverflow before coming here. and i came here because i had no response

**Comment by jay-ph** [comment]
@samtstern you want me to debug it. where? at which lines i should do it
