### ISSUE TITLE
Customize firebase-ui android to look like this ?

### ISSUE THREAD

**Issue by ahmedosama5200** [firebase/FirebaseUI-Android#1797]
### Feature
Is there a way to achieve that ?
![Info_new](https://user-images.githubusercontent.com/31630951/85163668-786ae800-b263-11ea-86fb-c858c0920264.png)

**Comment by samtstern** [comment]
@ahmedosama5200 we support custom XML layouts you can see an example of this if you run the sample app (the `app` module) included in this repo:
https://github.com/firebase/FirebaseUI-Android/blob/master/app/src/main/java/com/firebase/uidemo/auth/AuthUiActivity.java#L244

**Comment by ahmedosama5200** [comment]
I know that, but I don't want the `sign in with email` button like in the example. I can create the layout like in the picture, but what about the `sign in` button, what will its click listener be ? Will I have to implement that myself ?

**Comment by samtstern** [comment]
@ahmedosama5200 ah sorry I see what you mean now.  No we do not support "inline" email/password flow on that screen.  If that's the flow you want you'll have to implement it yourself, FirebaseUI won't be very useful.

**Comment by ahmedosama5200** [comment]
Well, It sounds like a feature request, right ?

**Comment by samtstern** [comment]
@ahmedosama5200 we don't plan to allow a UI like this in FirebaseUI.  FirebaseUI is meant to be a good starting point for apps that want a nice sign-in UI in their app, it can't support every sign-in UI pattern that people want though!

**Comment by ahmedosama5200** [comment]
It can't support every possible pattern, That's for sure. But, This pattern is really really common in many apps, so, why not support it. In addition, you only need to provide three methods in your custom auth picker, to link the ids of `sign in`, `create account` and `forgot passowrd` buttons.

**Comment by samtstern** [comment]
I’m sorry but we won’t support this UI pattern in FirebaseUI

**Comment by ahmedosama5200** [comment]
Ok, I understand. Thanks
