### ISSUE TITLE
How to load certain number of childs with FirebaseRecyclerViewAdapter

### ISSUE THREAD

**Issue by santoshgistto** [firebase/FirebaseUI-Android#18]
Ex: lets say GeoFire returns me 50 keys, i need to iterate the key list, how we can achieve this.
please help me out

**Comment by puf** [comment]
Can you give a code sample of what you're trying to do and where you're having trouble (see http://stackoverflow.com/help/mcve)? I see no relation between FirebaseUI and Geofire, but might well be missing something crucial.

**Comment by santoshgistto** [comment]
Hi @puf  i want to load the data depending on the location.
Ex: hotels
how we can achieve with FirebaseRecyclerViewAdapter ?

**Comment by puf** [comment]
Geofire is a library on top of Firebase. It fires its own events when keys enter and exit from the range that you query for. FirebaseUI does not respond to these events.

So you'll have to create your own adapter class that does the same as FirebaseRecyclerViewAdapter, but then for Geofire events. When `key_entered` fires you add the item to the underlying array, when `key_exited` fires you remove the item from the array and when `key_moved` fires you move it to its (potentially) new spot in the array.

https://github.com/firebase/geofire-js#geoqueryoneventtype-callback

**Comment by santoshgistto** [comment]
@puf  thanks done :+1:
