### ISSUE TITLE
Is possible order the data(Object) obtained from Firestore by the @Exclude field?

### ISSUE THREAD

**Issue by LukeDaniel16** [firebase/FirebaseUI-Android#1802]
### Step 2: Describe your environment

  * Android device: J6+
  * Android OS version: 9.0
  * Google Play Services version: Updated
  * Firebase/Play Services SDK version: Updated
  * FirebaseUI version: Latest release
  
### Step 3: Describe the problem:
I have a list of documents published on Firestore Database, i need order the Query with an Field that not exist in Firestore, i mark this field with @Exclude on my Class Model, then, he's not hosted on Firestore when the Query push all data, i define them field in client side on Execution time (this field is location of the User current to user that publish the Object (data) on Firestore);
  
  
#### Expected Results:

I hope I can sort a list of objects obtained from Firestore by the an field Excluded from Firestore side, to orderBy with the field inserted on document published on firestore is necessary just put command "orderBy" in the end of Query object, this is simple, but, orderBy the field that not published on firestore looks impossible;
  
#### Relevant Code:

  ```
query = anyCollectionReference.orderBy(field, Query.Direction.DESCENDING).limit(100); // This is example of ordenate by the field hosted on document on Firestore

  ```

**Comment by samtstern** [comment]
@LukeDaniel16 sorry we don't support custom sort orders in FirebaseUI, we only support the sort order returned from the database.  Anything else would make the code much more complex as we'd have to update the sort after each child event.

I suggest forking the library if you want that kind of behavior!

**Comment by LukeDaniel16** [comment]
Allright, i'll try other method, thanks by your attention.
