### ISSUE TITLE
Custom Filters on List Items

### ISSUE THREAD

**Issue by Cosmopal** [firebase/FirebaseUI-Android#1804]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 2: Describe your environment

  * Android device: Redmi Note 4
  * Android OS version: Android 7.0
  * Google Play Services version: 6.04
  * Firebase/Play Services SDK version: 21.4.3 (firestore)
  * FirebaseUI version: 6.2.0
  
### Step 3: Describe the problem:
Based on need of the user, I need to filter the items in the list based on mutliple criterion. I can't use the filter operations on queries is because 
(a) Firestore order queries require me to sort by queried field first. So if I need to filter by, say, 'id' of the object then I'll have to sort the data by 'id' first. It practically makes the other ordering irrelevant! 
(b) It unnecessarily forces me to make a whole new query where all I need to do is show/hide list items. 
(c) This criterion may later be based on fields that are not directly stored on firebase but are computed when I convert the stored data to my object. 

So could there be a way to apply a custom filter on the adapter? All implementations of filters on recyclerview I saw modify the data itself to exlcude filtered items. An alternate approach is to just hide the view, but that would unncessarily put load on the system as layout rendering is very heavy!

This is feature request so I have no code or steps to reproduce

**Comment by samtstern** [comment]
@Cosmopal this should be fairly simple to do when creating your subclass of the recycler adapter.  In `onBindViewHolder` you could choose to hide the item entirely if it doesn't match your custom filter:

```java
FirestoreRecyclerAdapter adapter = new FirestoreRecyclerAdapter<Chat, ChatHolder>(options) {
    @Override
    public void onBindViewHolder(ChatHolder holder, int position, Chat model) {
        if (!MyCustomFilter.matches(model)) {
          // Set the root view of the ChatHolder to visibility "GONE"!
        }
    }

    @Override
    public ChatHolder onCreateViewHolder(ViewGroup group, int i) {
        // ...
    }
};
```

This is not a feature we're going to add as a top-level thing to FirebaseUI, it will have to be done within your own subclass.

**Comment by Cosmopal** [comment]
@samtstern but the view still exists and would use up system resources, right?

**Comment by samtstern** [comment]
@Cosmopal yes but it will be negligible
