### ISSUE TITLE
Firebase Auth - No Provider Data on Android

### ISSUE THREAD

**Issue by Queskr** [firebase/FirebaseUI-Android#181]
Hi,

I've upgraded to the 9.0.2 SDK version following the [solved auth problem on Android devices](https://status.firebase.google.com/incident/Authentication/16001). My FirebaseUI-Android package version is 0.4.0 and my device's Google Play Services version is 9.0.83.

Following the fix, my app does authenticate, but alas it does not populate any provider data automatically (see snapshort below), nor does it provide it when called via getProviderData().

![snapshot](https://cloud.githubusercontent.com/assets/17469969/15883888/0bc7a162-2d55-11e6-9b97-5eb5f84589fe.PNG)

When getProviderData().toString() is called, I get: 
com.google.android.gms.internal.zzadf@3a3aa0b
com.google.android.gms.internal.zzadf@a00f0e8

It does give the provider itself when getProviders().toString() is called (e.g. "google.com").

Thanks, 
Yohay

**Comment by tikurahul** [comment]
[FirebaseUser#getProviderData](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser) returns a list of [UserInfo](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/UserInfo).

Can you try calling methods on the instance of `UserInfo` that you get back ? Also bear in mind that some of the fields in `UserInfo` are nullable, and dependent on the permissions associated to the underlying `idToken` or `accessToken` used to sign in.

You can also try logging in with other providers.

**Comment by Queskr** [comment]
OK, there's some progress :)

I ran the below:
FirebaseUser logged_user = FirebaseAuth.getInstance().getCurrentUser();
        Log.d("Queskr", "UserInfo name: "+logged_user.getDisplayName());
        Log.d("Queskr", "UserInfo email: "+logged_user.getEmail());
        Log.d("Queskr", "UserInfo photo: "+logged_user.getPhotoUrl());
        Log.d("Queskr", "UserInfo ProviderData: "+logged_user.getProviderData().toString());

For both Google and FB login, I get the display name and the photo URL, but for some reason I don't get the email (which is most important to me). 

I've also ran through the list of UserInfo provided by getProviderData and it shows the same thing (name is available, as well as photo url, but no email).

You wrote that some details are dependent on the idToken and accessToken - does this apply to email as well? how can I influence the tokens?

Thanks!

**Comment by jasoncheng** [comment]
@Queskr  I spent two days on this, let me share my experience, hope can help :)

Base on firebase sdk 9.0.x

It's all about new config on firebase new console -> auth -> enable/disable unique email for multi accounts.

For legacy firebase.com, they use UID like "google:12321323" or "facebook:2312312332", so we can create same email with different accounts from different provider.

For new firebase console:
1. If you enable unique email address, new firebase will automatic generate UID like "7qDrrlmAnQOSeQD4EsnIYdSOpe13", and you can get email from FirebaseUser.getEmail without any problem.

2. If you enable legacy behavior, then you won't be able get email from FirebaseUser.getEmail, but you still can get user email through using AccessToken(fb) or GoogleSignInAccount object (google)

[ref](https://support.google.com/firebase/answer/6400716)

**Comment by Queskr** [comment]
Thanks Jason, it worked!

I needed to enabe unique email and delete all previously defined users, but now it works :)

**Comment by davidgcalle** [comment]
@jasoncheng Hi, could u care to specify how get the user email through AccesToken and GoogleSignInAccount, need to use other libraries?

**Comment by xiaofanwu** [comment]
cordovaoath is a good library :)
