### ISSUE TITLE
PR for auth/README.md code example fix.

### ISSUE THREAD

**Issue by carrizo** [firebase/FirebaseUI-Android#1816]
I have a small patch for  `auth/README.md`, looks like `getIntent().getExtras().getString(ExtraConstants.EMAIL_LINK_SIGN_IN)` doesn't work anymore, I had to change it to `getIntent().getData().toString()` and also there's an error in the null check of the example.

Here's how firebase auth gets the link internally:
https://github.com/firebase/FirebaseUI-Android/blob/6d41fb2992a7ce01d7f38e8451805e49e96e5628/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L238

My patch is here:
https://github.com/carrizo/FirebaseUI-Android/commit/db9507c1e0a97352755a72f71d50c67b2c954584

Does it look fine for a PR?

**Comment by samtstern** [comment]
@carrizo thanks for asking!  Happy to accept your PR.
