### ISSUE TITLE
I found solution to delete data/document (in database) when we using Paginate

### ISSUE THREAD

**Issue by LukeDaniel16** [firebase/FirebaseUI-Android#1818]
Hi, i wanted delete data when the user click on button delete, but, the Paginate not have `getSnapshots()` method to getId from document and delete data, if you are interested in deleting a document from the database even using Pagination, you can do the following:

Steps:
**1. In your onBindViewHolder on your adapter instantiate or class direct, you can access the method `getCurrentList();`

2. Using `getCurrentList()`, you can get the currently position from your data, example:
When the user click in a some button, your action(setOnClick...) is:
`getCurrentList().get(positon);`
3. position is the integer var from your onBindViewHolder, and returns the index of your element of bindViewHolder, then,
through this, you can get `DocumentReference` and delete the document clicked
4.To delete document, you just need now the DocumentReference, example
`DocumentReference doc = FirebaseFirestore.getInstance().collection("Collection").document(getCurrentList().get(position).getId());
and... delete: doc.delete();` **
After this, you just `notifyDataSetChanged` or modify the visualization into your RecyclerView.

**Comment by samtstern** [comment]
@LukeDaniel16 thank you for sharing your solution with everyone!

**Comment by LukeDaniel16** [comment]
To complement, if you remove from visual UI(client view), you can call (after successfull delete from database/firestore) `getCurrentList().remove(position); notifyItemRemoved(position);`, the clicked item is removed from layout, remembering to that this works fine it is necessary that in your **adapter**, you need has override the methods to:

`
          @Override
            public long getItemId(int position) {
                return position;
            }
`
`
            @Override
            public int getItemViewType(int position) {
                return position;
            }
`

**Comment by LukeDaniel16** [comment]
After remove from database/firestore, to update the screen UI, just need `refresh();` `notifyItemRemoved(position);` after successfull delete operation.

And, in your adapter instantiate or construct, need override two methods, `getItemId` and `getItemViewType` to:
`@Override
            public long getItemId(int position) {
                return position;
            }
`
`           @Override
            public int getItemViewType(int position) {
                return position;
            }
`

Just it and your visual UI is updated and the data deleted of Database disappear.
