### ISSUE TITLE
Phone authentication sms message is different with template

### ISSUE THREAD

**Issue by iqbalza** [firebase/FirebaseUI-Android#1822]
In the firebase console the template for sms message is: %LOGIN_CODE% is your verification code for %APP_NAME%.
But when i test it with Indonesian phone number, the message was only this "Enter:(code)". Is this because the app is still in development or  was this the template for Indonesian number?

**Comment by samtstern** [comment]
@iqbalza this doesn't sound like it's an issue with FirebaseUI.  For help debugging this SMS message please reach out to Firebase support:
https://firebase.google.com/support
