### ISSUE TITLE
Endless Scrolling ListView (оr pagination)

### ISSUE THREAD

**Issue by proudUzbek** [firebase/FirebaseUI-Android#183]
I need endless scrolling list view. How can i solve it?

Sorry for my bad english, have a nice day!!

**Comment by tikurahul** [comment]
Look at the [RecyclerView](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.html) and [RecyclerView.Adapter](https://developer.android.com/reference/android/support/v7/widget/RecyclerView.Adapter.html). 

There is some great documentation [here](https://developer.android.com/training/material/lists-cards.html).
