### ISSUE TITLE
Orientation lock on phones

### ISSUE THREAD

**Issue by dimipaun** [firebase/FirebaseUI-Android#1834]
There are many times when you'd like to lock the activities to portrait on the phone, but not on a tablet. For ex:
https://stackoverflow.com/questions/50596476/disable-landscape-orientation-for-phones-but-allow-for-tablets/50596650

This has to be done through code it seems.

Would a flag controlling this behavior be acceptable? E.g. `setLockOrientationToPortraitOnSmallDevices(true)`

**Comment by samtstern** [comment]
@dimipaun thanks for the feedback.  I'm open to something like this but I think it would just be `setLockOrientation(...)` and I'd leave it up to the developer to do conditional logic to only set that on small devices.  What do you think?

**Comment by samtstern** [comment]
This has been released in version `6.4.0`
