### ISSUE TITLE
How to catch the exception if a user has been disabled from Firebase UI

### ISSUE THREAD

**Issue by Paul9834** [firebase/FirebaseUI-Android#1835]
I'm trying to catch the following exception so I can inform the user that their account has been disabled, but I haven't been able to achieve it. I tried try/catch, but didn't work. I am using Firebase UI to login users with email and password, Google Sign-In, any ideas?

`2020-08-30 15:28:01.737 30855-30855/com.paul9834.clubapp E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.FirebaseUiException: The user account has been disabled by an administrator.`

` startActivityForResult(AuthUI.getInstance()
                    .createSignInIntentBuilder()
                    .setTosAndPrivacyPolicyUrls(
                        "https://example.com/terms.html",
                        "https://example.com/privacy.html")
                     .setTheme(R.style.Theme_ClubApp)
                    .setLogo(R.drawable.logo)
                    .setIsSmartLockEnabled(false)
                    .setAvailableProviders(providers)
                    .build(),AUTH_REQUEST_CODE)`

**Comment by rosariopfernandes** [comment]
@Paul9834 errors can be handled in your `onActivityResult()` method by checking the response code, as shown in the section [Handling the sign-in response](https://developers.google.com/android/reference/com/google/android/gms/auth/GoogleAuthUtil#public-static-string-gettoken-context-context,-string-accountname,-string-scope).

**Comment by samtstern** [comment]
@rosariopfernandes thanks for responding, I think you mean to paste this link:
https://github.com/firebase/FirebaseUI-Android/tree/master/auth#handling-the-sign-in-response

But yeah your answer is correct.

**Comment by rosariopfernandes** [comment]
@samtstern clipboard error. Thanks, that's the one.

**Comment by Paul9834** [comment]
> @rosariopfernandes thanks for responding, I think you mean to paste this link:
> https://github.com/firebase/FirebaseUI-Android/tree/master/auth#handling-the-sign-in-response
> 
> But yeah your answer is correct.

I just carried out the tests with ActivityOnResult, doing the Google Sign-In authentication, the account is disabled, I only receive the generic exception, but not the exception from this. It has not worked

**Comment by Paul9834** [comment]
Thanks!
