### ISSUE TITLE
Why firebase authUI can't use google account login now, but can login before?

### ISSUE THREAD

**Issue by Squall-Huang** [firebase/FirebaseUI-Android#1837]
Why firebase authUI can't use google account login now, but can login before? Use "Sign in with email" can login but use "Sign in with Google" failed now. Both sign in function were normal before.

https://stackoverflow.com/questions/63970830/why-firebase-authui-cant-use-google-account-login-now-but-can-login-before

**Comment by malcolmdeck** [comment]
Hey there!

Please provide a code sample that reproduces this issue, as well as a stack trace with the full error for when this happens to you. With that information, we should better be able to help you :)

Thanks,
~Malcolm

**Comment by Squall-Huang** [comment]
Hi Malcolm:

This is my code.
https://gist.github.com/Squall-Huang/34e0e658370ddf0605f413b7b2b7e653

regards

Malcolm Deck <notifications@github.com> 於 2020年9月22日 週二 上午3:01寫道：

**Comment by samtstern** [comment]
@Squall-Huang error code "10" is `DEVELOPER_ERROR", here are some existing links on the topic that I found:
https://github.com/googlesamples/google-services/issues/360#issuecomment-381648685
https://medium.com/@alif.valutac/how-to-fix-error-10-google-sign-in-problem-410cba2a9735
https://stackoverflow.com/q/51314476/324977

Please double-check your SHA1 registration as well as all other configuration.  This is unfortunately not a bug in FirebaseUI

**Comment by Squall-Huang** [comment]
Hi Sam:
Thank you for your reply.
I still don't know what should I do?
I don't understand SHA-1's running theory.
I don't know Stackoverflow's 3 Key method how to implement it?



Sam Stern <notifications@github.com> 於 2020年9月22日 週二 下午7:37寫道：

**Comment by Squall-Huang** [comment]
Hi Sam:
Below are my this project's API Key and SHA-1.
Could you tell me what should I do?

[image: firebase1.png]
[image: firebase2.png]
[image: GoogleCloud.png]

Sam Stern <notifications@github.com> 於 2020年9月22日 週二 下午7:37寫道：

**Comment by Squall-Huang** [comment]
Hi Sam:
I followed your link's method to try and now can login with google account.
Very thank you for your help!!😃😄

Regards
Squall

Sam Stern <notifications@github.com> 於 2020年9月22日 週二 下午7:37寫道：
