### ISSUE TITLE
Link Auth Accounts

### ISSUE THREAD

**Issue by branflake2267** [firebase/FirebaseUI-Android#184]
Provide the ability to link multiple accounts. Is this even possible? 

The goal, login to Google and then come back and login to facebook (or visa versa), so I can access features from both Google and Facebook services.

**Comment by samtstern** [comment]
@branflake2267 account linking is definitely possible with Firebase Authentication but it's not yet available in Firebase UI.

If you'd like to attempt it yourself, you can get started here: https://firebase.google.com/docs/auth/android/account-linking

I am going to close this issue as we are already tracking this feature request elsewhere.

**Comment by tchkreddy** [comment]
Is the account linking available in Firebase Auth UI by now? I dont see any reference doc.

**Comment by samtstern** [comment]
It is not yet available, see #1171
