### ISSUE TITLE
Android Studio issue after updating to Android Studio 4.1

### ISSUE THREAD

**Issue by lakmall** [firebase/FirebaseUI-Android#1845]
In flutter doctor it shows that Android Studio (Not installed) even thought i have completely installed the AS with flutter and dart plugins. This problem actually appeared after updating the AS  4.1. Then I uninstalled the AS and then installed the previous version.then problem solved. what could be the reason for that. is that a problem of android Studio 4.1.

**Comment by samtstern** [comment]
@lakmall this doesn't seem to have anything to do with FirebaseUI or Firebase, sounds like an issue with Flutter.  Please report this elsewhere.
