### ISSUE TITLE
[FR] Make dependency on play-services-auth optional

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1858]
See #1856 for a similar request.

As of `firebase-auth` version `20.0.0` (`firebase-bom` version `26.0.0`) there is no longer any Firebase dependency on Play services. However FirebaseUI still depends on `play-services-auth` for Google Sign In, which does have this dependency.

We need to refactor the library to make the dependency optional at runtime without crashing.

**Comment by wangjiejacques** [comment]
Hi @samtstern , do you have a plan about 7.1.0, will it be available in some days, weeks or months?

**Comment by samtstern** [comment]
@wangjiejacques we don't have any strict timelines here but I'd say "months" is the best estimate.

**Comment by samtstern** [comment]
@wangjiejacques well that was easier than I thought!  As of version `7.1.0` you should be able to use almost all features on devices without Play services.  You just need to make sure you're not using Google Sign In or SmartLock (saving credentials / hint selector) as those have hard dependencies.
