### ISSUE TITLE
Facebook sign in error

### ISSUE THREAD

**Issue by vinaybn92** [firebase/FirebaseUI-Android#186]
If the phone does not have the facebook app and is not signed in, it shows you a "You are not logged in: You are not logged in. Please log in and try again." error message instead of a dialog that lets you sign in to your facebook account like most other applications.

**Comment by sreekanth-krishnan** [comment]
I too had this issue. But was because I didn't configure my android app in my facebook app settings. Error gone when I added those details in the app dashboard/settings

**Comment by samtstern** [comment]
@all I am going to close this issue since there is not a lot to go on and I believe @sreekanth-krishnan is correct that this is caused by a lack of proper Facebook configuration.
