### ISSUE TITLE
Auth provider button icon

### ISSUE THREAD

**Issue by AryanNajafi** [firebase/FirebaseUI-Android#1860]
Due to AppCompat now supports vector compound drawables on pre-L devices, Auth provider buttons could be just Button instead of custom View class SupportVectorDrawablesButton. Also uses of SupportVectorDrawablesButton in sample app and warning notes about not using this View class could be removed for less confusion.

**Comment by samtstern** [comment]
@AryanNajafi thanks for reporting this!  Would you like to submit a Pull Request to fix this?  If so make sure to target the `version-7.0.0-dev` branch.

**Comment by samtstern** [comment]
This has been released in version `7.0.0`
