### ISSUE TITLE
Two queries is not support Firestore paging adaper

### ISSUE THREAD

**Issue by sumonshil** [firebase/FirebaseUI-Android#1862]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: ___Mi A3__
  * Android OS version: ___10__
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: _firestore:6.4.0___
  
### Step 3: Describe the problem:

When I use two query (whereEqualTo() and orderBy()) In firestore paging adaper recyclerview shows null.when I use only one query then it's work fine.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem

Query query= FirebaseFirestore.getInstance()
                 . collection ("ImageFeed")
                 . whereEqualTo ("uid",uId)
                  . orderBy("mTimestamp", Query.Direction.DESCENDING):

  ```

**Comment by laurentiu-git** [comment]
Do you get this error in logcat?
> The query requires an index. You can create it here :

**Comment by sumonshil** [comment]
**I couldn't find log error**

but when I using two query it's onLoadingStateChanged state says ERROR..

`  com.google.firebase.firestore.Query query = FirebaseFirestore.getInstance()
                .collection("ImageFeed")
                .whereEqualTo("uid",FirebaseAuth.getInstance().getCurrentUser().getUid())
                .orderBy("mTimestamp", com.google.firebase.firestore.Query.Direction.DESCENDING);
`
when I use only one of them it's work fine. I don't understand what is the error here please help me..

**my total code is**

`  com.google.firebase.firestore.Query query = FirebaseFirestore.getInstance()
                .collection("ImageFeed")
                .whereEqualTo("uid",FirebaseAuth.getInstance().getCurrentUser().getUid())
                .orderBy("mTimestamp", com.google.firebase.firestore.Query.Direction.DESCENDING);

        PagedList.Config config = new PagedList.Config.Builder()
                .setEnablePlaceholders(false)
                .setInitialLoadSizeHint(6)
                .setPageSize(5)
                .build();

        FirestorePagingOptions<ImageFeedsModel> options = new FirestorePagingOptions.Builder<ImageFeedsModel>()
                .setLifecycleOwner(this)
                .setQuery(query, config, ImageFeedsModel.class)
                .build();


        adapter = new FirestorePagingAdapter<ImageFeedsModel, ImageFeedViewHolder>(options) {
            @Override
            protected void onBindViewHolder(@NonNull ImageFeedViewHolder holder, int position, @NonNull ImageFeedsModel model) {
                holder.setView(model.getpId(),model.getcT(),model.getPic(),model.gettM(),model.gettH(),model.getY(),model.getM(),model.getD(),model.getUid());

                final String CurrentUser= FirebaseAuth.getInstance().getCurrentUser().getUid();
                final String postKey=model.getpId();

                holder.setLikeButtonStatus(postKey);

                holder.commentBtn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Intent intent=new Intent(holder.commentBtn.getContext(), CommentActivity.class);
                        intent.putExtra("postKey",postKey);

                        Pair[] pairs=new Pair[1];
                        pairs[0]=new Pair<View,String>(holder.commentBtn,"commentTs");

                        if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP){
                            ActivityOptions optionsTS= ActivityOptions.makeSceneTransitionAnimation((Activity) holder.commentBtn.getContext(),pairs);
                            holder.itemView.getContext().startActivity(intent,optionsTS.toBundle());
                        }else {
                            holder.itemView.getContext().startActivity(intent);
                        }

                    }
                });
                holder.likeBtn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        likechecker=true;
                        final DatabaseReference likeRef= FirebaseDatabase.getInstance().getReference("likes");
                        likeRef.addValueEventListener(new ValueEventListener() {
                            @Override
                            public void onDataChange(@NonNull DataSnapshot snapshot) {
                                if (likechecker.equals(true)){
                                    if (snapshot.child(postKey).hasChild(CurrentUser)){
                                        likeRef.child(postKey).child(CurrentUser).removeValue();
                                        likechecker=false;
                                    }else {
                                        likeRef.child(postKey).child(CurrentUser).setValue(true);
                                        likechecker=false;
                                    }
                                }
                            }

                            @Override
                            public void onCancelled(@NonNull DatabaseError error) {

                            }
                        });
                    }
                });

            }

            @NonNull
            @Override
            public ImageFeedViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
                return new ImageFeedViewHolder(LayoutInflater.from(parent.getContext()).inflate(R.layout.image_feeds,parent,false));
            }


            @Override
            protected void onLoadingStateChanged(@NonNull LoadingState state) {
                super.onLoadingStateChanged(state);
                switch (state) {
                    case LOADING_INITIAL:
                        // The initial load has
                        swipeRefreshLayout.setRefreshing(true);
                        // ...
                        break;
                    case LOADING_MORE:
                        // The adapter has started to load an additional page
                        progressBarI.setVisibility(View.VISIBLE);                        // ...
                        break;
                    case LOADED:
                        // The previous load (either initial or additional) completed
                        swipeRefreshLayout.setRefreshing(false);
                        progressBarI.setVisibility(View.INVISIBLE);                        // ...

                        // ...
                        break;
                    case FINISHED:
                        progressBarI.setVisibility(View.INVISIBLE);                        // ...
                        break;
                    case ERROR:
                        // The previous load (either initial or additional) failed. Call
                        //adapter.retry();
                        Toast.makeText(getContext(),"Failed"+ state,Toast.LENGTH_SHORT).show();
                        //swipeRefreshLayout.setRefreshing(true);
                        // the retry() method in order to retry the load operation.
                        // ...
                        break;
                }
            }


        };

        imageFeeds.setAdapter(adapter);

        swipeRefreshLayout.setOnRefreshListener(new SwipeRefreshLayout.OnRefreshListener() {
            @Override
            public void onRefresh() {
                adapter.refresh();
                swipeRefreshLayout.setRefreshing(false);
            }
        });
`

**Comment by samtstern** [comment]
@sumonshil please use the issue template when filing issues, you have not provided any information to indicate that this is a bug in FirebaseUI.

In the `onError` method of the adapter you can get the error, please show the message.  It probably contains the solution.

**Comment by sumonshil** [comment]
My problem sloved by Firestore indexes
