### ISSUE TITLE
Getting JsonParsing error when upgraded to 7.0 

### ISSUE THREAD

**Issue by rshibley** [firebase/FirebaseUI-Android#1867]
I upgraded to 7.0 and I am receiving exceptions when compiling with 

  shrinkResources true
  minifyEnabled true

What are the proguard rules that need to be added. Once I compile with Proguard, it throws json parsing exception. 

This did not happen with 6.4.0

**Comment by samtstern** [comment]
@rshibley please use the issue template when filing issues, what you've posted is not nearly enough to help you.  What JSON error do you get? When do you get it? How can I reproduce it?
