### ISSUE TITLE
No virtual method verifyPhoneNumber

### ISSUE THREAD

**Issue by colorgold** [firebase/FirebaseUI-Android#1868]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: __motorola one vision___
  * Android OS version: ___10__
  * Google Play Services version: ___4.3.4__
  * Firebase/Play Services SDK version: __19.0.0___
  * FirebaseUI version: __6.4.0__
  
### Step 3: Describe the problem:
Since I upgraded to `com.google.firebase:firebase-auth:20.0.1`, my app crashes when users try to register/login using their phone numbers
#### Steps to reproduce:

  1. __Create a sign in intent builder with phone provider___
  2. __Choose phone number___
  3. ___App crashes when phone number selected__
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  ```
Fatal Exception: java.lang.NoSuchMethodError
No virtual method verifyPhoneNumber(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/Executor;Lcom/google/firebase/auth/PhoneAuthProvider$OnVerificationStateChangedCallbacks;Lcom/google/firebase/auth/PhoneAuthProvider$ForceResendingToken;)V in class Lcom/google/firebase/auth/PhoneAuthProvider; or its super classes (declaration of 'com.google.firebase.auth.PhoneAuthProvider' appears in base.apk!classes2.dex)

com.firebase.ui.auth.ui.phone.PhoneNumberVerificationHandler.verifyPhoneNumber (PhoneNumberVerificationHandler.java:32)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.onNext (CheckPhoneNumberFragment.java:164)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.start (CheckPhoneNumberFragment.java:155)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment.access$100 (CheckPhoneNumberFragment.java:37)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment$2.onSuccess (CheckPhoneNumberFragment.java:113)
com.firebase.ui.auth.ui.phone.CheckPhoneNumberFragment$2.onSuccess (CheckPhoneNumberFragment.java:110)
com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged (ResourceObserver.java:69)
com.firebase.ui.auth.viewmodel.ResourceObserver.onChanged (ResourceObserver.java:19)
```
#### Expected Results:

  * What did you expect to happen?
  I expected to get a text message with a verification number.
#### Relevant Code:

  ```
startActivityForResult(
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(phoneProvider)
                            .setTheme(R.style.BlankTheme)
                            .build(),REQUEST_SIGN_IN
            );
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@colorgold FirebaseUI 6.4.0 is only compatible with `firebase-auth` versions 19.x and below.  If you want to use `firebase-auth` 20.x you need to upgrade to FirebaseUI 7.0.0 or higher.

The main breaking changes in `firebase-auth` 20.0.0 were around phone auth, that's why you see this crash.

**Comment by colorgold** [comment]
> @colorgold FirebaseUI 6.4.0 is only compatible with `firebase-auth` versions 19.x and below. If you want to use `firebase-auth` 20.x you need to upgrade to FirebaseUI 7.0.0 or higher.
> 
> The main breaking changes in `firebase-auth` 20.0.0 were around phone auth, that's why you see this crash.

I forgot to check for FirebaseUI update and was only upgrading the auth and database. Thank you.
