### ISSUE TITLE
Still show dialog about "won't run without Google Play Services" when device has not GSM using 7.1 

### ISSUE THREAD

**Issue by 15563988825** [firebase/FirebaseUI-Android#1871]
when i using sdk 7.1
there still show dialog as below 

in gradle:
    implementation platform('com.google.firebase:firebase-bom:26.0.0')
    implementation 'com.google.firebase:firebase-core'
    implementation 'com.google.firebase:firebase-firestore'
    implementation 'com.google.firebase:firebase-storage'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-messaging'
    implementation 'com.firebaseui:firebase-ui-auth:7.1.0'

incode:
AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setAvailableProviders(listOf(
                                    AuthUI.IdpConfig.EmailBuilder().build()))
                            .build(),

but i got a dialog like this whithout GSM on device
![device-2020-11-21-161628](https://user-images.githubusercontent.com/4360198/99871483-19e0d600-2c16-11eb-9592-7bde5964abf2.png)

**Comment by wangjiejacques** [comment]
You need to disable the SmartLock by `setIsSmartLockEnabled(false)`

**Comment by samtstern** [comment]
Thanks for following up!  Very glad to know it worked.
