### ISSUE TITLE
Phone Login Pre-built UI Auto-retrieval

### ISSUE THREAD

**Issue by colorgold** [firebase/FirebaseUI-Android#1879]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: ___LGE K31__
  * Android OS version: __10___
  * Google Play Services version: __19.0.0___
  * Firebase/Play Services SDK version: __4.3.4___
  * FirebaseUI version: __7.1.0__
  
#### Steps to reproduce:

  1. __Choose sign in with phone provider___
  2. ___select phone number__
  3. __SMS received but not retrieved automatically__
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  When the SMS is received, it won't detect the incoming verification SMS and verify user automatically
#### Expected Results:

  * What did you expect to happen?
  On FirebaseUI version 6.3.0 the SMS was detected and the user would be verified automatically. On the 7.1.0 version, however, the user has to input the verification code. 
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
List<AuthUI.IdpConfig> phoneProvider = Collections.singletonList(
                new AuthUI.IdpConfig.PhoneBuilder().build());
startActivityForResult(
                    AuthUI.getInstance().createSignInIntentBuilder()
                            .setAvailableProviders(phoneProvider)
                            .setTheme(R.style.BlankTheme)
                            .build(),REQUEST_SIGN_IN
            );
  ```

**Comment by trueman1** [comment]
Facing the same issue on 7.1.1 running on Android 10

**Comment by BertAnthonyRochester** [comment]
> Welcome to FirebaseUI and thanks for submitting an issue!
> 
> Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.
> 
> If not, please feel free to fill in the following info so we can help faster!
> ### Step 1: Are you in the right place?
> 
>     * For issues or feature requests related to the code **in this repository** file a GitHub issue.
> 
>     * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
> 
>     * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
> 
>     * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)
> 
> 
> ### Step 2: Describe your environment
> 
>     * Android device: _**LGE K31**
> 
>     * Android OS version: **10**_
> 
>     * Google Play Services version: **19.0.0**_
> 
>     * Firebase/Play Services SDK version: **4.3.4**_
> 
>     * FirebaseUI version: **7.1.0**
> 
> 
> ### Step 3: Describe the problem:
> #### Steps to reproduce:
> 
>     1. **Choose sign in with phone provider**_
> 
>     2. _**select phone number**
> 
>     3. **SMS received but not retrieved automatically**
> 
> 
> #### Observed Results:
> 
>     * What happened?  This could be a description, `logcat` output, etc.
>       When the SMS is received, it won't detect the incoming verification SMS and verify user automatically
> 
> 
> #### Expected Results:
> 
>     * What did you expect to happen?
>       On FirebaseUI version 6.3.0 the SMS was detected and the user would be verified automatically. On the 7.1.0 version, however, the user has to input the verification code.
> 
> 
> #### Relevant Code:
> 
> ```
> // TODO(you): code here to reproduce the problem
> List<AuthUI.IdpConfig> phoneProvider = Collections.singletonList(
>               new AuthUI.IdpConfig.PhoneBuilder().build());
> startActivityForResult(
>                   AuthUI.getInstance().createSignInIntentBuilder()
>                           .setAvailableProviders(phoneProvider)
>                           .setTheme(R.style.BlankTheme)
>                           .build(),REQUEST_SIGN_IN
>           );
> ```

**Comment by build3r** [comment]
Having the sample Problem on Android 9, 8, 8.1 etc. 
Also during verification a browser is being opened to check for robot. Which breaks our apps UX. And after verification the OTP is not prefilled.

**Comment by colorgold** [comment]
I am using the following versions for now:
```
implementation 'com.google.firebase:firebase-auth:19.4.0'
implementation 'com.firebaseui:firebase-ui-database:6.3.0'
'com.firebaseui:firebase-ui-auth:6.4.0'
```

These are working well together, auto-retrieval and all

**Comment by Oleh-Havrysh** [comment]
Looks like Firebase started to include app token a few days ago, so now latest version of SDK is able to retrieve SMS

![image](https://user-images.githubusercontent.com/16573512/102012537-bf89ef80-3d53-11eb-87c1-78b5d005375b.png)

**Comment by malcolmdeck** [comment]
We rolled out a flag on our backend - this should be resolved. Please re-open if the issue persists.
