### ISSUE TITLE
Error:Could not find com.google.firebase:firebase-database:9.0.2

### ISSUE THREAD

**Issue by billyjoker** [firebase/FirebaseUI-Android#188]
Hi, i've just tried open your project but it launchs a compile error:

```
Error:Could not find com.google.firebase:firebase-database:9.0.2.
Required by:
    FirebaseUI-Android-master:app:unspecified
    FirebaseUI-Android-master:app:unspecified > com.firebaseui:database:0.4.1
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

I've tried also including the required dependency with no success.

**Comment by im182cm** [comment]
1. Open "Android SDK Manager"
2. install "Android Support Library"

this helped me work out.

or you should install other SDK in Android SDK Manager that looks like related with Firebase.

**Comment by samtstern** [comment]
@billyjoker this should be fixed by installing the latest version of Google Play Services and Google Repository in the Android SDK manager.

Please see this answer for the general process: http://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0/
