### ISSUE TITLE
ERROR_MISSING_CLIENT_IDENTIFIER

### ISSUE THREAD

**Issue by AnYuer** [firebase/FirebaseUI-Android#1882]
您好，接入电话验证码发送的时候 报了这个错误提示：ERROR_MISSING_CLIENT_IDENTIFIER
This request is missing a valid app identifier, meaning that neither SafetyNet checks nor reCAPTCHA checks succeeded. Please try again, or check the logcat for more details.

请问该怎么解决，万分感激

**Comment by samtstern** [comment]
@AnYuer please use the issue template when filing an issue, this is not enough information to debug.
