### ISSUE TITLE
Email link sign in button not shown when using custom layout

### ISSUE THREAD

**Issue by rstjepanj** [firebase/FirebaseUI-Android#1885]
### Step 1: Are you in the right place?

I believe so. Also, this problem seems to be a regression as it was already described and resolved in [1658](https://github.com/firebase/FirebaseUI-Android/issues/1658)

### Step 2: Describe your environment

  * Android device: Pixel_3a_API_30_x86
  * Android OS version: 11
  * Google Play Services version: 19.0.0
  * Firebase/Play Services SDK version: 20.0.0
  * FirebaseUI version: 7.1.1

### Step 3: Describe the problem:

When using custom layout and email link sign in the email button is not shown.

#### Steps to reproduce:

  1. Pull latest version of firebase-ui
  2. Create new firebase project with google sign in provider and email link provider 
  3. Download google-services.json and put it in app directory
  4. Run the application and select AuthUI demo with layout radio button set to custom and providers set to Google and Email link
![Screenshot 2020-12-21 at 17 42 32](https://user-images.githubusercontent.com/26767158/102801905-2e032900-43b6-11eb-9a12-b19fd69ac00e.png)
  
#### Observed Results:

The Email sign in button (textView) is not shown
![Screenshot 2020-12-21 at 17 43 02](https://user-images.githubusercontent.com/26767158/102802006-4f641500-43b6-11eb-8b05-bfb1ed06571a.png)
  
#### Expected Results:

 I expected the email button to be shown
  
#### Relevant Code:

No code changes necessary.

#### Possible fix

Adding a new method setEmailLinkButtonId in [AuthMethodPickerLayout](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/AuthMethodPickerLayout.java) and removing the method [providerOrEmailLinkProvider](https://github.com/firebase/FirebaseUI-Android/blob/735bf7b00501542f7af2e18bc9a8fc8308ed35d6/auth/src/main/java/com/firebase/ui/auth/ui/idp/AuthMethodPickerActivity.java#L262) as well as the one reference to it. 
[This](https://github.com/rstjepanj/FirebaseUI-Android/commit/a2da107c4585871dbe0a2a25053af1c747f6a006) is the solution I used to fix it locally so that I can use it on a project.

**Comment by sipersso** [comment]
Any workarounds for this one @samtstern? Will this be fixed? It's been a while since this was opened...

**Comment by sipersso** [comment]
6 months and no progress? No workaround?

**Comment by samtstern** [comment]
This was fixed and released in version `7.2.0`
