### ISSUE TITLE
How to Using smoothScrollToPosition in recyclerview of firebase/firestore?

### ISSUE THREAD

**Issue by SungJun9212** [firebase/FirebaseUI-Android#1887]
In the main activity, I use a query to get the Firestore document using firestoreRecyclerOption I have specified an adapter.

This code..
-------------------------------------

```java
        CollectionReference chatref=db.collection("chat");
        Query query=chatref.document(email)
        .collection(account_mail).orderBy("time",Query.Direction.ASCENDING);

        FirestoreRecyclerOptions<chat> options=new FirestoreRecyclerOptions.Builder<chat>()
                .setQuery(query,chat.class)
                .build();
        adapter= new chattingAdapter(options,email);

        recyclerView=findViewById(R.id.chat_recycler_view);
        recyclerView.setHasFixedSize(true);
        recyclerView.setLayoutManager(new LinearLayoutManager(this));
        recyclerView.setAdapter(adapter);
        System.out.println(recyclerView.getAdapter().getItemCount());  //result >0
        recyclerView.smoothScrollToPosition(recyclerView.getAdapter().getItemCount()); //no action
```
-------------------------------------

The last two lines don't work.
The result is 0 and scrolltoposition does not work. (It does not work even if you enter an arbitrary number)

However, multiple recyclerview results are displayed on the screen.

**Comment by samtstern** [comment]
@SungJun9212 you need to start the adapter:
https://github.com/firebase/FirebaseUI-Android/blob/master/firestore/README.md#firestorerecycleradapter-lifecycle

```java
adapter.startListening();
```

This will begin **asynchronously** loading the documents.  You can't expect `getItemCount()` to immediately be > 0.  It will take some time.

So you need to subscribe to data events:
https://github.com/firebase/FirebaseUI-Android/blob/master/firestore/README.md#data-and-error-events

In the `onDataChanged` callback it is safe to do `smoothScrollToPosition`
