### ISSUE TITLE
Include a class that handles Firebase.ServerValues.TIMESTAMP

### ISSUE THREAD

**Issue by ceruleanotter** [firebase/FirebaseUI-Android#19]
A class that handles Firebase.ServerValues.TIMESTAMP would be helpful because currently developers need to jump through some hoops to create POJOs that can both serialize and deserialize ServerValues.TIMESTAMP. Thank you!

**Comment by WildWeazel** [comment]
+1
Dealing with a map that turns into a long in a statically typed language is tricky for such a basic feature.

**Comment by jdimond** [comment]
One trick is to use Object and then have a getter that returns ServerValues.TIMESTAMP, the setter accepting a Long, and then using an getter with an exclusion annotation to always return a long for local use (Using System.currentTimeMillis() when it's set to ServerValues.TIMESTAMP).

**Comment by puf** [comment]
I'm pretty sure that's what @ceruleanotter had in mind with this feature
request. :-)

**Comment by SUPERCILEX** [comment]
This issue should probably be closed now with the explanation from #355.

**Comment by samtstern** [comment]
@SUPERCILEX thanks for following up, and for taking a shot at implementing (even though it didn't pan out)
