### ISSUE TITLE
Unable to change the color of Floating Edit Text in LOGIN WITH EMAIL

### ISSUE THREAD

**Issue by kumarkeviv** [firebase/FirebaseUI-Android#190]
Hi Firebase Team

I am trying to change the color of the FLOATING EDIT TEXT in the Firebase UI Login with Email, but its not reflecting the changes as per the style.xml.

XML code i am using to change the LOGIN THEME, whose parent is FIREBASEUI THEME

`<item name="android:textColorHint">@color/nliveo_white</item>
<item name="colorControlNormal">@color/nliveo_blue_alpha_colorPrimaryDark</item>
<item name="colorControlActivated">@color/nliveo_blue_colorPrimary</item>
<item name="colorControlHighlight">@color/authui_colorActivated</item>`

**Comment by kumarkeviv** [comment]
Here is the screenshot of my app:
![screenshot_2016-06-18-22-09-02](https://cloud.githubusercontent.com/assets/17118240/16172271/d35e2c82-35a2-11e6-8bc5-72b6960a2d55.png)

**Comment by davidgcalle** [comment]
Same here, only works if you have a light backgound but if have a dark one, it's really hard to read.

**Comment by kumarkeviv** [comment]
Firebase Team, are we expecting the option for custom changes in element design in recent release? Because without customization it really look awkward and will lead to bad user experience.

**Comment by ErnestMushinge** [comment]
I had the same problem but I solved it by creating a theme in styles.xml then assigning the right parent to that theme I created in styles.xml (parent = "FirebaseUI"). After assigning a parent, then customize the settings in the theme. Make sure you are able to access the FirebaseUI styles in values.xml [www.shungarts.com](http://www.shungarts.com)

`<style name="GreenTheme" parent="FirebaseUI">



        <item name="android:windowBackground">@drawable/bg_login</item>
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>

        <item name="android:textColor">@color/colorTitle</item>
        <item name="colorButtonNormal">@drawable/button_selector</item>
        <item name="android:buttonStyle">@style/FriendlyButtonStyle</item>
        <item name="android:textColorHint">@color/colorPrimary</item>
        <item name="colorControlNormal">@color/colorPrimary</item>
        <item name="colorControlActivated">@color/colorTitle</item>
        <item name="colorControlHighlight">@color/colorAccent</item>
        <item name="android:colorButtonNormal">@drawable/button_selector</item>
       
    </style>`
