### ISSUE TITLE
Progress Indication - Replace third party library with material components LinearProgressIndicator

### ISSUE THREAD

**Issue by postfixNotation** [firebase/FirebaseUI-Android#1907]
* FirebaseUI version: 7.1.1
  
With the most recent releases of Material Components for Android there's a [ProgressIndicator](https://material.io/components/progress-indicators/android) component.

In my opinion this component should be used to replace [me.zhanghai.android.materialprogressbar:library:1.6.1](https://github.com/firebase/FirebaseUI-Android/blob/master/buildSrc/src/main/kotlin/Config.kt) which is used in [the auth module](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/build.gradle.kts).

The intention of this issue is to reduce the number of unofficial third party libs.

**Comment by samtstern** [comment]
@postfixNotation thanks for pointing this out!  We're looking at moving to all Material Components as part of an `8.0.0` release (it's a breaking change because of how themes work) so I'll add this work to that milestone.

**Comment by samtstern** [comment]
This has been implemented and released in version `8.0.0`
