### ISSUE TITLE
Error message when user is offline.

### ISSUE THREAD

**Issue by Abhimanyu14** [firebase/FirebaseUI-Android#1908]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Android device: Redmi Note 5
  * Android OS version: 8.1.0
  * Google Play Services version: 20.50.16 (On test device)
  * Firebase/Play Services SDK version: 
  * FirebaseUI version: 7.1.1
  
### Step 3: Describe the problem:
Authentication error when the user is offline is not user-friendly. 
The technical details can be abstracted for the end user.

#### Steps to reproduce:

1. Try authenticating when the device is offline,

#### Observed Results:
Error message: 
"An internal error has occurred. [Unable to resolve host "www.googleapis.com": No address associated with hostname ]"
  
![Offline_error_message 1](https://user-images.githubusercontent.com/29737108/106358955-4b240380-6335-11eb-8606-8f4ab8ef1e4b.jpg)

#### Expected Results:

A much more user-friendly message to denote that the user is offline.

**Comment by samtstern** [comment]
@Abhimanyu14 thanks for reporting!  Agree, we should make this much friendlier.

**Comment by samhorlbeck** [comment]
@samtstern I created a bug to track this internally as well (b/179035604)

**Comment by samtstern** [comment]
This was fixed and released in version `7.2.0`
