### ISSUE TITLE
Upload artifacts to Maven Central

### ISSUE THREAD

**Issue by keyboardr** [firebase/FirebaseUI-Android#1910]
JCenter is being [sunset](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). This library needs to be uploaded to Maven Central before May 1st.

**Comment by samtstern** [comment]
@keyboardr thanks for the issue, I've been stressing about this since yesterday. I'll definitely solve this before then but it's an unexpected work item.

**Comment by samtstern** [comment]
Version `7.1.1` is now on Maven Central and all future versions will be there as well.
