### ISSUE TITLE
How to change the text of the Button to non-English in idp_button_google.xml and idp_button_facebook.xml?

### ISSUE THREAD

**Issue by shortstopyomin** [firebase/FirebaseUI-Android#192]

**Comment by shortstopyomin** [comment]
A pull request #191 is intended to fix.

**Comment by samtstern** [comment]
This will be in the next release by #191.  Follow local installation instructions to use it manually.

**Comment by shortstopyomin** [comment]
Nice!  wait for so long. Thanks!
