### ISSUE TITLE
UserCancellationException while implementing FirebaseUI Phone Authentication

### ISSUE THREAD

**Issue by Mohamed-Rabiaa** [firebase/FirebaseUI-Android#1920]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: huewei y9 2019
  * Android OS version: Android 9
  * Google Play Services version: 20.45.16
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: 6.4.0
  
#### Steps to reproduce:

 I am having a problem trying to implement the FirebaseUI phone Authentication for the first time ,but every time I run the App on my phone and put my number and click on the verify phone number I get a null response without pressing the back button and it keeps sending me back to the sign in page.

  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.

  * I receive a UserCancellationException whenever I run the app and use FirebaseUI Phone Authentication .

 ```
  my Logcat : 

  * 2021-03-04 05:03:29.600 20159-20159/? E/AuthUI: A sign-in error occurred.
    com.firebase.ui.auth.data.model.UserCancellationException: Unknown error
        at com.firebase.ui.auth.data.remote.PhoneSignInHandler.onActivityResult(PhoneSignInHandler.java:39)
        at com.firebase.ui.auth.ui.idp.AuthMethodPickerActivity.onActivityResult     (AuthMethodPickerActivity.java:383)
        at android.app.Activity.dispatchActivityResult(Activity.java:7797)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4409)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4470)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState     (TransactionExecutor.java:145)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
  
```

 #### Expected Results:

  * What did you expect to happen?
  * to complete the phone Authentication sign in after I put my number and press the verification button

#### Relevant Code:

  ```

  // TODO(you): code here to reproduce the problem
 ```
####Here is my Main Activity code :

```
package com.development.myfirebaseapp;

import androidx.annotation.NonNull;
import androidx.appcompat.app.AppCompatActivity;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.constraintlayout.widget.ConstraintSet;
import android.annotation.SuppressLint;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.Toast;
import com.firebase.ui.auth.AuthUI;
import com.firebase.ui.auth.IdpResponse;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseUser;
import java.util.Arrays;
import java.util.List;



public class MainActivity extends AppCompatActivity {

final Context context = this;

List<AuthUI.IdpConfig> providers;

private final static int SIGN_IN_INTENT_REQUESTCODE = 1;

@Override
protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_main);

    createSignInMethods();
}

public void createSignInMethods()
{
            providers = Arrays.asList(
            new AuthUI.IdpConfig.PhoneBuilder().build(),
            new AuthUI.IdpConfig.EmailBuilder().build(),
            new AuthUI.IdpConfig.GoogleBuilder().build(),
            new AuthUI.IdpConfig.TwitterBuilder().build());

    startActivityForResult(AuthUI.getInstance().createSignInIntentBuilder()
            .setAvailableProviders(providers)
            .build(), SIGN_IN_INTENT_REQUESTCODE);

}

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data)
{
    super.onActivityResult(requestCode,resultCode,data);

    if(requestCode == SIGN_IN_INTENT_REQUESTCODE)
    {
        IdpResponse response = IdpResponse.fromResultIntent(data);

        if(resultCode == RESULT_OK)
        {
            FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();

            Toast.makeText(context,"Successfully signed in",Toast.LENGTH_SHORT).show();

        }
        else
        {
            int errorCode = response.getError().getErrorCode();

            Log.d("authErrorCode",String.valueOf(errorCode));

            Toast.makeText(context,"Failed to sign in",Toast.LENGTH_SHORT).show();
        }
    }
 }
    
}
```
###And here is my App Build.gradle file :

```

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'

android {
compileSdkVersion 29
buildToolsVersion "29.0.2"

defaultConfig {
    applicationId "com.development.myfirebaseapp"
    minSdkVersion 18
    targetSdkVersion 29
    versionCode 1
    versionName "1.0"

    testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
}

buildTypes {
    release {
        minifyEnabled false
        proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
    }
 }

}

dependencies {
implementation fileTree(dir: 'libs', include: ['*.jar'])

implementation 'androidx.appcompat:appcompat:1.2.0'
implementation 'androidx.constraintlayout:constraintlayout:2.0.4'
testImplementation 'junit:junit:4.12'
androidTestImplementation 'androidx.test.ext:junit:1.1.2'
androidTestImplementation 'androidx.test.espresso:espresso-core:3.3.0'

implementation platform('com.google.firebase:firebase-bom:26.5.0')
implementation 'com.firebaseui:firebase-ui-auth:6.4.0'
implementation 'com.twitter.sdk.android:twitter-core:3.1.1'
}

**Comment by saswat711** [comment]
Using the Firebase Android BoM, declare the dependency for the Firebase Authentication Android library in your module (app-level) Gradle file (usually app/build.gradle).

implementation 'com.google.firebase:firebase-auth'

also upgrade the 
implementation platform('com.google.firebase:firebase-bom:26.5.0') to the latest version

If still didnt work Certain Google Play services (such as Google Sign-in and App Invites) require you to provide the SHA-1 of your signing certificate so we can create an OAuth2 client and API key for your app. To get your SHA-1, follow the instructions to use Keytool or Gradle's Signing Report.

check out this link for complete guide on generating SHA-1 key
https://developers.google.com/android/guides/client-auth

**Comment by Mohamed-Rabiaa** [comment]
> Using the Firebase Android BoM, declare the dependency for the Firebase Authentication Android library in your module (app-level) Gradle file (usually app/build.gradle).
> 
> implementation 'com.google.firebase:firebase-auth'
> 
> also upgrade the
> implementation platform('com.google.firebase:firebase-bom:26.5.0') to the latest version
> 
> If still didnt work Certain Google Play services (such as Google Sign-in and App Invites) require you to provide the SHA-1 of your signing certificate so we can create an OAuth2 client and API key for your app. To get your SHA-1, follow the instructions to use Keytool or Gradle's Signing Report.
> 
> check out this link for complete guide on generating SHA-1 key
> https://developers.google.com/android/guides/client-auth

Thanks bro, I updated the Firebase Bom to the latest version (26.6.0) and the FirebaseUI Auth to version (7.1.1) and finally my problem solved 😃

**Comment by samhorlbeck** [comment]
Hi @Mohamed-Rabiaa, thanks for filing this. I'm going to close this out for now since it sounds like your issue was resolved, but please reopen if anything else comes up.
