### ISSUE TITLE
The request is messing a valid app identifier , meaning that neither safetyNet checks ... 

### ISSUE THREAD

**Issue by MustafaGasNas** [firebase/FirebaseUI-Android#1923]
![WhatsApp Image 2021-03-09 at 1 45 08 PM](https://user-images.githubusercontent.com/71601497/110551005-686e9d80-813d-11eb-883d-bd077f23dcf5.jpeg)

**Comment by MustafaGasNas** [comment]
You support please (Urgent Case)

**Comment by samtstern** [comment]
@MustafaGasNas please fill out the issue template when filing issues if you need help.

You can also try Firebase support:
https://firebase.google.com/support
