### ISSUE TITLE
Styling Spinner for Phone Auth UI

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/FirebaseUI-Android#1925]
### Step 2: Describe your environment

  * Android device: Xiaomi Redmi Note 2
  * Android OS version: Lollipop
  * Google Play Services version: 4.3.3
  * Firebase/Play Services SDK version: 20.0.1
  * FirebaseUI version: 7.1.1
  
### Step 3: Describe the problem:

Cannot change the colors of Spinner pop up dialog check https://stackoverflow.com/q/66655624/10053046

#### Steps to reproduce:

  1. Use Firebase UI for Android
  2. Implement Phone Auth UI
  3. Try to make a custom theme or override the FirebaseUI theme to change Spinner style
  
#### Observed Results:

  Frustration, None of the define style applied
  
#### Expected Results:

  Ability to change Spinner item color and its pop up background
  
#### Relevant Code:

Here
https://stackoverflow.com/q/66655624/10053046

**Comment by ArcherEmiya05** [comment]
Already got my solution in [here](https://stackoverflow.com/a/66673366/10053046) though still limited to customization it will serve well for now as long as the spinner pop up view colorization is readable and correct.

**Comment by yuchenshi** [comment]
Closing for now. Let us know if there's more flexibility needed for configuration.

**Comment by ArcherEmiya05** [comment]
Unfortunately my previous wont work when working with `MaterialComponents` as the app main theme,
