### ISSUE TITLE
Country code selection spinner should stay to the left of the phone number in rtl screens

### ISSUE THREAD

**Issue by Itayc3578** [firebase/FirebaseUI-Android#1933]
### Step 1: Are you in the right place?
Yes

### Step 2: Describe your environment

  * Android device: Galaxy S9 (and some emulators)
  * Android OS version: 10
  * Google Play Services version: 21.09.15
  * Firebase/Play Services SDK version: 
  * FirebaseUI version: 7.1.1
  * Locale: "iw" (Israel - Hebrew and rtl)
  
Again, I believe my problem is general

### Step 3: Describe the problem:

When I am signing in with the phone authentication provider and I get to the screen in which the phone number is required, 
the country code selection Spinner appears to the right of the phone number EditText. I believe the reason for it is that
my default locale is "iw", which means my app language is Hebrew with rtl screens. I dont find this behavior right, I think that even though the device's default screen direction is rtl, the country code selection Spinner should be to the left of the phone number.

#### Steps to reproduce:

  1. Enable phone auth provider in the app
  2. try to authenticate using phone number
  
#### Observed Results:

![image](https://user-images.githubusercontent.com/82466877/114595816-7745f400-9c97-11eb-85a3-75da92ae69a8.png)

  
#### Expected Results:

![image](https://user-images.githubusercontent.com/82466877/114595957-ac524680-9c97-11eb-8ff2-b7c4856c9338.png)

**Comment by samtstern** [comment]
@Itayc3578 thanks for this feedback! Seems like a clear bug and an easy fix.

**Comment by samtstern** [comment]
This was fixed and released in version `7.2.0`
