### ISSUE TITLE
startAt with null value doesn't work when ordered by child value

### ISSUE THREAD

**Issue by b95505017** [firebase/FirebaseUI-Android#1934]
https://github.com/firebase/FirebaseUI-Android/blob/3d578ef2ef110ca01e07ba64f1a0808fcd279e4c/database/src/main/java/com/firebase/ui/database/paging/FirebaseDataSource.java#L120

It looks like `startAt(null, params.key)` doesn't work when Query is sorted by `orderByChild()`, we have to specify child value explicitly.

https://github.com/firebase/firebase-js-sdk/issues/35#issuecomment-306651328

**Comment by samtstern** [comment]
@b95505017 can you give a bit more information? What is the code you have written and what does not work?
