### ISSUE TITLE
Work with Firebase Functions instead of Firestore directly 

### ISSUE THREAD

**Issue by Monabr** [firebase/FirebaseUI-Android#1937]
Hello, I really like your pagination library for Firestore, but here's a problem I couldn't solve with it. Let's say I have a collection of documents, for example, these are posts. They have both service information and display information. The problem is that there can be a lot of service ones and it is not used in the application, but it still comes back and eats Internet traffic. The solution to this problem would be to filter the returned result using Firebase Functions, but I cannot work with them using them as a data source in the current implementation. Could you add such a possibility?

**Comment by samtstern** [comment]
@Monabr thanks for the request! That's not something we plan to add to this library. FirebaseUI is about having complete solutions for the most common usage patterns. When you have a totally custom usage pattern like yours, you're going to have to write your own code to bind it to the UI.  Maybe fork this library as a start!
