### ISSUE TITLE
PagedList is now deprecated leading to crash in the latest implementation(androidx.paging:paging-runtime:3.0.0)

### ISSUE THREAD

**Issue by jagadishnallappa** [firebase/FirebaseUI-Android#1942]
Hi, 

With the latest implementation (androidx.paging:paging-runtime:3.0.0), FirestorePagingAdapter crashes with the following error

"**Attempt to access dataSource on a PagedList that was instantiated with a InitialPagingSource instead of a DataSource**"

Further investigation in the IDE, 

1) PagedList is deprecated. 

And **public val dataSource: DataSource<*, T>** in the file **PagedList.kt** is throwing the following exception:
**"Attempt to access dataSource on a PagedList that was instantiated with a " +
                    "${pagingSource::class.java.simpleName} instead of a DataSource"**

For now, I can continue keeping the implements version **implementation 'androidx.paging:paging-runtime:2.1.2'** instead of **implementation(androidx.paging:paging-runtime:3.0.0)** to prevent this from bothering me(crashing). But however, I notice that the latest implementation(though in the alpha stage) brings in some drastic changes. 

Thank you very much.

**Comment by samtstern** [comment]
@jagadishnallappa FirebaseUI uses Paging 2.0, we are moving to Paging 3.0 soon:
https://github.com/firebase/FirebaseUI-Android/pull/1915

For now please don't mix versions, that will lead to crashes or strange behavior.
