### ISSUE TITLE
FirestorePagingAdapter- Real-time events are not respected by this adapter

### ISSUE THREAD

**Issue by nirazv** [firebase/FirebaseUI-Android#1949]
Suppose i wanted to build an application like twitter where i have to display list of feeds with live counting of likes and comments.

But the **FirestorePagingAdapter** doesn't support realtime updates when using for large sets of data or with paging

What possible solution i can expect from firebase team?

**What I wanted to be implemented is:**

I wanted to observe (attach snapshotListeners) only those data sets which are visible to screen. and when i scrolls, the listener should be pointed to next visible items? it this possible if i try another methods such as using paging 3 library?

**Comment by samtstern** [comment]
@nirazv this is the intended behavior, we don't support paging and realtime at the same time in this library.
