### ISSUE TITLE
Auth UI sometimes get stuck (keeps loading, no crash, no error log) when using google sign in

### ISSUE THREAD

**Issue by jordyamc** [firebase/FirebaseUI-Android#1964]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Moto OneZoom
  * Android OS version: 10
  * Google Play Services version: 21.24.13
  * Firebase/Play Services SDK version: bom 28.1.0
  * FirebaseUI version: 7.2.0
  
### Step 3: Describe the problem:
When using google sign in method sometimes the progress get stuck after account selection, the UI keeps the loading animation, but don't complete the login, no error code.

Canceling the login and starting it again works fine, the login now completes successfully.

When using smartlock the screen is covered with a dimmer but the login never completes.

My app was working correctly some weeks ago, I didn't changed anything related to login, signatures, keys, etc.

#### Steps to reproduce:

  1. Auth UI using Google, email and twitter
  2. Start Auth UI
  3. Try to login using google
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
  The account choose windows opens, but after selecting one the UI keeps loading and the login never completes.
  
#### Expected Results:

  * What did you expect to happen?
  
  The login completes successfully
  
#### Relevant Code:

```kotlin
val providers = arrayListOf(
                    AuthUI.IdpConfig.EmailBuilder().build(),
                    AuthUI.IdpConfig.GoogleBuilder().build(),
                    AuthUI.IdpConfig.TwitterBuilder().build()
            )
startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setAvailableProviders(providers)
                            .setLogo(R.drawable.ic_launcher_login)
                            .setIsSmartLockEnabled(false)
                            .build()
                    , 1111
            )
```

**Comment by samtstern** [comment]
> When using google sign in method sometimes the progress get stuck after account selection, the UI keeps the loading animation, but don't complete the login, no error code.

In this case it sounds like something is going wrong with Google Sign In, which is not part of FirebaseUI (we just depend on it). Unfortunately without any logs or a way to reproduce this consistently in a test I don't think there is anything we can do about this. There's no way to know where the issue is.

**Comment by sipersso** [comment]
I have received a bug report stating the exact same issue. Nothing happens when pressing the google sign in button. If it helps, the user was not using the built in 3g connection, but on the phone.
