### ISSUE TITLE
Could not find com.google.firebase:firebase-auth:

### ISSUE THREAD

**Issue by h-hagawa-r** [firebase/FirebaseUI-Android#1965]
I'm trying to use Maven Central before closing JCenter.

Only for this task "com.firebaseui:firebase-ui-auth: 7.2.0" cannot be found.
`app: lintDebug`.
Found in other tasks.

build.gradle
```
buildscript {
...
  repositories {
    google()
    mavenCentral()
    ...
  }
  ...
}

allprojects {
    repositories {
        google()
        mavenCentral()
        ...
    }
}

...
```

build.gradle(:app)

```
...

dependencies {
...
  implementation "com.firebaseui:firebase-ui-auth:7.2.0" // or 7.1.1
...
}
```

log

```
* What went wrong:
Could not determine the dependencies of task ':app:lintDebug'.
> Could not resolve all artifacts for configuration ':app:productionDebugAndroidTestCompileClasspath'.
   > Could not find com.google.firebase:firebase-auth:.
     Required by:
         project :app > com.firebaseui:firebase-ui-auth:7.2.0
```

**Comment by samtstern** [comment]
@h-hagawa-r as you can see here the artifact is definitely on Maven Central:
https://search.maven.org/artifact/com.firebaseui/firebase-ui-auth/7.2.0/aar

If there is an issue locating it, that's something to do with your project or your development machine. I wish I could help you but I can't really debug that kind of issue! Your best bet is to try StackOverflow.
