### ISSUE TITLE
[Internal] Move to Java 8 and AGP 7

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#1966]
Version 8.0 of FirebaseUI can/should require Java 8 to allow us to take on newer dependencies. This also partially unblocks a future move to Kotlin.

cc @rosariopfernandes

**Comment by samtstern** [comment]
Looks like the latest version of AGP is `7.0.0-beta05`:
https://maven.google.com/web/index.html?q=com.android.tools.#com.android.tools.build:gradle:7.0.0-beta05

@rosariopfernandes have you heard anything about when `7.0.0` stable will be out?

**Comment by rosariopfernandes** [comment]
@samtstern Not really, but I know Jetpack Compose is going stable this month ([rc01 is out](https://developer.android.com/jetpack/androidx/releases/compose)). I'm guessing AGP7 will be stable alongside Compose and AS Arctic Fox.

**Comment by samtstern** [comment]
This has been implemented and released in version `8.0.0`
