### ISSUE TITLE
Facebook permissions need to be dynamic "public_profile", "email" are not enough

### ISSUE THREAD

**Issue by Ibrahimhassan1** [firebase/FirebaseUI-Android#197]
The latest Facebook Graph API doesn't return the list of user_friends who are playing the game, it used to return them with current library permissions ("public_profile", "email") but this is returning empty array now. So there should to be a way to add more permissions without touching the library core files.

**Comment by samtstern** [comment]
@Ibrahimhassan1 thanks for the suggestion, I agree this would be useful and we'll look into it.

**Comment by talosdev** [comment]
I needed custom permissions in my app too, so I created a fork and made the facebook permissions configurable.
I have created a pull request, my first one here, so let me know if there's something missing.

@puf 
@mcdonamp

**Comment by talosdev** [comment]
Created a new pull request, correcting the error with the CLA.

**Comment by samtstern** [comment]
This was fixed in #224.  Can now be  overridden in a string array resource.

**Comment by tuxtux59** [comment]
Hi,
I'm using also the facebook connect using Facebook login using FirebaseUI and the app need to list friends. Where do I can add the users permissions?

Thanks :)

**Comment by SUPERCILEX** [comment]
@tuxtux59 Please read the [docs](https://github.com/firebase/FirebaseUI-Android/tree/master/auth#facebook) or create a new issue if they don't cover your use case.

**Comment by tuxtux59** [comment]
Thanks I found help using the IDE autocompletion ;)
