### ISSUE TITLE
CountryListSpinner does not set the selected CountryInfo

### ISSUE THREAD

**Issue by c2call** [firebase/FirebaseUI-Android#2005]
Firebase Auth-UI sign-in with phone number has an issue as the CountryListSpinner does not provider the actual selected CountryInfo via method getSelectedCountryInfo().
I've checked the code an there is a small change required:

        mListPopupWindow.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                CountryInfo info = mCountryListAdapter.getItem(position);
                if (info != null) {
                    mSelectedCountryInfo = info; // This needs to be added in order to set the selected country info 
                    setText(info.toShortString());
                }

                onUnfocus();
            }
        });

Please check, "mSelectedCountryInfo = info;" needs to be set as commented above.
Please update, as phone number authentication is not working in version 8.0.0 due to missing country code.

**Comment by mikehardy** [comment]
This looks like it would be a great PR - you can just hit the edit button on the top right of that file here on github and propose it ? https://github.com/firebase/FirebaseUI-Android/blob/980d0cc8e0f319fece43c23716ec126858936fea/auth/src/main/java/com/firebase/ui/auth/ui/phone/CountryListSpinner.java#L89

**Comment by EricAlvarez292** [comment]
>                 mSelectedCountryInfo = info; // This needs to be added in order to set the selected country info 
when can we expect this fix push to latest release?

**Comment by Surendar7** [comment]
Hi, When will the next version be released with this fix?

**Comment by DzmitryKavaliou** [comment]
Guys, it's terrible. You have a critical issue for several month. You have more than 10 people who is waiting for a fix. Finally, you have this fix. Why you don't just release a new version with a fix? Does google pay for development of this library? If it does it definitely should not!

**Comment by sam-gc** [comment]
The fix will be available in version `8.0.1` which should be available shortly
