### ISSUE TITLE
FirebaseRecyclerPagingAdapter problem scroll

### ISSUE THREAD

**Issue by OneDevUA** [firebase/FirebaseUI-Android#2021]
Good day! i am using FirebaseRecyclerPagingAdapter. I include reverseLayout and stackFromEnd. Everything works fine until another pagination page loads. There is a problem with scrolling.

**Comment by puf** [comment]
Please follow the issue template when filing an issue.

**Comment by OneDevUA** [comment]
So what is not clear from the description of the problem? You have to sit for half an hour and fill the template with meaningless information. Enable reverseLayout and stackFromEnd in pagination mode and see the problem.
