### ISSUE TITLE
Country code is not working

### ISSUE THREAD

**Issue by Sosotess93** [firebase/FirebaseUI-Android#2023]
Hey support,

I do have an issue with the country code.
No matter which country code I choose, the SMS is always sent on the country code +33 even though it is not the one I chose.
I'm using the latest version of FirebaseUI.

`private void authSMS() {
        List<AuthUI.IdpConfig> providers = Collections.singletonList(new AuthUI.IdpConfig.PhoneBuilder().build());
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setAvailableProviders(providers)
                        .setTheme(R.style.FirebaseUI)
                        .build(), RC_SIGN_IN);
    }`

I'm using this code to create the Instance.
Can you please help me ?

**Comment by lisajian** [comment]
Hi, thanks for filing this issue! We are unable to promise any timeline for this, but if others also have this issue, adding a +1 on this issue can help us prioritize adding this to the roadmap.

(Googler-only internal tracking bug: [b/217765697](https://b.corp.google.com/issues/217765697))

**Comment by Sosotess93** [comment]
Hey @lisajian,

Do you have any news regarding this issue ?

**Comment by DzmitryKavaliou** [comment]
Hi, @Sosotess93 most likely this is a duplicate for https://github.com/firebase/FirebaseUI-Android/issues/2005
As far as I understand it can be fixed with one line, they even have a PR with fix.
But for some reason it has been going on for 4 months and no one cares about to merge this PR and release a fixed version.

**Comment by rosalyntan** [comment]
This is fixed in #2025 and is available in the `8.0.1` release.
