### ISSUE TITLE
Facebook signin error

### ISSUE THREAD

**Issue by naviens** [firebase/FirebaseUI-Android#203]
Error:
Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. To use this URL  you must add a valid native platform in your App's settings.

Note: I have properly configured oauth redirect uri in FB app page

**Comment by samtstern** [comment]
@naviens there must be something wrong with your Facebook configuration in the console, I'd suggest double checking each step.  As this is not an issue with FirebaseUI (that message comes directly from Facebook) I am going to close this issue.  I'd suggest opening a ticket with one of the Facebook developer support channels.

**Comment by Saturnyn** [comment]
If anyone runs into the same problem and ends up on this page: on the facebook developer page, after creating your app, you also need to add the Android platform on the Dashboard page, and follow the steps.
(Seems obvious in retrospect but the doc should probably mention it)

**Comment by cutiko** [comment]
Had the same problem and thanks to @Saturnyn Facebook login is working now. I would like to add that, when creating a new Android platform for Facebook, uploading the app to the Play Store and then using the package name and a class name is not very agile for development. Is better to add the SHA1 keys, there is a point in the Facebook wizard to know how to get the keys (is different format than the use in the Firebase configuration project).

**Comment by samtstern** [comment]
@cutiko you don't need to upload to the Play Store to test a Facebook app when you're developing.

The command Facebook uses to get the keystore hash is:

```bash
keytool -exportcert -alias androiddebugkey -keystore ~/.android/debug.keystore | openssl sha1 -binary | openssl base64
```

**Comment by jamesdmurphy51** [comment]
Hi @Saturnyn how do you "add the Android platform on the Dashboard page"
