### ISSUE TITLE
No son card ui

### ISSUE THREAD

**Issue by Carroll8686** [firebase/FirebaseUI-Android#2040]
this is mani fest

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="www.partopars.com.bigbag">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />

    <application
        android:name=".Utils.FontDastnevis"
        android:allowBackup="true"
        android:icon="@mipmap/icon"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/icon"
        android:screenOrientation="portrait"
        android:supportsRtl="false"
        android:theme="@style/AppTheme"
        tools:replace="android:supportsRtl">
        <service
            android:name=".Utils.GetCitiesService"
            android:enabled="true"
            android:exported="true"></service>
<activity android:name=".Sarasari.SarasariActivity"
    />
        <activity android:name=".SplashActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@mipmap/icon" />
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
        
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id" />
        <activity android:name=".Main.MainActivity" >

        </activity>
        <activity android:name=".Categories.CategoryActivity" />
        <activity android:name=".Vip.VipActivity" />
        <activity android:name=".Question.QuestionActivity" />
        <activity android:name=".SearchActivity" />
        <activity android:name=".Categories.Group3Activity" />
        <activity android:name=".Views.Activities.AboutActivity" />
        <activity android:name=".Views.Activities.BasketActivity" />
        <activity android:name=".Views.Activities.DetailsActivity" />
        <activity android:name=".Views.Activities.FilterActivity" />
        <activity android:name=".Views.Activities.OrderHistoryActivity" />
        <activity android:name=".Views.Activities.ProductActivity" />
        <activity android:name=".Compare.CompareActivity" />
        <activity android:name=".Basket.Basket1Activity" />
        <activity android:name=".Basket.Basket2Activity" />
        <activity android:name=".Views.Activities.ProductCompareActivity" />
        <activity android:name=".Views.Activities.FavoriteActivity" />
        <activity
            android:name=".Login.RegisterActivity"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=".Login.Register2Activity"
            android:windowSoftInputMode="adjustPan" />
        <activity
            android:name=".Login.ActiveCodeActivity"
            android:windowSoftInputMode="adjustResize" />
        <activity
            android:name=".Login.LoginActivity"
            android:windowSoftInputMode="adjustResize" />

        <receiver
            android:name=".Utils.NetworkReciver"
            android:enabled="true">
            <intent-filter>
                <action android:name="android.net.conn.CONNECTIVITY_CHANGE" />
                <action android:name="android.net.wifi.WIFI_STATE_CHANGED" />
                <action android:name="android.net.wifi.STATE_CHANGE" />
            </intent-filter>
        </receiver>

        <activity android:name=".Utils.DisconnectedActivity" />

        <service android:name=".Firebase.MyFirebaseMessagingService">
            <intent-filter>

                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        <service android:name=".Firebase.MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>

        <activity android:name=".Basket.Basket3Activity" />
        <activity android:name=".Basket.onlinePay" />
        <activity android:name=".Basket.finalBasketActivity"></activity>
    </application>

</manifest>

_Originally posted by @mehdidavarpanah66 in https://github.com/firebase/quickstart-android/issues/941#issuecomment-527069165_

**Comment by shrutip90** [comment]
Is there an issue here? Otherwise please close it.
