### ISSUE TITLE
Firebase UI Auth: What is the correct way to link provider Phone and Email/Password?

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/FirebaseUI-Android#2057]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

Yes

### Step 2: Describe your environment

  * Android device: Any
  * Android OS version: Any
  * Google Play Services version: 4.3.13
  * Firebase/Play Services SDK version: 21.0.7
  * FirebaseUI version: 8.0.1
  
### Step 3: Describe the problem:
We are using email/password for authenticating user, we would like to use phone auth of Firebase UI to verify their mobile number that will be save to Firestore. We will not use phone for authenticating user. Our flow starts with authentication using email/password then launch another screen for phone auth, from there we will get the phone auth credential and link it like this.

    val response: IdpResponse? = IdpResponse.fromResultIntent(result.data)
    
    if (result.resultCode == Activity.RESULT_OK && response != null)
       Firebase.auth.currentUser!!.linkWithCredential(response.credentialForLinking!!)

This throws NPE
`Failure delivering result ResultInfo{who=null, request=1236788821, result=-1, data=Intent { (has extras) }} to activity {com.sample.app/com.sample.apppresentation.AuthActivity}: java.lang.NullPointerException`

Not sure if the `response.credentialForLinking!!` or the user is null but we just sign in with phone auth so it should not.

Not sure again if this is the correct flow to link email/password and phone in Firebase since it looks like what just happened here is we overwrite the previous session of email/password with phone auth. What we think the correct way is after running phone auth OTP we will get again the `AuthCredential` of email/password and link it with the current user (phone auth)?

#### Steps to reproduce:

  1. Implement your own simple email/password sign in with Firebase Auth
  2. Integrate Firebase UI and use only Phone Auth as provider
  3. Create account using email/password provider and launch Firebase UI phone auth for OTP
  
#### Observed Results:

NPE
  
#### Expected Results:

Link phone auth provider to email/password provider.

**Comment by ArcherEmiya05** [comment]
Just check it again, the `credentialForLinking` is null. Why?
![image](https://user-images.githubusercontent.com/38008900/187046963-01bb1b7c-6b15-426a-a2c1-294e7740df73.png)

**Comment by ArcherEmiya05** [comment]
**Update**

What we tried so far is sign in with email/password (verified) then open Firebase Auth UI (Phone). Finish OTP then link the account using this approach.

    val authCredential = EmailAuthProvider.getCredential("sample@gmail.com", "password")
    
    viewModel.linkAccountCredential(user, authCredential)

This returns however an error:

![image](https://user-images.githubusercontent.com/38008900/187049335-f4a6f8f1-dff5-48c0-9c3c-2311487f0b46.png)

**Comment by sam-gc** [comment]
Hi @ArcherEmiya05, one thing to note is that you cannot link existing accounts. Similarly, I believe `credentialForLinking` only applies if you're trying to link an account that already exists. Also, if you link a phone number your users will be able to use SMS sign in as well, but in your first post you say

> We will not use phone for authenticating user

If your goal is to verify phone numbers but not use them for authentication, I think Firebase Auth is not the best solution.
