### ISSUE TITLE
With sample auth app, Facebook sign in hang and never get to SignedInActivity

### ISSUE THREAD

**Issue by xzwang2005** [firebase/FirebaseUI-Android#2062]
### Step 1: Are you in the right place?

I hope so.

### Step 2: Describe your environment

  * Android device: pixel 4
  * Android OS version: 13
  * Google Play Services version: 
  * Firebase/Play Services SDK version: 
  * FirebaseUI version: build from source
  
### Step 3: Describe the problem:

I downloaded the source (commit 8155b33a) and build the sample [app](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md).  The changes I made include:

- add the google-services.json file
- update facebook app id in app/src/main/res/values/config.xml

Email and Google sign in work fine. But I couldn't get facebook sign in working.  It hangs after I provided sign in info on **Log in With Facebook**. I've setup OAuth Redirect URIs in facebook developer dashboard.

#### Steps to reproduce:

Scenario 1:

1. Start the app, click **Auth UI Demo**
2. Keep default providers, click **START** (Facebook is checked once APP ID is set)
3. Click **NONE OF THE ABOVE** on Smart Lock pop-up (I tested with Google sign in first)
4. On **AuthMethodPickerActivity**, click **Sign in with Facebook**
5. **Log in With Facebook** opens, click **Continue as XXX** (this is the only option I got after signed in for the first time)
6. Returns to **AuthMethodPickerActivity** with progress bar moving

Scenario 2:

1. Start the app, click **Auth UI Demo**
2. Uncheck all other providers, only keep **Facebook**, click **START**
3. **Log in With Facebook** opens, click **Continue as XXX**
4. Returns to **AuthUiActivity** and show circle spinner

  
#### Observed Results:

  * Sample app hangs after return from **Log in With Facebook**.  I'm not sure if OAuth redirect URI was working properly but don't know how to verify.  I did get to step into Facebook sdk's **LoginManager** by breakpoints I set in **FacebookSignInHandler**. `LoginManager.onActivityResult()` returned ok; although the breakpoints are not triggered every time.
  
#### Expected Results:

  * Sample app opens **SignedInActivity** once Facebook sign in completed.
  * My google and facebook accounts do share the same email. I found old posts about Google sign in overrides facebook sign in by design.  Is my issue here the same?

**Comment by thatfiredev** [comment]
@xzwang2005 Did you find a solution to your issue?

**Comment by xzwang2005** [comment]
yes. 

1. add `<string name="facebook_client_token">CLIENT_TOKEN</string>` in app/src/main/res/values/config.xml
2. add `<meta-data
             android:name="com.facebook.sdk.ApplicationId"
             android:value="@string/facebook_application_id"/>
            <meta-data
            android:name="com.facebook.sdk.ClientToken"
            android:value="@string/facebook_client_token" />` in AndroidManifest.xml

**Comment by thatfiredev** [comment]
@xzwang2005 Thanks for posting your solution! I'll be sure to add that to the docs.
