### ISSUE TITLE
activity leaks

### ISSUE THREAD

**Issue by gubo** [firebase/FirebaseUI-Android#209]
Hello.

using [LeakCanary,](https://github.com/square/leakcanary) I think I have identified more instances of activity leaks when GoogleApiClient is left connected...

**IDPSignInContainerActivity** can be leaked when mIDPProvider is instanceof GoogleProvider,
because it has not been built with auto manage enabled nor is disconnect being called.
suggest add:
```
@Override
protected void onStop() {
    super.onStop();
    if ( GoogleProvider.class.isInstance( mIDPProvider ) ) {
        ( ( GoogleProvider)mIDPProvider).disconnect();
    }
}
```

**SaveCredentialsActivity** is being leaked because mCredentialsApiClient has not been built with auto manage enabled nor is disconnect being called.
suggest add:
```
@Override
protected void onStop() {
    super.onStop();
    if ( mCredentialsApiClient != null ) {
        mCredentialsApiClient.disconnect();
    }
}
```

**ChooseAccountActivity** is being leaked.
ex. (in onActivityResult, line 203)
`mCredentialsApi.handleCredential(credential);`

**Comment by samtstern** [comment]
@gubo thanks for calling this out, we should likely move to using automanage internally.

**Comment by ErstwhileWork** [comment]
Looks like the "9.2.1" versions became available yesterday. I am now using
### // Android Studio v2.2 Preview 4 now works with Firebase and Google Play Services (works in emulator too)
    compile 'com.firebaseui:firebase-ui-database:0.4.0'
    compile 'com.google.firebase:firebase-core:9.2.1'
    compile 'com.google.firebase:firebase-auth:9.2.1'
    compile 'com.google.firebase:firebase-database:9.2.1'
    compile 'com.google.android.gms:play-services-appindexing:9.2.1'

**Comment by samtstern** [comment]
@gubo this has been fixed in `master` and the fix will be rolled into the next release.

**Comment by samtstern** [comment]
0.4.4 has been released!
