### ISSUE TITLE
Feature Request: Add support for the ViewHolder pattern for the FirebaseListAdapter

### ISSUE THREAD

**Issue by ceruleanotter** [firebase/FirebaseUI-Android#21]
Feature request. Could we get support for the [ViewHolder](http://developer.android.com/training/improving-layouts/smooth-scrolling.html#ViewHolder) pattern for FirebaseListAdapter?

**Comment by samtstern** [comment]
@ceruleanotter I am going through old issues and I am going to close this one, as I believe if you want to use the `ViewHolder` pattern you are better off using a `FirebaseRecyclerView`.

If there's something I am missing, let me know.
