### ISSUE TITLE
Provide DESCRIPTIVE release notes PLEASE

### ISSUE THREAD

**Issue by thefaj** [firebase/FirebaseUI-Android#2134]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * FirebaseUI version: *
  
### Step 3: Describe the problem:

The development team needs to provide release notes for everything here.

#### Steps to reproduce:

  1. See releases for this library
  2. No step 2
  
#### Observed Results:

• A fatal crashing upon login issue happened with version 6.4.0 of this library on Android 31. There is no information in the release notes about this bug that Google both created and neglected to alert developers about.
  
#### Expected Results:

  * Google Developers should provide descriptive, detailed release notes instead of the generic (and lazy): "Improvements & bug fixes" for each version.
  
#### Relevant Code:

…every single release of this library.

**Comment by thatfiredev** [comment]
@thefaj All of our releases contain a "Changes" sections which describes what fixes were included in that release:

![Screenshot 2023-07-18 at 16 24 52](https://github.com/firebase/FirebaseUI-Android/assets/16766726/07773ca1-f718-48b7-a3e2-9ccfea0f4514)



Am I missing something?

**Comment by thatfiredev** [comment]
@thefaj I'm closing this for now since there hasn't been any activity, but feel free to re-open if I missed anything.
