### ISSUE TITLE
Add option to enable Chrome Custom Tabs for Facebook signin

### ISSUE THREAD

**Issue by suyash192** [firebase/FirebaseUI-Android#214]
Facebook signin in Android has an option to [enable Chrome Custom Tabs](https://developers.facebook.com/docs/facebook-login/android#chrome_custom_tabs) instead of the webview for the login dialog when the Facebook app is not installed. There should be an option to enable this.

This has two main advantages:

1. Users don't have to re-enter their credentials each time since they're already logged into their Facebook accounts in Chrome most of the times.
2. Better security since Chrome Custom Tabs is not a part of the app so the users don't have to worry about the app spying on their passwords.

**Comment by samtstern** [comment]
Thanks for this suggestion, this is something we should definitely do when we upgrade the underlying Facebook SDK.

**Comment by samtstern** [comment]
@suyash192 I have opened pull request #249 to address this issue.  Please check out the change to see if it meets your requirements.

**Comment by suyash192** [comment]
Yup, everything looks great!

**Comment by samtstern** [comment]
Fix implemented, will be rolled into the next release.

**Comment by samtstern** [comment]
This fix for this issue is included in version 0.5.0.

**Comment by SteveFirsake** [comment]
Hello,

Please help with this issue:

https://stackoverflow.com/q/48509212

two step verification requires someone to minimize the app and look into a new app for verification codes yet on opening the original app (login page) - the chrome tab is disappeared.
