### ISSUE TITLE
No found google-services-json

### ISSUE THREAD

**Issue by emaLorenzo** [firebase/FirebaseUI-Android#215]
**Hi! I cant run the app, there is no google-services.json file, i found one empty and i get the error:**

> Error:FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':app:processDebugGoogleServices'. > No matching client found for package name 'com.firebase.uidemo'  * Try: Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. 

**I see that everybody can run the example, so please can you give a hand with this? How did you load that file?**

**Comment by sorab2142** [comment]
Login to firebase.com and create an app (or use your existing one) and go through the configurator, it will generate the file for you.

**Comment by samtstern** [comment]
@sorab2142 you need to go to the [Firebase console](console.firebase.google.com) and follow the flow to get a `google-services.json` file, as @sorab2142 pointed out (although `firebase.com` is the wrong URL, click the link in this comment).
