### ISSUE TITLE
0.4.3 is not working

### ISSUE THREAD

**Issue by cutiko** [firebase/FirebaseUI-Android#219]
Greetings

I notice today there was a change from 0.4.2 to 0.4.3, is not working, none.

<img width="481" alt="captura de pantalla 2016-07-19 a las 4 12 09 p m" src="https://cloud.githubusercontent.com/assets/6012585/16964878/8ec05b72-4dcb-11e6-9a9a-da7964afa585.png">

Im talking about [this commit](https://github.com/firebase/FirebaseUI-Android/commit/e5cd5eebef5922f08662903e1a2d3a049aa65234)

**Comment by samtstern** [comment]
This seems to be a real issue.  If you look here: https://dl.bintray.com/firebaseui/firebase-ui/com/firebaseui/firebase-ui-database/

The 0.4.3 folders exist but are empty.  I will investigate why that is.

**Comment by samtstern** [comment]
For now please use `0.4.2`.

**Comment by cutiko** [comment]
Greetings again

@samtstern yes it is there but empty :/

Actually, I notice the change early but didnt felt like upgrading, however, got hit by this other issue https://github.com/firebase/FirebaseUI-Android/issues/145 and I thought "Maybe the new version fix it". The good thing there is a work arround.

Also, yes Im using 0.4.2 I thought the correct way to proceed was to report the issue.

**Comment by samtstern** [comment]
@cutiko I just re-did the upload to Maven Central and jCenter.  That folder is no longer empty and I think this should work now.  Could you give it a try?  Note that there could be a small propagation delay from Bintray so maybe wait a few minutes.

**Comment by peterhav** [comment]
Hi @samtstern, it does now work. I encountered the same issue when switching to 0.4.3, but since 5 minutes my app compiles and runs with 0.4.3.
Thanks!

**Comment by samtstern** [comment]
Works for me too, closing. Thanks for @cutiko for catching this.
