### ISSUE TITLE
Infinite progress without a configured google account

### ISSUE THREAD

**Issue by Fax3D** [firebase/FirebaseUI-Android#221]
Hi,

i'm using the last 0.4.3 version of this library, and i noticed this strange behaviour.

On a new phone without a google account configured, if i run my own application, when i launch the intent for choosing an account, progress bar never ends!

`startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            .setProviders(
                                    AuthUI.EMAIL_PROVIDER)
                            .build(),
                    RC_CODE);`

Additionally, configuring a google account doesn't solve the problem: progress bar never ends! 
**Only after clearing all app data and restarting, i can pick my account.**

I think this happens on all Android version, but just to be precise i'm using a Samsung phone with Android 6.0.1.

Thanks.

**Comment by samtstern** [comment]
@Fax3D your issue describes a problem with a Google account but your code only shows the `EMAIL_PROVIDER` enabled.  Are you still having this problem?  If so, can you show a screenshot of the issue?

**Comment by samtstern** [comment]
It's been a long time since this issue was updated and I have not heard similar reports so I am going to close this issue. Feel free to re-open it or start a new one if you want to discuss more!
