### ISSUE TITLE
When adding a background on the Sign in views, the app gets really slow

### ISSUE THREAD

**Issue by davidgcalle** [firebase/FirebaseUI-Android#222]
### Describe your environment

  * Android device: Nexus 6
  * Android OS version: 6.0.1
  * Google Play Services version: 9.0.2
  * Firebase/Play Services SDK version: 9.0.2
  * FirebaseUI version: 0.4.1
  
### Describe the problem:

I need to put a background image on the sign in view to get a better UI/UX design, but the only way I see to do it, is applying it on the Theme that I'm passing on the `.createSignInIntentBuilder()`. 

Two issues if I apply the style `<item name="android:background">@drawable/image_name</item>`
this is what I got: 

![screenshot_20160725-125922](https://cloud.githubusercontent.com/assets/6651015/17113395/3cb9ef7e-5270-11e6-973e-dda20a34b7c8.png)

So I tried the next style `<item name="android:windowBackground">@drawable/image_name</item>` and this is what I got:

![screenshot_20160725-130128](https://cloud.githubusercontent.com/assets/6651015/17113451/779c02bc-5270-11e6-997c-a078d398d2a5.png)

All it's good aside the fact that everything in the sign in view gets really slow, till the point that it's not usable at all.

What I suggest? well it will be most appreciated if a method `.setBackgroundImage() ` is added with a center crop, full screen Image View so it be easier and efficient to apply a background image. Like this:

```
 AuthUI.getInstance()
      .createSignInIntentBuilder()
      .setTheme(R.style.theme)
      .setLogo(R.drawable.logo)
      .setBackgroundImage(R.drawable.image_name)
      .setProviders(
                 AuthUI.EMAIL_PROVIDER,
                 AuthUI.GOOGLE_PROVIDER,
                 AuthUI.FACEBOOK_PROVIDER)
      .build()
```

I'm open to any suggestions.

Thanks in advance.

**Comment by samtstern** [comment]
I can't imagine a reason why the image would affect things this badly.  Could you try using a very low res image as the background and see if you get the same issue?

**Comment by davidgcalle** [comment]
@samtstern The image dimentions are 1080*1776 px and the size is 37.6KB, it a really optimized image, but I can either see why this could be a reason to affect. Will upload a image sample. 
![welcome_port](https://cloud.githubusercontent.com/assets/6651015/17193596/76bcef64-5419-11e6-909c-f45c96840662.jpg)

**Comment by samtstern** [comment]
@davidgcalle unfortunately I don't think this is an issue with this library.  See this post:
http://stackoverflow.com/questions/35301697/android-extreme-lag-when-using-high-resolution-drawables

Even though your image is reasonably compressed, because it is high resolution it is very large when held in memory.  And it will stay in memory as the app runs.

I'm going to close this issue since it's not a library problem and we are tracking increasing customization abilities elsewhere.  Thanks for reporting!

**Comment by davidgcalle** [comment]
@samtstern  Thanks for your help!, sorry not posting this reacently but found a solution for the issue, as you mention was not an issue of the library but was an issue on andriod.

The solution I found was to have several assets for each display density and orientation, this to have a better user experience.
