### ISSUE TITLE
Build failing - Error:Could not find com.google.firebase:firebase-database:9.4.0.

### ISSUE THREAD

**Issue by animeshjain** [firebase/FirebaseUI-Android#233]
I just took a fresh clone of the repo, and gradle is not able to build the project.

Error:Could not find com.google.firebase:firebase-database:9.4.0.
Required by:
    FirebaseUI-Android:app:unspecified
    FirebaseUI-Android:app:unspecified > com.firebaseui:database:0.4.4
<a href="searchInBuildFiles">Search in build.gradle files</a>

**Comment by animeshjain** [comment]
Update: 

When I reverted versions in common/constants.gradle to

project.ext.firebase_version = '9.2.1'
project.ext.version = '0.4.3'

then I was able to build.

**Comment by samtstern** [comment]
@animeshjain 9.4.0 was released on Monday, you just need to go to the Android SDK manager and update **Google Repository** and **Google Play Services**.

See my answer on StackOverflow for step-by-step instructions: http://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0/37310513#37310513

**Comment by animeshjain** [comment]
Thanks Sam. My bad :/
