### ISSUE TITLE
Error:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (24.0.0) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

### ISSUE THREAD

**Issue by runia1** [firebase/FirebaseUI-Android#239]
* Android device: Nexus 5X
  * Android OS version: 6.0.1
  * Google Play Services version: 9.x
  * Firebase/Play Services SDK version: 9.4.0
  * FirebaseUI version: 0.4.0  

In the firebase android demo: "Friendly Chat" their app build.gradle has firebase version 9.4.0 and UI version 0.4.0 which builds fine, but in your README you say to use firebase versions 9.4.0 with UI version 0.4.4.  When UI version changed to 0.4.4 it produces the following error:

Error:Conflict with dependency 'com.android.support:support-annotations'. Resolved versions for app (24.0.0) and test app (23.2.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

I don't know enough about gradle to really understand what is going on, I simply saw that the demo app provided was not using the UI version it's supposed to.  A short explanation of of what's going on here would be super helpful!

**Comment by samtstern** [comment]
This just means that the test dependencies (marked with `androidTestCompile`) and the app dependencies (marked with `compile`) disagree on the version of the support annotations library.  This is a common conflict and is fixed with snippet like [this](https://github.com/firebase/quickstart-android/blob/master/config/app/build.gradle#L25:27):

```
configurations.all {
    resolutionStrategy.force 'com.android.support:support-annotations:24.0.0'
}
```

I will submit a pull request on friendlychat to fix this.

**Comment by samtstern** [comment]
See https://github.com/firebase/friendlychat/pull/67 for further discussion, going to close this issue as it's not something wrong with FirebaseUI.

**Comment by runia1** [comment]
@samtstern   Thanks for the response, I figured it was something like that.  I actually tried changing the versions of the compile sdk and such but I didn't know the 
```
configurations.all {
    resolutionStrategy.force 'com.android.support:support-annotations:24.0.0'
}
```
trick.

**Comment by snehal97** [comment]
Thank you @samtstern  this snippet solve my error
