### ISSUE TITLE
Issue with FirebaseUI and FirebaseRecyclerAdapater

### ISSUE THREAD

**Issue by wdhodges** [firebase/FirebaseUI-Android#240]
So I have the following gist that I'm trying to use the FirebaseRecyclerAdapater:

    @Override
        protected void onStart() {
            super.onStart();
    
            FirebaseRecyclerAdapter<String, FSViewHolder> adapter = new FirebaseRecyclerAdapter<String, FSViewHolder>(
                    String.class,
                    android.R.layout.two_line_list_item,
                    FSViewHolder.class,
                    fsRef
            ) {
                
                @Override
                protected void populateViewHolder(FSViewHolder viewHolder, String model, int position) {
                    
                }
            };
    
        }
    
        public static class FSViewHolder extends RecyclerView.ViewHolder {
            TextView fsText;
    
            public FSViewHolder(View v) {
                super(v);
                fsText = (TextView) v.findViewById(android.R.id.text1);
            }
    }

When I run the app in the studio i get an error message that says this:

Error:(88, 65) error: no suitable constructor found for FirebaseRecyclerAdapter(Class<String>,int,Class<FSViewHolder>,Firebase)
constructor FirebaseRecyclerAdapter.FirebaseRecyclerAdapter(Class<String>,int,Class<FSViewHolder>,Query) is not applicable
(argument mismatch; Firebase cannot be converted to Query)
constructor FirebaseRecyclerAdapter.FirebaseRecyclerAdapter(Class<String>,int,Class<FSViewHolder>,DatabaseReference) is not applicable
(argument mismatch; Firebase cannot be converted to DatabaseReference)

I'm really confused on what is going on. Can anyone tell me what I'm doing wrong?

**Comment by wdhodges** [comment]
I do have `compile 'com.firebaseui:firebase-ui:0.4.4'` in my build.gradle

**Comment by tajchert** [comment]
I have the same problem.
Firebase 9.4.0 here.

**Comment by puf** [comment]
Cross-post: http://stackoverflow.com/questions/38810981/issue-with-firebaseui-and-firebaserecycleradapater.

Solved there, so closing here.
