### ISSUE TITLE
Show internet required dialog in case of no internet connection

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#241]
Using 0.4.4 of this library (and earlier), when starting the Sign In intent without internet, the behavior is as follows:

For a mail sign in: after clicking next on adding the user mail, nothing happens
For Google sign in: after clicking the sign in button nothing happens

I would propose to show a 'internet connection required' dialog at the moment the Sign In intent is started without having an internet connection available.

**Comment by samtstern** [comment]
@peterhav this is a good idea.  It's worth considering if FirebaseUI should show a dialog or if it should return an error code to the calling app and allow that app to decide on error UI.

**Comment by BoogieMAN2K** [comment]
I would prefer an error messages, that way you can customize your response to the error. 
El 8 ago. 2016 10:46, Sam Stern <notifications@github.com> escribió:@peterhav this is a good idea.  It's worth considering if FirebaseUI should show a dialog or if it should return an error code to the calling app and allow that app to decide on error UI.

**Comment by hijamoya** [comment]
I need this function, too!
