### ISSUE TITLE
Remove duplicates strings in auth/src/main/res/values/strings.xml

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#242]
To make the live of translators easier, I would recommend to remove duplicates from the strings.xml:

Next (2x)
Sign In (5x)
Password (2x)
Ok -> replace with android.R.string.ok

Is it ok to add translations to other languages already?

**Comment by samtstern** [comment]
@peterhav which languages were you considering adding translations for?  This is something we'd have to coordinate across platforms.

However a PR to reduce duplication in string resources would be welcome if you'd like to submit it.

**Comment by peterhav** [comment]
The PR has been created. I would be able to add Dutch translations for the auth lib strings.xml

**Comment by samtstern** [comment]
Thanks for the PR!  As for the dutch translation, let's hold off for now.  I think we have some plans to get all translations done at once for this library (and the iOS version) and I don't want to have you put in the effort now only to see it deleted later.  We do appreciate the offer though :+1:

**Comment by samtstern** [comment]
The PR has been merged so I consider this issue fixed.  Thanks again!
