### ISSUE TITLE
Allow retrieving data from a reference of keys in FirebaseArray

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#243]
The documentation says to index data like so: https://firebase.google.com/docs/database/android/structure-data.

How would you go about giving Firebase UI a reference of your keys and a reference of the location of the data for those keys to populate a recyclerview? I've tried in the following diff, but it doesn't work and I think I'm going about it in the wrong way: https://github.com/SUPERCILEX/FirebaseUI-Android/commit/fb4e704f9a8d4ac1391ed28917b488aa0eed6d25

Could you guys implement this feature or give me some clues as to how to do it? Thanks!

**Comment by puf** [comment]
See http://stackoverflow.com/questions/34559171/coupling-firebaserecyclerviewadapter-to-a-boolean-string-map-entry for one way to already join data from a different location when using FirebaseUI. We already have a feature request open for this, so I'm going to close this as a dupe of #12 .

**Comment by SUPERCILEX** [comment]
Thanks! I got it working!
