### ISSUE TITLE
Skip login button ?

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#247]
Hello.
Is it possible to allow user to skip login ? 
Something like button or item in action bar menu ?

**Comment by samtstern** [comment]
@stasbar what would be the purpose of a skip login button?  Trying to better understand this feature request.

**Comment by SpotVL** [comment]
for example for anonymously signing in.

**Comment by samtstern** [comment]
@SpotVL if you want the user to sign in anonymously it would be better to do so before launching the FirebaseUI flow, rather than adding a button to the UI that skips authentication.

**Comment by SpotVL** [comment]
may be, but in some case it will be good to give user a choice to sign in anonymously in list with other providers like email, google etc at one activity.

**Comment by stasbar** [comment]
Exactly, that's what we call User Experience.

**Comment by stasbar** [comment]
@samtstern yes, exactly, and the "Skip" should be MenuItem in Action Bar

**Comment by samtstern** [comment]
This is an old issue, we've thought about it a few times but it's not on the roadmap for a future release as we believe this should be implemented in the containing app's UI.
