### ISSUE TITLE
Refactor SaveCredentialsActivity

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#254]
SaveCredentialsActivity has no UI and therefore does not need to be an Activity at all.  It could be embedded as a Fragment or refactored in some other way to avoid the janky UI of starting a blank Activity.

**Comment by peterhav** [comment]
+1 for this!

**Comment by samtstern** [comment]
It seems that `ChooseAccountActivity` is the same, it is a no-UI activity that only serves to host a `GoogleApiClient` and interact with the Credentials API.

**Comment by SUPERCILEX** [comment]
`IDPSignInContainerActivity` is in the same boat.

**Comment by SUPERCILEX** [comment]
`EmailHintContainerActivity` too

**Comment by SUPERCILEX** [comment]
I think `WelcomeBackIDPPrompt` should be removed as well since the user only has the option to proceed. Also, I don't think it is necessary for them to know they already have an account: all a user would really care about is just signing in.

Removing this would prevent extra steps for #309 when the user links an account with smart lock enabled.

**Comment by SUPERCILEX** [comment]
@samtstern @amandle Any objections to me removing `WelcomeBackIdpPrompt`? See https://github.com/firebase/FirebaseUI-Android/issues/254#issuecomment-252446320.

**Comment by amandle** [comment]
@SUPERCILEX if the user chose to sign in with facebook, then signed in I think it would be surprising to see the Google Sign In picker pop up. I think we need to explain why they are seeing it.

**Comment by SUPERCILEX** [comment]
@amandle what do you think of only showing the prompt if the provider isn't email or Google?

**Comment by amandle** [comment]
@SUPERCILEX I still think it needs to be shown since otherwise it will behave surprisingly without an explanation.  I don't think email or Google are special cases here and will still need the prompt.

**Comment by SUPERCILEX** [comment]
@amandle agreed. I'll have to take out some of the sign-in logic in #309.
