### ISSUE TITLE
compile 'com.firebaseui:firebase-ui-auth:0.4.4' points to earlier version

### ISSUE THREAD

**Issue by tsadoklf** [firebase/FirebaseUI-Android#255]
AuthUI version 0.4.4 does not have setIsSmartLockEnabled. 

My gragle.build has 

`compile 'com.firebaseui:firebase-ui-auth:0.4.4'`

When i drill down I can see that the last lines in AuthUI.java  are - 

`public Intent build() {`

            Context context = mApp.getApplicationContext();
            List<IDPProviderParcel> providerInfo =
                    ProviderHelper.getProviderParcels(context, mProviders);
            return ChooseAccountActivity.createIntent(
                    context,
                    new FlowParameters(
                            mApp.getName(),
                            providerInfo,
                            mTheme,
                            mLogo,
                            mTosUrl));
        }`

But in Github the code is - 

`public Intent build() {`

            Context context = mApp.getApplicationContext();
            List<IDPProviderParcel> providerInfo =
                    ProviderHelper.getProviderParcels(context, mProviders);
            return ChooseAccountActivity.createIntent(
                    context,
                    new FlowParameters(
                            mApp.getName(),
                            providerInfo,
                            mTheme,
                            mLogo,
                            mTosUrl,
                            mIsSmartLockEnabled));
        }`

**Comment by gabrielgd** [comment]
Same issue here.

**Comment by samtstern** [comment]
@tsadoklf @gabrielgd you're right, and this is intentional.  What you see in the `master` branch is the result of the absolute latest work we've done, and not necessarily the latest release.

Each release has an associated release branch that is frozen in time.  For example [here is the branch](https://github.com/firebase/FirebaseUI-Android/tree/version-0.4.4) for 0.4.4.  If we ever had to do a fix for 0.4.4 (say 0.4.41) we would check out that branch, cherry pick the change in, and release again.

**Comment by tsadoklf** [comment]
So how can one use the code snippets shown in the [read me](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md) section and specifically the setIsSmartLockEnabled method?

**Comment by samtstern** [comment]
@tsadoklf ah, I see the issue now.

I should not have updated the README until the release, this is my mistake.  The smart lock feature will not be enabled until version 0.5.0 (coming soon).  If you want to use it now, you can build the library locally following the instructions in the README.
