### ISSUE TITLE
Clean up Activity titles to allow for overrides

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#256]
See discussion in #252 for motivation and possible implementations

**Comment by samtstern** [comment]
@PaoloRotolo I went back and filed this issue so that we have something to mark as fixed when the feature is done.

**Comment by bcscarlosrojas** [comment]
Can you please show how in a normal app I can change the title of the firebase UI method picker activity? I tried to follow the issue and no luck

**Comment by samtstern** [comment]
@bcscarlosrojas you can see the Activity titles here:
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/AndroidManifest.xml

So you could define:
```xml
<string name="fui_default_toolbar_title">My Name</string>
```
Note that we don't consider this a public API so this may break between releases.  Use at your own risk.
