### ISSUE TITLE
FirebaseRecyclerAdapter implement getKey(int position) method.

### ISSUE THREAD

**Issue by runia1** [firebase/FirebaseUI-Android#262]
In FirebaseRecyclerAdapter please implement a new method.

```
public String getKey(int position) {
    return mSnapshots.getItem(position).getKey();
}
```

This is useful in cases where the list needs to be used for a join in order to get the data to display.  For example the adapter is passed the ref for a user's groups.  Inside populateViewHolder I could do something like this:
```
@Override
protected void populateViewHolder(GroupMessageViewHolder viewHolder, Notify notify, final int position) {
 String groupKey = mFirebaseAdapter.getKey(position);
 DatabaseReference dbr = FirebaseDatabase.getInstance().getReference().child(GROUPS_CHILD+"/"+groupKey);
        dbr. addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                Group g = dataSnapshot.getValue(Group.class);
                //populate view holder with group's data here.
            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.w(TAG, "Failed to read value.", error.toException());
            }
        });
}
```

**Comment by puf** [comment]
Try adapter.getRef(position).getKey()

**Comment by runia1** [comment]
@puf I think you meant 
```
mFirebaseAdapter.getRef(position).getKey();
```
but I see what you mean from the other issue you linked.  I was unaware DatabaseReference had that method.
Thank you!  I really appreciate how fast you guys respond!

**Comment by hari2babloo** [comment]
Thank

> @puf I think you meant
> 
> ```
> mFirebaseAdapter.getRef(position).getKey();
> ```
> 
> but I see what you mean from the other issue you linked. I was unaware DatabaseReference had that method.
> Thank you! I really appreciate how fast you guys respond!

Thankyou Brother
