### ISSUE TITLE
Unable to use FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by dalapati** [firebase/FirebaseUI-Android#264]
I am getting cannot resolve FirebaseRecyclerAdapter when trying to use it even after adding firebase ui in gradle dependency.Thanks in advance

**Comment by samtstern** [comment]
@dalapati I'll need more information to help you here.

Can you show me your `build.gradle` file?

**Comment by puf** [comment]
Cross-post:
http://stackoverflow.com/questions/39083826/unable-to-use-firebaserecycleradapter

**Comment by SUPERCILEX** [comment]
Solved in stackoverflow post.
