### ISSUE TITLE
Unable to build project when including FirebaseUI-Android as a .aar dependency

### ISSUE THREAD

**Issue by animeshjain** [firebase/FirebaseUI-Android#270]
### Environment

  * Android Studio 2.1.3
  * FirebaseUI-Android ver 0.5.1
  
### Problem

I was trying to do some customisation on the Firebase Android UI layouts. So I figured instead of pulling the default libraries from maven central, I'd import the aar file into my project as a library. However, Android studio now fails to compile my project with a errors like this -

```
/ExampleAndroidProject/app/build/intermediates/exploded-aar/ExampleAndroidProject/firebase-ui-auth-release/unspecified/res/layout/forgot_password_layout.xml
Error:(10) No resource identifier found for attribute 'errorTextAppearance' in package 'com.example.sample'
Error:(10) No resource identifier found for attribute 'hintTextAppearance' in package 'com.example.sample'
/ExampleAndroidProject/app/build/intermediates/exploded-aar/ExampleAndroidProject/firebase-ui-auth-release/unspecified/res/layout/register_email_layout.xml
Error:(15) No resource identifier found for attribute 'errorTextAppearance' in package 'com.example.sample'
Error:(15) No resource identifier found for attribute 'hintTextAppearance' in package 'com.example.sample'
Error:(35) No resource identifier found for attribute 'errorTextAppearance' in package 'com.example.sample'
Error:(35) No resource identifier found for attribute 'hintTextAppearance' in package 'com.example.sample'
Error:(55) No resource identifier found for attribute 'errorTextAppearance' in package 'com.example.sample'
Error:(55) No resource identifier found for attribute 'hintTextAppearance' in package 'com.example.sample'

```

#### Steps to reproduce

  1. Get the FirebaseUI .aar files by running prepareArtifacts task in gradle
  2. Import .aar files into the project as a module
  3. Set the module as a dependency to your project
 
See - https://developer.android.com/studio/projects/android-library.html#AddDependency

#### Other observations

* I cannot see the styles.xml inside the .aar file. Is this expected. The styles are however present in the values.xml
* I tried to compare if there was any difference between the folder structures or files when one defines the dependency via maven vs manually including the .aar. In the `app/build/intermediates/exploded-aar` folder the maven dependencies show up in a folder structure such as

 ```
com.firebaseui
  |- firebase-ui
    |- 0.5.1
      |- res
        |- values.xml
 ```
But if I include using .aar file the folder structure is as
 ```
ExampleAndroidProject
  |- firebase-ui-release
    |- unspecified
      |- res
        |- values.xml
 ```

**Comment by samtstern** [comment]
@animeshjain a few questions:

1. What are you trying to achieve by including an `aar`?  This is not something we normally support.  If you want to make customizations you can follow the instructions for installing locally.
1. Which `aar` files are you including?
1. Rather than importing the `aar` as a module, could you try including the `aar` directly?  See [this answer](http://stackoverflow.com/a/23326397/324977) on StackOverflow for some information.

**Comment by animeshjain** [comment]
Hey @samtstern,

1. I modified a layout file to suit the theme of the app and include some extra graphical elements. I might even have to include a check box for TnC in the login screen, which will require a modification. So I did that and built an `aar` and included it, isn't that what installing locally means? I don't have very deep Android knowledge but I was under the impression it was similar to including a `jar` file in a java project.
2. I tried including both `firebase-ui-auth-release.aar` and `firebase-ui-release.aar`. So basically in `build.gradle` for my project, instead of 

 ```
compile 'com.google.firebase:firebase-auth:9.4.0'
compile 'com.firebaseui:firebase-ui:0.5.1'
 ```
I included

 ```
compile project(':firebase-ui-auth-release')
compile project(':firebase-ui-release')
```

3. I am getting the same errors with this method as well. No luck!

Weird thing is that the `.aar` files are exactly the same (as evidenced by the same `exploded-aar` contents), whether they come from maven or I include them directly. Only their location is different inside `exploded-aar`.

**Comment by samtstern** [comment]
@animeshjain there are actually instructions for installing locally so you can avoid all of this `aar` stuff. Let's try that.

As you can see [here](https://github.com/firebase/FirebaseUI-Android#installing-locally) you can do the following:
  1. Go into the `constants.gradle` file and choose a new version for your version of FirebaseUI. How about `0.5.99`?
  2. In the FirebaseUI project make your changes and then run `./gradlew :library:prepareArtifacts :library:publishAllToMavenLocal` (like in the link above).
  3. In your application add `mavenLocal()` to your repositories right above where it currently says `jcenter()`.
  4. Then you can depend on `compile 'com.firebaseui:firebase-ui:0.5.99'` and have the library with your changes.

**Comment by animeshjain** [comment]
Yup this works pretty easy! Thank you Sam.

**Comment by samtstern** [comment]
@animeshjain glad we could work through it!  Going to close the issue now.
