### ISSUE TITLE
Remove enums in FirebaseArray

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#277]
Remove enums in FirebaseArray:
[Enums == bad](https://developer.android.com/training/articles/memory.html#Overhead) if you don't need them

**Comment by puf** [comment]
I recommend testing what the actual memory gains are from such a change. On a library with the amount of functionality that FirebaseUI offers, the impact of these enums on memory pressure is going to be minimal.

**Comment by samtstern** [comment]
@SUPERCILEX agree with @puf here, while Enums are not recommended it's not clear there will be a noticeable gain from making this change.

Also when replacing enums with `int` it's preferable to use [`@IntDef`](https://developer.android.com/reference/android/support/annotation/IntDef.html).

**Comment by SUPERCILEX** [comment]
Since you guys don't think there will be memory gains, I'll close this issue.
