### ISSUE TITLE
Deadlinks in README.md

### ISSUE THREAD

**Issue by indiumindeed** [firebase/FirebaseUI-Android#299]
Links to firebase-ui-database and firebase-ui-auth usage examples in README.md are dead.

**Comment by samtstern** [comment]
@indiumindeed good catch!  Would you mind submitting a PR to fix it?  If you don't want to, I will take this issue.

**Comment by SUPERCILEX** [comment]
I'm not seeing this issue. Are you talking about this readme: https://github.com/firebase/FirebaseUI-Android/blob/master/README.md#usage?

**Comment by JarmoKukkola** [comment]
Seems to work now. I do not know why but before the links did not work for me.

Issue can be closed.

**Comment by samtstern** [comment]
@all huh it does seem to have been transient.  Relative links in the README are something that Github encodes magically so maybe it was a Github issue.  Closing.
