### ISSUE TITLE
In FirebaseAuth cannot resolve method verifyIdToken() 

### ISSUE THREAD

**Issue by thomaskanzig** [firebase/FirebaseUI-Android#300]
Hello everyone,

I use Firebase Auth and I try the use [verifyIdToken()](https://firebase.google.com/docs/auth/server/verify-id-tokens) for decode my token generated by firebase sdk, but this method cannot resolve.

Please somebody can tell me which class must be dependency or show me an code example.
Thanks

**Comment by samtstern** [comment]
@thomaskanzig I don't think this has anything to do with `FirebaseUI` so I am going to close this issue, bu I'll see if I can help first.

That link you posted for `verifyIdToken()` is part of the Firebase **Server** SDK, which means it's not meant to work in Android code.

If you want to use the Firebase Java SDK on your server to verify ID tokens sent from a device, start here:
https://firebase.google.com/docs/server/setup#add_the_sdk
