### ISSUE TITLE
After I added dependencies on Android Studio, but I can't find it

### ISSUE THREAD

**Issue by starkshaw** [firebase/FirebaseUI-Android#31]
According to the README, I need `FirebaseLoginBaseActivity.java` however after I added dependencies this file is nowhere to find. What can I do next?

**Comment by puf** [comment]
Hi Zhenbang,

We just released 0.3, so it might still have been in flight. Are you sure
you are using 0.3.0?

     Frank

**Comment by hdioui** [comment]
Failed to resolve: com.firebase:firebase-ui:0.3.0
the only version available for me is 0.1.0 and give me the same problem as above

**Comment by puf** [comment]
Version 0.2 and above are in the com.firebaseui group.

So: com.firebaseui:firebase-ui:0.3.0
