### ISSUE TITLE
Leak in ChooseAccountActivity

### ISSUE THREAD

**Issue by javmarina** [firebase/FirebaseUI-Android#313]
- Android device: Sony Xperia Z (C6603)
- Android OS version: 5.0.2
- Google Play Services version: 9.6.83
- Firebase/Play Services SDK version: 9.4.0
- FirebaseUI version: 0.5.3
#### Steps to reproduce:

The only thing you have to do is sign in with an account and wait.
#### Observed Results:
- What happened?  This could be a description, `logcat` output, etc.

Using Leak Canary, got a leak report (com.javapps.iSwim is my app):

> In com.javapps.iSwim:1.0:1.
> - com.firebase.ui.auth.ui.ChooseAccountActivity has leaked:
> - GC ROOT android.app.LoadedApk$ServiceDispatcher$DeathMonitor.this$0
> - references android.app.LoadedApk$ServiceDispatcher.mConnection
> - references com.google.android.gms.common.internal.zzn$zzb$zza.yX
> - references com.google.android.gms.common.internal.zzn$zzb.yT
> - references java.util.HashSet.backingMap
> - references java.util.HashMap.table
> - references array java.util.HashMap$HashMapEntry[].[3]
> - references java.util.HashMap$HashMapEntry.key
> - references com.google.android.gms.common.internal.zzd$zzh.xG
> - references com.google.android.gms.auth.api.credentials.internal.zzg.mContext
> - leaks com.firebase.ui.auth.ui.ChooseAccountActivity instance
> - Retaining: 7,5 KB.
> - Reference Key: 2ff855ce-73e3-412f-afcc-f92d9bd4bc6b
> - Device: Sony Sony C6603 C6603
> - Android Version: 5.0.2 API: 21 LeakCanary: 1.4 6b04880
> - Durations: watch=5313ms, gc=157ms, heap dump=10212ms, analysis=77015ms
> - Details:
> - Instance of android.app.LoadedApk$ServiceDispatcher$DeathMonitor
>   |   mName = android.content.ComponentName@322252928 (0x13353080)
>   |   mService = android.os.BinderProxy@322240800 (0x13350120)
>   |   this$0 = android.app.LoadedApk$ServiceDispatcher@322028496 (0x1331c3d0)
> - Instance of android.app.LoadedApk$ServiceDispatcher
>   |   mActiveConnections = android.util.ArrayMap@322042432 (0x1331fa40)
>   |   mActivityThread = android.app.ActivityThread$H@315128544 (0x12c87ae0)
>   |   mConnection = com.google.android.gms.common.internal.zzn$zzb$zza@322023776 (0x1331b160)
>   |   mContext = com.javapps.iSwim.iSwim@315250848 (0x12ca58a0)
>   |   mIServiceConnection = android.app.LoadedApk$ServiceDispatcher$InnerConnection@322042464 (0x1331fa60)
>   |   mLocation = android.app.ServiceConnectionLeaked@322042528 (0x1331faa0)
>   |   mUnbindLocation = null
>   |   mDied = false
>   |   mFlags = 129
>   |   mForgotten = false
> - Instance of com.google.android.gms.common.internal.zzn$zzb$zza
>   |   yX = com.google.android.gms.common.internal.zzn$zzb@322028400 (0x1331c370)
> - Instance of com.google.android.gms.common.internal.zzn$zzb
>   |   xL = android.os.BinderProxy@322240800 (0x13350120)
>   |   yR = android.content.ComponentName@322252928 (0x13353080)
>   |   yS = com.google.android.gms.common.internal.zzn$zzb$zza@322023776 (0x1331b160)
>   |   yT = java.util.HashSet@322023792 (0x1331b170)
>   |   yV = com.google.android.gms.common.internal.zzn$zza@322042272 (0x1331f9a0)
>   |   yW = com.google.android.gms.common.internal.zzn@316087232 (0x12d71bc0)
>   |   mState = 1
>   |   yU = true
> - Instance of java.util.HashSet
>   |   static $staticOverhead = byte[8]@1874111721 (0x6fb4ace9)
>   |   static serialVersionUID = -5024744406713321676
>   |   backingMap = java.util.HashMap@322028448 (0x1331c3a0)
> - Instance of java.util.HashMap
>   |   static MINIMUM_CAPACITY = 4
>   |   static serialPersistentFields = java.io.ObjectStreamField[1]@1884607184 (0x7054d2d0)
>   |   static EMPTY_TABLE = java.util.HashMap$HashMapEntry[2]@1884607576 (0x7054d458)
>   |   static serialVersionUID = 362498820763181265
>   |   static $staticOverhead = byte[48]@1874107441 (0x6fb49c31)
>   |   static MAXIMUM_CAPACITY = 1073741824
>   |   static DEFAULT_LOAD_FACTOR = 0.75
>   |   entryForNullKey = null
>   |   entrySet = null
>   |   keySet = java.util.HashMap$KeySet@322746176 (0x133cb740)
>   |   table = java.util.HashMap$HashMapEntry[4]@322042368 (0x1331fa00)
>   |   values = null
>   |   modCount = 3
>   |   size = 1
>   |   threshold = 3
>   |   keySet = null
>   |   valuesCollection = null
> - Array of java.util.HashMap$HashMapEntry[]
>   |   [0] = null
>   |   [1] = null
>   |   [2] = null
>   |   [3] = java.util.HashMap$HashMapEntry@322042400 (0x1331fa20)
> - Instance of java.util.HashMap$HashMapEntry
>   |   key = com.google.android.gms.common.internal.zzd$zzh@322023760 (0x1331b150)
>   |   next = null
>   |   value = java.util.HashSet@322023792 (0x1331b170)
>   |   hash = -1513077
> - Instance of com.google.android.gms.common.internal.zzd$zzh
>   |   xG = com.google.android.gms.auth.api.credentials.internal.zzg@321760384 (0x132dac80)
>   |   xJ = 0
> - Instance of com.google.android.gms.auth.api.credentials.internal.zzg
>   |   do = null
>   |   aL = null
>   |   dT = java.util.Collections$UnmodifiableSet@322471488 (0x13388640)
>   |   tN = com.google.android.gms.common.internal.zzg@322508688 (0x13391790)
>   |   mContext = com.firebase.ui.auth.ui.ChooseAccountActivity@322474384 (0x13389190)
>   |   mHandler = com.google.android.gms.common.internal.zzd$zzd@322561568 (0x1339e620)
>   |   tz = com.google.android.gms.common.GoogleApiAvailability@316022080 (0x12d61d40)
>   |   xA = com.google.android.gms.common.internal.zzk$2@322471568 (0x13388690)
>   |   xC = java.lang.String@322388832 (0x13374360)
>   |   xD = java.util.concurrent.atomic.AtomicInteger@322471616 (0x133886c0)
>   |   xr = com.google.android.gms.common.internal.zzn@316087232 (0x12d71bc0)
>   |   xs = java.lang.Object@322471600 (0x133886b0)
>   |   xt = com.google.android.gms.common.internal.zzu$zza$zza@322746192 (0x133cb750)
>   |   xu = com.google.android.gms.internal.zzpw$zza@322704800 (0x133c15a0)
>   |   xv = com.google.android.gms.auth.api.credentials.internal.zzk$zza$zza@322746576 (0x133cb8d0)
>   |   xw = java.util.ArrayList@322561536 (0x1339e600)
>   |   xx = com.google.android.gms.common.internal.zzd$zzh@322023760 (0x1331b150)
>   |   xz = com.google.android.gms.common.internal.zzk$1@322471552 (0x13388680)
>   |   zzahv = android.os.Looper@315128448 (0x12c87a80)
>   |   zzail = java.lang.Object@322471584 (0x133886a0)
>   |   xn = 0
>   |   xo = 1474400720175
>   |   xq = 0
>   |   xB = 68
>   |   xm = 0
>   |   xp = 0
>   |   xy = 3
> - Instance of com.firebase.ui.auth.ui.ChooseAccountActivity
>   |   static RC_CREDENTIALS_READ = 2
>   |   static RC_IDP_SIGNIN = 3
>   |   static RC_PLAY_SERVICES = 6
>   |   static RC_AUTH_METHOD_PICKER = 4
>   |   static $staticOverhead = byte[48]@321200129 (0x13252001)
>   |   static RC_EMAIL_FLOW = 5
>   |   static TAG = java.lang.String@322388672 (0x133742c0)
>   |   mCredentialsApi = com.firebase.ui.auth.util.CredentialsAPI@322507920 (0x13391490)
>   |   mPlayServicesHelper = com.firebase.ui.auth.util.PlayServicesHelper@322470560 (0x133882a0)
>   |   mActivityHelper = com.firebase.ui.auth.ui.ActivityHelper@322391456 (0x13374da0)
>   |   mActionBar = null
>   |   mActivityInfo = android.content.pm.ActivityInfo@314815232 (0x12c3b300)
>   |   mActivityTransitionState = android.app.ActivityTransitionState@322324608 (0x13364880)
>   |   mAllLoaderManagers = android.util.ArrayMap@322704352 (0x133c13e0)
>   |   mApplication = com.javapps.iSwim.iSwim@315250848 (0x12ca58a0)
>   |   mComponent = android.content.ComponentName@315121920 (0x12c86100)
>   |   mContainer = android.app.Activity$1@322470304 (0x133881a0)
>   |   mCurrentConfig = android.content.res.Configuration@322349040 (0x1336a7f0)
>   |   mDecor = null
>   |   mDefaultKeySsb = null
>   |   mEmbeddedID = null
>   |   mEnterTransitionListener = android.app.SharedElementCallback$1@1884760064 (0x70572800)
>   |   mExitTransitionListener = android.app.SharedElementCallback$1@1884760064 (0x70572800)
>   |   mFragments = android.app.FragmentManagerImpl@322348816 (0x1336a710)
>   |   mHandler = android.os.Handler@322390592 (0x13374a40)
>   |   mInstanceTracker = android.os.StrictMode$InstanceTracker@322470320 (0x133881b0)
>   |   mInstrumentation = android.app.Instrumentation@314724768 (0x12c251a0)
>   |   mIntent = android.content.Intent@315179712 (0x12c942c0)
>   |   mLastNonConfigurationInstances = null
>   |   mLoaderManager = null
>   |   mMainThread = android.app.ActivityThread@314765568 (0x12c2f100)
>   |   mManagedCursors = java.util.ArrayList@322390528 (0x13374a00)
>   |   mManagedDialogs = null
>   |   mMenuInflater = null
>   |   mParent = null
>   |   mResultData = android.content.Intent@314599744 (0x12c06940)
>   |   mSearchManager = null
>   |   mTitle = java.lang.String@319438432 (0x130a3e60)
>   |   mToken = android.os.BinderProxy@315111136 (0x12c836e0)
>   |   mTranslucentCallback = null
>   |   mUiThread = java.lang.Thread@1945139216 (0x73f07810)
>   |   mVoiceInteractor = null
>   |   mWindow = com.android.internal.policy.impl.PhoneWindow@316593920 (0x12ded700)
>   |   mWindowManager = android.view.WindowManagerImpl@322391040 (0x13374c00)
>   |   mCalled = true
>   |   mChangeCanvasToTranslucent = false
>   |   mChangingConfigurations = false
>   |   mCheckedForLoaderManager = true
>   |   mConfigChangeFlags = 0
>   |   mDefaultKeyMode = 0
>   |   mDestroyed = true
>   |   mDoReportFullyDrawn = false
>   |   mEnableDefaultActionBarUp = false
>   |   mFinished = true
>   |   mIdent = 258009390
>   |   mLoadersStarted = false
>   |   mResultCode = -1
>   |   mResumed = false
>   |   mStartedActivity = false
>   |   mStopped = true
>   |   mTemporaryPause = false
>   |   mTitleColor = 0
>   |   mTitleReady = true
>   |   mVisibleBehind = false
>   |   mVisibleFromClient = true
>   |   mVisibleFromServer = true
>   |   mWindowAdded = true
>   |   mInflater = com.android.internal.policy.impl.PhoneLayoutInflater@322322288 (0x13363f70)
>   |   mOverrideConfiguration = null
>   |   mResources = android.content.res.Resources@315008928 (0x12c6a7a0)
>   |   mTheme = android.content.res.Resources$Theme@322391072 (0x13374c20)
>   |   mThemeResource = 2131427392
>   |   mBase = android.app.ContextImpl@321759488 (0x132da900)
> - Excluded Refs:
>   | Field: android.app.ActivityThread$ActivityClientRecord.nextIdle
>   | Field: android.view.inputmethod.InputMethodManager.mNextServedView
>   | Field: android.view.inputmethod.InputMethodManager.mServedView
>   | Field: android.view.inputmethod.InputMethodManager.mServedInputConnection
>   | Field: android.view.inputmethod.InputMethodManager.mCurRootView
>   | Field: android.animation.LayoutTransition$1.val$parent
>   | Field: android.view.textservice.SpellCheckerSession$1.this$0
>   | Field: android.support.v7.internal.widget.ActivityChooserModel.mActivityChoserModelPolicy
>   | Field: android.widget.ActivityChooserModel.mActivityChoserModelPolicy
>   | Field: android.accounts.AccountManager$AmsTask$Response.this$1
>   | Field: android.media.MediaScannerConnection.mContext
>   | Field: android.os.UserManager.mContext
>   | Field: android.appwidget.AppWidgetHost$Callbacks.this$0
>   | Field: android.media.AudioManager$1.this$0
>   | Field: android.widget.Editor$Blink.this$0
>   | Field: android.view.Choreographer$FrameDisplayEventReceiver.mMessageQueue (always)
>   | Static field: android.media.session.MediaSessionLegacyHelper.sInstance
>   | Static field: android.text.TextLine.sCached
>   | Thread:FinalizerWatchdogDaemon (always)
>   | Thread:main (always)
>   | Thread:LeakCanary-Heap-Dump (always)
>   | Class:java.lang.ref.WeakReference (always)
>   | Class:java.lang.ref.SoftReference (always)
>   | Class:java.lang.ref.PhantomReference (always)
>   | Class:java.lang.ref.Finalizer (always)
>   | Class:java.lang.ref.FinalizerReference (always)
#### Expected Results:
- What did you expect to happen?

No leak at all
#### Additional information

Leak Canary 1.4

**Comment by amandle** [comment]
I enabled Leak Canary but was unable to replicate this particular leak, could you please provide the exact steps you went through in the flow?

**Comment by SUPERCILEX** [comment]
This should be fixed in #357 because I cleaned up the smart lock stuff.

**Comment by GaborPeto** [comment]
I've also seen a Leak in ChooseAccountActivity in version 1.0.0
https://github.com/firebase/FirebaseUI-Android/issues/406

**Comment by SUPERCILEX** [comment]
Fixed in #357.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.0.1`.
