### ISSUE TITLE
Missing scroll to new item option (FirebaseRecyclerAdapter)

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#315]
I'm using the FirebaseRecyclerAdapter at many locations in my Firebase app. A function that is miss is (optional) automatic smooth scrolling to newly inserted items: add this moment it happens that a user inserts an item (using a FAB button) but when the item is added outside of the to him visible items, it looks like nothing happens.
Since we can only override the populateView method, I see no way to implement this properly with the current implementation.

**Comment by samtstern** [comment]
@peterhav it's actually not hard to do achieve this, using an `AdapterDataObserver`.  We do it in our `friendlychat` sample here:
https://github.com/firebase/friendlychat/blob/master/android/app/src/main/java/com/google/firebase/codelab/friendlychat/MainActivity.java#L160

In case that goes away in the future, I will post an example here for good measure:
```java
 mFirebaseAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onItemRangeInserted(int positionStart, int itemCount) {
                super.onItemRangeInserted(positionStart, itemCount);
                int friendlyMessageCount = mFirebaseAdapter.getItemCount();
                int lastVisiblePosition = mLinearLayoutManager.findLastCompletelyVisibleItemPosition();

                // If the recycler view is initially being loaded or the user is at the bottom of the list, scroll
                // to the bottom of the list to show the newly added message.
                if (lastVisiblePosition == -1 ||
                        (positionStart >= (friendlyMessageCount - 1) && lastVisiblePosition == (positionStart - 1))) {
                    mMessageRecyclerView.scrollToPosition(positionStart);
                }
            }
        });
```
