### ISSUE TITLE
How import verifyIdToken() method?????

### ISSUE THREAD

**Issue by thomaskanzig** [firebase/FirebaseUI-Android#316]
Hi guys, I try to decode my token generated from firebase sdk, but the method cannot resolved....
How can I import this method?? Which firebase class??

The code is this here below:

```java
FirebaseAuth.getInstance().verifyIdToken(idToken)
    .addOnSuccessListener(new OnSuccessListener<FirebaseToken>() {
        @Override
        public void onSuccess(FirebaseToken decodedToken) {
            String uid = decodedToken.getUid();
            // ...
        }
});
```

**Comment by samtstern** [comment]
The `verifyIdToken` method is part of the Firebase Java **Server** SDK and is not available on Android or any other **client** SDKs.

The intended usage is for you to use `FirebaseUser.getToken()` on the client to get a token to send to your server, where you use `verifyIdToken` to verify the user's identity.
