### ISSUE TITLE
While sign in the logcat says " com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred."

### ISSUE THREAD

**Issue by SenthilEternus** [firebase/FirebaseUI-Android#319]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by SenthilEternus** [comment]
I have created users in the firebase console not from the signup activity as to let only some users to sign in to the app as of now. I have set the AuthStateListener and called the signInWithEmailAndPassword method as per the guideline in the following URL : https://firebase.google.com/docs/auth/android/password-auth 

I am giving the correct user name and password but it is not signing in and when I am checking in the logcat console it shows the above error. Could you please help me with this?

**Comment by samtstern** [comment]
@SenthilEternus please use the issue template in the future, it's there so we can help you.

The error description implies you don't have a good network connection.  Are you sure your device is online and that you can establish a connection to Google?

**Comment by SenthilEternus** [comment]
I checked the device's internet connection before it was working fine and it was there but somehow it was disconnected :( I am really sorry for this silly mistake I have done. Now it is working fine. Thanks for your immediate reply @samtstern . Next time I will use the issue template if I have any issue in FirebaseUI.

**Comment by TapanHp** [comment]
I am facing same issue right now, i have checked my internet connection it's pretty good, but every time it shows same error. @samtstern

**Comment by mikethedon** [comment]
Please help me too. My internet is working fine and yet my app keep saying com.google.firebase.FirebaseNetworkException: A network error (such as timeout, interrupted connection or unreachable host) has occurred."

**Comment by Soumya7391** [comment]
I am facing the same issue. But only for Android OS version 5.1.1 
Please revert soon.
