### ISSUE TITLE
Consider using Dart/Henson libraries

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#320]
https://github.com/f2prateek/dart

We do a lot of communication via inter-Activity Intents with Intent extras.  This is error prone and hard to reason about.

The Dart library (no relation to the language) makes it easy to define contracts across activities and reduce boilerplate.

**Comment by puf** [comment]
Are you looking to include this in the library? Or in the sample app?

The latter I'm fine with. But including another library in our library is
something I'd prefer to not do (lightly).

**Comment by samtstern** [comment]
Was looking to include it in the library.

**Comment by samtstern** [comment]
I no longer plan to do this, helper methods are just as good.
