### ISSUE TITLE
Failed to resolve: com.firebaseui:firebase-ui-storage:0.6.0

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#325]
`Error:Failed to resolve: com.firebaseui:firebase-ui-storage:0.6.0`

Getting this error when upgrading from `compile 'com.firebaseui:firebase-ui:0.5.3'` to `compile 'com.firebaseui:firebase-ui:0.6.0'`.

@samtstern Any ideas?

**Comment by ahaverty** [comment]
I'm also seeing this for -storage too.

**Comment by samtstern** [comment]
Are you trying to pull from jcenter or Maven Central?

**Comment by ahaverty** [comment]
jcenter

**Comment by SUPERCILEX** [comment]
It's working for me with Play Services 9.6.1.

@ahaverty Any luck?

**Comment by samtstern** [comment]
My jcenter inclusion for the package just got approved so this should be
fixed now.  Sorry, didn't know there would be a delay!

**Comment by SUPERCILEX** [comment]
Awesome!
