### ISSUE TITLE
AuthUI flow starts twice when rotated

### ISSUE THREAD

**Issue by danielmai** [firebase/FirebaseUI-Android#338]
### Step 2: Describe your environment

  * Android device: Nexus 5X (x86_64 emulator)
  * Android OS version: 6.0
  * Google Play Services version: 9.6.83 (480-133155058)
  * Firebase/Play Services SDK version: 9.6.1
  * FirebaseUI version: 0.6.0
  
### Step 3: Describe the problem:

  * After starting the AuthUI flow and rotating the device, completing the sign in starts a second AuthUI flow.

#### Steps to reproduce:

  1. Start AuthUI flow (with `startActivityForResult(...)`)
  2. Rotate device
  3. Complete sign in process
  
#### Observed Results:

  * After Step 3, AuthUI starts again when completed.
  
#### Expected Results:

  * I expected to return back to the main activity instead of starting another AuthUI sign in flow.
  
#### Relevant Code:

Create a new Android Studio project (Empty Activity template is fine) and add the following `// ADDED` code to the main activity to start the AuthUI flow in onCreate:

  ```
public class MainActivity extends AppCompatActivity {

    // Added
    private static final int RC_SIGN_IN = 1;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        // Added
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setIsSmartLockEnabled(false)
                        .build(),
                RC_SIGN_IN);
    }
}
  ```

**Comment by samtstern** [comment]
@danielmai this seems to be working as intended, although I agree there is room for improvement.  `onCreate` is called every time you rotate the device, and you're launching a new auth `Intent` each time `onCreate` is called, so I would expect multiple instances of FirebaseUI to start in the app as you have coded it.

**Comment by danielmai** [comment]
Ah, that makes sense. Thanks for taking the time to help, @samtstern.
