### ISSUE TITLE
Login with google hangs with spinner

### ISSUE THREAD

**Issue by mihai-chiorean** [firebase/FirebaseUI-Android#34]
Tried this in the emulator. Used firebase UI. Fired up the dialog, clicked the login with google button, it just hangs on a spinner. Didn't hit a breakpoint in either onXXX handlers. Just hangs. Can't find any logs from the firebase library either.

**Comment by puf** [comment]
I'm having the same problem in the emulator. It works fine on a physical device, but my main activity is showing a blank screen after adding Google auth. I'll let you know if we discover what causes this problem.

**Comment by mihai-chiorean** [comment]
thank you!!

**Comment by mihai-chiorean** [comment]
An update here: Tried on my phone. It worked here, but as soon as I selected a google account, I got this:
`failed: User closed login dialog.`

**Comment by puf** [comment]
I'll consider that progress. :-)   I've tested on various emulators, but all are failing with similar symptoms. I would've given up, except that the sample app that comes with FirebaseUI-Android opens the login dialog without problems.

I'll give it a try on a physical device tomorrow. I know multiple people tested that flow, but that may all have been with the sample app.

**Comment by frto** [comment]
Hi, I tested RecyclerViewDemoActivity on a Samsung S4 running Android 5.0.1. Google login and hereafter reading from my firebase app works fine the first time. Logout and again login results in a hanging spinner. Restarting the app and we can again login/logout for one time.

**Comment by puf** [comment]
OK. Just tried this on some more "devices":

1. on the Android emulator with a Nexus 5X image I always get a blank popup, even with just the password provider. Interestingly enough the controls seem to be in there, as I can click and tab. So it's likely a rendering issue.
2. on the Genymotion emulator with a Nexus 5X image I get a popup for the password provider. But when I enable the google provider, I get an exception. Most likely my device is missing Google Play Services.
3. on a physical Nexus 7, I get the popup but am having some other issues. I'll keep digging.

I'm going to re-assign this issue to @abehaskins for fixing the layout issue. Let's treat the others as separate issues. That includes the one you just submitted a PR for @frto .

**Comment by frto** [comment]
Hi all, tested again on Samsung S4 and issue is indeed solved now. Thanks for this!
I removed my pull request cause the proper solution is indeed commit 625cc85.

**Comment by puf** [comment]
Thanks for testing Frederik! The fix will be in the next release. We're
still working on some more fixes that need to go in there.

**Comment by troy21688** [comment]
What is the fix? I am receiving an error after I select an account that says "User Closed Login Dialog." Any help is appreciated.

**Comment by hocinehamdi** [comment]
There is a problem in GoogleAuthProvider.java

`public void onActivityResult(int requestCode, int resultCode, Intent data) {
        if (requestCode == GoogleActions.SIGN_IN && resultCode == -1) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            handleSignInResult(result);
        }

        if (requestCode == GoogleActions.SIGN_IN && resultCode == 0) {
            Log.d(TAG, data.getExtras().keySet().toString());
            getHandler().onUserError(new FirebaseLoginError(FirebaseResponse.LOGIN_CANCELLED, "User closed login dialog."));
        }
    }`

In the Google Doc it was specified like this:

`public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == RC_SIGN_IN) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            handleSignInResult(result);
        }
    }`

https://github.com/googlesamples/google-services/blob/master/android/signin/app/src/main/java/com/google/samples/quickstart/signin/SignInActivity.java#L136-L139

**Comment by snigavig** [comment]
Hello, sorry to bother you, but I'm still stuck on this error. Using firebase-ui:0.3.1
Could you please check it?
