### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#345]
There are a bunch of stale branches that have been merged and should be deleted:
 * yg-chat-demo-activity
 * alfongj-readme
 * puf-fix-password
 * puf-kill-switches
 * samtstern-patch-1
 * ianbarber-patch-1

**Comment by samtstern** [comment]
@SUPERCILEX :+1: I went and deleted a whole bunch of branches, including those.

**Comment by SUPERCILEX** [comment]
Thanks! Looks much cleaner now. 👍
