### ISSUE TITLE
Add Github as an IDP

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#346]
Tracked on IOS too: https://github.com/firebase/FirebaseUI-iOS/issues/275

**Comment by samtstern** [comment]
@SUPERCILEX this is definitely on the long-term roadmap because it's supported by Firebase Auth.  However it's a little more complicated due to how Github does OAuth.

FYI: for version `1.0.0` the plan is to add Twitter (already done on a branch)

**Comment by SUPERCILEX** [comment]
Awesome!

**Comment by sc4ryb3ar** [comment]
@samtstern So, essentially what you're saying is; there's practically not much of a way to use it in it's current form?

**Comment by samtstern** [comment]
@sc4ryb3ar you can use Github with Firebase (and some apps do) but not with FirebaseUI.

**Comment by sc4ryb3ar** [comment]
@samtstern do you, by any chance, know of any open source projects, or full code samples that I could peruse? I'm have a heck of a time getting the login auth code working right?

**Comment by rogerbosman** [comment]
Any updates on this? I'd like to add GitHub now if possible :)

**Comment by SUPERCILEX** [comment]
@rogerbosman Go for it! If you don't want to figure out how to integrate it with FirebaseUI, just show me a way to get an OAuth token from Chrome Custom Tabs and I'll see about getting Github integrated into FirebaseUI. (I suck at the OAuth stuff, so if you know how to do it, please show me!)

**Comment by SUPERCILEX** [comment]
Hi everyone, it's finally coming! Approaching 2 years later, but here it is: https://github.com/firebase/FirebaseUI-Android/pull/1199. 😆

**Comment by samtstern** [comment]
This has been released in version `4.1.0`
