### ISSUE TITLE
How to partly populate a FirebaseRecyclerAdapter ?

### ISSUE THREAD

**Issue by afaucogney** [firebase/FirebaseUI-Android#35]
I do need to populate a recyclerAdapter partly. I mean that some item will be removed or even not displayed ever:

Use cases:
- give the ability to no display ever an item (e.g from item child value)
- If a user get the possibility to discard an item.

I assume the FirebaseRecyclerAdapter is strongly link with the FB Database. I there any trick or way to do that, by getting access to the Snapshop ?

Is there any plan for clean Api on that way ?

**Comment by puf** [comment]
With FirebaseUI you don't manipulate the items in the view directly. Instead, you update the item in the Firebase database and ensure that your view shows the correct set of items.

To handle deleting an item, you'll need to capture the event from the user on the RecyclerView. Once you have that, you'll also have the position of the item the user interacted with. With that position, you can do the following:

I'll leave it to you to figure out what item the user clicked on (but this might be a good start).

Once you know the position of the item the user clicked on, you can remove it from Firebase easily with:

    Firebase itemRef = adapter.getRef(position);
    itemRef.removeValue();

This will remove the item from the database, from the adapter and from the view.

Also see http://stackoverflow.com/questions/34028599/firebase-android-studio-remove-item-from-firebaselistadapter

**Comment by afaucogney** [comment]
@puf  What about user specific filtering ? I need to not display an item for a specific user, not removing the item itself from the base.

Any idea how we can do that with FBUI ? Or should I use the "standard SDK" ?

In any case, I think this is a common need.

**Comment by puf** [comment]
Downloading a value that you're not displaying to the user is wasting bandwidth, which is especially bad on mobile. The built-in filtering of the SDK happens server-side, prevents the need to download the data. We intend to eventually add filtering to FirebaseUI (see https://github.com/firebase/FirebaseUI-Android/issues/15), but that will likely mean client-side filtering.

**Comment by afaucogney** [comment]
Yes, ofcourse this is not the most efficient, but we both know that built-in filtering is still (very) limited at the moment. (lack of multi-filtering dimension & lack of reverse (opposite order) operator & Collection Normalization or equivalent).

This would be required for at least for the 2 following use cases:
- user specific search/filtering (if not using the gateway to elasticsearch)
- if user want to discard the viewholder after it has been displayed (for what ever "user" reason (understood, no need, already saw, already known))

**Comment by mykisaacs** [comment]
On the FirebaseRecyclerAdapter constructor use a Query object that has your sorted/filtered criteria instead of the DatabaseReference (4th parameter).
