### ISSUE TITLE
AuthMethodPickerActivity is started multiple times

### ISSUE THREAD

**Issue by Alex100** [firebase/FirebaseUI-Android#354]
- Start the firebase demo (version-0.6.0) 
- Rotate the device during the Smartlock account chooser dialog (called by the `ChooseAccountActivity` in `resolveSavedEmails(Activity activity)`)

![image](https://cloud.githubusercontent.com/assets/4115023/19347879/5f1d2a4e-914b-11e6-8c7d-08c0d5c2fc72.png)
- Press the back button multiple times until the `AuthMethodPickerActivity` is visible

![image](https://cloud.githubusercontent.com/assets/4115023/19348136/ab287276-914c-11e6-9960-e75795fbd7d8.png)
- Then the `AuthMethodPickerActivity` is multiple times on the activity stack

The reason for that behaviour is that Smartlock account chooser dialog activity is started every time you rotate the device. This results in multiple calls of `onActivityResult` in ChooseAccountActivity, which starts every time the `AuthMethodPickerActivity`.

**Comment by SUPERCILEX** [comment]
This is fixed in #357.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.0.1`.
