### ISSUE TITLE
enabling native ads within FirebaseRecyclerView adapter

### ISSUE THREAD

**Issue by mahmoudelfeel** [firebase/FirebaseUI-Android#360]
is there a way to put native ads every like 10 posts withing the adpater i tried but i failed

**Comment by samtstern** [comment]
@mahmoudelfeel this is not a feature of the library and it's something you'd have to implement yourself.  Try overriding [`getItem()` and  `getItemCount()`](https://github.com/firebase/FirebaseUI-Android/blob/a86fdb50e65bbc92a8619c57544e47e967e7f87b/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java#L137-144) to insert a custom element for every ~10th item.
