### ISSUE TITLE
Audit all uses of IdentityProviders constants

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#361]
See #356, when adding Twitter we clearly missed a few spots.  The safest thing to do here is check every time the `GOOGLE` or `FACEBOOK` constants are referenced and then make sure `TWITTER` is also referenced in appropriate.

In the long term, the responsibility should probably be inverted so that we don't have to go hunting through the codebase each time an IDP is added.

**Comment by amandle** [comment]
Resolved with #366
