### ISSUE TITLE
Automatically send verification email upon account creation

### ISSUE THREAD

**Issue by forneverafter** [firebase/FirebaseUI-Android#387]
Hi!
I'm new to GitHub, but would really love to contribute my two cents.
I want to add a new boolean parameter to FlowParameters.java called sendVerificationEmail which could be implemented in the `registerUser` method of RegisterEmailActivity.java . My plan is to add 

`     //Send verification email`
`      if (mActivityHelper.getFlowParams().sendVerificationEmail) {
           firebaseUser.sendEmailVerification();
      }`

in  .addOnSuccessListener .

Then I could just code

`startActivityForResult(`
                    `AuthUI.getInstance()`
                            `.createSignInIntentBuilder()`
                            `.setIsSmartLockEnabled(true)`
                            `.sendVerificationEmail(true)`
                            `.setProviders(AuthUI.EMAIL_PROVIDER)`
                            `.build(),`
                    `RC_SIGN_IN);`

in my activity.
I've found that it is really clunky to try to catch a result showing that the user created a new account, because I am only using the `AuthUI.EMAIL_PROVIDER`.

Also, what do you think would be the best way to notify the user to check their email account and verify? I thought about changing

`<string name="progress_dialog_signing_up">Signing up…</string>`
to
`<string name="progress_dialog_signing_up">Sending verification email to</string>`
and change line 255
`mActivityHelper.showLoadingDialog(R.string.progress_dialog_signing_up);`
to
`mActivityHelper.showLoadingDialog(getResources().getString(R.string.progress_dialog_signing_up) +
                " " + email);`

Thank You,
Winston

**Comment by samtstern** [comment]
Thanks for the idea(s) @forneverafter .

I think what you're saying is a totally valid feature request, but I think it exposes a larger need.  In general, I think FirebaseUI could do a better job returning more information to the app at the end of the flow (did the user sign up?  Was it a new account?  What provider was used?  etc).  Rather than add boolean parameters for each option a developer might want, if we return more information at the end of the flow you could then do things like send verification email yourself.

Would getting more information about new vs existing account as a result of the sign-in flow solve your use case?

**Comment by forneverafter** [comment]
Your right! I think it makes way more sense to pass this back as a key/value in an Intent to onActivityResult. That will work perfect for me, but I do think sending a verification email is par for the course in email authentication. Thanks and I can help in whatever way necessary.

**Comment by SUPERCILEX** [comment]
I think this could be part of v2:

- #309 (anonymous authentication)
- #357 which breaks the public api but makes things much faster and prettier and #374 
- As part of the #357 public api rewrite, we could directly return `IdpConfig` and include methods such as `getPrevUid()` for #309, `isNewUser()` for this issue and so on.

**Comment by samtstern** [comment]
Marking this as a duplication of #312 that's the earliest issue to track email verification requests.
