### ISSUE TITLE
FirebaseUI Demo not work in Phonegap

### ISSUE THREAD

**Issue by richarddiogo** [firebase/FirebaseUI-Android#388]
https://i.stack.imgur.com/5ScPX.png

**Comment by samtstern** [comment]
@richarddiogo a few things:

1. Please use the issue template, it is there so we can help you.
1. This seems like a bug with firebaseui-web, I'd recommend filing the issue over there.  If you choose to do that, please provide more information than a screenshot or they will have a hard time helping you.
