### ISSUE TITLE
Add support for ordering/transforming data from Firebase Database before displaying it

### ISSUE THREAD

**Issue by morganchen12** [firebase/FirebaseUI-Android#389]
One of our most requested database features is being able to sort/order/transform stuff from database before displaying it in a view. Mirrors https://github.com/firebase/FirebaseUI-iOS/issues/183

**Comment by SUPERCILEX** [comment]
Possible duplicate of #15.

**Comment by samtstern** [comment]
Cleaning old issues and this is a duplicate of #15.
