### ISSUE TITLE
Feature request: proguard configuration in the library

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#397]
-Firebase/Play Services SDK version:  9.8.0
-FirebaseUI version: 1.0.0

After upgrading to version 1.0.0 the release build (using proguard) fails. I solved this by adding -ignorewarnings to my app's proguard configuration, but IMHO a better apporach would be a library specific proguard configuration as part of this library.

**Comment by samtstern** [comment]
@peterhav what Proguard rules did you have to add?

**Comment by peterhav** [comment]
It seems that adding this single line makes the release build (with Proguard step) runs OK again:

`-dontwarn retrofit2.**`

After the update from 0.6.2 to 1.0.0 proguard reports these warnings and fails the build:

```
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandle
Warning: retrofit2.Platform$Java8: can't find referenced class java.lang.invoke.MethodHandles$Lookup
Warning: retrofit2.Platform$Java8: can't find referenced class org.codehaus.mojo.animal_sniffer.IgnoreJRERequirement

* What went wrong:
Execution failed for task ':app:transformClassesAndResourcesWithProguardForRelease'.
> java.io.IOException: Please correct the above warnings first.
```

Adding the above line to my proguard configuration makes the build run again. I have (not yet) encountered any functionality that is not working correclty in the obfuscated release build (but then again I'm only using the Google and Email sign in methods).

Thanks for the huge steps made in the 1.0.0 release!

**Comment by GaborPeto** [comment]
I also have to add `-dontwarn okio.**`

**Comment by samtstern** [comment]
@GaborPeto @peterhav I can confirm both of these lines are needed.  I'll see about a fix.

**Comment by samtstern** [comment]
@GaborPeto @peterhav  see https://github.com/firebase/FirebaseUI-Android/pull/413

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.0.1`.

**Comment by oscardelgado** [comment]
I have this issue, with firebase-ui-auth:2.1.1

**Comment by nathanvogel** [comment]
I'm also having this issue with firebase-ui-auth:2.2.0
It was solved when adding this to Proguard: 
`-dontwarn retrofit2.**`
