### ISSUE TITLE
[Known Issue] NoSuchMethodError: No virtual method launchUrl

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#398]
There is a known issue in the `1.0.0` release that can occur when using Facebook login with the optional Chrome Custom Tabs configuration and support library version `25.x`.  There is a fix being discussed in #396.

Some known workarounds:
  * Do not use Chrome Custom tabs with Facebook login
  * Downgrade your application to support libraries `24.x`

If the above workarounds do not solve the issue, please chime in so we can further diagnose.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.0.1`.

**Comment by lawloretienne** [comment]
I think this is still an issue with Custom Tabs
http://stackoverflow.com/questions/40319860/com-android-supportcustomtabs-no-virtual-method-launchurl

This is still an issue with the following dependencies : compile "com.android.support:customtabs:25.0.1" and compile 'com.facebook.android:facebook-android-sdk:4.19.0'

**Comment by SUPERCILEX** [comment]
@lawloretienne you're mixing support library versions. Please use `v25.1.0` to use the same version as FirebaseUI and see if that fixes it.

**Comment by lawloretienne** [comment]
so i'm not using firebase at the moment, but i noticed this same issue of facebook login and custom tabs was documented here.

**Comment by SUPERCILEX** [comment]
@lawloretienne Got it, check out our [`build.gradle` file](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/build.gradle#L44). You basically need to include all of the support libraries Facebook uses and override them with the version of the support library you are using to prevent incompatibilities.

**Comment by lawloretienne** [comment]
Got it. That worked.  Looks like these dependencies can get very brittle sometimes.  Wish it wasn't the case.

**Comment by SUPERCILEX** [comment]
@lawloretienne Glad to hear the issue was fixed!
