### ISSUE TITLE
Digits auth button

### ISSUE THREAD

**Issue by rostopira** [firebase/FirebaseUI-Android#403]
# Feature request

Please, add Digits auth provider. It's supported as well as twitter (digits accounts appearing as twitter in console) # #

**Comment by ryanrain** [comment]
Hi all, 
Any update on whether work will be done to support user authentication via SMS now that Fabric (including Digits) has been acquired by Google? I'm planning a project and hoping to get an idea of timelines.
Thanks everyone for all your work!
-ryan

**Comment by samtstern** [comment]
@ryanrain right now this work has not been started and I can't offer any timelines for when it might be done.  We are getting to know the Fabric team, in the long term I think we'll build some exciting things together.

**Comment by ryanrain** [comment]
thanks for the quick response @samtstern 
guess i should just keep an eye on the [firebase blog](https://firebase.googleblog.com/), no? 
thanks a lot! and of course my big +1 for digits as a top priority

**Comment by ArtMartiros** [comment]
+1

**Comment by samtstern** [comment]
We're going to bring Phone Auth soon with the help of the digits team!  See #716.
