### ISSUE TITLE
Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference 

### ISSUE THREAD

**Issue by alssory** [firebase/FirebaseUI-Android#408]
### Step 2: Describe your environment

  * Android device: Galaxy S4
  * Android OS version: 5.0.1
  * Google Play Services version: 7.1.15
  * FirebaseUI version: 1
  
#### Steps to reproduce:

  1. Sign in and go to another activity(Activity1)
  2. Press on signOut button in (Activity1)
  3. The app crash
  
#### Observed Results:

java.lang.RuntimeException: Unable to start activity ComponentInfo{*****.****.firebaserules/com.firebase.ui.auth.ui.email.SignInActivity}: java.lang.NullPointerException: Attempt to read from field 'int com.firebase.ui.auth.ui.FlowParameters.themeId' on a null object reference

  
#### Expected Results:

signOut from account and go to signInActivity
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
//onClick
public void signOut(View view) {
            AuthUI.getInstance()
                    .signOut(this)
                    .addOnCompleteListener(new OnCompleteListener<Void>() {
                        public void onComplete(@NonNull Task<Void> task) {
                            // user is now signed out
                            startActivity(new Intent(MainActivity.this, SignInActivity.class));
                            finish();
                        }
                    });
    }
  ```

versions:
 'com.firebaseui:firebase-ui:1.0.0'
'com.google.gms:google-services:3.0.0'

**Comment by SUPERCILEX** [comment]
You can't just start the AuthUI flow manually, see the proper way to start a sign in flow: https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#sign-in

**Comment by samtstern** [comment]
@alssory please see the advice above.
