### ISSUE TITLE
Activity not found, when used build flavors

### ISSUE THREAD

**Issue by Belobobr** [firebase/FirebaseUI-Android#410]
Hey! I have a problem with build flavors and firebase auth ui

Environment

  * Google Play Services version: 24.2.1
  * Firebase/Play Services SDK version: 9.8.0
  * FirebaseUI version: 1.0.0
  
When i add firebase auth ui dependency and default activity declared in  build flavor android.manifest , then have an error: "Activity not found". When i declare it in common android.manifest - everything fine.

I want to use different launch activity in my build flavor.

**Comment by samtstern** [comment]
Can you provide a little more information?  What's the activity that is not
found?  What error message do you get?

**Comment by samtstern** [comment]
@Belobobr this issue has been open for 3 weeks without a response so I am going to close it.  Please re-open if you're still having this issue and can provide more information.
