### ISSUE TITLE
A question about the FirebaseIndexRecyclerAdapter

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#411]
* Android device: Nexus 6P
  * Android OS version: Nougat 7.1.1
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 9.8.0
  * FirebaseUI version: 1.0.0

The documentation for the [`FirebaseIndexRecyclerAdapter`](https://github.com/firebase/FirebaseUI-Android/blob/master/database/README.md#using-firebaseui-with-indexed-data) is pretty sparse, not even providing an extended example like the one provided for the regular `FirebaseRecyclerAdapter`.

I'm using FirebaseUI version 1.0.0 for the record.

I tried to implement a subclass of the adapter while updating my project's Firebase Database to fit the recommended way to index objects, and the items weren't populated like expected. @SUPERCILEX, since you authored the commits, could you give some guidance?

My simplified database:

    {
      shopItems: {
        randomKey1: {
          name: "Item 1",
          description: "Just an item"
        },
        randomKey2: {
          name: "Item 2",
          description: "Just an item"
        }
      },
      users: {
        randomUserId1: {
          shopItems: {
            randomKey1: true,
            randomKey2: true
          }
        }
      }
    }

My simplified implementation:

    FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
    DatabaseReference keyRef = FirebaseDatabase.getInstance().getReference().child("users")
            .child(user.getUid()).child("shopitems");
    DatabaseReference dataRef = FirebaseDatabase.getInstance().getReference().child("shopItems");

    RecyclerView userShopItemList = (RecyclerView) findViewById(R.id.list_user_shop_item);
    userShopItemList.setAdapter(new FirebaseIndexRecyclerAdapter<ShopItem, ShopItemHolder>(ShopItem.class, R.layout.shop_item_viewholder, ShopItemHolder.class, keyRef, dataRef) {
        @Override
        public void populateViewHolder(ShopItemHolder viewHolder, ShopItem item, int position) {
            viewHolder.setName(item.getName());
            viewHolder.setDescription(item.getDescription());
        }
    });

The end result is no items being visibly populated.

If you're wondering, the `ShopItemHolder` is basically a `RecyclerView.ViewHolder` subclass with two methods to set an item's name and description.

**Comment by SUPERCILEX** [comment]
I think you might have made a typo:
`DatabaseReference keyRef = ref.child("users").child(user.getUid()).child("shopitems"); // Should be "shopItems"`

If that is not it, are you calling `super(viewHolder)` in `ShopItemHolder`?

**Comment by TheCraftKid** [comment]
Actually, that typo isn't in the real code. Also, yes, I am calling super(viewHolder) in the ViewHolder class.

**Comment by SUPERCILEX** [comment]
Hmmm, I'm not sure what's going on. Could you check the logs for warnings and errors?

**Comment by SUPERCILEX** [comment]
With the added complexity of the index adapter, there 3 possible sources of failure:

1. A `DatabaseError` occurs retrieving the keys
2. A `DatabaseError` occurs retrieving the data
3. One or several keys are not found at the data location

**Comment by TheCraftKid** [comment]
Okay, I didn't see any errors in the logs. I'm curious, how would you implement a subclass? I didn't see any new updates to the sample app...

**Comment by SUPERCILEX** [comment]
Okay, I'm stumped then. I'll show you how I'm implementing my adapter (which includes using a subclass) and you can see if you're doing anything different. At this point, you'll just have to step through your code line by line because I don't see anything wrong. BTW, did this work with a `FirebaseRecyclerAdapter` before? If you jumped straight to `FirebaseIndexRecyclerAdapter`, could you show me your xml so I can see what you're doing there?

Here's a simplified version of what I'm doing:
Also, make sure you're online and check your security rules to make sure it isn't something dumb like that (though there should have been logged warnings if it was a security rule problem).

Setup:
```java
mAdapter = new TeamAdapter(
        Team.class,
        R.layout.team_list_row_layout,
        TeamHolder.class,
        BaseHelper.getDatabase().child(Constants.FIREBASE_TEAM_INDICES).child(BaseHelper.getUid()),
        BaseHelper.getDatabase().child(Constants.FIREBASE_TEAMS));
mManager = new LinearLayoutManager(this);
mTeams = (RecyclerView) findViewById(R.id.list);
mTeams.setHasFixedSize(true); // Improves performance if the size of your list items doesn't change dynamically
mTeams.setLayoutManager(mManager);
mTeams.setAdapter(mAdapter);
```

Subclass:
```java
public class TeamAdapter extends FirebaseIndexRecyclerAdapter<Team, TeamHolder> {
    public TeamAdapter(Class<Team> modelClass,
                       int modelLayout,
                       Class<TeamHolder> viewHolderClass,
                       Query keyRef,
                       Query dataRef) {
        super(modelClass, modelLayout, viewHolderClass, keyRef, dataRef);
    }

    @Override
    public void populateViewHolder(TeamHolder teamHolder, Team team, int position) {
        teamHolder.bind(team);
    }
}
```

Simplified viewHolder:
```java
public class TeamHolder extends RecyclerView.ViewHolder {
    private TextView mNumber;

    @Keep
    public TeamHolder(View itemView) {
        super(itemView);
        mNumber = (TextView) itemView.findViewById(R.id.number);
    }

    public void bind(Team team) {
        mNumber.setText(team.getNumber());
    }
}
```

xml:
```xml
<?xml version="1.0" encoding="utf-8"?>
<android.support.v7.widget.RecyclerView
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:id="@+id/list"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:clipToPadding="false"
    android:paddingBottom="8dp"
    android:paddingTop="8dp"/>
```

Sample data:
```json
{
  "team-indices" : {
    "kH9e42L9NkNv8AHN0Uhs4fGb4T13" : {
      "-KX3j5Lp1sKQ5K-APfx_" : true,
      "-KX3k3WpGpjHIlznD7R3" : true
    }
  },
  "teams" : {
    "-KX3j5Lp1sKQ5K-APfx_" : {
      "media" : "https://www.chiefdelphi.com/media/img/773/773cdb19c77a06938fbe355ccd7e8d1a_l.jpg",
      "name" : "Shockwave",
      "number" : "4488",
      "timestamp" : 1479695689791,
      "website" : "http://glencoerobotics.com/"
    },
    "-KX3k3WpGpjHIlznD7R3" : {
      "media" : "https://i.imgur.com/4raDoqP.png",
      "name" : "SERT",
      "number" : "2521",
      "timestamp" : 1479696119224,
      "website" : "http://www.sert2521.org"
    }
  }
}
```

Holy guacamolee, that's the most code I have ever posted! If this doesn't help, then I'll just go cry in a corner because I have no clue what's happening! 😄

**Comment by TheCraftKid** [comment]
My question is if your code worked with the public FirebaseUI branch or perhaps the newly added #412.

**Comment by SUPERCILEX** [comment]
Yeah, it works fine without #412 which is mainly future proofing things.

**Comment by TheCraftKid** [comment]
Okay, after days of on-and-off looking at code, silly bonehead me didn't see the obvious warnings in the logs: "W/FirebaseIndexArray: Key not found at ref: ..." It turned out that in the process of modifying code that updates the database references, I was actually creating two different keys using push() twice instead of using push() then getting the key from one and setting that as the key to another database reference.

Well, I guess it's now time to test the speed difference between this and a normal `FirebaseRecyclerAdapter`.

**Comment by SUPERCILEX** [comment]
@TheCraftKid Oh no!!! That would kill me to know it was something a simple as that! Anyway, I'm super glad you figured it out and I'll remember to refer people to your comment if anyone has abnormal problems with the `FirebaseIndexRecyclerAdapter` in the future.
