### ISSUE TITLE
Twitter auth, how to get email?

### ISSUE THREAD

**Issue by cutiko** [firebase/FirebaseUI-Android#419]
Greetings

It took me awhile but I can finally see what is in the new 1.0 release. So I handle to create the Twitter authentication and the user is correctly logged in. I was very surprised when in the firebase.google console the user have no email!

The first thing I did was to check it using:

```
String email = FirebaseAuth.getInstance().getCurrentUser().getEmail();
Toast.makeText(this, email, Toast.LENGTH_SHORT).show();
```

**But there is no email**. So I have being doing some search and found [here](https://firebase.google.com/docs/auth/web/twitter-login?hl=es) some indications to get the email in web. However, in the [Android documentation](https://firebase.google.com/docs/auth/android/twitter-login?hl=es) there is no email reference. What confuses me most is this [StackOverflow question](http://stackoverflow.com/questions/24922921/get-users-email-address-with-firebases-twitter-simple-login) where is explained there is no way to get the email.

UPDATE: Another attempt to get more details was to send email verification, which didn't work with Twitter, cross check using email/password login.

Can we get the user email with Twitter login? Thanks in advanced.

**Comment by juanlet** [comment]
I just had the same problem. The email comes empty.....Maybe it's a privacy policy

**Comment by SUPERCILEX** [comment]
I'm pretty sure this isn't related to Firebase-UI: https://apps.twitter.com lets you request the email permission in the permissions tab. I haven't tested it so I can't confirm that this works, sorry.

**Comment by SUPERCILEX** [comment]
@cutiko @juanlet I finally got around to testing it today and I can confirm that the email is received if you request it in the Twitter dashboard:
![image](https://cloud.githubusercontent.com/assets/9490724/20849816/36dc0776-b88d-11e6-8d33-b7a3372e4226.png)

Also, what do you think of this [update to the README](https://github.com/firebase/FirebaseUI-Android/pull/433/files)?

**Comment by SUPERCILEX** [comment]
@samtstern Oops! You merging closed this issue, sorry!

**Comment by SUPERCILEX** [comment]
@cutiko @juanlet Just FYI, to get the email you'll need to reset the permissions used by your app by going to https://twitter.com/settings/applications and revoking it.

**Comment by cutiko** [comment]
Just came to confirm this is working, thanks for the help

**Comment by Toofoo** [comment]
Hi, even when I chekc the "request email adress from user" box and reset the permisssion, I can't access the email from Twitter. 
The FirebaseUI log display : 
"com.firebase.uidemo` E/TwitterProvider: Failure retrieving Twitter email. Your application may not have access to email addresses or the user may not have an email address. To request access, please visit https://support.twitter.com/forms/platform."`

**Comment by cutiko** [comment]
@Toofoo "or the user may not have an email address". In Twitter the user have the choice to make the email private. I have being wonderimg what would happen in this scenario. Can you confirm this is the case?

**Comment by Toofoo** [comment]
Actually in the the twitter account  it written that the e-mail adresse will not be displayed to public; but I don't see any option to change this. ???
(I checked the box : allow anybody to find me by email address

**Comment by lborgman** [comment]
Just found that the email address is in result.user.providerData. Should not that be copied to result.user.email?
