### ISSUE TITLE
Update README to remove serverClientId

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#42]
Docs were not changed to reflect code changes in #41

**Comment by puf** [comment]
There is no release yet that includes this. The docs will be updated when
that release comes out.

I'll keep this issue open until then.

**Comment by abehaskins** [comment]
@puf whats status on this? Do we need more README changes?

**Comment by puf** [comment]
Nope, not that I know of. Just waiting for the PR to land before closing it.

**Comment by abehaskins** [comment]
Thanks! Marking as fix-implemented
