### ISSUE TITLE
Splitting FirebaseUI

### ISSUE THREAD

**Issue by porfirioribeiro** [firebase/FirebaseUI-Android#423]
I a using FirebaseUI for quick add a login interface to my app.

I am using e-mail and google sign in for now.

Is there any way to remove the reference to other sdks like Twitter and Facebook? 
They are just increasing my apk size

**Comment by samtstern** [comment]
Are you finding that these classes are retained in your APK even after
ProGuard?  Normally that should strip the unused classes.

**Comment by porfirioribeiro** [comment]
If i open the apk in Android Studio, i can ser allot of resources, drawables etc. From twitter ans facebook.

I tried to hard remove dependencies with gradle but then some of firebaseui resources are tied to Facebook and Twitter resources.

**Comment by samtstern** [comment]
@porfirioribeiro I see, that's a good point about the resources (ProGuard can't do very much about those).  Right now the design of FirebaseUI would make it very hard to allow selective inclusion of the 3p SDKs but we can keep this issue open and see if we think of anything to improve the situation.

**Comment by porfirioribeiro** [comment]
Ok, i see the problem, i hope in the future you can find some solution for this!

It's not a big issue, but i don't like to see the apk size grow so much, but in the other end i dont want to the implementation all by myself :wave:

**Comment by kirtan403** [comment]
Even with the `shrinkResources true` I can see all twitter resources in my apk. I just checked through Android Studio's APK Analyzer. Or with some proguard rules or something which can remove those resources or classes. Because I can see a lots of methods and resources. 

Here is the screenshot:

![facebook-twitter-sdk](https://cloud.githubusercontent.com/assets/7900938/20753815/376cee22-b72e-11e6-855b-8e9920dad309.png)

**Comment by nielsz** [comment]
What I like about Square's Retrofit is that it only loads what you need:
```
com.squareup.retrofit2:converter-gson
com.squareup.retrofit2:converter-jackson
```
FirebaseUI could do something like this.
```
com.firebaseui:firebase-ui-auth:1.0.1
com.firebaseui:firebase-ui-auth-twitter:1.0.1
com.firebaseui:firebase-ui-auth-facebook:1.0.1
```

**Comment by porfirioribeiro** [comment]
Yes, that's was what i was suggesting, split the library into smaller ones

**Comment by pushbit** [comment]
In addition to the benefits mentioned above, it would also be great if we (and anyone downstream from us) didn't need to add the Fabric repository if we aren't using anything related to Twitter.

**Comment by SUPERCILEX** [comment]
Hello everyone, in FirebaseUI `v2.0` the Facebook and Twitter libraires aren't included by default so there's no APK size increase unless you use Facebook or Twitter auth.

@samtstern I believe the underlying issue of increased APK size has been resolved.

**Comment by samtstern** [comment]
Yep I think the original issue is resolved.  You can now leave out the Twitter and Facebook SDK if you're not using those sign in options.
