### ISSUE TITLE
Login without network connection should return error msg

### ISSUE THREAD

**Issue by jsanchezgarcia** [firebase/FirebaseUI-Android#428]
Currently, if user tries to login with no network connection, nothing happens. This is hard to debug.
FirebaseUI should throw an error to make it easier to identify this problem when it happens

**Comment by samtstern** [comment]
Have you checked for `RESULT_NO_NETWORK`?  You can see the documentation here:
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#response-codes

**Comment by jsanchezgarcia** [comment]
thansk! we missed that one during our Andevcon16 today

**Comment by samtstern** [comment]
:+1: enjoy AnDevCon!
