### ISSUE TITLE
Feature request: Compatibility with Google Play services 9.x.x

### ISSUE THREAD

**Issue by consp1racy** [firebase/FirebaseUI-Android#438]
Do not force consumers to use latest Play services library.

Since this project started at 9.0.0 let's assume that this is the actual minimum.

Same goes for support library. Google play services need at least 24.0.0 so that should be minimum.

Dependencies on Facebook and Twitter SDK should be `provided` instead of `compile` (if applicable).

**Comment by samtstern** [comment]
@consp1racy could you explain why you are hesitant to upgrade to the latest play services libraries?  There have been many critical bug fixes to firebase auth since 9.0.0 and we'd like to encourage developers to use the latest when possible.

**Comment by consp1racy** [comment]
> why you are hesitant to upgrade to the latest play services libraries?

@samtstern I come from old school (i.e. market) where people are reluctant to update apps (incl. Google Play services) or have disabled automatic updates. It used to be about lack of space, now it's about conserving data.

Unless it's absolutely necessary we don't want to bother users with updating an external app (GMS), even more so when the core app does not leverage any new features of 10.0.x (but can still leverage security fixes if a newer version is installed on the device, right?).

> we'd like to encourage developers to use the latest when possible.

Encourage - yes. Force - no.

**Comment by SUPERCILEX** [comment]
@consp1racy since FirebaseUI is an extension of the core Firebase APIs, I don't think we'll ever support lower Play Services versions.

@samtstern what are your thoughts, should this issue be closed?

**Comment by consp1racy** [comment]
Last week our customers definitely were not able to get play services 11. As long as you keep the minimum at 10.x.x it should be ok at this point in time. 

Just... keep the required version lower than the newest sdk. In terms of gradle dependencies:

    compile 'gms:10'
    provided 'gms:11'

and fail gracefully. That would be awesome.

**Comment by samtstern** [comment]
I am going through old issues and I am going to close this one.  Although I totally understand the benefit the opposite request is much more common: users want to use a **newer** version of play services with an older version of FirebaseUI.  In general it's much more aligned with the goals of this library to depend on the latest library version which has all new features, bugfixes, etc.

We do plan to move over to the new gradle `implementation` designation soon, which may help here.

Thank you @consp1racy for filing originally, it inspired some good conversations.
