### ISSUE TITLE
Error:(31, 26) error: cannot access zzans class file for com.google.android.gms.internal.zzans not found

### ISSUE THREAD

**Issue by Mosa-Albnyan** [firebase/FirebaseUI-Android#439]
when i add     compile 'com.firebaseui:firebase-ui-database:1.0.1'
and run my app show that error please advice?

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  * FirebaseUI version: ____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by SUPERCILEX** [comment]
Are you using different firebase/play services versions in your `build.gradle` file? See the compatibility table: https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries.

**Comment by samtstern** [comment]
@Mosa-Albnyan going to close this issue as there has been no response for a week and I believe @SUPERCILEX has given you the correct answer.
