### ISSUE TITLE
Unable to run sample app

### ISSUE THREAD

**Issue by IgorGanapolsky** [firebase/FirebaseUI-Android#446]
#### Steps to reproduce:

  1. Clone the latest repository
  2. Import in Android Studio 2.3
  3. Try to run the app
  
#### Observed Results:
 Build error:
> Error:Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  /Users/igorganapolsky/workspace/git/google/FirebaseUI-Android/app/src/debug/google-services.json
  /Users/igorganapolsky/workspace/git/google/FirebaseUI-Android/app/google-services.json
 
#### Expected Results:
App should run

**Comment by samtstern** [comment]
@IgorGanapolsky as stated in the error, you're missing the `google-services.json` file in the app folder.

See [this page](https://firebase.google.com/docs/android/setup) for instructions.
