### ISSUE TITLE
Can I add custom RequestListener to Glide request using FirebaseImageLoader ?

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#451]
Hello.
Is it possible to add my own listener to Glide request using FirebaseImageLoader ?
In this case

                    StorageReference bannerRef = FirebaseUtil.getStorageRef().child("banners").child("vapeblockbanner.png");
                    Glide.with(getActivity())
                            .using(new FirebaseImageLoader())
                            .load(bannerRef)
                            .fitCenter()
                            .listener(new RequestListener<StorageReference, GlideDrawable>() {
                                @Override
                                public boolean onException(Exception e, StorageReference model, Target<GlideDrawable> target, boolean isFirstResource) {
                                    /* Some Code */
                                    LogUtils.d("onException");
                                    return false;
                                }

                                @Override
                                public boolean onResourceReady(GlideDrawable resource, StorageReference model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                                    /* Some Code */
                                    LogUtils.d("onResourceReady");
                                    return false;
                                }
                            })
                            .into(ivVapeBlockAdBottom);

So the onResourceReady and onException will be triggered ?

**Comment by samtstern** [comment]
@stasbar hi there, can you explain what's not working about the code above?  Is the `listener()` method just not available to you?

**Comment by stasbar** [comment]
@samtstern No, The problem is that neither onException nor onResourceReady are called

**Comment by samtstern** [comment]
I can't reproduce unfortunately.  I added a listener to the sample provided in this repo so the code is as follows:

```java
        Glide.with(this)
                .using(new FirebaseImageLoader())
                .load(mImageRef)
                .centerCrop()
                .crossFade()
                .listener(new RequestListener<StorageReference, GlideDrawable>() {
                    @Override
                    public boolean onException(Exception e, StorageReference model, Target<GlideDrawable> target, boolean isFirstResource) {
                        Log.d(TAG, "listener.onException");
                        return false;
                    }

                    @Override
                    public boolean onResourceReady(GlideDrawable resource, StorageReference model, Target<GlideDrawable> target, boolean isFromMemoryCache, boolean isFirstResource) {
                        Log.d(TAG, "listener.onResourceReady");
                        return false;
                    }
                })
                .into(mImageView);
```

The logcat output I see is:
```
12-09 08:21:13.128 28015-28015/? D/ImageDemo: signInAnonymously:true
12-09 08:21:31.871 28015-28015/? D/ImageDemo: uploadPhoto:onSuccess:/6e180d8a-1faf-4651-acde-d3e7dd190776
12-09 08:21:35.740 28015-28015/? D/ImageDemo: listener.onResourceReady
```

So I think the short answer is that you can definitely attach listeners with FirebaseUI Storage, but there must be something in particular about your setup that's not working.

**Comment by stasbar** [comment]
Ok so I have to find Bug somewhere else :)
Thank you for support
