### ISSUE TITLE
RecyclerView Animations

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#454]
Are animations available for the Firebase RecyclerView adapter?

**Comment by SUPERCILEX** [comment]
Yup, we're just using the default `RecyclerView.Adapter` so any animations that are available there can be used with `FirebaseRecyclerViewAdapter`.

**Comment by samtstern** [comment]
@SUPERCILEX is correct, the ability to use animations is separate from FirebaseUI.  So anything you're used to should work.
