### ISSUE TITLE
Build error related to okhttp3 as soon as I include firebaseui

### ISSUE THREAD

**Issue by Frantch** [firebase/FirebaseUI-Android#465]
Hello,

I would like to start using firebaseui-auth in my  app but as soon as I include the lib

compile 'com.firebaseui:firebase-ui-auth:1.0.0' (or 1.0.1, it's the same)

I cannot build my app anymore I get these kind of errors:

Error:(96, 20) error: cannot find symbol method close() 
Error:(35, 21) error: incompatible types: try-with-resources not applicable to variable type
(Response cannot be converted to AutoCloseable)

All these line are related to okhttp3.Response class.. It doesn't fid .close()? I can perfectly see a .close() on it.. and it's owkring fine without firebase-ui lib
I dont know what it does this but for some reason it's getting confused?

**Comment by samtstern** [comment]
@Frantch can you show the rest of your `build.gradle` file?

**Comment by Frantch** [comment]
apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
    compileSdkVersion 24
    buildToolsVersion "25.0.1"


    defaultConfig {
        applicationId "com.alert.poke"
        minSdkVersion 19
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }

    buildTypes {
        release {
          //  minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
        }

        debug {
           // minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            zipAlignEnabled true
        }
    }

    lintOptions {
        disable 'MissingTranslation'
    }

    dexOptions {
        javaMaxHeapSize "4g"
    }

    productFlavors {
        lite {
            applicationId = 'xxxxx'
            versionCode xx
            versionName = "xxx"
        }
    }

}

dependencies {
    //compile fileTree(include: ['*.jar'], dir: 'libs')
    compile ('com.google.android.gms:play-services-maps:9.8.0')
    compile ('com.google.android.gms:play-services-location:9.8.0')
    compile 'com.google.android.gms:play-services-places:9.8.0'
    compile ('com.android.support:appcompat-v7:24.2.0')
    compile ('com.android.support:design:24.2.0')
    compile ('com.android.support:cardview-v7:24.2.0')
    compile ('joda-time:joda-time:2.9.4')
    compile ('com.google.firebase:firebase-ads:9.8.0')
    compile ('com.android.support:multidex:1.0.1')
    compile group: 'com.google.maps.android', name: 'android-maps-utils', version: '0.4.3'

    //This is jar is a JAR is a lib I build myself and this is the one that contains Okhttp3 3.4.1
    compile files('libs/a-third-party-jar.jar')
   
    compile 'ch.acra:acra:4.9.0'
    compile 'com.squareup:otto:1.3.8'
    compile 'com.github.amlcurran.showcaseview:library:5.4.3'
    compile 'com.github.clans:fab:1.6.4'
    compile 'com.bignerdranch.android:recyclerview-multiselect:+'
    compile 'com.firebaseui:firebase-ui-auth:1.0.0'
}
apply plugin: 'com.google.gms.google-services'
//apply plugin: "maven"

**Comment by SUPERCILEX** [comment]
@Frantch FirebaseUI already includes OkHttp (v3.2.0) so you can remove your custom jar. If you really need a newer version, you can manually override FirebaseUI's dependency by including the following: `compile 'com.squareup.okhttp3:okhttp:3.5.0'`.

**Comment by Frantch** [comment]
Oh I see.. I have tried looking into FirebaseUI repo to see if that lib was somehwere but couldn't find. In that case this worked:
```
compile ('com.firebaseui:firebase-ui-auth:1.0.0') {
        exclude group: 'com.squareup.okhttp3', module: 'okhttp'
    }
```
Only using this 
`compile 'com.squareup.okhttp3:okhttp:3.5.0'.`

didn't work for me as I was getting a ZipAlign error saying some okhttp3 class were duplicated

**Comment by SUPERCILEX** [comment]
@Frantch Glad to hear it worked!

**Note:** If you are using Twitter, you might want to check that things are working properly because they rely heavily on retrofit and okhttp. (Also, please upgrade to FirebaseUI 1.0.1! 😄 There were a ton of bugs fixes especially related to Twitter and memory leaks.)

**Comment by samtstern** [comment]
I believe this has been resolved?  Closing the issue, please re-open if I am incorrect
