### ISSUE TITLE
Configure email signIn to not ask first and last name?

### ISSUE THREAD

**Issue by Paul776** [firebase/FirebaseUI-Android#467]
Hi

Is it possible customise the email signup screen to not ask the first and last name ?

Thanks

**Comment by samtstern** [comment]
@Paul776 that's not currently possible in the library but I do think that would be a good customization for the future.

The main roadblock to adding this and other minor customizations is we want to avoid filling the library with boolean flags that create more room for error (by us or by devs using the library).

**Comment by Paul776** [comment]
I understand, and yes this could be marked as an "improvement suggestion" then. As a starter that field can be either "hidden" or maybe simply give a customisation possibility to change the text label. (due to the nature of my app I'd rather call that field "nickname" than first name and last name.

**Comment by SUPERCILEX** [comment]
@Paul776 You can actually do that by creating a string resource overriding FirebaseUI's: `<string name="name_hint">Nickname</string>`.

Do watch out for new versions FirebaseUI though because they may change the ids of these string resources at anytime and without notice.

**Comment by samtstern** [comment]
Tracking on other platforms:
  * https://github.com/firebase/firebaseui-web/issues/41
  * https://github.com/firebase/FirebaseUI-iOS/issues/245

**Comment by SUPERCILEX** [comment]
@samtstern Ok, if #1083 goes through, we can do some crazy cool stuff! I'm not sure if we'd want this kind of feature, but I was thinking of enabling a fully customizable sign-in field template. That is, devs would be able to supply required and optional fields that we generate views for on-the-fly and use annotations and reflection to support custom validation.

The new builder APIs in my PR would enable this kind of customization that could be used to build conference apps or something else that requires many fields. What do you think? If you like the idea, I'd whip up a PR so we can have it ready by `v3.2.0`.

**Comment by samtstern** [comment]
@SUPERCILEX let's first offer a long-awaited flag for this particular issue, release `3.2.0` and then do further features based on demand.  I don't really like the words "crazy" and "reflection" used together in a feature proposal :-)

**Comment by SUPERCILEX** [comment]
@samtstern Haha, that SGTM. At least the doors will be open now! 😁

**Comment by Kurt29** [comment]
@SUPERCILEX 
That would be the feature that I actually wanted/needed for a long time. But since I am still not done with other parts of my app, I was too lazy to actually try to implement this.

**Comment by Levelleor** [comment]
Is this issue still can't be fixed? Same here as someone already said. "First & last name" simply sounds weird in my app and might scare people to type anything.

**Comment by samtstern** [comment]
@Levelleor this is on the `3.2.0` milestone which means we hope to close it in our next release.  @SUPERCILEX did some refactoring to make this possible.

**Comment by samtstern** [comment]
@SUPERCILEX this is the last bug on the `3.2.0` hotlist that is not `fix-implemented`.  We should probably implement this and then release `3.2.0`, get some of the new architecture out into the wild before racing ahead any further.

**Comment by SUPERCILEX** [comment]
@samtstern Yup, SGTM!

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.0`.
