### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by sornnaser** [firebase/FirebaseUI-Android#473]
* Android device: Huawei Honor
  * Android OS version: 6
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.0.1
  
I've successfully setup the login screen with firebaseui.
Signing in with Google and Email works fine.
However when I try to sign in with Facebook it just loads for a second or two and then goes back to the login page like nothing happened. A new account is not created (even when no accounts exist with the email).

No error message either.

I configured the app id, meta-data, app secret, hash key, OAuthredirect.

Other's seem to have the some problem to.

**UPDATE:**

If I click the sign in with Facebook while being signed out of Facebook, Facebook's login screen appears and asks me for email and password. When entered the problem reappears.

I also tried removing compile 'com.facebook.android:facebook-android-sdk:[4,5)'

**Comment by knissophiliac** [comment]
same here. how did you solve this?

**Comment by HarshitAgarwal1** [comment]
My problem is not solving with any of the ways suggested above in the linkL

> same here. how did you solve this?
> edit: i solved my problem. mine was related to http://stackoverflow.com/a/39127275
