### ISSUE TITLE
Thread Leak on AuthMethodPickerActivity when using Firebase UI

### ISSUE THREAD

**Issue by ankit7sethi** [firebase/FirebaseUI-Android#474]
On using Firebase UI for Authentication picker for Facebook, a direct leak occurs. On choosing Twitter and Google, the account selection or permission access windows are displayed correctly but after selecting the option, the same leak happens. Upon debugging I found this leak in my Redmi 3S, Redmi Note 3, OnePlus X, Nexus 6, and HTC Desire. Find attached the heap dump file and LeakCatcher's analysis.
[firebase_ui_library_bug_001.txt](https://github.com/firebase/FirebaseUI-Android/files/673357/firebase_ui_library_bug_001.txt)
Screenshot: [https://cloud.githubusercontent.com/assets/3744778/21487368/56f97d04-cbed-11e6-9f1c-9a392c582aae.png](url)

**Comment by SUPERCILEX** [comment]
I believe this was fixed in FirebaseUI 1.0.1. If not, please wait until v1.1.0 coming out early January which shouldn't have this leak.

**Comment by ankit7sethi** [comment]
@SUPERCILEX Okay Thanks!
