### ISSUE TITLE
AuthUI.delete() does not handle reauthenticate

### ISSUE THREAD

**Issue by alexisvapillon** [firebase/FirebaseUI-Android#478]
Firebase documentation says: "To delete a user, the user must have signed in recently. See Re-authenticate a user."
https://firebase.google.com/docs/auth/android/manage-users#delete_a_user

This is not handled by FirebaseUI, as far as I can see.
(Android and Web, but other platforms as well I guess)

Is it a known limitation?
Is the implementation planned?

**Comment by samtstern** [comment]
@alexisvapillon sorry for the delayed response here but thanks for reporting this.  This is a good feature request.

**Comment by samtstern** [comment]
I checked with the auth team and in the context of delete, "recently" is defined as 5 minutes.  So you are right, it would be great for FirebaseUI to handle this case as it's hard to handle without insecurely storing auth credentials on the client.

**Comment by alexisvapillon** [comment]
Any ETA for this feature (even rough estimate) ?
I'd like to know if it is worth implementing something crappy myself, or if I should better wait for FirebaseUI team to do it.

**Comment by samtstern** [comment]
No ETA right now, we have not started to implement this so if you're going to need it soon I'd say forking and working on your own version would be worthwhile.

**Comment by samtstern** [comment]
@alexisvapillon  we are going to track this work in #563, thank you for the report!
