### ISSUE TITLE
How to search for a value in firebase Android

### ISSUE THREAD

**Issue by Shajeel-Afzal** [firebase/FirebaseUI-Android#48]
I am saving data as follows in the Firebase:

![screen-shot-2015-12-31-at-1 41 30-am](https://cloud.githubusercontent.com/assets/3718283/12057773/3e414d0e-af66-11e5-99b0-b70d547b438b.png)

I want to find all records that have #Yahoo in their title. What will be the exact query for that?

I am confused with the random key created. I am not sure how to handle this so i am posting it here.

```
Firebase firebase = new Firebase(Constants.FIREBASE_URL_USER_TASKS).child(Utils.encodeEmail(unProcessedEmail));
        Query queryRef = firebase.orderByKey().startAt("#" + mHashTag).endAt("#" + mHashTag + "\uf8ff");

        queryRef.addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                mTasksList.clear();
                mAdapter.notifyDataSetChanged();
                for (DataSnapshot task : dataSnapshot.getChildren()) {
                    mTasksList.add(task.getValue(TaskModel.class));
                }
                mAdapter.notifyItemRangeInserted(0, mTasksList.size());
                mSwipeToRefresh.post(new Runnable() {
                    @Override
                    public void run() {
                        mSwipeToRefresh.setRefreshing(false);
                    }
                });
            }

            @Override
            public void onCancelled(FirebaseError firebaseError) {
                mSwipeToRefresh.post(new Runnable() {
                    @Override
                    public void run() {
                        mSwipeToRefresh.setRefreshing(false);
                    }
                });
            }
        });
```

I have also posted it on SO: http://stackoverflow.com/questions/34537369/how-to-search-for-a-value-in-firebase-android

Please suggest.

Thanks.

**Comment by puf** [comment]
This issue is not related to FirebaseUI. Let's keep it on StackOverflow: http://stackoverflow.com/questions/34537369/how-to-search-for-a-value-in-firebase-android

**Comment by Shajeel-Afzal** [comment]
Ok @puf, can you please suggest what is the solution to that problem?

**Comment by salmank888** [comment]
Answer : simply do following query : 
databaseReference.orderByChild('_searchLastName')
                 .startAt(queryText)
                 .endAt(queryText+"\uf8ff")
                 .once("value")
http://stackoverflow.com/a/40633692/4409113

Shajee-Afzal, ap edhr bhi solution rakh daity,  3 hours mn solution mil gaya wrna.. LOL.
Shahid.
