### ISSUE TITLE
Where is my .setTosUrl ?

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#483]
Hello.
Where is the Terms of Services url available to users during login process ?
`.setTosUrl("...")`

**Comment by SUPERCILEX** [comment]
Only in the email sign up flow.

**Comment by SUPERCILEX** [comment]
![screenshot_20161231-112446](https://cloud.githubusercontent.com/assets/9490724/21578982/c92e841c-cf4b-11e6-9f7c-223658511c9b.png)

**Comment by samtstern** [comment]
Thanks @SUPERCILEX for explaining.
