### ISSUE TITLE
Set Tag of ViewHolder Item and Later Retrieve View by Tag

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#493]
So I have learned that the default `FirebaseRecyclerAdapter` behavior is to repopulate the `RecyclerView` on any updates. However, I do not want to update the `RecylcerView` this way; I simply want to set an ID or Tag for each view in the `RecyclerView`, and then later retrieve that view.

In order to make this work, I want the actual ID to be the `push.getKey()` value that I originally use to write an item to Firebase. Then, as I listen for changes from Firebase, I can reference a particular view based on the `push.getKey()` value that is returnred from my `ValueEventListener`, which now ultimately serves as the tag for each view in the RecylcerView.

Is there a way to set a tag = `push.getKey()`; and then later retrieve that `viewHolder` / `RecyclerView` view based on that tag?

Below is my code:

    public class LiveFragment extends Fragment {
    // TODO: Rename parameter arguments, choose names that match
    // the fragment initialization parameters, e.g. ARG_ITEM_NUMBER
    private static final String ARG_PARAM1 = "param1";
    private static final String ARG_PARAM2 = "param2";

    private RecyclerView mRecyclerview;
    private DatabaseReference mBaseRef;
    private DatabaseReference mPollsRef;
    private LinearLayoutManager mLayoutManager;
    private FloatingActionButton mFloatingActionAdd;

    private FirebaseRecyclerAdapter<Poll, PollHolder> mFireAdapter;

    private RecyclerView.ItemAnimator mItemAnimator;

    // TODO: Rename and change types of parameters
    private String mParam1;
    private String mParam2;

    private OnFragmentInteractionListener mListener;

    public LiveFragment() {
        // Required empty public constructor
    }

    /**
     * Use this factory method to create a new instance of
     * this fragment using the provided parameters.
     *
     * @param param1 Parameter 1.
     * @param param2 Parameter 2.
     * @return A new instance of fragment LiveFragment.
     */
    // TODO: Rename and change types and number of parameters
    public static LiveFragment newInstance(String param1, String param2) {
        LiveFragment fragment = new LiveFragment();
        Bundle args = new Bundle();
        args.putString(ARG_PARAM1, param1);
        args.putString(ARG_PARAM2, param2);
        fragment.setArguments(args);
        return fragment;
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        mBaseRef = FirebaseDatabase.getInstance().getReference();
        mPollsRef = mBaseRef.child("Polls");

        if (getArguments() != null) {
            mParam1 = getArguments().getString(ARG_PARAM1);
            mParam2 = getArguments().getString(ARG_PARAM2);

        }
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        final View v = inflater.inflate(R.layout.fragment_new, container, false);
        Log.v("TAG", "ON CREATE CALLED FROM NEW");

        mRecyclerview = (RecyclerView) v.findViewById(R.id.list);
        mRecyclerview.setItemAnimator(new SlideInLeftAnimator());

        mLayoutManager = new LinearLayoutManager(getContext());
        mLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
        mLayoutManager.setReverseLayout(true);
        mLayoutManager.setStackFromEnd(true);

        mFloatingActionAdd = (FloatingActionButton) getActivity().findViewById(R.id.myFAB);
        mFloatingActionAdd.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent I = new Intent(getActivity().getApplicationContext(), CreateActivity.class);
                startActivity(I);
            }
        });

        mRecyclerview.setLayoutManager(mLayoutManager);
        return v;
    }

    @Override
    public void onStart() {
        super.onStart();

        mFireAdapter = new FirebaseRecyclerAdapter<Poll, PollHolder>(Poll.class, R.layout.latest_item, PollHolder.class, mBaseRef.child("Polls")) {

            @Override
            public void onChanged(EventType type, int index, int oldIndex) {
                if (type != EventType.CHANGED)
                    super.onChanged(type, index, oldIndex);
            }

            @Override
            protected void populateViewHolder(final PollHolder viewHolder, final Poll model, final int position) {
                viewHolder.mPollQuestion.setText(model.getQuestion());
                String voteCount = String.valueOf(model.getVote_count());
                viewHolder.mView.setId(position);
 
                Picasso.with(getActivity().getApplicationContext())
                        .load(model.getImage_URL())
                        .fit()
                        .into(viewHolder.mPollImage);
                viewHolder.mView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {
                        Log.v("TAG", model.toString());
                        Log.v("TAG","ONCLICKED");
                        Intent toPoll = new Intent(getActivity(), PollHostActivity.class);
                        //TODO: Go back to clicked item when navigating from Poll Fragment back to LiveFragment
                        toPoll.putExtra("POLL_ID", mFireAdapter.getRef(viewHolder.getAdapterPosition()).getKey());
                        startActivity(toPoll);

                    }
                });
                Log.v("TAG", mFireAdapter.getRef(position).getKey());
                Log.v("TAG", String.valueOf(position));
                Log.v("TAG", model.getQuestion());
                Log.v("TAG", model.getImage_URL());
            }
        };

        mRecyclerview.setAdapter(mFireAdapter);
        scrollToPosition();

    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (mFireAdapter != null) {
            mFireAdapter.cleanup();
        }
    }

    @Override
    public void onActivityCreated(@Nullable Bundle savedInstanceState) {
        super.onActivityCreated(savedInstanceState);

    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        if (context instanceof OnFragmentInteractionListener) {
            mListener = (OnFragmentInteractionListener) context;
        } else {
            throw new RuntimeException(context.toString()
                    + " must implement OnFragmentInteractionListener");
        }
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mListener = null;
    }

    public static class PollHolder extends RecyclerView.ViewHolder {

        TextView mPollQuestion;
        TextView mVoteCount;
        ImageView mPollImage;
        View mView;

        public PollHolder(View itemView) {
            super(itemView);

            mPollQuestion = (TextView) itemView.findViewById(R.id.latest_item_question);
            mPollImage = (ImageView) itemView.findViewById(R.id.pollThumbNailImage);
            mVoteCount = (TextView) itemView.findViewById(R.id.latest_item_poll_count);
            this.mView = itemView;
        }

    }

    private void scrollToPosition(){
        mFireAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onItemRangeInserted(int positionStart, int itemCount) {
                super.onItemRangeInserted(positionStart, itemCount);
                int pollCount = mFireAdapter.getItemCount();
                int lastVisiblePosition = mLayoutManager.findLastCompletelyVisibleItemPosition();

                // If the recycler view is initially being loaded or the user is at the bottom of the list, scroll
                // to the bottom of the list to show the newly added message.
                if (lastVisiblePosition == -1 ||
                        (positionStart >= (pollCount - 1) && lastVisiblePosition == (positionStart - 1))) {
                    mRecyclerview.scrollToPosition(positionStart);
                }
            }
        });
       }

      }

**Comment by samtstern** [comment]
@troy21688 you've presented a lot of code here and it's not clear what part is not working as you've expected.  Please keep code snippets as short as they can be while demonstrating the issue.

You say "this way; I simply want to set an ID or Tag for each view in the RecyclerView, and then later retrieve that view." ... can you explain what exactly you mean here?  As you know, RecyclerView *recycles* the `ViewHolder` and `View` instances so there's no guarantee that a view for each item would even exist at a given time.

As for the update mechanics, the adapter only changes items where the backing data from Firebase has changed.

**Comment by samtstern** [comment]
@troy21688 it's been 26 days since the last update so closing this issue.
