### ISSUE TITLE
Firebase-ui incompability with android FloatingActionButton

### ISSUE THREAD

**Issue by ridwan85** [firebase/FirebaseUI-Android#499]
After input the firebaseUI dependencies in the gradle build file
compile 'com.firebaseui:firebase-ui-database:1.0.0'
My app can't start and crash.

`java.lang.RuntimeException: Unable to start activity android.view.InflateException: Binary XML file line #53: Error inflating class android.support.design.widget.FloatingActionButton`

It seems that firebaseUI is in conflict with FloatingActionButton.

Same issue reported here also 
[http://stackoverflow.com/questions/41052459/firebase-ui-and-floatingactionbutton-incompatibility](http://stackoverflow.com/questions/41052459/firebase-ui-and-floatingactionbutton-incompatibility)

**Comment by samtstern** [comment]
@ridwan85 can you show all of the dependencies in your `build.gradle` file?

**Comment by samtstern** [comment]
FirebaseUI version `1.0.1` uses support library version `25.0.1` for all of the `com.android.support` libraries.  Could you try changing the version used in your app to match that and see if it resolves the error?

**Comment by ridwan85** [comment]
Thanks @samtstern . Changing the version to 1.0.1 fixed the issues. 
But compilesdk version also need to changed to the version `25.0.1`

from
`compileSdkVersion 23`
  `buildToolsVersion "23.0.3"`
to 
`compileSdkVersion 25`
    `buildToolsVersion "25.0.1"`

and also
` compile 'com.android.support:appcompat-v7:23.4.0'`
   ` compile 'com.android.support:support-v4:23.4.0'`
    `compile 'com.android.support:recyclerview-v7:23.4.0'`
    `compile 'com.android.support:design:23.4.0'`
to
`compile 'com.android.support:appcompat-v7:25.0.1'`
   ` compile 'com.android.support:support-v4:25.0.1'`
    `compile 'com.android.support:recyclerview-v7:25.0.1'`
    `compile 'com.android.support:design:25.0.1'`
