### ISSUE TITLE
Wrong colors used in AuthUI when Night Mode enabled

### ISSUE THREAD

**Issue by the-dagger** [firebase/FirebaseUI-Android#502]
* Android device: OnePlus 3
  * Android OS version: 7.0
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.0.1
  
#### Steps to reproduce:

  1. Set the default app theme as dark `AppCompatDelegate.setDefaultNightMode(AppCompatDelegate.MODE_NIGHT_YES);`
  2. Try logging in via email
  
#### Observed Results:
  The TextColor in EditText was black 
#### Expected Results:
 The TextColor in EditText should be white, or a light color
#### Relevant Code:

![screenshot_20170110-021308](https://cloud.githubusercontent.com/assets/6565270/21783667/6e73a6d4-d6de-11e6-8cae-d3b0fd4f58b7.png)
![screenshot_20170110-021258](https://cloud.githubusercontent.com/assets/6565270/21783670/6f27238a-d6de-11e6-90a3-b06c0abd3a9b.png)

**Comment by samtstern** [comment]
Let's keep this open and 'fix-implemented' until the release goes out.

**Comment by the-dagger** [comment]
Sure, sounds good. 👍

**Comment by samtstern** [comment]
@the-dagger unfortunately I had to revert this change (in #515) since this was making the EditText colors wrong in all non-dark situations.  Rather than try to make it work in both cases, I went for the revert strategy for max safety for the 1.1.0 release.

Happy to try and get this in for the 1.2.0 release.

**Comment by the-dagger** [comment]
@samtstern Thanks for pointing it out.
I'll see what caused this issue.

**Comment by the-dagger** [comment]
@samtstern Should i push the fix to 1.1.0-dev?

**Comment by samtstern** [comment]
@the-dagger yes create a PR with that as the base branch and I will review it.

**Comment by the-dagger** [comment]
Sure, thanks​

**Comment by samtstern** [comment]
The fix for this issue has been released in `v2.1.0`.
