### ISSUE TITLE
AuthMethodPicker is not showing up ?

### ISSUE THREAD

**Issue by AruLNadhaN** [firebase/FirebaseUI-Android#506]
I have added both the facebook & Google provider. But it automatically shows the Google ID Picker. 
I can't choose the Facebook provider.

I'm using the latest version - 1.0.1

```
@Override
    public void showLogin() {
        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setProviders(Arrays.asList(
                                new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build()))
                        .build(),
                100);
    }
```

**Comment by SUPERCILEX** [comment]
@AruLNadhaN when you have both Google and smart lock enabled, the Google sign in pops up for lightning fast sign in. Just push "none of the above" or the back button to get the other options.

**Comment by AruLNadhaN** [comment]
Thanks!

**Comment by SUPERCILEX** [comment]
You're welcome!
