### ISSUE TITLE
Unable to set the SignInActivity to portrait mode

### ISSUE THREAD

**Issue by r3dm4n** [firebase/FirebaseUI-Android#514]
### Step 2: Describe your environment

  * Android device: Nexus 5x
  * Android OS version: 6.0.0(emulator) & 7.1.1(phone)
  * Google Play Services version: 10.0.1
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.0.1
  
### Step 3: Describe the problem:

**Orientation doesn't stay in portrait mode.** 

#### Observed Results:

Orientation goes to landscape, although I specify portrait only.

**Comment by samtstern** [comment]
@r3dm4n sorry could you clarify your question?  I see a few things in your issue:

- The title mentions something about portrait mode.  FirebaseUI Auth works in portrait mode, are you having an issue with that?
- Are you having some collision with the XML name `activity_signin`?
- FirebaseUI Auth has nothing to do with a snackbar, we just use one in the sample.  You are free to use any snackbar implementation you want.

**Comment by r3dm4n** [comment]
Sure, I've I want to set FirebaseUI Auth to portrait mode only. So i've added this : 

   <activity
            android:name=".activities.SignInActivity"
            android:configChanges="keyboardHidden|orientation"
            android:screenOrientation="portrait"
            android:theme="@style/FirebaseLoginTheme">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

to my Manifest, but it still goes to Landscape mode when I turn my phone. 

What can I do about it? 
I've also posted this here http://stackoverflow.com/questions/41607336/firebaseui-login-orientation

**Comment by aviadmini** [comment]
Do you want to lock it to portrait-only orientation?

**Comment by r3dm4n** [comment]
Yes.

**Comment by samtstern** [comment]
In #522 we plan to support better landscape layouts.  We've chosen to go that direction with this rather than supporting locking this activity to portrait.
