### ISSUE TITLE
feature : User profile management

### ISSUE THREAD

**Issue by the-dagger** [firebase/FirebaseUI-Android#519]
Are there any plans of implementing user profile management to be incorporated in FirebaseUI?
According to me, it would be a pretty nifty feature that would reduce the workload done by devs.

I have implemented it in my app and was thinking about sending a pull request for the same.
My Implementation (Can also add more fields like resetting the password, etc): 

![screenshot_20170113-175422](https://cloud.githubusercontent.com/assets/6565270/21929940/62847c80-d9b9-11e6-9853-2fd2f9ace1bf.png)

Any reviews on this would be great.
Cheers.

**Comment by krisu7** [comment]
It's a duplicate of issue #235. Look there and show your idea.

**Comment by the-dagger** [comment]
Thanks,  didn't notice.
