### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by krisu7** [firebase/FirebaseUI-Android#520]
* Android device: LG Spirit 4G LTE
  * Android OS version: 6.0
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.0
  
### Step 3: Describe the problem:
FirebaseUI doesn't support RTL. Manifest merger fail.
#### Steps to reproduce:

  1. Add `android:supportsRtl="true"` to application tag in AndroidManifest
  2. build
  
#### Observed Results:

  * Error shows:
```
Error:Execution failed for task ':common:processDebugAndroidTestManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(false) from [com.firebaseui:firebase-ui-auth:1.1.0] AndroidManifest.xml:14:18-45
	is also present at [com.lapism:searchview:4.0] AndroidManifest.xml:11:18-44 value=(true).
	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at manifestMerger1460875751612441869.xml:7:5-9:19 to override.
```
  
#### Expected Results:

  * No error.
  
#### Temporary solution:

  * Add `android:supportsRtl="true"` and `tools:replace="supportsRtl"` to AndroidManifest

**Comment by alexodus** [comment]
+1

**Comment by alexodus** [comment]
my workaround:
```
 <application
        ....
        android:supportsRtl="true"
        tools:replace="android:supportsRtl"
```

**Comment by samtstern** [comment]
Using `tools:replace="android:supportsRtl"` in your own layout (as @alexodus suggested) is the correct solution.  At this time we have only tested FirebaseUI with LTR languages so we use the `supportsRtl=false` property to indicate that to end developers.

If we translate into RTL languages in the future we will change the flag.

**Comment by samtstern** [comment]
We decided to remove the RTL flag from our manifest since it was causing confusion, this change will be reflected in version `1.2.0`

**Comment by Phantomphyre** [comment]
rtl:utf-16

**Comment by shashi693** [comment]
<application
        ....
        android:supportsRtl="true"
        tools:replace="android:supportsRtl"

This solution worked out for me

**Comment by marceloslacerda** [comment]
> We decided to remove the RTL flag from our manifest since it was causing confusion, this change will be reflected in version 1.2.0

But have you tested with rtl languages?

**Comment by samtstern** [comment]
@marceloslacerda no right now FirebaseUI only supports english, so we have not done any RTL testing yet.
