### ISSUE TITLE
Support landscape and tablet layouts on all screens

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#522]
In particular, the `auth_method_picker_layout.xml` looks bad when in landscape or when on a large tablet screen.

Other screens are functional but could look nicer.

**Comment by samtstern** [comment]
Tried to fix landscape in #515 but introduced bug #521.

**Comment by aviadmini** [comment]
Non-tablet layout in landscape with logo looks pretty ugly too.

Would it be possible to use custom layouts there? (with a requirement to contain button holder layout maybe)

**Comment by samtstern** [comment]
@aviadmini yes agreed the non-tablet layout in landscape looks horrible.  We will fix this in `1.2.0`.

**Comment by consp1racy** [comment]
NestedScrollView with fillViewport I presume.

**Comment by samtstern** [comment]
Assigning this to myself, so if anyone else is working on this or was planning on starting it please contact me

**Comment by samtstern** [comment]
In #562 a fix was put in for the picker Activity.  I believe that's the only one that was totally broken in landscape.

**Comment by SUPERCILEX** [comment]
@samtstern Looks like https://github.com/firebase/FirebaseUI-Android/issues/375 is a duplicate of this issue.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.2.0`.
