### ISSUE TITLE
Firebase ui-auth dependencies do not resolve: manifest merger failed

### ISSUE THREAD

**Issue by andrewrapp** [firebase/FirebaseUI-Android#524]
### Step 2: Describe your environment

  * Android device: N/A
  * Android OS version: 6
  * Google Play Services version: N/A_____
  * Firebase/Play Services SDK version: 10.1 _____
  * FirebaseUI version: 1.1.1____
  
compileSdkVersion 25
buildToolsVersion "25.0.2"

### Step 3: Describe the problem:

I'd like to use the firebase-ui-auth with google, ex:

        startActivityForResult(
                AuthUI.getInstance()
                        .createSignInIntentBuilder()
                        .setIsSmartLockEnabled(!BuildConfig.DEBUG)
                        .setProviders(Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                                new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build()))
                        .build(),
                RC_SIGN_IN);

But I'm unable to resolve the dependencies

#### Steps to reproduce:

Make project with deps

    compile 'com.android.support:appcompat-v7:25.1.0'
    compile 'com.android.support:design:25.1.0'
    compile 'com.squareup.okhttp3:okhttp:3.5.0'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
    compile 'com.google.firebase:firebase-core:10.0.1'
    compile 'com.google.firebase:firebase-crash:10.0.1'
    compile 'com.firebaseui:firebase-ui-auth:1.1.1'

#### Observed Results:

Error is Error:Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : Attribute application@supportsRtl value=(true) from AndroidManifest.xml:15:9-35
  	is also present at [com.firebaseui:firebase-ui-auth:1.1.1] AndroidManifest.xml:14:18-45 value=(false).
  	Suggestion: add 'tools:replace="android:supportsRtl"' to <application> element at AndroidManifest.xml:11:5-50:19 to override.
  

Same result if I add:

compile 'com.google.android.gms:play-services-auth:10.0.1'

#### Relevant Code:

n/a

**Comment by krisu7** [comment]
@andrewrapp look at the issue #520

**Comment by andrewrapp** [comment]
That seems to have fixed it. In addition I had to add xmlns:tools="http://schemas.android.com/tools" to the manifest. Thanks!
