### ISSUE TITLE
Login Dialog Disappears on Screen Rotation

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#53]
When calling the showFirebaseLoginPrompt() method after a button click, I have the login screen open. However, when it is opened, if I rotate the device, the dialog resets to showing no providers.

I believe a fix needs to be implemented in the DialogFragment. If anybody knows an alternative workaround, let me know.

**Comment by abehaskins** [comment]
We're working on a fix for this in 3.1 - so it's on it's way!
