### ISSUE TITLE
Disable sign-up if email not found.

### ISSUE THREAD

**Issue by xsorifc28** [firebase/FirebaseUI-Android#530]
Welcome to FirebaseUI and thanks for submitting an issue!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Nexus 6P
  * Android OS version: 7.1
  * Google Play Services version: 10.0.1
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1
  
#### Steps to reproduce:

  1. Sign in with an email not in firebase's authentication database
  
#### Observed Results:

   FirebaseUI will open sign-up page

  
#### Expected Results:

  Be given the option to disable sign up and only allow sign in if email pre-exists.
  
#### Relevant Code:

  None

**Comment by samtstern** [comment]
@xsorifc28 we've seen this request before and I don't think we plan to support this in FirebaseUI.  I am going to close the issue for now, but can you explain why you don't want sign up in your app?

**Comment by xsorifc28** [comment]
@samtstern We are building an app for a conference which should only allow users to login if they have pre-registered and paid using our web-app.

**Comment by samtstern** [comment]
Ok thanks for explaining.  This was also asked in #385.  I think forking the library to do this should be fairly simple, but right now (as I said) it's not on our roadmap.

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.2.0`.

**Comment by lindsaymacvean** [comment]
Where is the configuration setting for this? I have looked through the documentation and I cannot find it.

**Comment by ArtbyRere** [comment]
Trying to add,
import java.util.ArrayList;
11
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L11>
import java.util.Arrays;
12
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L12>
import java.util.List;
13
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L13>
14
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L14>
public class ConfigurationUtils {
15
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L15>
16
<https://github.com/firebase/FirebaseUI-Android/blob/8bda799672d44fd2994d2498441859fae3ccb530/app/src/main/java/com/firebase/uidemo/util/ConfigurationUtils.java#L16>
public static boolean isGoogleMisconfigured(Context context) {

**Comment by lindsaymacvean** [comment]
ah I made a mistake and thought I was still looking at threads for Firebase web UI. Thankyou for replying.

**Comment by SoleR7** [comment]
If this have been implemented can anyone guide me of how to do it?
I have a Login Activity with a Google OAuth button but I only want users that are already registered in my Firebase Auth to LogIn.

**Comment by lindsaymacvean** [comment]
I think we implemented something in Angular here

https://github.com/aromakh/learning-fortress-frontend/commit/f3b6ad4b51fc3d45ed3850a0e22725622d7ce24e#diff-3166fa712a8793a6d8af6eafc3aa44f2R21

**Comment by SoleR7** [comment]
I work with Java in an Android Studio project do you know if it would work? Thanks :)

**Comment by rami-alloush** [comment]
@SoleR7 .. the working code is here https://github.com/firebase/FirebaseUI-Android/issues/1410#issuecomment-412715410
Hope this helps :)
