### ISSUE TITLE
How to change from setReadPermissions in Facebook provider to setPublishPermissions

### ISSUE THREAD

**Issue by judeebene** [firebase/FirebaseUI-Android#535]
What is the best method to change from  read permission to publish permission in facebook Provider Using Firebase UI.

By default, Firebase UI uses  "facebook read permission for login"  as seen in FacebookProvider.java in  line 114   loginManager.logInWithReadPermissions(activity, permissionsList);

 which is quite OK ,but when the user want to share on facebook, it require that the read permission should be changed to  publish permission.
and trying to change directly without firebase UI, seems not to work 
 LoginManager.getInstance().logInWithPublishPermissions(...)

so What is the best method to do it with Firebase UI?

**Comment by samtstern** [comment]
@judeebene thanks pointing this out.  I don't think we had considered the two types of permissions, I will try to address this in the next version

**Comment by samtstern** [comment]
@judeebene unfortunately after some investigation we can't support this feature please see discussion in #592 for the reasons.

Facebook makes it intentionally hard to request read and publish permissions at the same time so it won't fit within the flow of FirebaseUI.  The best thing to do is provide only your read permissions to FirebaseUI and then after the user has signed in ask again for the publish permissions (which is what Facebook's guidelines suggest)
