### ISSUE TITLE
FirebaseUI AboutLibraries

### ISSUE THREAD

**Issue by krisu7** [firebase/FirebaseUI-Android#538]
Hi, I recently came across library AboutLibraries by Mike Penz, you can find it here: [https://github.com/mikepenz/AboutLibraries](https://github.com/mikepenz/AboutLibraries)

Some applications need a disclaimer about opensource libraries used in the project and AboutLibraries makes it easy and painless (no endless copying). AboutLibraries provides auto detection.

To provide info from FirebaseUI we just need to insert one strings file to resources that looks like this:

```
<?xml version="1.0" encoding="utf-8"?>

<resources>
	<string name="define_int_firebaseuiforandroid—storage"></string>
	<!-- Author section -->
	<string name="library_firebaseuiforandroid—storage_author">Google</string>
	<string name="library_firebaseuiforandroid—storage_authorWebsite">https://firebase.google.com</string>
	<!-- Library section -->
	<string name="library_firebaseuiforandroid—storage_libraryName">FirebaseUI for Android — Storage</string>
	<string name="library_firebaseuiforandroid—storage_libraryDescription">UI bindings for Firebase</string>
	<string name="library_firebaseuiforandroid—storage_libraryWebsite">https://github.com/firebase/FirebaseUI-Android/tree/master/storage</string>
	<string name="library_firebaseuiforandroid—storage_libraryVersion">1.1.1</string>
	<!-- OpenSource section -->
	<string name="library_firebaseuiforandroid—storage_isOpenSource">true</string>
	<string name="library_firebaseuiforandroid—storage_repositoryLink">https://github.com/firebase/FirebaseUI-Android/tree/master/storage</string>
	<!-- ClassPath for autoDetect section -->
	<string name="library_firebaseuiforandroid—storage_classPath">com.firebase.ui.storage</string>
	<!-- License section -->
	<string name="library_firebaseuiforandroid—storage_licenseId">apache_2_0</string>
	<!-- Custom variables section -->
</resources>
```
to database, auth and storage. It can be generated here: [http://def-builder.mikepenz.com/](http://def-builder.mikepenz.com/)

I can submit a PR containing this and change sample application to include overflow menu with About item.

```
new LibsBuilder()
        //provide a style (optional) (LIGHT, DARK, LIGHT_DARK_TOOLBAR)
        .withActivityStyle(Libs.ActivityStyle.LIGHT_DARK_TOOLBAR)
        //start the activity
        .start(this);
```

**Comment by samtstern** [comment]
@krisu7 thanks for showing this to us.  I was not previously familiar with this "AboutLibraries" repository.  I think for right now this is something better left to individual developers and not made part of the core library, since this is the first request we've had.  If we get more requests of this type I'd be happy to reconsider.

Also I went through the wizard and generated strings you can use (although yours look fine too!):
```xml
<?xml version="1.0" encoding="utf-8"?>

<resources>
	<string name="define_firebaseui_android"></string>
	<!-- Author section -->
	<string name="library_firebaseui_android_author">Google, Inc</string>
	<string name="library_firebaseui_android_authorWebsite">https://firebase.google.com</string>
	<!-- Library section -->
	<string name="library_firebaseui_android_libraryName">FirebaseUI-Android</string>
	<string name="library_firebaseui_android_libraryDescription">UI bindings for Firebase</string>
	<string name="library_firebaseui_android_libraryWebsite">https://firebase.google.com/docs</string>
	<string name="library_firebaseui_android_libraryVersion">1.1.1</string>
	<!-- OpenSource section -->
	<string name="library_firebaseui_android_isOpenSource">true</string>
	<string name="library_firebaseui_android_repositoryLink">https://github.com/firebase/firebaseui-android</string>
	<!-- ClassPath for autoDetect section -->
	<string name="library_firebaseui_android_classPath">com.firebase.ui</string>
	<!-- License section -->
	<string name="library_firebaseui_android_licenseId">apache_2_0</string>
	<!-- Custom variables section -->
</resources>
```

**Comment by SUPERCILEX** [comment]
@krisu7 I've been using https://github.com/yshrsmz/LicenseAdapter which works quite well for me.

**Comment by krisu7** [comment]
@samtstern Thanks for the string resources

@SUPERCILEX Thanks for the suggestion, it looks nice

**Comment by mobiRic** [comment]
+1 for AboutLibraries config file to be included in this project.

@samtstern Thanks again for the string resources. However I think it is important to note that many people disregard the OSS licence requirements, and the easier each project makes it to include valid licencing, the better. 

The nice thing in AboutLibraries is that by including that xml file in your repo, Mike Penz's project will automatically include your library in the list without further developer intervention.
