### ISSUE TITLE
Could I implement generic ChildEventListener?

### ISSUE THREAD

**Issue by CyberNyanta** [firebase/FirebaseUI-Android#548]
I'm trying to implement generic analog of FirebaseArray,
And I'd like to know can I somehow put generic type in 
`snapshot.getValue(Generic)`
in methods `onChildAdded`, `onChildChanged`, `onChildRemoved`, `onChildMoved`

**Comment by CyberNyanta** [comment]
I found related solution for Lists with `GenericTypeIndicator`
[firebase.com/docs/...](https://www.firebase.com/docs/java-api/javadoc/com/firebase/client/GenericTypeIndicator.html)
```
GenericTypeIndicator<List<Message>> t = new GenericTypeIndicator<List<Message>>() {};
     List<Message> messages = snapshot.getValue(t);
```
But I couldn't adapt it for single items

**Comment by samtstern** [comment]
@CyberNyanta I'm not sure if I completely understand your question, but let me see if I can.

I think you'd like to implement a class like this:

```java
public class MyArray<T> implements ChildEventListener {

   // ...

   @Override
   public void onChildAdded(DataSnapshot child, String prevChildKey) {
       T data = child.getData(T.class);
   }

}
```

Unfortunately due to the way Java implements generics you can'd do that, but you can do this:

```java
public class MyArray<T> implements ChildEventListener {

   // ...

   private Class<T> mClazz;

   public MyArray(Class<T> clazz) {
     mClazz = clazz;
   }


   @Override
   public void onChildAdded(DataSnapshot child, String prevChildKey) {
       T data = child.getData(mClazz);
   }

}
```

**Comment by CyberNyanta** [comment]
Thank you!
