### ISSUE TITLE
Authenticating or Logging In

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#55]
I am setting up my Facebook Login flow and am unsure if this code is redundant. Does the onFirebaseLogged in method authenticate the user or simply log them in?

    @Override
    protected void onFirebaseLoggedIn(AuthData authData) {
        mUserRef.authWithOAuthToken(authData.getProvider(), authData.getToken(), new Firebase.AuthResultHandler() {
            @Override
            public void onAuthenticated(AuthData authData) {
                Map<String, Object> loginMap = new HashMap<String, Object>();
                loginMap.put("email", authData.getProviderData().get("email"));
                loginMap.put("provider", authData.getProvider());
                mUserRef.child(authData.getUid()).updateChildren(loginMap);
            }

            @Override
            public void onAuthenticationError(FirebaseError firebaseError) {
                Toast.makeText(getApplicationContext(), firebaseError.getMessage(), Toast.LENGTH_LONG).show();

            }
        });

    }

**Comment by puf** [comment]
The `onFirebaseLoggedIn()` method is invoked when the user is authenticated with Firebase. You don't have to perform further calls on the ref to authenticate them

**Comment by troy21688** [comment]
Thanks!
