### ISSUE TITLE
Email authentication typo results in poor UX

### ISSUE THREAD

**Issue by togic8** [firebase/FirebaseUI-Android#554]
#### Versions

  * Google Play Services version: 10.0.1
  * FirebaseUI version: 1.1.1

#### Steps to reproduce:

  1. Authenticate using email.
  2. Sign out.
  3. Try to authenticate again, using the same email, but "accidentally" introduce a typo (for example, replace an "n" with an "m" in the email address).
  
#### Observed Results:

  * Firebase correctly assumes this is a new email address, rather than a returning user; however, after the user realizes they have entered their email address incorrectly and proceeds to fix their mistake on the "new user" page, they must re-enter their name and password. This is not the problem. The problem is when they try to log in and then they are met with the error "an account already exists with that email address" rather than being authenticated using the correct email & password combination.
  
#### Expected Results:

  * After correcting their email address and entering their name and password, if their email address & password hash match a record in the user base, they should be authenticated as that user. If you really want to be paranoid, make it so that the name also has to match (ignoring case, probably) the name already on record for that account.

**Comment by SUPERCILEX** [comment]
@samtstern @togic8  This was a conscious decision https://github.com/firebase/FirebaseUI-Android/pull/447#discussion_r91544515 to make the UX feel less janky, but I'm wondering if we could compromise and forward the user along to the sign in page while showing a toast or something.

https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/ui/email/RegisterEmailFragment.java#L288
