### ISSUE TITLE
FirebaseIndexRecyclerView does not take sorting into account

### ISSUE THREAD

**Issue by peterhav** [firebase/FirebaseUI-Android#555]
### Step 2: Describe your environment

  * Android device: emulator
  * Android OS version: 25
  * Google Play Services version: 10.0.1
  * Firebase/Play Services SDK version: 25.1.0
  * FirebaseUI version: 1.1.1
  
#### Observed Results:

When creating my (Index) adapter as follows:

`mAdapter = new FirebaseIndexRecyclerAdapter<Participant, ParticipantViewHolder>( Participant.class, R.layout.participant_card, ParticipantViewHolder.class, DataUtil.getParticipantIndexList( mEventKey), DataUtil.getParticipantsRoot( mEventKey ).orderByChild( fieldToSortOn )) {`

The result is a list that is not sorted on the '`fieldToSortOn`'.

When I switch to a 'non' index adapter (directly pointing to the root of the data):

`mAdapter = new FirebaseRecyclerAdapter<Participant, ParticipantViewHolder>( Participant.class, R.layout.participant_card, ParticipantViewHolder.class, DataUtil.getParticipantsRoot( mEventKey).orderByChild( fieldToSortOn )) {`

the list is sorted on the '`fieldToSortOn`' as expected.
  
#### Expected Results:

I would expect the `FirebaseIndexRecyclerAdapter `to display the items with keys located at '`Query keyRef`' using the sorting as provided in the '`Query dataRef`' argument.

**Comment by SUPERCILEX** [comment]
@peterhav This is expected behavior, see the [README](https://github.com/firebase/FirebaseUI-Android/blob/master/database/README.md#a-note-on-ordering).

If you want an explanation and some discussion: https://github.com/firebase/FirebaseUI-Android/issues/537#issuecomment-275943049.

**Comment by samtstern** [comment]
Thanks @SUPERCILEX
