### ISSUE TITLE
Order Firebase RecyclerView by Child Value

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#557]
I have a data structure (see below) and I essentially want to create a "trending" section that emphasizes the items that have the most votes. Votes are accounted for in the vote_count field of my Firebase database.

I know there is the .orderByChild() method available in Firebase. Would it be possible to have my RecyclerView sort the data based on the value of the vote_count child (descending order)?

![image](https://cloud.githubusercontent.com/assets/16483832/22442115/c01eb132-e6ff-11e6-8c1d-ac9901fa5e94.png)

  ```

**Comment by SUPERCILEX** [comment]
@troy21688 indexed or plain?

**Comment by troy21688** [comment]
Can you elaborate Alex? I do not understand what you mean. Appreciate the
prompt response.

**Comment by SUPERCILEX** [comment]
Sorry, are you using the index adapters or just the plain ones (`FirebaseIndexRecyclerAdapter` vs `FirebaseRecyclerAdapter`).

**Comment by troy21688** [comment]
The plain adapter but believe I have my Pojo set up for index if necessary.

**Comment by SUPERCILEX** [comment]
@troy21688 No, that's good. Since you can pass in a query, just use `orderByChild("vote_count")` for the query/ref you pass into your adapter.

**Comment by samtstern** [comment]
I believe @SUPERCILEX has the correct solution here so closing the issue.

@troy21688 in general it's better to post "how to" type questions on StackOverflow, issues here should be reporting instances where the library does not work as expected.

**Comment by jesusignazio** [comment]
And what about to make data appear in descending order as he requested?
There is no inverted .orderByChild() function...
There is some way? Thanks

**Comment by karamJAB** [comment]
@jesusignazio setReverseLayout with your layout manager and then setstackfromend will do the descending order

**Comment by jesusignazio** [comment]
@karamJAB yes, I edited my message when I got the solution.

Thanks.
