### ISSUE TITLE
Consider allowing email hints even when smartlock disabled

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#558]
We should consider allowing email autofill in the email flow even when smartlock is disabled for actual retrieval/storage of credentials.

Pros:
  * We know this increases conversion rates for email flows significantly
  * Does not really hurt development

Cons:
  * The email hint selector looks like the Google account picker and may be confusing

**Comment by SUPERCILEX** [comment]
@samtstern I'm in strong favor of doing this, but there's another con you mentioned before: still using smart lock when the developer explicitly said we shouldn't breaks the API contact. However, this use of smart lock isn't related to saving passwords so I think it should be fine.

**Comment by samtstern** [comment]
Yeah @SUPERCILEX we'd likely have to change the name of the flag

**Comment by SUPERCILEX** [comment]
@samtstern Hmmmm, this would cause problems for stuff like #200. 😢
