### ISSUE TITLE
NullPointer Exception with Twitter Implementation

### ISSUE THREAD

**Issue by troy21688** [firebase/FirebaseUI-Android#57]
I have added Twitter Login to my application, however I am receiving the following error:

```
01-11 15:04:20.474 31823-31823/? D/AndroidRuntime: Shutting down VM
01-11 15:04:20.474 31823-31823/? W/dalvikvm: threadid=1: thread exiting
with uncaught exception (group=0x41819da0)
01-11 15:04:20.474 1181-1181/? D/WfcActivityStateReceiver: onReceive():
packageName=com.sourcey.materialloginexample, activityState=resume
01-11 15:04:20.474 31823-31823/? E/AndroidRuntime: FATAL EXCEPTION: main
Process:
com.sourcey.materialloginexample, PID: 31823

java.lang.NullPointerException at com.firebase.ui.auth.twitter.TwitterPromptActivity$1.onPostExecute(TwitterPromptActivity.java:98)
at com.firebase.ui.auth.twitter.TwitterPromptActivity$1.onPostExecute(TwitterPromptActivity.java:71)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5692)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
at dalvik.system.NativeStart.main(Native Method)
01-11 15:04:20.484 767-931/? D/PointerIcon: setMouseIconStyle1 pointerType:
1001iconType:101 flag:0
```

**Comment by troy21688** [comment]
I have added Twitter Login to my application, however I am receiving the following error:

01-11 15:04:20.474 31823-31823/? D/AndroidRuntime: Shutting down VM
01-11 15:04:20.474 31823-31823/? W/dalvikvm: threadid=1: thread exiting
with uncaught exception (group=0x41819da0)
01-11 15:04:20.474 1181-1181/? D/WfcActivityStateReceiver: onReceive():
packageName=com.sourcey.materialloginexample, activityState=resume
01-11 15:04:20.474 31823-31823/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process:
com.sourcey.materialloginexample, PID: 31823

 java.lang.NullPointerException
                                                       at
com.firebase.ui.auth.twitter.TwitterPromptActivity$1.onPostExecute(TwitterPromptActivity.java:98)
                                                       at
com.firebase.ui.auth.twitter.TwitterPromptActivity$1.onPostExecute(TwitterPromptActivity.java:71)
                                                       at
android.os.AsyncTask.finish(AsyncTask.java:632)
                                                       at
android.os.AsyncTask.access$600(AsyncTask.java:177)
                                                       at
android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
                                                       at
android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at
android.os.Looper.loop(Looper.java:146)
                                                       at
android.app.ActivityThread.main(ActivityThread.java:5692)
                                                       at
java.lang.reflect.Method.invokeNative(Native Method)
                                                       at
java.lang.reflect.Method.invoke(Method.java:515)
                                                       at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1291)
                                                       at
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1107)
                                                       at
dalvik.system.NativeStart.main(Native Method)
01-11 15:04:20.484 767-931/? D/PointerIcon: setMouseIconStyle1 pointerType:
1001iconType:101 flag:0

**Comment by abehaskins** [comment]
Thanks for the report.

Can you provide the steps you followed to receive this error? Please be as detailed as possible. 

I suspect this is an issue related to tearing down and rebuilding of activities which happens when someone clicks away from your app or the phone locks/unlocks, but I'll need more info to be sure :)

Thanks!
