### ISSUE TITLE
Double tap shown when doing a tap on a row in the SmartLock ViewList

### ISSUE THREAD

**Issue by danielemaddaluno** [firebase/FirebaseUI-Android#570]
#### The enviroment
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.1.1
  
#### Steps to reproduce:

  1. Launch the demo Firebase-Ui app for Android
  2. Go in the Auth section
  3. Turn on Smart Log
  4. Tap on Start
  5. Tap on an item row
  
#### Observed Results:

  * You can see a double tap on that row instead of a single tap.
You can see two gray circles in the image below instead of a single one inside the row:
![media-20170203](https://cloud.githubusercontent.com/assets/1886810/22591850/e9f33068-ea16-11e6-8cb8-457356a8d886.png)
  
#### Expected Results:

  * Only a single tap should be shown

**Comment by SUPERCILEX** [comment]
@samtstern @danielemaddaluno This isn't controlled by FirebaseUI, it's a Smart Lock thing (eg Play Services).

PS: I can't repro so they probably fixed in the 10.2.0 release.

**Comment by samtstern** [comment]
@SUPERCILEX thanks!
