### ISSUE TITLE
Remove label and allowBackup from library AndroidManifest

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#58]
This is the contents of the `AndroidManifest.xml` file in the `library` folder:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.firebase.ui">
    <application android:allowBackup="true" android:label="@string/app_name">
    </application>
</manifest>
```

The `allowBackup` and `label` properties should be removed so they do not affect applications that include FirebaseUI.

**Comment by abehaskins** [comment]
Thanks Sam,

This was already addressed in #45 so it's coming in 3.1!
