### ISSUE TITLE
How to get the position of an item in FirebaseRecyclerAdapter.parseSnapshot()

### ISSUE THREAD

**Issue by Brianvdb** [firebase/FirebaseUI-Android#580]
I am using my own class which extends the `FirebaseReyclerAdapter` to make it more modular. 

Yet I come accross one issue. I am overriding the `parseSnapshot(DataSnapshot dataSnapshot)` method to do custom parsing but when that method gets called I do not know what position the DataSnapshot belongs to. I also cannot get the `mSnapshots` instance variable because it is private. Because of that it is also not possible to override the `getItem(int position)` method. I need the position / viewtype for custom parsing.

My suggestion is to add a position parameter to the `parseSnapshot` method. Or is there an other way to get the position?

**Comment by puf** [comment]
Passing the position to `parseSnapshot` sounds like a useful addition to me. So +1.

**Comment by SUPERCILEX** [comment]
@puf if #544 goes through, I'd rather not do that because it would make the `SnapshotParser` interface messy. (People will be able to do `mSnapshots.indexOf(snapshot)` because it's just a list.)

**Comment by samtstern** [comment]
As #544 has been merged I am going to close this issue.  @Brianvdb I agree with @SUPERCILEX here, the snapshot parsing should be kept separate from the list ordering/presentation.  I believe that when version 2.0 comes out you will have enough customization abilities to implement what you're trying to do though.

**Comment by marcos2122** [comment]
has probado con
@Override
    public int getItemViewType(int position){
        return position; }
