### ISSUE TITLE
Changing order of auth providers

### ISSUE THREAD

**Issue by davidvavra** [firebase/FirebaseUI-Android#586]
When I setup the library, I always get this provider order on the first screen:
1. Facebook
2. Google
3. Email

I would like to have Google first. There doesn't need to be a new API for this, just following the order in the provider list.

**Comment by SUPERCILEX** [comment]
@davidvavra Just change the order in which you provide the `IdpConfig` builders:
```java
Collections.unmodifiableList(
        Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.TWITTER_PROVIDER).build(), // It's backwards for some reason, the top ones are last visually.
                      new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build(),
                      new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                      new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build())); // Email is always on the bottom.
```

**Comment by davidvavra** [comment]
OK, thanks this workaround works. But it's still a bug - the library should follow the specified order.

**Comment by SUPERCILEX** [comment]
@davidvavra Yeah, but at this point changing it would break the order for everyone already using FirebaseUI so we're kind of stuck in a tough situation.

@samtstern Do you think we should fix the order bug or leave it given what I said above?

**Comment by samtstern** [comment]
Yeah I'd rather not break current people, even though @davidvavra is right that it would have been better to follow the specified order in the first place!

**Comment by davidvavra** [comment]
Well, I think at least this should be documented somewhere.
