### ISSUE TITLE
ProgressDialog of SignInDelegate in KickOffActivity uses the wrong progress bar color

### ISSUE THREAD

**Issue by Alex100** [firebase/FirebaseUI-Android#588]
KickOffActivity does not set the customized theme. That's the reason why the SignInDelegate fragment uses the default progress bar color. KickOffActivity should extend from AppCompatBase to fix this bug.
Tested in FB UI 1.1.1

**Comment by SUPERCILEX** [comment]
@Alex100 this was a calculated decision. If we use the custom theme, `KickOffActivity` will not be transparent and it will look gross. If you can think of a way to use the custom theme while keeping `KickOffActivity` transparent, that would be awesome!

**Comment by Alex100** [comment]
This line in FragmentHelper inside of showLoadingDialog() would do the trick:
Context context = getFlowParams().themeId !=  0 ? new ContextThemeWrapper(mFragment.getContext(), getFlowParams().themeId) : mFragment.getContext();

Here the whole method:

    @Override
    public void showLoadingDialog(String message) {
        dismissDialog();

        Context context = getFlowParams().themeId !=  0 ? new ContextThemeWrapper(mFragment.getContext(), getFlowParams().themeId) : mFragment.getContext();
        mProgressDialog = ProgressDialog.show(context, "", message, true);
    }

**Comment by samtstern** [comment]
@Alex100 huh I had no idea about `ContextThemeWrapper`, thanks for the tip!  I think you're right, we can fix this.

**Comment by SUPERCILEX** [comment]
@samtstern It worked!!!!!! That's so amazing! @Alex100 You're a god, thanks! 😆

![screenshot_20170213-130010](https://cloud.githubusercontent.com/assets/9490724/22903184/a4bfd39c-f1ec-11e6-968a-9c54e43d086e.png)

**Comment by SUPERCILEX** [comment]
@Alex100 @samtstern Uh oh, the whole class is marked as a restricted api.

**Comment by Alex100** [comment]
@SUPERCILEX There are two implementations of `ContextThemeWrapper`:

1. `android.support.v7.view.ContextThemeWrapper` (restricted)
2. `android.view.ContextThemeWrapper` (not restricted)

(https://code.google.com/p/android/issues/detail?id=227580)

**Comment by SUPERCILEX** [comment]
@Alex100 yeah, it was my bad. #589 was already merged so we're good. Thanks for the explanation though!

**Comment by samtstern** [comment]
The fix for this issue has been released in version `1.2.0`.
