### ISSUE TITLE
getConnectedGoogleApiClient() of  GoogleApiClientTaskHelper returns a unconnected GoogleApiClient

### ISSUE THREAD

**Issue by Alex100** [firebase/FirebaseUI-Android#597]
My debugger showed me that `getConnectedGoogleApiClient` in the `GoogleApiClientTaskHelper` class can return an unconnected `googleApiClient`:

![image](https://cloud.githubusercontent.com/assets/4115023/23023531/6257a90a-f456-11e6-963d-2fa6f1dea194.png)

At the moment I am not able to reproduce this state of the `GoogleApiClientTaskHelper`. This state, however results in a not responding callback of any following `Auth.CredentialsApi.<method>()` (see http://stackoverflow.com/a/34539716). I guess that the missing implementation of `public void onConnectionSuspended(int i) {}` in `GoogleApiClientTaskHelper` causes this state.

**Comment by SUPERCILEX** [comment]
@samtstern I think this issue can be closed since that stuff was deprecated in `v1.2.0`.

@Alex100 Please use the [much improved class](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/util/GoogleApiHelper.java#L43) instead.

**Comment by samtstern** [comment]
@SUPERCILEX thanks for responding.
