### ISSUE TITLE
FirebaseRecyclerAdapter not recognizing Constructor view in SDK 25.1.1

### ISSUE THREAD

**Issue by RagingRiver** [firebase/FirebaseUI-Android#598]
I was updating to the latest SDK and libraries when the FirebaseRecyclerAdapter starting crashing due to an unknown view. So the recycler adapter is working with SDK 25.1.0 but not with 25.1.1. The adapter fails when it tries to update the Constructor in the method below with NoSuchMethodException error:

    @Override
    public VH onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(viewType, parent, false);
        try {
            Constructor<VH> constructor = mViewHolderClass.getConstructor(View.class);
            return constructor.newInstance(view);
        } catch (NoSuchMethodException e) {
            throw new RuntimeException(e);
        } catch (InvocationTargetException e) {
            throw new RuntimeException(e);
        } catch (InstantiationException e) {
            throw new RuntimeException(e);
        } catch (IllegalAccessException e) {
            throw new RuntimeException(e);
        }
    }

**Comment by samtstern** [comment]
@RagingRiver can you paste the error you're getting here?

**Comment by RagingRiver** [comment]
@samtstern I went back to SDK 25.1.1 to reproduce the error and it no longer exists. Firebase has a lot of persistent data and it may be related to that. You can close this bug report out for now. Thanks
