### ISSUE TITLE
Facebook login failed and crash with Firebase UI  Auth 1.1.1

### ISSUE THREAD

**Issue by davidgcalle** [firebase/FirebaseUI-Android#599]
Hi, as the title says, had some issues with the version 1.1.1 of  com.firebaseui:firebase-ui-auth, when trying to login with Facebook crashes on my Nexus 6, Android 7 device. Later try to login with an Huawei G Play mini, and failed to login but didn´t crashed.

Had to come back to version 1.0.0 of com.firebaseui:firebase-ui-auth and google services version 9.8.0.

Any tip on this will be most appreciated.

**Comment by samtstern** [comment]
Can you provide a log from the crash?

**Comment by SUPERCILEX** [comment]
@samtstern I'm going through old issues and it looks like this one hasn't been updated in a few months so might as well close it.

**Comment by samtstern** [comment]
@SUPERCILEX good catch.
