### ISSUE TITLE
email & password fields visible even if password provider disabled

### ISSUE THREAD

**Issue by JuhaniLehtimaeki** [firebase/FirebaseUI-Android#60]
Only enabling 3rd party providers removes the "login" button from the popup but the email & password fields are still visible as well as the "or" divider.
If password is not enabled all of those components should be set to GONE.

**Comment by jeetdholakia** [comment]
I'm facing the same issue, how do I solve that?

**Comment by jorgevvr** [comment]
Please, how i can do to use this fix, cause i want publish my app, but i want not show the login fields, only the facebook and google login.

thanks in advance.

**Comment by puf** [comment]
The fix is in the master branch waiting for release. We're just waiting to
get some more fixes in before cutting a release.

If you can't wait for that, you can build a release of the library yourself
with the instructions in the README.

**Comment by ethnp** [comment]
Any idea when this will be released? I'm having the same issue :(

**Comment by jorgevvr** [comment]
I got it working, if you want contact me i will be happy to help.

**Comment by ankitrampal** [comment]
@jorgevvr Can you tell how to do it ?

**Comment by jorgevvr** [comment]
Send me email, jorgevvr@gmail.com

**Comment by zdr00** [comment]
What is the name of the elements to hide? with Visibility.set(View.GONE);
