### ISSUE TITLE
Support library version too low

### ISSUE THREAD

**Issue by yudhir** [firebase/FirebaseUI-Android#613]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: All
  * Android OS version: All
  * Google Play Services version: 10.2.0
  * Firebase/Play Services SDK version: 10.2.0
  * FirebaseUI version: 1.2
  
### Step 3: Describe the problem:

Customtabs at version 25.1.1 while it should be
#### Steps to reproduce:

  1. Gradle Warns about the multiple version

  
#### Observed Results:

  Warning
  
#### Expected Results:

  Slow Downs
  
#### Relevant Code:

  ```
 
  ```

**Comment by TomislavHorvat1** [comment]
I can confirm this issue

**Comment by samtstern** [comment]
Changed the title of this issue so we can use it to track all discussions about the support lib dependency and associated pain.

**Comment by qvivr-jeffrey** [comment]
Hi, is there any update for this? Would like to get hands dirty on the new support library for O. I am seeing latest firebase core 11.0.0 and support library 25.3.1. Hope there are new update from this UI library.

**Comment by samtstern** [comment]
Update coming very soon to version `2.0` which will depend on `11.0.0` and `25.3.1`.

**Comment by qvivr-jeffrey** [comment]
Thank you, but today I downloaded android O sdk, and now I need to be on 26.0.0 🤔

**Comment by samtstern** [comment]
@qvivr-jeffrey this will always be something we are chasing, but you can normally work around it.  See the instructions here:
https://github.com/firebase/FirebaseUI-Android/tree/version-2.0.0-dev#upgrading-dependencies

**Comment by TheCraftKid** [comment]
Hey, I'm wondering if the new [Gradle version](https://docs.gradle.org/3.4/release-notes.html#compile-avoidance-for-java) will be of any use for managing dependencies. Otherwise, I think we should update the build.gradle files to take into account `compile` deprecation in favor of using `api` or `implementation`.

**Comment by samtstern** [comment]
@TheCraftKid we do plan to switch to `implementation` once the `3.0` plugin stabilizes.  When I experimented with it there were a few errors in each of the `alpha` versions and I decided to go the safe route.

**Comment by SUPERCILEX** [comment]
@TheCraftKid yeah that's the plan: the Firebase and support  lib deps will be `api` and the rest will be `implementation`.

**Comment by edmundjohnson** [comment]
I'm getting the following:

`All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.4.0, 25.3.1. Examples include com.android.support:animated-vector-drawable:25.4.0 and com.android.support:cardview-v7:25.3.1`

with these dependencies, as per constants.gradle:

```
compile "com.android.support:appcompat-v7:25.4.0"
compile "com.google.firebase:firebase-core:11.0.1"
compile "com.google.firebase:firebase-auth:11.0.1"
compile "com.firebaseui:firebase-ui-auth:2.0.1"

```
Hope it's OK to comment on a closed issue, rather than opening a new one.

**Comment by samtstern** [comment]
@edmundjohnson you have two options:

1. Change your appcompat dependency to `25.3.1`
2. Add explicit dependencies on all of FirebaseUI's support lib deps at version `25.4.0`.

See: https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies

**Comment by kikin81** [comment]
I'm also running into this issue.
Our app depends on appcompat version `27.0.2` but the Firebase core ui is stuck on `25.0.2`
