### ISSUE TITLE
Facebook Provider getPhotoUrl()  URL is now returning URL signature expired

### ISSUE THREAD

**Issue by judeebene** [firebase/FirebaseUI-Android#614]
When ever  a User login with facebook , i set the profile picture using  FirebaseUser.getPhotoUrl().
Everything was working just fine but now the profile picture has suddenly stopped working. Opening it's URL in a browser gives me this message "URL signature expired"

[https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/14947700_10211346547930488_8169418338838920166_n.jpg?oh=714b8042c1c1a510af58da515660d951&oe=588E990D](https://scontent.xx.fbcdn.net/v/t1.0-1/p100x100/14947700_10211346547930488_8169418338838920166_n.jpg?oh=714b8042c1c1a510af58da515660d951&oe=588E990D)

Its the a way i can  refresh the url and get the latest version whenever i call FirebaseUser.getPhotoUrl()?

**Comment by samtstern** [comment]
@judeebene thanks for this report, looking into it

**Comment by HarrisonGuzman** [comment]
FirebaseUser user = mAuth.getCurrentUser();
                        if (user != null) {
                            // User is signed in
                            // Name, email address, and profile photo Url
                            String facebookUserId = "";
                            Global.nombresusuario = user.getDisplayName();
                            Global.emailusuario = user.getEmail();
                            Global.uid = user.getUid();
                            Global.proveedor="facebook";
                         

                            // find the Facebook profile and get the user's id
                            for(UserInfo profile : user.getProviderData()) {
                                facebookUserId = profile.getUid();
                               
                            }

                            Global.linkfoto = "https://graph.facebook.com/" + facebookUserId + "/picture?height=500";

**Comment by HarrisonGuzman** [comment]
for(UserInfo profile : user.getProviderData()) { 
facebookUserId = profile.getUid();
 }
 Global.linkfoto = "https://graph.facebook.com/" + facebookUserId + "/picture?height=500";

**Comment by samtstern** [comment]
Hey all, I am still pushing to see if we can do anything about this on the backend but it's not an issue with FirebaseUI so going to close it here.  Thanks everyone for reporting this and detailing workarounds.
