### ISSUE TITLE
Persistence between providers

### ISSUE THREAD

**Issue by tremerhl** [firebase/FirebaseUI-Android#62]
New login flow returns authData for all providers, but facebook & twitter data doesn't have user email (and they often use nickname/phone as a login), so it can't be used to link google, email, fb and twitter accounts to provide seamless experience even if user logs in with different provider. 
Is it possible to somehow link them and provide a unique id? (currently uid is different per provider)

**Comment by puf** [comment]
Would indeed be an awesome feature. But unfortunately it is not feature of the underlying Firebase Authentication service, so can't be easily wrapped in FirebaseUI.
