### ISSUE TITLE
Support Facebook login without email

### ISSUE THREAD

**Issue by puilp0502** [firebase/FirebaseUI-Android#623]
The gist is same as #352.  

Currently, if the GraphRequest response object does not have an email field for whatever reason (e.g. User's denial, [Facebook's error](http://stackoverflow.com/questions/16630972/facebook-graph-api-wont-return-email-address), etc), it just logs JSONException and fail([src](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/provider/FacebookProvider.java#L148-L151)). 
 However, [TwitterProvider.java](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/java/com/firebase/ui/auth/provider/TwitterProvider.java#L99-L102) just creates user with no email, and I think FacebookProvider.java should do the same. 
 The current implementation, if not provided with email, just returns to the AuthMethodPicker without providing user with additional information, which is very bad in terms of UX.

The source doesn't seem to be complicated, so I would be able to write a PR for this if desired.

**Comment by SUPERCILEX** [comment]
@puilp0502 Smart lock won't work if we do that, but I can see how it's better to just get the user logged in anyway. Unless @samtstern has any objects I think we should let the user deny us the email permission. 

@puilp0502 do you want to submit a PR for this? If not, I'll go ahead and do it.

**Comment by puilp0502** [comment]
@SUPERCILEX Yeah, I'll write a PR for that.

**Comment by SUPERCILEX** [comment]
SGTM!

**Comment by samtstern** [comment]
@puilp0502 thanks for the PR.  I have a question about this in general: do you have the 'multiple accounts per email' switch turned on in the Firebase console?

**Comment by puilp0502** [comment]
No, it's set to 'One account per email address'.

**Comment by cpauwels** [comment]
Hi, is there an estimated release date for these fixes?

This is quite the issue in developing countries where many users are signed in with their phone number instead of an email, leading to the errors.

We launched our beta yesterday and did 8 user testing interviews, and 2 of our users could not sign in. This is a huge issue if 25% of our user base can't create an account.

**Comment by samtstern** [comment]
@cpauwels this will be in version `2.0.0`.  No release date chosen yet.

You can always do this:
  * Clone the repo
  * Checkout `version-2.0.0-dev`
  * Edit `constants.gradle` to make the version number 2.0.0
  * Run `./gradlew :libraryPublishAllToMavenLocal`
  * Use the local version in your app
