### ISSUE TITLE
can not login using email on small devices (e.g. Nexus One) - buttons are offscreen

### ISSUE THREAD

**Issue by LeeHounshell** [firebase/FirebaseUI-Android#626]
* Android device: Nexus One
  * Android OS version: any
  * Google Play Services version: 25.2.0
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.2.0
  
### Step 3: Describe the problem:

It is impossible to re-login using email on small devices, like the Nexus One.
The "Welcome back!" message takes up the entire screen and buttons are not visible.

#### Steps to reproduce:

  1. create Nexus One emulator
  2. create a test program using Firebase UI
  3. login
  4. logout
  5. login again (it is impossible now)
  
#### Observed Results:

  when I press enter or tab on the keyboard, focus should move to the SIGN IN button.
  it does not do this.  instead focus moves to the "eye" then back to the login.
  Please add KEYCODE_ENTER to input processing and move focus to the SIGN-IN button.
  or put everything into a scroll view.   There needs to be a way to get the button in view.
![login_problem](https://cloud.githubusercontent.com/assets/1031573/23837166/4a625658-0741-11e7-9bb6-53616e1d77e9.png)

  
#### Expected Results:

  I expected to be able to press the login button.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by LeeHounshell** [comment]
One idea is to attempt login when the user finishes password input.  Then the user would be able to login even when the sign in button is offscreen.  Something like this:

    mPasswordEditText.setOnEditorActionListener(new AppCompatTextView.OnEditorActionListener() {

        @Override
        public boolean onEditorAction(TextView v, int actionId, KeyEvent event) {
            if ((event != null && (event.getKeyCode() == KeyEvent.KEYCODE_ENTER)) || (actionId == EditorInfo.IME_ACTION_DONE)) {

                // attempt login here
            }
            return false;
        }
    });

**Comment by samtstern** [comment]
@LeeHounshell thanks for the very detailed bug report, this is a clear issue and I will get a fix in for the next version.  That device is smaller than the smallest one I used for testing.

I think it will be a combination of a few things:
   * Reduce margins / padding for small devices, a lot of wasted space in that screenshot!
   * Consider reducing font size for small devices.
   * Put everything in a `ScrollView` just to be sure.
