### ISSUE TITLE
[Feature request] FirebaseListFragment

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#628]
From my experience, I find myself implementing a common pattern using a `FirebaseRecyclerAdapter` often: I create a class for a fragment which only includes a `RecyclerView` initialized with a `FirebaseRecyclerAdapter` that also includes some utility methods and a callback for a `Fragment`/`Activity` to intercept touch events. I'm wondering if this would be an appropriate addition to the library considering that this is likely a common pattern for developers.

**Comment by samtstern** [comment]
@TheCraftKid the way to answer such questions as follows: is there something that would be different in a `FirebaseRecyclerFragment` versus just a `RecyclerFragment` that does the same thing (intercept touch events and give them back to the host).

As far as I understand the feature request, I don't think there's anything firebase-specific, which would mean it's not something that would belong in the library.

**Comment by TheCraftKid** [comment]
Whoops, I should mention that the fragment would be populated with data backed from a Firebase Database location (using an index or otherwise), but I thought about this as a helper class that would be as much help to creating a list of items populated by Firebase as FirebaseUI Auth is to signing in. I suppose this would be better in an addons library, correct?

**Comment by samtstern** [comment]
@TheCraftKid yes I think so, this is the type of thing that we hope people build as an add-on, we provide the building blocks of `FirebaseRecyelerAdapter` and (in the future) `FirebaseArray`.

**Comment by TheCraftKid** [comment]
Okay. Thanks for responding! BTW, is there any ETA for the production version of FirebaseUI 2.0.0?

**Comment by samtstern** [comment]
@TheCraftKid that ETA depends on some iOS timelines (we need them to match new features) so hard to say.  I'd personally like to see it go out in ~1month or less but no promises!

**Comment by samtstern** [comment]
Closing this issue due to discussion above, thanks for bringing this possible add-on to our attention.
