### ISSUE TITLE
[Feature request] Callbacks for data population 

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#631]
I'm probably wrong, but I don't think the `FirebaseRecyclerAdapter` and its children have callbacks for when the data is about to be initially populated or when it's finished populating items. I checked docs and code for the current and 2.0.0 branches, and I didn't see listeners or callbacks that would allow someone to display a progress bar if the database is taking a lot of time to fetch some items on a slow network and hide it when the items are populated. I know it's possible to do this for simple references like so:
```java
dataRef.addValueEventListener(new ValueEventListener() {
    @Override
    public void onDataChange(DataSnapshot dataSnapshot) {
        Data data = dataSnapshot.getValue(Data.class);
        textView.setText(data.getText());
        progressBar.setVisibility(View.GONE);
    }

    @Override
    public void onCancelled(DatabaseError databaseError) {
        // ...
    }
});
```
However, I'm wondering if something like this should be implemented in the FirebaseRecyclerAdapters:
```java
dataAdapter.setOnPopulatedListener(new OnPopulatedListener() {
    @Override
    public void onPopulation() {
        progressBar.setVisibility(View.GONE);
    }
});

// Or perhaps, probably the right choice, by subclassing

public void onInitialPopulation() {
    progressBar.setVisibility(View.GONE);
}
```

**Comment by SUPERCILEX** [comment]
The callback is [`onDataChanged`](https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java#L217) which is available on the master branch.

A note of caution: there is little support for this method. It is completely broken for the index adapters and will never get called in certain situations when offline. I've just been using `onChildChanged` to know if I should show an empty list hint.

**Comment by TheCraftKid** [comment]
No wonder I didn't catch that small line of code! :open_mouth: Does the 2.0.0 branch include this method?

**Comment by SUPERCILEX** [comment]
@TheCraftKid Yup! (Though it still isn't supported for the index stuff and probably won't be.)

**Comment by TheCraftKid** [comment]
Why won't it be supported for the indexing? Is it an implementation issue? Also, in what situations is onDataChanged not called?

**Comment by SUPERCILEX** [comment]
@TheCraftKid So many questions! 😄 Well, now #633 should take care of it.

See https://github.com/firebase/FirebaseUI-Android/pull/477#issuecomment-270283875 for when `onDataChanged` isn't called.
