### ISSUE TITLE
My firebaserecycleradapter not populate 

### ISSUE THREAD

**Issue by akhileshthakre8** [firebase/FirebaseUI-Android#637]
Here is my code

MainActivity1.java

package com.example.akhil.rtmnuforum;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.support.v7.widget.DividerItemDecoration;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.CardView;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.Query;
import com.google.firebase.database.ValueEventListener;
import com.squareup.picasso.Callback;
import com.squareup.picasso.NetworkPolicy;
import com.squareup.picasso.Picasso;

public class MainActivity1 extends AppCompatActivity {

    private RecyclerView mQuestionList;

    private CardView mCardVieww;

    private DatabaseReference mDatabase;
    private FirebaseAuth mAuth;
    private FirebaseAuth.AuthStateListener mAuthListener;
    private DatabaseReference mDatabaseUsers;
    private LinearLayoutManager layoutManager;

    private DatabaseReference mDatabaseCurrentUsers;

   // private Query mQueryCurrentUser;
    private  DatabaseReference mDatabaseLike;

    private boolean mProcessLike = false;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main1);

        mAuth=FirebaseAuth.getInstance();

        mAuthListener=new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {

                if (firebaseAuth.getCurrentUser()== null){

                    Intent loginIntent=new Intent(MainActivity1.this,LoginActivity.class);
                    loginIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                    startActivity(loginIntent);
                }
            }
        };

        mDatabase= FirebaseDatabase.getInstance().getReference().child("Question");
        mDatabaseUsers=FirebaseDatabase.getInstance().getReference().child("Users");
        mDatabaseLike=FirebaseDatabase.getInstance().getReference().child("Likes");

     //   mCardVieww=(CardView) findViewById(R.id.cardview);

//       String currentUserId=mAuth.getCurrentUser().getUid(); //for displaying only single user post
//
//       mDatabaseCurrentUsers=FirebaseDatabase.getInstance().getReference().child("Question");
//
//        mQueryCurrentUser=mDatabaseCurrentUsers.orderByChild("uid").equalTo(currentUserId);  //for displaying only single user post

        mDatabaseUsers.keepSynced(true);
        mDatabaseLike.keepSynced(true);
        mDatabase.keepSynced(true);

        mQuestionList=(RecyclerView) findViewById(R.id.question_list);
        layoutManager=new LinearLayoutManager(this);
        layoutManager.setReverseLayout(true);
        layoutManager.setStackFromEnd(true);

        mQuestionList.setHasFixedSize(true);
        mQuestionList.setLayoutManager(layoutManager);

       // mQuestionList.addItemDecoration(new DividerItemDecoration(getApplicationContext(),LinearLayoutManager.VERTICAL));

        checkUserExist();
    }

    @Override
    protected void onStart() {
        super.onStart();

        mAuth.addAuthStateListener(mAuthListener);

        //setContentView(R.layout.question_row);

       FirebaseRecyclerAdapter <Question,QuestionViewHolder> fireRecyclerAdapter = new FirebaseRecyclerAdapter <Question,QuestionViewHolder>(
                Question.class,
               R.layout.question,
                QuestionViewHolder.class,
               //mQueryCurrentUser  //for displaying only single user post
                mDatabase
        ){

            @Override
            protected void populateViewHolder(QuestionViewHolder viewHolder,Question model, int position){

                final String post_key = getRef(position).getKey();

               //// //setContentView(R.layout.question_row);//you can remove it

                viewHolder.setTitle(model.getTitle());
                viewHolder.setDesc(model.getDesc());
                viewHolder.setImage(getApplicationContext(),model.getImage());
                viewHolder.setUsername(model.getUsername());

                viewHolder.setLikeBtn(post_key);

                viewHolder.mView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

                       // Toast.makeText(MainActivity1.this,post_key,Toast.LENGTH_LONG).show();

                        Intent singleQuestionIntent=new Intent(MainActivity1.this,QuestionSingleActivity.class);
                        singleQuestionIntent.putExtra("question_id",post_key);
                        startActivity(singleQuestionIntent);
                    }
                });

                viewHolder.mLikeBtn.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View v) {

                        mProcessLike = true;

                            mDatabaseLike.addValueEventListener(new ValueEventListener() {

                                @Override
                                    public void onDataChange(DataSnapshot dataSnapshot) {
                                        if (mProcessLike) {

                                        if (dataSnapshot.child(post_key).hasChild(mAuth.getCurrentUser().getUid())) {

                                            mDatabaseLike.child(post_key).child(mAuth.getCurrentUser().getUid()).removeValue();
                                            mProcessLike = false;

                                        } else {

                                            mDatabaseLike.child(post_key).child(mAuth.getCurrentUser().getUid()).setValue("RandomValue");
                                            mProcessLike = false;
                                        }
                                    }
                                }

                                @Override
                                public void onCancelled(DatabaseError databaseError) {

                                }
                            });
                        }

                });
            }

        };

        mQuestionList.setAdapter(fireRecyclerAdapter);

    }
    //cgeck user exist or not
    private void checkUserExist() {

        if (mAuth.getCurrentUser() != null) {

            final String user_id = mAuth.getCurrentUser().getUid();

            mDatabaseUsers.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot) {
                    if (!dataSnapshot.hasChild(user_id)) {

                        Intent setupIntent = new Intent(MainActivity1.this, SetupActivity.class);
                        setupIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
                        startActivity(setupIntent);
                    }
                }

                @Override
                public void onCancelled(DatabaseError databaseError) {

                }
            });
        }
    }

    public  static class QuestionViewHolder extends RecyclerView.ViewHolder{

        View mView;

        ImageButton mLikeBtn;

        DatabaseReference mDatabaseLike;
        FirebaseAuth mAuth;

        public QuestionViewHolder(View itemView) {

            super(itemView);

            mView=itemView;

            mLikeBtn=(ImageButton) mView.findViewById(R.id.likeBtn);

            mDatabaseLike= FirebaseDatabase.getInstance().getReference().child("Likes");

            mAuth=FirebaseAuth.getInstance();
            mDatabaseLike.keepSynced(true);
        }

        public void setLikeBtn(final String post_key){

            mDatabaseLike.addValueEventListener(new ValueEventListener() {
                @Override
                public void onDataChange(DataSnapshot dataSnapshot) {

                    if (dataSnapshot.child(post_key).hasChild(mAuth.getCurrentUser().getUid())){

                        mLikeBtn.setImageResource(R.mipmap.thumb_grey);
                    }else{
                        mLikeBtn.setImageResource(R.mipmap.thumb_grey);
                    }
                }

                @Override
                public void onCancelled(DatabaseError databaseError) {

                }
            });
        }

        public void setTitle(String title){
            TextView post_title=(TextView) mView.findViewById(R.id.post_title);
            post_title.setText(title);

        }

        public void setDesc(String desc){
            TextView post_desc=(TextView) mView.findViewById(R.id.post_desc);
            post_desc.setText(desc);
        }

        public void setUsername(String username){
            TextView post_username=(TextView) mView.findViewById(R.id.post_username);
            post_username.setText(username);
        }

      public void setImage(final Context ctx, final String image){

            final ImageView post_image=(ImageView) mView.findViewById(R.id.post_image);
           //Picasso.with(ctx).load(image).into(post_image);

            Picasso.with(ctx).load(image).networkPolicy(NetworkPolicy.OFFLINE).into(post_image, new Callback() {
                @Override
                public void onSuccess() {

                }
                @Override
                public void onError() {
                    Picasso.with(ctx).load(image).into(post_image);

                }
            });
        }
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.main_menu,menu);
        return super.onCreateOptionsMenu(menu);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if(item.getItemId()==R.id.action_add){

            startActivity(new Intent(MainActivity1.this,PostActivity.class));
        }

        if(item.getItemId()==R.id.action_logout){

            logout();
        }

        if(item.getItemId()==R.id.action_Qp){

            startActivity(new Intent(MainActivity1.this,MainActivity2.class));
        }

        return super.onOptionsItemSelected(item);
    }

    private void logout() {
        mAuth.signOut();
    }

}

Here is my layouts

activity_main1.xml

<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.example.akhil.rtmnuforum.MainActivity1">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/question_list"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="@drawable/background">
</android.support.v7.widget.RecyclerView>

</LinearLayout>

Question.xml
<android.support.v7.widget.CardView
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/cardview"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_margin="20dp"
    android:visibility="visible"
    tools:context="com.example.akhil.rtmnuforum.MainActivity1">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="vertical">

        <ImageView
            android:id="@+id/post_image"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:adjustViewBounds="true"
            android:scaleType="centerCrop"
            android:src="@mipmap/add_btn" />

        <TextView
            android:id="@+id/post_title"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:padding="15dp"
            android:text="Post Title Goes here"
            android:textSize="16dp"
            android:textStyle="bold" />

        <TextView
            android:id="@+id/post_desc"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="15dp"
            android:paddingLeft="15dp"
            android:paddingRight="15dp"
            android:text="Question Description Goes here" />

        <TextView
            android:id="@+id/post_username"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:paddingBottom="15dp"
            android:paddingLeft="15dp"
            android:paddingRight="15dp"
            android:text="username"
            android:textSize="12dp"
            android:textStyle="bold" />

        <ImageButton
            android:id="@+id/likeBtn"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="10dp"
            android:background="@color/cardview_light_background"
            app:srcCompat="@mipmap/ic_thumb_up_black_24dp" />
    </LinearLayout>

</android.support.v7.widget.CardView>

Pls tell me problem Everytime it shows empty screen even if all data present in firebase database.

**Comment by samtstern** [comment]
@akhileshthakre8 sorry, we can't debug issues like this.  All that has been presented is an enormous amount of code and a small description of what's going on.  If you believe there is a bug in one of the `RecyclerAdapter` or `ListAdapter` classes in this library please provide a [MCVE](https://stackoverflow.com/help/mcve) to show it.

Otherwise, this sort of debugging question belongs on StackOverflow.
