### ISSUE TITLE
Add back the Adapter constructors that take a DatabaseReference

### ISSUE THREAD

**Issue by puf** [firebase/FirebaseUI-Android#642]
In FirebaseUI 0.4 the database adapters had an [overloaded constructor that would take a `DatabaseReference`](https://github.com/firebase/FirebaseUI-Android/blob/0.4.0/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java#L122) (just called `Firebase` back then) instead of a `Query`. 

While this overload was not strictly needed (as `DatabaseReference` extends `Query`), we found in developer feedback sessions that not all developers are aware that they can pass their database reference. 

We had one case where the developer spent quite some time researching Firebase queries. While that was a great learning experience for the developer, it would've been better if the API was harder to mis-interpret, which is the reason we added an overload that takes a database location.

**Comment by SUPERCILEX** [comment]
@samtstern Do you think #679 is enough? Also, this should become less relevant in FirebaseUI `v3.0`. 😉

**Comment by samtstern** [comment]
I have not seen any confusion about this issue, although puf does offer evidence from the original developer feedback sessions on FirebaseUI.

My theory is that over time `Query` has become a more essential piece of the puzzle for RTDB developers and most of them have heard of it before they get here.  So I am inclined to close this issue (with your doc comments) but I'll give @puf a final chance to tell me that I am very wrong :-)

**Comment by puf** [comment]
I chatted to Sam about this offline. We haven't seen as much confusion in practice as in the initial API feedback tests. I still have a preference to be able to pass in either a `Query` or a `DatabaseReference`, but I'm also fine leaving it out for now.
