### ISSUE TITLE
"Errors while executing operation ProxyAuthAppLoginQuery" 

### ISSUE THREAD

**Issue by fabio-limardo** [firebase/FirebaseUI-Android#649]
Hi guys,
I try to use Firebase UI to setup authentication on my app.
Authentication via Email or "Google sign in" works, but not facebook.
App ask me if I want to continue with my profile, but after I accept nothing happend.
In Android Debug I see this error message

_Error logging in with Facebook. SERVER_ERROR: [code] 1675030 [message]: Error performing query. [extra]: Errors while executing operation "ProxyAuthAppLoginQuery": At Query.proxy_auth_app_login: Failed to resolve field._

I set up facebook login both on firebase console and facebook developer console.

This is my develop environment
  * Android device: Xperia Z1
  * Android OS version: 5.1.1
  * Google Play Services version: 10.2.0
  * Firebase/Play Services SDK version: 10.2.0
  * FirebaseUI version: 1.2.0
  
Thank you everyone!

**Comment by samtstern** [comment]
@fabio-limardo this does not seem like an issue with the FirebaseUI library, could you ask this question on StackOverflow instead?

**Comment by grantespo** [comment]
this problem persists when FireBase is in my project.

**Comment by jnovaes** [comment]
same problem with my project. Ionic, firebase and facebook connect plugin.

**Comment by muddassir235** [comment]
The issues is that the email address linked to the Facebook account should be verified. Also, please not that old emails weren't verified on facebook if you aren't sure whether your email is verified or not please try adding a new email to the facebook account. 

This resolved the issue for me 100% of the time.

**Comment by jnovaes** [comment]
I test the facebook login only in a empty project and it seems that problem is with facebook login only, and not with firebase-ui.

The problem occurs with my facebook account, email verified 7 years ago.

I report to facebook: https://developers.facebook.com/bugs/1175449379233133

**Comment by muddassir235** [comment]
https://play.google.com/store/apps/details?id=com.erun.app.erun_nust&hl=en&pli=1

A few of my users faced this issue today and the issue was resolved for most of them through this approach. Don't know what else could be wrong but this solved it for me.

**Comment by muddassir235** [comment]
One of ours users thought that the account was verified but was still facing the same issue, but when he added a new email and verified that one, the issue was resolved. So the error is definitely from Facebook's side.

**Comment by zetazaw** [comment]
Change the switch on at Facebook Dashboard setting
Login from Devices
Enables the OAuth client login flow for devices like a smart TV
