### ISSUE TITLE
25.1.1 cardview , needs update to 25.3.0

### ISSUE THREAD

**Issue by DroidPulkit** [firebase/FirebaseUI-Android#650]
Welcome to FirebaseUI and thanks for submitting an issue!

Please take a look at [open issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aopen+is%3Aissue), as well as [resolved issues](https://github.com/firebase/FirebaseUI-Android/issues?q=is%3Aissue+is%3Aclosed), to see if your issue is either already being addressed, or has been solved by someone else.

If not, please feel free to fill in the following info so we can help faster!

### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a GitHub issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: All
  * Android OS version: All
  * Google Play Services version: 10.2.0
  * Firebase/Play Services SDK version: 1.2.0
  * FirebaseUI version: 1.2
  
### Step 3: Describe the problem:
Cardview at version 25.1.1 while it should be 25.3.0

#### Steps to reproduce:

  1. Gradle Warns about the multiple version at compile 'com.android.support:appcompat-v7:25.3.0' stating that : 
"All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.3.0, 25.1.1"
 
  
#### Observed Results:

  Warning
  
#### Expected Results:

  Slow Downs
  
#### Relevant Code:

  ```
  compile 'com.android.support:appcompat-v7:25.3.0'
  compile 'com.firebaseui:firebase-ui-auth:1.2.0'
  ```

**Comment by DroidPulkit** [comment]
@SUPERCILEX have a look at this

**Comment by samtstern** [comment]
The more general version of this is #613 so we can keep discussing there

**Comment by sreekanth-krishnan** [comment]
How to avail this fix? I'm still getting the warning.

This is how my dependencies look like.

`dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support:design:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    compile 'com.firebaseui:firebase-ui:1.2.0'
    testCompile 'junit:junit:4.12'
}`

This is the warning I get.

> All com.android.support libraries must use the exact same version specification (mixing versions can lead to runtime crashes). Found versions 25.3.1, 25.1.1. Examples include com.android.support:animated-vector-drawable:25.3.1 and com.android.support:cardview-v7:25.1.1

**Comment by SUPERCILEX** [comment]
@sreekanth-krishnan Add `com.android.support:cardview-v7:25.3.1` to your dependency list.

**Comment by Shirane85** [comment]
I also needed to add
`compile 'com.android.support:palette-v7:25.3.1'
    compile 'com.android.support:customtabs:25.3.1'
    compile 'com.android.support:design:25.3.1'`

**Comment by pipsApp** [comment]
I added exclude word, and the error disappeared
compile ('com.firebaseui:firebase-ui-storage:2.0.1') { exclude group: 'com.android.support' }
compile ('com.firebaseui:firebase-ui-database:2.0.1') { exclude group: 'com.android.support' }
