### ISSUE TITLE
crash application on retriving data from firebase

### ISSUE THREAD

**Issue by juned3247** [firebase/FirebaseUI-Android#655]
My applicatoin giving crash in FirebaseRecyclerAdapter class

    public T getItem(int position) {
        return parseSnapshot(mSnapshots.getItem(position));
    }
    protected T parseSnapshot(DataSnapshot snapshot) {
        return snapshot.getValue(mModelClass);
    }

and

    @Override
    public void onBindViewHolder(VH viewHolder, int position) {
        T model = getItem(position);
        populateViewHolder(viewHolder, model, position);
    }

can ayone give me solution?

**Comment by SUPERCILEX** [comment]
@juned3247 What's the crash?

**Comment by juned3247** [comment]
problem solved by adding default constructor in Message(my class)

public Message() { }

thanks @SUPERCILEX  for replying
