### ISSUE TITLE
UI not getting properly

### ISSUE THREAD

**Issue by PriyankaKada** [firebase/FirebaseUI-Android#658]
I want login buttons to appear at middle, but they coming at bottom, also i need to modify their size, 
If I apply any custom background suppose any dark color background, then its displayed while google new account as well 
Please help me out with this 
this is code 
   startActivityForResult(AuthUI.getInstance()
                    .createSignInIntentBuilder()
                    .setIsSmartLockEnabled(false)
                    .setProviders(Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.EMAIL_PROVIDER).build(),
                            new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),//googleIdp,
                            new AuthUI.IdpConfig.Builder(AuthUI.FACEBOOK_PROVIDER).build()))
                    .setTheme(R.style.GreenTheme)
                    .build(),RC_SIGN_IN);

**Comment by samtstern** [comment]
@PriyankaKada right now the placement of the buttons is not customizable, nor is the background beyond basic themeing.  There are some other issues where people discuss hacking some styles for more customization but that's not officially supported.
