### ISSUE TITLE
google play version 10.2.1

### ISSUE THREAD

**Issue by qvivr-jeffrey** [firebase/FirebaseUI-Android#659]
I am trying to use the new Google Play Serivce lib 10.2.1, but there is no support for that, the latest 1.2.0 only supports up to Google Play Service 10.2.0. Same goes with support library 25.1.1.

**Comment by samtstern** [comment]
`10.2.0` should be the same as `10.2.1` unless you're on O Preview, so I'd just stick with 10.2.0 for now.  As for the support library version, we are looking for a long-term solution to stop chasing that number.

**Comment by samtstern** [comment]
See #613

**Comment by mindwing** [comment]
I just encountered error with Google Play Service lib 10.2.1 with FirebaseUI 1.2.0
(There is no problem using Google Play Service lib 10.2.0)

[logcat]
FATAL EXCEPTION: main
Process: kr.mindwing.fastground.dev, PID: 6854
    java.lang.NoSuchMethodError: No virtual method zzUU()Z in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/kr.mindwing.fastground.dev-1/split_lib_dependencies_apk.apk:classes30.dex)
    at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
    at com.google.firebase.database.FirebaseDatabase.getInstance(Unknown Source)
...
