### ISSUE TITLE
No sign of a React-Native module for FirebaseUI?

### ISSUE THREAD

**Issue by MichelDiz** [firebase/FirebaseUI-Android#664]
I'm excited about the Firebase services. But also with React-Native. I would love to use FirebaseUI in my projects. But even though it's been a while since FirebaseUI (11 months?) Nobody has released a module for RN by then. I do not know yet how to create a native module for RN if it would not for that and would create and make it available myself.

Do you know of any projects in progress?

Best Regards

**Comment by samtstern** [comment]
@MichelDiz we don't have any plans to make a React Native module for FirebaseUI, I think something like that would need to come from a community fork if it's going to happen any time soon.  Thanks for asking!

**Comment by MichelDiz** [comment]
Quote myself 

> Some devs are moving to RN and new ones are coming. RN is improving support to multi-platform and that means "popularity". Your code can be used by far for more projects. Even creating a module whose support only the IOS has value. You can open the door to others fork you and support others platforms.
> 
> The question is - Why not? Enjouy the Hype. Get traction, get atention. Improove your self! We thankful!
