### ISSUE TITLE
minSdkVersion=16 in AndroidManifest.xml

### ISSUE THREAD

**Issue by mickamy** [firebase/FirebaseUI-Android#68]
Minimum SDK version set in AndroidManifest.xml is 16, though [the tutorial](https://github.com/firebase/FirebaseUI-Android/tree/master/codelabs/chat) says "Set the minimum SDK to 10 or higher."

I needed to override AndroidManifest in my project like this.
```xml
    <uses-sdk
        android:minSdkVersion="15"
        tools:overrideLibrary="com.firebase.ui"/>
```

Or have you left pre-16 android versions?

**Comment by puf** [comment]
The `Adapter` classes work on Android versions 10 and higher. But some of the social authentication providers need a higher API level. Since the codelab only uses email+password it should be able to  get by with level 10. Is that not your experience?

**Comment by mickamy** [comment]
I understand.
You mean like facebook sdk, right?
Thanks for your quick response.
I'll close this issue.

**Comment by puf** [comment]
Yeah, I wasn't sure which one was it that needed a higher level. Perfect.
If something indeed doesn't work, feel free to open an issue for it.
