### ISSUE TITLE
Proposal: Migrate to OpenYOLO

### ISSUE THREAD

**Issue by dxslly** [firebase/FirebaseUI-Android#682]
Hello everyone, 

I maybe jumping the gun a bit with this proposal, but development of OpenYOLO is well underway.  For those unfamiliar with OpenYOLO, it is inspired by, and ultimately intended to replace, Google's Smart Lock for Passwords API, which is internally known as YOLO (You Only Login Once).  Once OpenYOLO reaches a production ready state I propose FirebaseUI migrates.

### Background
Firebase-UI currently uses the Google's Smart lock for Passwords API to save and retrieve credentials as well as retrieve hints to boot strap account creation. The next generation of this API, known as OpenYOLO, is current under review by a working group at the OpenID foundation, with the intention for it to become an implementors draft by Q3 2017.

### High Level Design
OpenYOLO mirrors the existing functionality also offering credential retrieve, save and hint flows. I anticipate migrating to OpenYOLO will be a straight forward process. For the most part it looks to be swapping one gradle decency for the other and refactoring the classes that handle each type of flow: SaveSmartLock.java (Save), SignInDelegate.java (Request), & CheckEmailFragment.java (Hint).

### Links
The [OpenYOLO-Android](https://github.com/openid/OpenYOLO-Android) Github project.

**Comment by TheCraftKid** [comment]
I'm sure @samtstern and the others will agree, but I don't think OpenYOLO is ready to be a part of the library considering the fact that the GitHub repo maintainers "do not recommend that it be used in production Android apps." I think we could easily have another branch for experimentation, though, until it is production-ready.

**Comment by samtstern** [comment]
Yep I think we're all on the same page here.  The OpenYOLO repo says standardization by Q4 2017 so that's about the earliest I'd consider making the move.  But in general, I am open to it and happy to leave this feature request open until OpenYOLO has stabilized.

Thanks for the detailed issue @dxslly.

**Comment by samtstern** [comment]
I am going to close this issue since, although it's a good request, I don't actually have any plans to get it done and I want to be realistic.  Getting on the OpenYOLO standard is not a priority for FirebaseUI-Android.  If I am told otherwise I'll re-open and we can get on this.

**Comment by gabrielittner** [comment]
Could you reevaluate this issue? It's now production ready and there are 4 providers (including Google) which gives it a significant advantage over smart lock.

**Comment by samtstern** [comment]
@gabrielittner do you have a link to the best place to read about the new changes and the four providers?

**Comment by samtstern** [comment]
I found this:
https://github.com/openid/OpenYOLO-Android/releases/tag/0.2.1

But hoping for something a little more "official" saying that this is ready for production given that the client library is still using `0.x` versioning.

**Comment by gabrielittner** [comment]
The readme says 
> OpenYOLO has reached beta production ready stage and can be integrated into production applications.

**Comment by samtstern** [comment]
Ok I asked around with some people who know a lot about OpenYOLO and the short answer is based on some future plans (both Google's and OpenYOLOs) there may be some future changes that we should wait for.

So it seems that getting rid of SmartLock and replacing it with the OpenYOLO API right now would not be a good use of resources. 

Once these plans materialize and I am sure what direction everyone is going, I will reconsider how it affects FirebaseUI.

@gabrielittner thank you for pushing on this!

**Comment by gabrielittner** [comment]
Sounds good to me. Thanks for looking at it
