### ISSUE TITLE
null pointer exception in SaveSmartLock

### ISSUE THREAD

**Issue by aayaffe** [firebase/FirebaseUI-Android#685]
I received this error in my application (using the Firebase crash reporting). I do not know when it happened or what caused it. These are all the details I have:

Exception java.lang.NullPointerException:
com.firebase.ui.auth.util.signincontainer.SaveSmartLock.saveCredentialsOrFinish (SaveSmartLock.java:208)
com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish (BaseHelper.java:124)
com.firebase.ui.auth.ui.BaseHelper.saveCredentialsOrFinish (BaseHelper.java:112)
com.firebase.ui.auth.ui.idp.CredentialSignInHandler.onComplete (CredentialSignInHandler.java:68)
com.google.android.gms.tasks.zzc$1.run ()
android.os.Handler.handleCallback (Handler.java:730)
android.os.Handler.dispatchMessage (Handler.java:92)
android.os.Looper.loop (Looper.java:176)
android.app.ActivityThread.main (ActivityThread.java:5419)
java.lang.reflect.Method.invokeNative (Method.java)
java.lang.reflect.Method.invoke (Method.java:525)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1046)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:862)
dalvik.system.NativeStart.main (NativeStart.java)

Device
Manufacturer: Samsung
Model: GT-I9300
Board: Smdk4x12
Android API: 18
Android OS: 4.3
Brand: Samsung
RAM: 830.93MB
Orientation: Portrait

Dependencies:
    compile 'com.google.firebase:firebase-auth:10.2.0'
    compile 'com.firebaseui:firebase-ui-auth:1.2.0'
    compile 'com.google.android.gms:play-services-auth:10.2.0'

**Comment by SUPERCILEX** [comment]
@aayaffe Thanks for the report! This should be fixed in FirebaseUI `v2.0`.
