### ISSUE TITLE
Is there method available to request facebook email 

### ISSUE THREAD

**Issue by Shajeel-Afzal** [firebase/FirebaseUI-Android#69]
Hi. 

I am storing users information against their Email on Firebase. I am using this library to show Firebase Login Dialog. 

However in case of Facebook i am not getting user email. I want to know if there is any helper method available in the SDK that can set permissions on the Facebook Login. If not then will it be available in future?

Thanks.

**Comment by abehaskins** [comment]
Not currently, no! 

However you should be able to easily modify the [FacebookAuthProvider](https://github.com/firebase/FirebaseUI-Android/blob/master/library/src/main/java/com/firebase/ui/auth/facebook/FacebookAuthProvider.java) class to request email scope and retrieve it that way while we look for a better solution.

**Comment by samtstern** [comment]
FirebaseUI now gets email from Facebook, closing this issue.  Please re-open if the new solution is not working for you.
