### ISSUE TITLE
[Feature request] Privacy policy link in FirebaseUI Auth sign-in flow

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#690]
I understand that one can add a Terms of Service URL to the sign-in flow like so:

    AuthUI.getInstance()
        .createSignInIntentBuilder()
        .setProviders(...)
        .setTosUrl("https://superapp.example.com/terms-of-service.html")
        .setTheme(...)
        .build()
However, since Google Play [policies](https://play.google.com/about/privacy-security/personal-sensitive/) require the disclosure of how personal data is used in apps, it would be nice to increase the visibility of this information during sign-up/sign-in. I'd be happy to add a method `setPrivacyPolicyUrl(String url)` to the sign-in builder if there aren't any major problems with the idea.

**Comment by samtstern** [comment]
@TheCraftKid thanks for the suggestion.  Let me ask a few people about this and get back to you.

**Comment by TheCraftKid** [comment]
Hey, @samtstern, what's the status on this?

**Comment by samtstern** [comment]
@TheCraftKid thanks for the reminder.  I'd be happy to see this in version 2.0 if we can find the right place for it.  Right now we show the `termsOfServiceUrl` only in the `RegisterEmailFragment`.  Where do you propose putting the privacy policy URL?

**Comment by TheCraftKid** [comment]
I think the privacy policy should be where the terms of service URL is. App developers should be putting the privacy policy in their apps anyway, right?

**Comment by samtstern** [comment]
@TheCraftKid sounds good to me, want to submit a PR?

**Comment by SUPERCILEX** [comment]
@TheCraftKid If you're busy, I'm happy to work on a PR for you. Just give me the green light and I'll go for it! 😄

**Comment by TheCraftKid** [comment]
@SUPERCILEX Could you check #727 out to see if there's any glaring problems? I didn't know the best way to handle the text spans for the separate terms of service and privacy policy. 

I still appreciate the offer even if I ended up doing it in the end. :smile:
