### ISSUE TITLE
How to integrate NativeExpressAdView to FirebaseRecyclerAdapter ? 

### ISSUE THREAD

**Issue by stasbar** [firebase/FirebaseUI-Android#692]
Hello,
I'm wondering if there is any good way of integrating native ad express to FirebaseRecyclerAdapter ? 
I'm struggling with the problem, how to connect NativeExpressAdView with your FirebaseArray container ? Any samples or suggestions ?

**Comment by samtstern** [comment]
@stasbar there's nothing specific about FirebaseRecyclerAdapter that should make it easier or harder to use an AdView versus a regular RecyclerAdapter.  Github issues should be reserved for possible bugs in the library (with code and logs) or specific feature requests.  Please ask this question on StackOverflow.
