### ISSUE TITLE
Change GitHub tagline to be the README tagline

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#695]
@samtstern Small nit I noticed, the GitHub tagline says `UI library for Firebase` which a little mundane and should instead say ` UI Bindings for Firebase`. 🚀 😄

![image](https://cloud.githubusercontent.com/assets/9490724/25835791/a7346c50-3436-11e7-828f-7382feeb7849.png)

**Comment by samtstern** [comment]
Done!

**Comment by SUPERCILEX** [comment]
Awesome!
