### ISSUE TITLE
Firebase-ui-auth Multi-language support

### ISSUE THREAD

**Issue by hkbb2014** [firebase/FirebaseUI-Android#697]
* Android device: nexus 5x
  * Android OS version: 7.1.2
  * Google Play Services version: 
  * Firebase/Play Services SDK version: 10.0.1
  * FirebaseUI version: 1.2.0

My app supports different languages. How can I change the language in the following screen? 

- Sign in with Google <=
- Sign in with email <= 

![image](https://cloud.githubusercontent.com/assets/28584288/25881599/799edc9a-3570-11e7-985c-0899e65cb7fd.png)

**Comment by samtstern** [comment]
@hkbb2014 we're working on this!  For now you can look in the `strings.xml` file in the auth module and see what strings you need to override.

**Comment by ErstwhileWork** [comment]
@samtstern why not provide "direction" or "design docs" for the long planned localization/internationalization of Firebase UI so we community members may be able to contribute to speeding up this?

**Comment by samtstern** [comment]
@ErstwhileWork unfortunately with the way we have translation set up at Google there's not much you could do to help right now.  Once we get initial translations though, any correction suggestions will be appreciated.

I can finally say that we are in the process of translating, I have already seen some translated strings come back and we should have a lot more progress very soon.

**Comment by WemadeItin** [comment]
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/src/main/res/values/strings.xml : the link to the string.xml , you can copy and paste it in yours ! or just see what string you want to  override . It's work for me !

**Comment by samtstern** [comment]
We are really close to landing this!  Check out #771 for our translation progress, we are just waiting for our translators to come back with some final edits and we'll have support for many locales.

**Comment by samtstern** [comment]
Closing this in favor of #77 which is the canonical issue.  This feature is nearly complete.
