### ISSUE TITLE
Revert reauthentication

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#715]
Reauth is not going to make it into the next version for iOS or Web so we are going to drop it from version 2.0 for Android :-(

**Comment by SUPERCILEX** [comment]
@samtstern aw dang! 😭 Could we do something similar to my idea for the anonymous auth PR? Just make the builder for reauth private so we can keep developing with the reauth code and make our lives easier... What do you think?

**Comment by samtstern** [comment]
I don't want to keep dead code around but this is a special case since we already merged it into the branch. 

@yramanchuk @morganchen12 could we get reauth in for iOS in the next ~month or so?  If we can then we'll just temporarily hide it on Android.  If not, we have to extract it completely.
