### ISSUE TITLE
Is this sign in flow normal

### ISSUE THREAD

**Issue by erikswed** [firebase/FirebaseUI-Android#717]
I use the [FirebaseUI-Android][1] on a test app and have the app running in Android Studio emulator and on a Galaxy Note 4 real device.

Here´s what happens.
On the emulator I sign in using Facebook IDP with email1@gmail.com everything looks ok and in Firebase under the Authentication section I now see the Facebook logo and the email1@gmail.com

Now I sign in from the Galaxy Note 4 using Gmail IDP with email1@gmail.com and now in the Firebase  Authentication section the Facebook logo icon changes to a google logo for the signed in user email1@gmail.com.

Is the expected?

I was expecting both the Facebook and google icons to show in the Firebase Authentication section for the email email1@gmail.com since I am currently signed in using both right?(having the same `getCurrentUser().getUid()` right)

From the emulator I now sign out from the IDP Facebook. When I try to sign in again using that Facebook the FirebaseUI say:  "You already used that email sign in with Google to continue". I can understand "now" I think, why but the message was confusing first. Why is Google sign in bias?

The bad part is that I cannot sign in with another Facebook account even I select to abort the Facebook sign in flow. When I uninstall/reinstall app on the emulator I can enter email/password for signing in with Facebook again.

Is the expected?

  [1]: https://github.com/firebase/FirebaseUI-Android

**Comment by SUPERCILEX** [comment]
@erikswed What version of FirebaseUI are you using? This shouldn't be happening...

**Comment by erikswed** [comment]
Using Android studio and the FirebaseUI version is 1.2.0.. I think what happen is by design after reading up a little here [When Jin Liu explains](https://groups.google.com/forum/#!searchin/firebase-talk/liu/firebase-talk/ms_NVQem_Cw/8g7BFk1IAAAJ)
