### ISSUE TITLE
Refactor database classes into common module

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#722]
@samtstern I'm thinking about the future here and I'm wondering if we should refactor `ObservableSnapshotArray` to have its listener logic and a few other things moved into a common module. If we want the common module to have a package name other than `com.firebase.ui.database`, we need to do this before `v2.0` is released. Otherwise, this doesn't really matter and we can do that later. What do you think?

**Comment by samtstern** [comment]
I agree that a `common` module could be useful, not concerned about the package name though so no need to rush and do this before `2.0`

**Comment by SUPERCILEX** [comment]
@samtstern cool! I was just worried about the package name so closing this as a "will come in time" issue.
