### ISSUE TITLE
Choose something besides 'Games' as an example scope for the demo app

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#723]
There are many strange edge cases with Games sign in, there's no need to complicate the demo app by using `GAMES` as one of the example scopes.

**Comment by SUPERCILEX** [comment]
@samtstern A thought occurred to me: what do you think of letting devs provide a list of permissions they want to request? It would make it a lot easier for them to test the sample app with different requested permissions. The `EditText`'s hint would suggest some example perms to enter as comma separated values so I don't think it would complicate the sample app too much, but I'll understand if you don't want to go that route.

**Comment by samtstern** [comment]
The issue is actually converting what they type in to valid scopes.  Theres the `Scope(String val)` constructor but it doesn't validate enough.  Most of them are long URLs.  I think checkboxes are easier and serve to demonstrate the idea, for now.  Honestly most people don't use anything but default scopes.

**Comment by SUPERCILEX** [comment]
@samtstern Yup, makes sense. What about the [Drive api](https://developers.google.com/identity/protocols/googlescopes#drivev3)?

**Comment by samtstern** [comment]
Drive can stay, it's a very normal scope.  The reason Games is strange is because if it's a new device or account Games pushes you into a special sign-in flow which people might confuse with being part of FirebaseUI.

**Comment by SUPERCILEX** [comment]
@samtstern Oh lol, I thought we didn't have an example with the drive api so I meant to ask if we could use that instead. 😆 Ok, back to looking for example api requests. 😄

**Comment by SUPERCILEX** [comment]
@samtstern How about the [gmail api](https://developers.google.com/identity/protocols/googlescopes#gmailv1), the [Google+ api](https://developers.google.com/identity/protocols/googlescopes#plusv1), or the [Youtube Data api](https://developers.google.com/identity/protocols/googlescopes#youtubev3)?

**Comment by samtstern** [comment]
Let's go with "https://www.googleapis.com/auth/youtube.readonly", which you suggested.  Gmail is scary and  Google+ is soooooo 2013 haha

**Comment by SUPERCILEX** [comment]
@samtstern Awesome, I'm on it! 😄

> Google+ is soooooo 2013

😆
