### ISSUE TITLE
IDP logins always have null name and photoUrl

### ISSUE THREAD

**Issue by SUPERCILEX** [firebase/FirebaseUI-Android#729]
@samtstern I was doing some debugging recently and I noticed that when logging in with IDPs, the user name and photoUrl is always null. I know those fields used to be populated automatically at some point, is that no longer the case in newer versions of the Firebase SDKs? If so, we'll need to manually perform a profile update when logging in with IDPs as we do with email login.

**Comment by samtstern** [comment]
@SUPERCILEX let's try to pinpoint what's going on.  Can you try changing the version of FirebaseUI or the Firebase SDK to an older one and see what changes?

**Comment by SUPERCILEX** [comment]
@samtstern I figured it out thanks to some help from @pamartineza: when using `linkWithCredential`, the profile url and name are taken from the original account and not the new one even if the existing account url and name are `null`.

@samtstern do you know if this is expected behavior or should I report it as a bug?

PS: in case I wasn't clear, this isn't an issue on master or dev since #309 hasn't been merged.

**Comment by samtstern** [comment]
@SUPERCILEX I will report it, thanks!

**Comment by SUPERCILEX** [comment]
@samtstern awesome! I'm closing this issue since it only happens in my fork.
