### ISSUE TITLE
Firebase UI storage 1.2.0 is not loading images 

### ISSUE THREAD

**Issue by mark922** [firebase/FirebaseUI-Android#730]
`final StorageReference islandRef = ...;
        ImageView imageView = ...;
        
        // Load the image using Glide
        Glide.with(context.getApplicationContext())
                .using(new FirebaseImageLoader())
                .load(islandRef)
                .placeholder(R.drawable.profile_image_place_holder)
                .into(imageView);`

Gradle version :- compile 'com.google.firebase:firebase-storage:10.2.6'
&& compile 'com.firebaseui:firebase-ui-storage:1.2.0'

Images are not loading after updating to this version of firebase SDK.

**Comment by samtstern** [comment]
@mark922 what happens if you use `com.google.firebase:firebase-storage:10.2.1`?

**Comment by edipo2s** [comment]
Use version minor than 10.2.1 will make conflict with Firebase performance tools

**Comment by itpablo** [comment]
Same problem here guys. Need to fallback to version 10.2.1

**Comment by debasiskoley** [comment]
Using version com.google.firebase:firebase-storage:10.2.1 and com.google.firebase:firebase-storage:10.2.0 and Glide version compile com.github.bumptech.glide:glide:3.7.0 is working fine but if updrage the version com.google.firebase:firebase-storage:10.2.6 Images are not loading. 
Please help.

**Comment by mailtoabhi15** [comment]
@samtstern falling back to 'com.google.firebase:firebase-storage:10.2.1' resolve the issue but 10.2.6 doesn't load & nothing is there in logs as well to point to.
Currently I changed to below configs in my gradle: 
    compile 'com.google.firebase:firebase-auth:10.2.6'
    compile 'com.google.firebase:firebase-storage:10.2.1'
    compile 'com.google.firebase:firebase-database:10.2.6'
    compile 'com.google.firebase:firebase-core:10.2.6'
    compile 'com.google.firebase:firebase-messaging:10.2.6'
    compile 'com.google.android.gms:play-services-auth:10.2.6'

So is it ok to just have storage @ 10.2.1 & other dependencies @ 10.2.6 ?

**Comment by samtstern** [comment]
Does this problem still occur with `2.0.0` or higher?

**Comment by mailtoabhi15** [comment]
@samtstern didn't face the issue with compile 'com.google.firebase:firebase-storage:11.0.0'

**Comment by mark922** [comment]
@samtstern It works fine with 10.2.1.

**Comment by samtstern** [comment]
@mailtoabhi15 that's good to know, `firebase-ui-storage:2.0.1` depends on `firebase-storage:11.0.1` so you should be able to use this library again.

**Comment by swftvsn** [comment]
11.0.1 + 2.0.1 works here too

**Comment by samtstern** [comment]
I've heard multiple reports that this issue is fixed in `11.0.x` so I am going to close this.  If someone can still reproduce this on the newest SDK please let me know.
