### ISSUE TITLE
Compile firebase-ui-auth:1.2.0 , error android.support:appcompat-v7:25.3.1 . 

### ISSUE THREAD

**Issue by trinhvanminh2009** [firebase/FirebaseUI-Android#732]
Compile firebase-ui-auth:1.2.0 , error android.support:appcompat-v7:25.3.1 . Does it any version for them can same version specification ?

**Comment by samtstern** [comment]
@trinhvanminh2009 going to close this issue since there's not enough information to debug, however you may want to try adding this:

```
  compile "com.android.support:design:23.2.1"
  compile "com.android.support:customtabs:23.2.1"
  compile "com.android.support:cardview-v7:23.2.1"
```

**Comment by trinhvanminh2009** [comment]
Thank you ! I was try that , but it's not working .
I'm compile 
    compile 'com.android.support:appcompat-v7:25.3.1'
 compile 'com.google.firebase:firebase-core:10.2.6'
    compile 'com.firebaseui:firebase-ui-database:1.2.0'
    compile 'com.firebaseui:firebase-ui-auth:1.2.0'
    compile 'com.firebaseui:firebase-ui-storage:1.2.0'
    compile 'com.firebaseui:firebase-ui:1.2.0'
  compile "com.android.support:design:25.3.1"
    compile "com.android.support:customtabs:25.3.1"
    compile "com.android.support:cardview-v7:25.3.1"
.Appcompat not compatibility with firebase-ui:1.2.0 . Can you show me which version are you in ?

**Comment by KumaranDH** [comment]
I have the same issue

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:design:25.3.1'
    compile 'com.google.firebase:firebase-database:10.2.6'
    compile 'com.google.firebase:firebase-auth:10.2.6'
    //compile 'com.firebaseui:firebase-ui-auth:1.2.0'

    testCompile 'junit:junit:4.12'
}

**Comment by kaivan-s** [comment]
dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support:design:26.1.0'
    implementation 'com.android.support:recyclerview-v7:26.1.0'
    implementation 'com.android.support:cardview-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    compile 'com.google.firebase:firebase-core:11.8.0'
    compile 'com.google.firebase:firebase-database:11.8.0'
    compile 'com.google.firebase:firebase-storage:11.8.0'
    implementation 'com.firebaseui:firebase-ui-database:3.2.2'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'
}
apply plugin: 'com.google.gms.google-services'


I have following dependencies but gives error in appcompat...

**Comment by nishankbhati** [comment]
facing the same error.

**Comment by umeklinks** [comment]
The error is been fixed here on this video https://youtu.be/Vjy_uv10t30

Or

add this `//noinspection GradleCompatible`

before

implementation `'com.android.support:appcompat-v7:28.0.0'`

and synch.

That's all.
