### ISSUE TITLE
Release 1.2.0 on Maven Central (or provide online Javadoc)

### ISSUE THREAD

**Issue by pushbit** [firebase/FirebaseUI-Android#739]
Please release version 1.2.0 to Maven Central so that we can view the Javadoc at https://javadoc.io/.  Alternatively, provide the Javadoc for online browsing.

**Comment by samtstern** [comment]
@pushbit thanks for the pointer.  I must have missed the Maven Central sync last time we released, I've just done it so you should be all set.
