### ISSUE TITLE
Cleanup pulls in GoogleAuthProvider even when it's not used

### ISSUE THREAD

**Issue by puf** [firebase/FirebaseUI-Android#74]
This code in `FirebaseLoginDialog` pulls in Google authentication even when it's not being used:

```
    public void cleanUp() {
        if (getGoogleAuthProvider() != null) getGoogleAuthProvider().cleanUp();
    }
``

**Comment by abehaskins** [comment]
Good catch, this definitely isn't ideal! Thanks for the report ;)

**Comment by samtstern** [comment]
Closing as this bug is no longer relevant in 0.4.0+
