### ISSUE TITLE
Firebase Auth: Migrate from Fabric to Twitter Core v3.0.0

### ISSUE THREAD

**Issue by rostopira** [firebase/FirebaseUI-Android#746]
Fabric is large library and is unnecessary in most cases.

Cons of using Twitter Core:
- APK size decreased by 1Mb
- Less pain with setup, no Fabric plugin required
- Less pain in future, because as we can see, Fabric is deprecated and will be merged in Firebase.

Am I welcome to fill pull request for it in 2.0.0-dev branch?
Thanks.

**Comment by rostopira** [comment]
Migration guides:
- https://dev.twitter.com/twitterkit/fabric
- https://dev.twitter.com/twitterkit/android/upgrading

**Comment by rostopira** [comment]
Just now checked, it's already updated, sorry)

**Comment by samtstern** [comment]
@rostopira thanks for checking the branch!  As you noticed, this will be in 2.0.  @ashwinraghav was the one who figured it out.
