### ISSUE TITLE
Ability to disable email scope

### ISSUE THREAD

**Issue by rostopira** [firebase/FirebaseUI-Android#747]
I don't need emails of my users, and I think they don't want to provide it either.

Can you please add option `removeEmailScope()` in `IdpConfig.Builder`?

Thanks.

**Comment by rostopira** [comment]
@samtstern Facebook and Google

**Comment by samtstern** [comment]
Email is very important as an identifier to Firebase Auth.  For example if your user signs in on one device with Facebook and on another with Google we can only launch the "link account" flow if we have their email.  Otherwise they will end up with two separate accounts.

**Comment by rostopira** [comment]
@samtstern developers often sending unwanted emails, we don't want users to expect the same behaviour. Privacy is very important in our app, so we want users won't worry about their data. Also, we want them to be sure, that data in app won't be linked to their accounts in any way.

**Comment by samtstern** [comment]
@rostopira I definitely agree with your evaluation, I am just not sure it's a good fit for this library since account linking is one of the major benefits of FirebaseUI.  I will mark this for consideration though, thank you for explaining!
