### ISSUE TITLE
Best way to fully customize FirebaseUI-Auth for Android?

### ISSUE THREAD

**Issue by bshikhar13** [firebase/FirebaseUI-Android#753]
I know that we can have a LoginTheme and can inject it in the FirebaseUI Auth. Since, the library is now open sourced, is there any best way to **fully** customize the Login Screen?

**Comment by samtstern** [comment]
@bshikhar13 right now the only official customization support is through themes, as you noticed.

If you wanted to take full control, you could abuse Android's layout system.  If you create an XML layout file in your project with the exact same name as the one in the `auth` library module and make sure it contains elements with the exact same `android:id` values then you'd override our layout.

However we don't consider our layout names or ID values part of the public API, so they could break between versions without any warning to you.

**Comment by samtstern** [comment]
We have a proposal to consider more customization inf #1477 if anyone would like to comment.
