### ISSUE TITLE
publish_actions can not be add to facebook permissions

### ISSUE THREAD

**Issue by inromualdo** [firebase/FirebaseUI-Android#755]
com.facebook.FacebookException: Cannot pass a publish or manage permission (publish_actions) to a request for read authorization at com.facebook.login.LoginManager.validateReadPermissions(LoginManager.java:388)

  * Android device: ____
  * Android OS version: ___4.4.2___
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: __11.0.0___
  * FirebaseUI version: __2.0.0__

**Comment by samtstern** [comment]
See #535 and #592 but basically we can't support non-read permissions for Facebook.  Facebook makes it clear they want these requests done after the initial login flow, and FirebaseUI is only concerned with the initial login flow.

You will need to use the Facebook SDK directly to request these permissions after FirebaseUI has completed.
