### ISSUE TITLE
Smart Lock with scopes results in SIGN_IN_REQUIRED

### ISSUE THREAD

**Issue by pushbit** [firebase/FirebaseUI-Android#760]
I'm using AuthUI to build a SignInIntent for GOOGLE_PROVIDER and scopes GAMES, DRIVE_APPFOLDER.  On first sign in it works fine, going through the Google and Play Games auth flow.  But if I then clear data and sign in again, Smart Lock automatically signs me in and the subsequent `GoogleApiClient.blockingConnect()` results in error code SIGN_IN_REQUIRED.  Repeated connect attempts have the same result for about 10 minutes.  Then connects start succeeding normally.  My guess is that Smart Lock only does the Google part of the sign in and some background sync process later does the Play Games sign in.

If I `setIsSmartLockEnabled(false)`, then the clear data/sign in cycle works fine and I can see it is immediately signing in to Play Games each time.  Is this a known limitation with Smart Lock or is there something that could be done on the app or library side to be able to use both Smart Lock and Play Games (and perhaps other scopes) at the same time?

**Comment by samtstern** [comment]
@pushbit thank you for reporting this, I definitely had not considered the complications of this case.

SmartLock doesn't have any magical ability to store Google scopes (or any other authorization).  All it really does for us is store a pointer to a Google account, which we can use to initialize Google Sign In with a specific email address and therefore skip over the account picker and possibly get 'silent sign in'.

**Comment by samtstern** [comment]
I still don't have a good answer for this so punting it out of the `2.1.0` release.  Suggestions welcome for how to solve this in a nice way!

**Comment by SUPERCILEX** [comment]
@samtstern I believe this was fixed at some point. I'm able to add permissions through the smart lock dialog even after clearing app data.

**Comment by samtstern** [comment]
:man_shrugging: ok!
