### ISSUE TITLE
FirebaseUI v2.0.1 requires unavailable Firebase/Play Services Version

### ISSUE THREAD

**Issue by FranSalguero** [firebase/FirebaseUI-Android#763]
Trying to compile 
`compile 'com.firebaseui:firebase-ui-auth:2.0.1' `
in app gradle file returns:
Error:Failed to resolve: com.google.firebase:firebase-auth:11.0.1

Looks like firebase 11.0.1 isn't still available, I just find 11.0.0.

**Comment by samtstern** [comment]
@FranSalguero you have to update 'Google Repository' in your SDK manager.  `11.0.1` was released last week.
