### ISSUE TITLE
Is FirebaseUI reading the Phone auth sms code 

### ISSUE THREAD

**Issue by erikswed** [firebase/FirebaseUI-Android#767]
* Android device: Samsung Note 4 
.  * Android OS version: 6.0.1
  * Google Play Services version:  11.0.1
  * Firebase/Play Services SDK version:  11.0.1
  * FirebaseUI version: 2..0.1
  
### Step 3: Describe the problem:
When sign in using Phone and when the code is sent trough sms sometimes I don't have to type
the sms-code, instead it gets typed automatically and I´m signed in. Sometimes I have to manually type the sms-code into FirebaseUI. 
Is this normal?

"typed automatically" means that when sms arrives the sign in flow continues automatically just like FirebaseUI is reading the sms and the  
```
    @MainThread
    private void handleSignInResponse(int resultCode, Intent data) {
```
 
i called.

**Comment by samtstern** [comment]
@erikswed yes in some cases Google Play services can read the incoming SMS and enter the code automatically: https://firebase.google.com/docs/auth/android/phone-auth#verification-callbacks

Under the hood this uses the SMS retriever API, which you can actually build into your own apps:
https://developers.google.com/identity/sms-retriever/

**Comment by erikswed** [comment]
Thanks I would like some popup saying, sms-code verification sign in granted or something..
