### ISSUE TITLE
Support Fragements for NavigationDrawer Layouts

### ISSUE THREAD

**Issue by RaphaelJenni** [firebase/FirebaseUI-Android#769]
Currently, to open the authentication screen you call:

```
startActivityForResult(
                    AuthUI.getInstance()
                            .createSignInIntentBuilder()
                            ...
                            .build(),
                    RC_SIGN_IN);
```

the problem here is, that it starts a new Activity. If you have a navigation side drawer, you need to launch a [`Fragment`](https://developer.android.com/reference/android/app/Fragment.html). 
Now Auth UI creates a new Activity, which is like a new window, so it messes up the style of the app.

Is there a way you can implement that, so the whole process also works with fragments?

**Comment by samtstern** [comment]
@RaphaelJenni we do many things that rely on our having an `Activity` under our complete control, so unfortunately I don't think we will be able to launch `AuthUI` as a `Fragment` any time soon.  Thank you for the feedback though, this is a use case I had not really thought about.
