### ISSUE TITLE
Firebase phone number auth - enter a valid phone number

### ISSUE THREAD

**Issue by yajur96** [firebase/FirebaseUI-Android#770]
I am using FirebaseUI phone number auth in an application based in India. For some phone numbers it works like a charm and I can authenticate those accounts easily, but for some numbers I am experiencing an issue. It says: please enter valid phone number. 

I know for a fact that these phone numbers are valid Indian mobile numbers which are in daily use.

**Comment by samtstern** [comment]
@yajur96 can you try entering them with/without a country code appended and see if that makes a difference?

**Comment by yajur96** [comment]
@samtstern is that possible using FirebaseUI?

**Comment by samtstern** [comment]
@yajur96 we've discovered some issues in validating phone numbers on certain carriers on devices less than Android L (so KitKat or below).

One such carrier is Jio, which I believe is an Indian carrier.  Is this the problem you're seeing?  And what Android OS version is the device running?

**Comment by yajur96** [comment]
Yes, this is exactly the problem. But, the device I am using it on has Android version 6.0.1 and the carrier is Jio.

**Comment by samtstern** [comment]
@yajur96 thanks for following up.  We're working out what to do about this, we may fix this in FirebaseUI but we may try to get the fix into the underlying Firebase Auth SDK.

**Comment by ramancse** [comment]
@samtstern yes I'm also having the same issues and it is critical issue for me that I have been migrated from digits to Firebase auth and  auth UI

**Comment by samtstern** [comment]
Moving this to #812, we're going to fix this.  Thanks everyone who reported.

**Comment by tanseerpasha** [comment]
I happen to fix the 'invalid phone number' issue for JIO sims using ISD code.  
String phoneNumberWithIsd = "+91" + mPhoneNumberField.getText().toString();

**Comment by goyalish** [comment]
I am able to receive OTP on JIO number. However I am not getting OTP on my other number.
I have tested with two vodafone prepaid numers out of which it worked for one for other I never received any OTP. Then I tested on JIO number and it worked. Then I tested on my friends numbers for some it works for others it does not. Please look into this. If this is going to be the firebase auth behaviour , I am afraid that I am going to use it. Need a reliable service for my app.

**Comment by akshaanbehl** [comment]
Many of my users complain of not receiving the OTP. Is it not 100% reliable with Indian Networks?

**Comment by garima123456** [comment]
Hi,
When I am trying to authenticate user from airtel number I am getting the OTP but when trying with vodaphone number I am not able to authenticate user, what is the problem ? can you please help?

**Comment by yashgautami** [comment]
> I am able to receive OTP on JIO number. However I am not getting OTP on my other number.
> I have tested with two vodafone prepaid numers out of which it worked for one for other I never received any OTP. Then I tested on JIO number and it worked. Then I tested on my friends numbers for some it works for others it does not. Please look into this. If this is going to be the firebase auth behaviour , I am afraid that I am going to use it. Need a reliable service for my app.

@goyalish Let me know if you have found any solution for this?

**Comment by Bakavani** [comment]
I was testing on Jio number it was never sending SMS .. gosh spent quite some time looking at my code, for solutions.., when I tested on Vodaphone number it worked fine. Sad google guys are promoting such a bad product. I'm in India BTW.
