### ISSUE TITLE
Use Context instead of Activity for layout inflation

### ISSUE THREAD

**Issue by TheCraftKid** [firebase/FirebaseUI-Android#773]
I'm updating an addon library to this library, and it appears the `FirebaseListAdapter` is using an `Activity` parameter in the constructor where only a `Context` is needed. This would help out in situations where a home screen widget uses the adapter but doesn't have access to an `Activity`.
I say replacing it with a `Context` is a good idea because we only need it to inflate the layout, and the system already provides a more generalized way to access the layout inflater.

Instead of `mActivity.getLayoutInflater().inflate(mLayout, viewGroup, false);` 
we should do this: `LayoutInflater.from(mContext).inflate(mLayout, viewGroup, false);` in the `FirebaseListAdapter`.

**Comment by TheCraftKid** [comment]
Shall I go ahead and submit a PR?

**Comment by SUPERCILEX** [comment]
@TheCraftKid go for it, I don't think @samtstern will bite!
 😀😂

**Comment by TheCraftKid** [comment]
I targeted the branch for 2.1.0. Is that a good target?

**Comment by samtstern** [comment]
Yep that's the correct target.

**Comment by samtstern** [comment]
The fix for this issue has been released in `v2.1.0`.
