### ISSUE TITLE
Instant verification or Auto-retrieval not working

### ISSUE THREAD

**Issue by jianleon** [firebase/FirebaseUI-Android#775]
* Android device: LG X Screen, LG X Play
  * Android OS version: Android 6.0.1
  * Google Play Services version: com.google.gms:google-services:3.0.0
  * Firebase/Play Services SDK version: compileSdk = 25, targetSdk = 23

I've tried the phone auth guide for Android(https://firebase.google.com/docs/auth/android/phone-auth#on-verification-completed) and this callback
`PhoneAuthProvider.OnVerificationStateChangedCallbacks`, never gets into onVerificationCompleted(). I always have to type manually the verification code.

I want the cellphone to validate automatically the SMS code and start the normal flow.
The guide specifies that "In some cases...", or "On some devices...", Is there any possibility to avoid the manual typing?

**Comment by samtstern** [comment]
@jianleon are you using FirebaseUI or building your own UI/

**Comment by jianleon** [comment]
@samtstern hi, I'm building my own, with the [Firebase guide](https://firebase.google.com/docs/auth/android/phone-auth)

**Comment by samtstern** [comment]
I see, in that case I am going to close this issue and re-open the other one.
