### ISSUE TITLE
Do not show FirebaseLoginDialog if only one login provider is enabled.

### ISSUE THREAD

**Issue by abond** [firebase/FirebaseUI-Android#78]
Hello!

It would be better if if only one provider is enabled, to start login process immediately instead of showing FirebaseLoginDialog with only one option available.

**Comment by abehaskins** [comment]
I like this idea! Marked as enhancement.

**Comment by samtstern** [comment]
@iainmcgin this is feedback on the old 0.3.x version but still applies to 0.4.0

**Comment by iainmcgin** [comment]
We currently skip the authentication method picker if only email authentication is in use. We don't skip it in the other cases (Google only or Facebook only) as we felt it may be a jarring experience to be thrown straight into an identity provider login flow. If only Google/Facebook are supported, I believe it would typically be easier to just directly integrate with the respective sign-in API and use the Firebase Auth library directly (signInWithCredential), as the recovery flows for account linking and so on are not relevant with only a single federated identity provider.

**Comment by nielsz** [comment]
<img width="274" alt="screen shot 2016-08-09 at 15 15 57" src="https://cloud.githubusercontent.com/assets/105541/17517611/6dfb55b6-5e44-11e6-9dc7-a1e20186f7cb.png">

Here's an ugly and unneeded interface when only Email/Password authentication (and anonymous) are used, on 0.4.4.

**Comment by samtstern** [comment]
@nielsz this is a known issue that happens when the device has no eligible accounts for the Credentials API.  A fix is in the works, it's outside of FirebaseUI though.

That said we are considering a flag to turn off the Credentials API integration with FirebaseUI, which would allow you to work around this bug.

**Comment by samtstern** [comment]
Closing this issue as it originally references the old version of FirebaseUI Auth and the comment by @nielsz is being tracked directly by the SmartLock team internally.
