### ISSUE TITLE
UI for registering new user for PASSWORD login provider.

### ISSUE THREAD

**Issue by abond** [firebase/FirebaseUI-Android#79]

**Comment by abehaskins** [comment]
We're considering this! Will mark as enhancement.

**Comment by runia1** [comment]
@abehaskins please please please build this.  Think about it.  If users can't signup / register through the app, they'll never be able to login anyways.  Seems you guys built it in reverse?

**Comment by runia1** [comment]
@abehaskins Actually I'm gonna go ahead and just fork you guys and build the signup feature.  I'll submit a pull request when I'm done and you can merge it if you want.

**Comment by abehaskins** [comment]
Sounds good - I look forward to the PR!

**Comment by cardenuto** [comment]
@abond @runia1 I have been working on code that uses this library and adds the new user creation capability (plus a bunch of other things). I did have to override the fragment_firebase_login.xml file locally, but made no additional overrides to this library. If you like it let me know what you think: https://github.com/cardenuto/FirebaseLogin any suggestions are welcome. Currently I designed my code to be added manually to a project as more of a template ... instructions are included in the repo.

**Comment by dazza5000** [comment]
+1 for this enhancement. Thank you!

**Comment by runia1** [comment]
@abehaskins I submitted a pull request for this feature.  I also added a Signup button to the demo app so you can see it in action.  @abond @cardenuto if you can't wait for the merge you can clone my fork https://github.com/runia1/FirebaseUI-Android

**Comment by samtstern** [comment]
This UI is available in the 0.4.0 version.  Closing as fixed.
