### ISSUE TITLE
Missed translation for auth

### ISSUE THREAD

**Issue by OlegTarashkevich** [firebase/FirebaseUI-Android#793]
I found that ui auth library has no translations for other languages. Please do it.

Digits by fabric it has, but I should to migrate to this.

**Comment by SUPERCILEX** [comment]
@OlegTarashkevich see #771, it'll happen by the time `v2.1` comes out.

**Comment by OlegTarashkevich** [comment]
@SUPERCILEX Thanks for the info!

**Comment by samtstern** [comment]
@OlegTarashkevich going to close this issue since we're already tracking this.  We're getting really close, right now all of our translations are being QAed by native speakers.
