### ISSUE TITLE
Toolbar title shows as ui_flow

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#823]
Related to #813, I am investigating.

![image](https://user-images.githubusercontent.com/8466666/28579265-013ac764-7111-11e7-945b-82a0006e737c.png)

**Comment by samtstern** [comment]
Hmm I can no longer reproduce this on a clean build (which makes sense).  I wonder what happened...

**Comment by bartekpacia** [comment]
Happens to me also. Strange issue.

**Comment by viniciusAbrantes** [comment]
I'm having the same issue, does anyone knows how to solve it?
