### ISSUE TITLE
phone auth is not working..

### ISSUE THREAD

**Issue by yash59** [firebase/FirebaseUI-Android#831]
I had used the phone auth provider but it's not working and showing the number as invalid but i am using that number and it's valid. I am from india..anyone tell me where is the problem..

**Comment by bernaferrari** [comment]
I am having (probably) a similar problem as you. Brazil changed the phone numbers length from 8 to 9 digits (adding a 9 in front of every number), Firebase only understands 8 digits, but the sms provider will attach the extra digit when sending the confirmation sms.

**Comment by samtstern** [comment]
@yash59 @bernaferrari thanks for the reports.  This is a duplicate of #812, we will fix it soon.

**Comment by imran-samed** [comment]
use +91 prefix in number  @yash59
