### ISSUE TITLE
No drop shadow on auth picker buttons on low API devices

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#842]
Here are some screenshots showing API 25 next to API 19.

|  **API 19 - No Shadow** |  
**API 25 - Shadow** |
|---|---|
| <img width="300" src="https://user-images.githubusercontent.com/8466666/28849043-13b602e6-76ca-11e7-8b8e-89adf03d629f.png" />  | <img  width="300" src="https://user-images.githubusercontent.com/8466666/28849044-13b69030-76ca-11e7-84a0-2d515b1544ab.png" /> |

**Comment by SUPERCILEX** [comment]
@samtstern Pretty sure shadows just aren't a thing pre-L. I remember reading a thing about `Toolbar` adding an extra view that faked the shadow, are you suggesting we should do that?

**Comment by samtstern** [comment]
@SUPERCILEX I am hacking on something right now involving the XML drawable.  I think I can make it work without additional views.

**Comment by SUPERCILEX** [comment]
@samtstern Oh sweet! 😄

**Comment by samtstern** [comment]
See #843.  Afaict it has no effect on post-L devices but on pre-L devices adds a shadow-looking thing.  It doesn't have the scatter / blur that a shadow would have but it at least adds contrast.

**Comment by samtstern** [comment]
The fix for this issue was released in version `2.2.0`.

**Comment by samtstern** [comment]
The fix for this issue was released in version `2.2.0`.
