### ISSUE TITLE
Conflict due to Firebase UI 2.2.0 Dependency

### ISSUE THREAD

**Issue by kumarkeviv** [firebase/FirebaseUI-Android#853]
Firebase/Play Services SDK version: 11.4.0
FirebaseUI version: 2.2.0
  
While trying to upgrade to Firebase UI 2.2.0, the build is failing because Firebase UI is using an old dependency (com.android.support:customtabs:25.4.0 (*)) which is in conflict with google support cardview (    compile 'com.android.support:cardview-v7:26.0.0').

The dependency tree for Firebase UI:
 +--- com.firebaseui:firebase-ui-auth:2.2.0
|    |    +--- com.android.support:design:25.4.0 -> 26.0.0 (*)
**|    |    +--- com.android.support:customtabs:25.4.0 (*)**
|    |    +--- com.android.support.constraint:constraint-layout:1.1.0-beta1

The snippet of the error is also attached.

Could you please assist the resolution?

Thanks Firebase Team
![error](https://user-images.githubusercontent.com/17118240/29023785-6bc79306-7b6f-11e7-8357-6d6e6993084e.PNG)

**Comment by SUPERCILEX** [comment]
@kumarkeviv Yeah, check out the [`README`](https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies).

**Comment by kumarkeviv** [comment]
@SUPERCILEX ok then look like will have to wait till the dependency gets updated at Firebase UI.

Thanks

**Comment by SUPERCILEX** [comment]
@kumarkeviv No, here's a quote from the README:
> If you would like to use **a newer version** of one of FirebaseUI's transitive dependencies, you need to add explicit `compile` declarations in your `build.gradle` for all of FirebaseUI's dependencies at the version you want to use.

So just add `compile com.android.support:customtabs:26.0.0` and you should be good to go.

**Comment by kumarkeviv** [comment]
Thanks @SUPERCILEX this resolves the issue.

I missed that point.
