### ISSUE TITLE
Is there a way to get the PhoneAuthCredential object in onActivityResult upon successful registration?

### ISSUE THREAD

**Issue by mlostekk** [firebase/FirebaseUI-Android#864]
Is there a way to get the 'PhoneAuthCredential' object in 'onActivityResult' upon successful registration with this library?

**Comment by samtstern** [comment]
@mlostekk can you explain a little more about what you'd use the `PhoneAuthCredential` for after the flow is complete?

**Comment by mlostekk** [comment]
I want to use the verificationId to be sent to my server in order to verify successful registration there to unlock the full features on our backend

**Comment by samtstern** [comment]
Sorry maybe I am just confusing terms, but can you explain a little more about the "verification ID"
 and what you'd do with it?  FirebaseUI has already verified the user's phone number for you and successfully registered the user with Firebase Authentication.

[`PhoneAuthCredential`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/PhoneAuthCredential) only exposes two methods that I can see:

  * `getProvider()`
  * `getSmsCode()`

It's not normally necessary to keep the `AuthCredential` objects around after they've already been used to sign in.

**Comment by mlostekk** [comment]
Well, on your backend side, we are following this guide

https://firebase.google.com/docs/auth/admin/verify-id-tokens

to verify the token that was registered on a mobile device.

**Comment by samtstern** [comment]
@mlostekk following that guide, you can get the ID token from the current user at any time with this snippet:

```java
FirebaseUser mUser = FirebaseAuth.getInstance().getCurrentUser();
mUser.getToken(true)
    .addOnCompleteListener(new OnCompleteListener<GetTokenResult>() {
        public void onComplete(@NonNull Task<GetTokenResult> task) {
            if (task.isSuccessful()) {
                String idToken = task.getResult().getToken();
                // Send token to your backend via HTTPS
                // ...
            } else {
                // Handle error -> task.getException();
            }
        }
    });
```

You don't need the `PhoneAuthCredential`.

**Comment by mlostekk** [comment]
Ah perfect. Thanks!

**Comment by joelEpping** [comment]
Hi! I have the same issue .. when I send the token to my web service in which method I need to put the token to login.  when the user is already register.
