### ISSUE TITLE
Gradle sync failed because Failed to resolve: com.android.support.constraint:constraint-layout-solver:1.1.0-beta1

### ISSUE THREAD

**Issue by ItsAnubhav** [firebase/FirebaseUI-Android#866]
I have no idea why I am facing this issue. I've updated the constraint layout and constraint layout solver too from SDK manager. Android Studio is updated. 
I am trying to use the latest version of firebase auth ui 

`compile 'com.firebaseui:firebase-ui-auth:2.2.0'`

I can't even use (because of the same problem)

`compile 'com.firebaseui:firebase-ui-auth:2.1.1'`

Searched a lot on StackOverflow but nothing helped.

**Comment by SUPERCILEX** [comment]
Have you added the Google repo?
```groovy
allprojects {
    repositories {
        jcenter()
        google()
    }
}
```

**Comment by ItsAnubhav** [comment]
I am using 
```
allprojects {
    repositories {
        jcenter()
        maven {
            url 'https://maven.google.com'
        }
    }
}
```
When I use this
```
allprojects {
    repositories {
        jcenter()
        google()
    }
}
```
it says 
`Error:(18, 0) Gradle DSL method not found: 'google()'`

**Comment by SUPERCILEX** [comment]
Hmmm, you should be fine with that setup. Maybe try again? 😆 Not sure what's going on...

**Comment by TheCraftKid** [comment]
You are trying to use the solver as a dependency. That's the problem. You should be using the library itself:
```gradle
dependencies {
    // ...
    implementation 'com.android.support.constraint:constraint-layout:1.1.0-beta1'
}
````
Also, using `google()` as a repository requires a newer version of the Android Gradle plugin, but I forgot the specific version.

As this probably doesn't pertain to the library, I suggest we close this issue.

**Comment by asiamamun2011** [comment]
``repositories {
    maven {
        url 'https://maven.google.com'
    }
}``
