### ISSUE TITLE
Facebook Login requires FB SDK dependency

### ISSUE THREAD

**Issue by Queskr** [firebase/FirebaseUI-Android#867]
Hi,

We get the below messgae:
java.lang.RuntimeException: Facebook provider cannot be configured without dependency. Did you forget to add 'com.facebook.android:facebook-android-sdk:VERSION' dependency?

After adding the right compile statement, it does compile (yet with ~22 warnings), but notice this step is not coumented anywhere nor is it clear what it is needed if the login process goes through the Firebase backend ...

Queskr

**Comment by krisu7** [comment]
It is documented here: [https://github.com/firebase/FirebaseUI-Android/tree/master/auth](https://github.com/firebase/FirebaseUI-Android/tree/master/auth)

**Comment by krisu7** [comment]
@Queskr by firebase backend do you mean custom authentication using your own server? If so, look here for android reference: [https://firebase.google.com/docs/auth/android/custom-auth](https://firebase.google.com/docs/auth/android/custom-auth)

and here for the server: [https://firebase.google.com/docs/auth/admin/create-custom-tokens](https://firebase.google.com/docs/auth/admin/create-custom-tokens)

**Comment by krisu7** [comment]
@Queskr If you want to check if user is logged in, look here: [https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#using-firebaseui-for-authentication](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#using-firebaseui-for-authentication)

**Comment by samtstern** [comment]
Thanks @krisu7 for jumping in!

**Comment by joknu1** [comment]
> It is documented here:
> https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#configuration

It should perhaps be mentioned here as well -> https://firebase.google.com/docs/auth/android/facebook-login
