### ISSUE TITLE
Firebase ref should be 11.2.0

### ISSUE THREAD

**Issue by nielsz** [firebase/FirebaseUI-Android#873]
https://github.com/firebase/FirebaseUI-Android/blob/f4494c4a5fcafc8b32351edcb02ed2834c6a32b4/constants.gradle#L13

FirebaseUI Version | Firebase/Play Services Version
-- | --
2.3.0 | 11.2.0

**Comment by peterhav** [comment]
I'm getting this output during builds when switching to Firebase-UI 2.3.0 and Play Services 11.2.0: 

```
error: cannot access aad
        FirebaseAuth auth = FirebaseAuth.getInstance();
                                        ^
  class file for com.google.android.gms.internal.aad not found
```

Might be caused by the above?

**Comment by samtstern** [comment]
@nielsz whoops I messed up in the README, good catch.

**Comment by samtstern** [comment]
@peterhav this means you have mixed versions of dependencies, see:
https://github.com/firebase/FirebaseUI-Android#compatibility-with-firebase--google-play-services-libraries

**Comment by prasannaboppe** [comment]
What is Firebase UI Version for Firebase/Play services version 11.2.0

**Comment by Kyrluckechuck** [comment]
@prasannaboppe As far as I'm able to tell, there isn't a compatible version of firebaseui out yet, oddly

**Comment by samtstern** [comment]
@prasannaboppe @Kyrluckechuck `2.3.0` should be compatible if you follow the instructions in my previous comment.

**Comment by Kyrluckechuck** [comment]
@samtstern That method may work, but it makes maintaining and future upgrades of the build.gradle a heck of a lot harder (needing 4 set modules per Firebase module)

So you're saying that the only way to use the stable version of Firebase (i.e. 11.2.0), is to manually add every dependency with the older version? Should this not be as simple as marking 11.2.0 as the firebase dependency if it was actually compatible?

**Comment by samtstern** [comment]
@Kyrluckechuck that's the case right now.  The reason is that we didn't want to keep chasing the firebase dependency and releasing FirebaseUI updates on that schedule.  We now release FirebaseUI updates only when it makes sense for this library.

As soon as the gradle plugin `3.0` hits stable (it's in `beta` right now) we can move most of our `compile` dependencies to `implementation` which will fix this problem forever.

**Comment by Kyrluckechuck** [comment]
@samtstern Alright, that's fair enough and makes sense! Couldn't find anything about that anywhere, so had no idea.

Will just stick to as it is now and when that release happens I'll happily switch over to the new methodology :)
