### ISSUE TITLE
What should be the version of FirebaseUI-Android when using Google Play Services API 11.2.0?

### ISSUE THREAD

**Issue by Reddhi** [firebase/FirebaseUI-Android#874]

**Comment by krisu7** [comment]
@Reddhi Use version 2.3.0 and add `compile 'com.google.android.gms:play-services-auth:11.2.0'`  as per documentation: [https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies](https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies)

**Comment by TheCraftKid** [comment]
It may likely be the next minor version release (2.4.0) unless there's a problem.

**Comment by samtstern** [comment]
@Reddhi the answer provided of @krisu7 is correct.  You should use the latest version of FirebaseUI (`2.3.0` as of this writing) and then override our dependencies.

**Comment by Reddhi** [comment]
Any timeline on when I can expect this update?

**Comment by samtstern** [comment]
@Reddhi no timeline, it depends on what features/fixes we are trying to put out in this library.

You shouldn't need any update to move forward, you can override our dependency and continue with `11.2.0`.
