### ISSUE TITLE
Using FirebaseListAdapter without refreshing the list?

### ISSUE THREAD

**Issue by Deespot** [firebase/FirebaseUI-Android#876]
Hey there, I hope its the right place for this question...
The FirebaseListAdapter works great for me but I dont want the whole list to restart everytime a child changes. Is there any way to do so?

**Comment by samtstern** [comment]
@Deespot if you're concerned about performance in general I'd use the `FirebaserRecyclerAdapter` which has more granular events and does not update the whole data set.

If you need to use the `ListAdapter` then you can override the `onChildChanged` method and make improvements there:

```java
    @Override
    public void onChildChanged(ChangeEventListener.EventType type,
                               DataSnapshot snapshot,
                               int index,
                               int oldIndex) {
        // BEFORE:
        // notifyDataSetChanged();
        //
        // AFTER:
        // TODO: make improvements
    }
```

**Comment by samtstern** [comment]
I am going to close this issue as however you decide to solve your issue will not require a change in FIrebaseUI code, but let us know what you decide to do!

**Comment by Deespot** [comment]
@samtstern Hey thank for your answer. If I will override onchildchanged and leave it blank will it do the work? If you can give me a direction or basic conept of how to approch this it will be much appreciated, im kind of new to programing.

**Comment by samtstern** [comment]
@Deespot if you leave it blank you won't see any changes!  I think the best advice I can give you is to switch to `RecyclerView`.  It's the best practice and is built for exactly what you are trying to do,

**Comment by Deespot** [comment]
@samtstern thank you for your help. will do :)
