### ISSUE TITLE
Move to Gradle 3.0 plugin (stable)

### ISSUE THREAD

**Issue by samtstern** [firebase/FirebaseUI-Android#877]
Context:
https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_separation

We've known this for a while, but `compile` dependencies are now deprecated in favor of choosing `api` or `implementation`.  

API vs Implementation:

> Dependencies appearing in the api configurations will be transitively exposed to consumers of the library, and as such will appear on the compile classpath of consumers. Dependencies found in the implementation configuration will, on the other hand, not be exposed to consumers, and therefore not leak into the consumers' compile classpath.

How to choose:

> As a guideline, you should prefer the implementation configuration first: leakage of implementation types to consumers would then directly lead to a compile error of consumers, which would be solved either by removing the type from the public API, or promoting the dependency as an API dependency instead.

The biggest hurdle here will be fixing our (already complicated) POM generation / publishing flow.  The new `maven-publish` plugin is supposed to understand `api`/`implementation` and produce the proper POMs but I don't have any information on that yet.

(Note: some discussion of benefits already in #875)

**Comment by SUPERCILEX** [comment]
@samtstern I believe this issue can have the implemented label and be added to the `3.1.1` hotlist.

**Comment by samtstern** [comment]
This is fixed in version `3.1.1`.
