### ISSUE TITLE
Update to Firebase 11.2.0

### ISSUE THREAD

**Issue by filol** [firebase/FirebaseUI-Android#881]
Can you update firebase (11.2.0), this causes different version problems if our application is in firebase version 11.2.0. Thanks

**Comment by SUPERCILEX** [comment]
@filol You can use Play Services `v11.2.0` by [overriding our dependencies](https://github.com/firebase/FirebaseUI-Android#upgrading-dependencies).

**Comment by filol** [comment]
Thank you, I did not think it was possible. But you can also update;)

**Comment by samtstern** [comment]
@filol we will update when we publish the next version of FirebaseUI, glad it worked out for you!
