### ISSUE TITLE
 How to set only even position into adapter not set odd position  in adapter of FirebaseIndexRecyclerAdapter?

### ISSUE THREAD

**Issue by sukhwinder-kaur** [firebase/FirebaseUI-Android#882]
While I am set the adapter only even position view , odd position view also show as blank , If set the condition like of this:
if ( position % 2 == 0 ){
      viewHolder.mView.setVisibility(View.VISIBLE);
}
 else{
         viewHolder.mView.setVisibility(View.GONE);
}

**Comment by samtstern** [comment]
@sukhwinder-kaur this is a general question about `RecyclerView.Adapter` and is not specific to Firebase.  Since there's not enough information in this issue to determine what is going wrong, please ask this question on StackOverflow.
