### ISSUE TITLE
How to have prefilled phone number from shared pref. in PhoneVerificationActivity?

### ISSUE THREAD

**Issue by pinkeshdarji** [firebase/FirebaseUI-Android#887]
Hi, I need to automatically fill phone number from shared pref. to firebase phone ui auth activity.
Is there any way that If I modify this
                        startActivityForResult(
                                AuthUI.getInstance().createSignInIntentBuilder().setAvailableProviders(
                                        Arrays.asList(new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()))
                                        .build(), RC_SIGN_IN);

in such a way that, when verify phone activity gets open, instead of asking for a phone number I should have it from shared pref and user can continue instead of giving phone number again which we have already stored while registration.

**Comment by samtstern** [comment]
@pinkeshdarji sorry this is not supported, as it's not a normal flow as far as FirebaseUI is concerned.  If you need to build custom flows like this, I suggest using [Firebase phone authentication](https://firebase.google.com/docs/auth/android/phone-auth) directly.

**Comment by samtstern** [comment]
This issue has been fixed in version `2.4.0`:
https://github.com/firebase/FirebaseUI-Android/releases/tag/2.4.0

**Comment by pinkeshdarji** [comment]
@samtstern can you please suggest how to use it? I am using firebase 3.0.0 version.
