### ISSUE TITLE
Doesn't work with product flavours

### ISSUE THREAD

**Issue by vivekjha1990** [firebase/FirebaseUI-Android#888]
I am using it with firebasephone auth.
In the verification sms we are supposed to get **%APP_CODE%** at last but that is missing. This is probably caused by build flavours.

For different flavours I am having this string in my build gradle
**resValue 'string', 'app_name', '"MyAwesomeApp"'**

**Comment by samtstern** [comment]
@vivekjha1990 it's unclear what your issue is.  Does this have to do with FirebaseUI or is it a general issue with Firebase Phone Authentication?

Maybe try contacting [Firebase Support](firebase.google.com/support) if you're having an issue with phone authentication.  There's not enough information presented here to help you.

**Comment by vivekjha1990** [comment]
Hi,
 This should be an issue with firebaseui. In readme it's mentioned to
provide app name in strings.XML.

I'm using build variants - restype for the same.

**Comment by vivekjha1990** [comment]
https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md#ui-customization

@samtstern I have tried removing build variants. It still doesn't work. You sure it's not firebaseUi issue? In that case I will try removing firebaseUi and will check if that issue still comes.

**Comment by samtstern** [comment]
@vivekjha1990 if this is a FirebaseUI issue can you describe the error message you're getting or provide a screenshot of what's going wrong?

**Comment by vivekjha1990** [comment]
@samtstern : No error message. Everything is fine. Except that in the verification sms I am not getting app name.
According to firebase auth I should be getting a message of this format : 

> %LOGIN_CODE% is your verification code for %APP_NAME%.

but I am getting app name only on ios device. On Android this is missing.

Functionality isn't broken. But this is something we need absolutely.

**Comment by samtstern** [comment]
@vivekjha1990 if it's an issue in the content of the text message (sounds like it) then this is definitely not caused by FirebaseUI but rather the Firebase Authentication backend.

Please use the Firebase support link above, they can help you get this configured correctly.
