### ISSUE TITLE
Duplicate title/toolbar when using android.R.style.Theme_Material

### ISSUE THREAD

**Issue by emaillenin** [firebase/FirebaseUI-Android#889]
* Android device: Genymotion (Google Nexus 5)
  * Android OS version: 5.1.0
  * Google Play Services version: 11.0.4
  * Firebase/Play Services SDK version: 11.0.4
  * FirebaseUI version: 2.3.0
  
### Step 3: Describe the problem:

When I use the Theme "android.R.style.Theme_Material", I see two Toolbar with the same app title.

#### Steps to reproduce:

```

        context.startActivityForResult(
                AuthUI.getInstance().createSignInIntentBuilder()
                        .setAvailableProviders(
                                Arrays.asList(
                                        new AuthUI.IdpConfig.Builder(AuthUI.GOOGLE_PROVIDER).build(),
                                        facebookIdp,
                                        new AuthUI.IdpConfig.Builder(AuthUI.PHONE_VERIFICATION_PROVIDER).build()
                                ))
                        .setIsSmartLockEnabled(!BuildConfig.DEBUG)
                        .setTosUrl("https://app.duggout.com/terms-and-conditions")
                        .setPrivacyPolicyUrl("https://app.duggout.com/privacy")
                        .setTheme(android.R.style.Theme_Material)
                        .build(),
                RC_SIGN_IN);

```  

## With theme:

<img src="https://user-images.githubusercontent.com/1235853/30044588-975d7496-921b-11e7-80f8-c5910d328e7e.png" width="240">

## Without theme:

<img src="https://user-images.githubusercontent.com/1235853/30044608-bd1d609c-921b-11e7-9e33-e584c96287f1.png" width="240">  

#### Expected Results:

  * Only one toolbar

**Comment by SUPERCILEX** [comment]
@emaillenin That's because you're mixing system and AppCompat themes. Internally, we use AppCompat and define our own support lib toolbar and I'm guess the system theme injects an additional toolbar somehow. Anyway, what kind of theming are you looking for? The default should pick your app's default colors if you're using AppCompat. See more [details on theming](https://github.com/firebase/FirebaseUI-Android/tree/master/auth#ui-customization).

**Comment by emaillenin** [comment]
Thanks for the info. My theme slightly overrides the default dark theme from AppCompat. When I use my custom theme, I get the same look & feel now, without the double toolbar.

**Comment by SUPERCILEX** [comment]
Awesome!
