### ISSUE TITLE
AuthUI as Fragment or Dialog

### ISSUE THREAD

**Issue by Eragon29** [firebase/FirebaseUI-Android#890]
### Step 1: Are you in the right place?
Asking for a solution or a feature related to AuthUI

### Step 2: Describe your environment

  * Android device: all
  * Android OS version: all
  * Google Play Services version: 11.2.0
  * Firebase/Play Services SDK version: 11.2.0
  * FirebaseUI version: 2.3.0
  
### Step 3: Describe the problem:
My app uses Fragments and a Navigation Drawer to navigate. When I use AuthUI the NavigationDrawer disappears because AuthUI is an Activity. 
Is it possible to use it as a Fragment, if not a workaround would be to use it as a Dialog I think.
Is one of them feasable?(I would prefer Fragment)

**Comment by samtstern** [comment]
@Eragon29 thanks for the feature request!  We can see how this would be helpful, but it's not feasible with our current architecture and not on our roadmap for now.

**Comment by mdhornet90** [comment]
Given Google's push towards [Navigation Architecture Component](https://developer.android.com/topic/libraries/architecture/navigation/navigation-implementing#Modify-activity), it seems like this might be worth revisiting.
