### ISSUE TITLE
Get the phone number after verification in onActivityResult

### ISSUE THREAD

**Issue by circassian8** [firebase/FirebaseUI-Android#897]
Can I get the phone number that was verified by the user in onActivityResult? I need to save the phone number so that I don't have to ask the user for it again

**Comment by SUPERCILEX** [comment]
Use `FirebaseUser#getPhoneNumber()`.

**Comment by samtstern** [comment]
@SUPERCILEX is right.

To elaborate, once you have signed in successfully you can do:

```java
FirebaseAuth.getInstance().getCurrentUser().getPhoneNumber()
```
