### ISSUE TITLE
Manifest merger failed while adding FirebaseUI library

### ISSUE THREAD

**Issue by jnpatel2811** [firebase/FirebaseUI-Android#899]
My app is targeting sdk 25, with minSdk 14, compiledSdk 25and buildToolsVersion 25.0.0

When I try to add following dependency,
compile 'com.firebaseui:firebase-ui-auth:2.3.0'

It gives: following error
Error:Execution failed for task ':app:processGoogleDebugManifest'.
> Manifest merger failed with multiple errors, see logs

when I checked logs of AndroidManifest error: 
It shows: uses-sdk:minSdkVersion 14 cannot be smaller than version 15 declared in library
and suggest me to add Suggestion: use tools:overrideLibrary="android.support.customtabs" to force usage.

when I am adding this, it gives various manifest merger errors. 
And while finding the solution, someone suggested to chage sdk version to 26, but it also give various error.

I'm just beginner in this, so please help me out.

**Comment by SUPERCILEX** [comment]
The `minSdkVersion` for the auth module is api `16`.

**Comment by jnpatel2811** [comment]
@SUPERCILEX I can't upgrade minSdkVersion, so is there anyway to use it?

**Comment by SUPERCILEX** [comment]
@jnpatel2811 Nope, sorry! 😢 😄

**Comment by jnpatel2811** [comment]
SO I'll have to implement my own UI. that's the only way. Isn't it the case, @SUPERCILEX ?

**Comment by SUPERCILEX** [comment]
Yep. I'm not sure why you can't just bump the `minSdkVersion` though, there can't be _that_ many users on 14-15, right? I'm guessing the support lib is also going to bump up to `16` next I/O, so might as well start early! 😄

**Comment by jnpatel2811** [comment]
yeah, I will talk to my team about this upgradation!

**Comment by jnpatel2811** [comment]
Got to know  that minSdkVersion required for using this is 16. but it is not clearly mentioned in the README.

**Comment by SUPERCILEX** [comment]
Yeah, we should mention that somewhere. TBH, you're the first! Not many people are still on API 14 which is both impressive and sad. 😄

**Comment by diedu89** [comment]
Currently when creating an app with android studio it defaults the minsdk to 15, so maybe this really should be in the README
