### ISSUE TITLE
Missing translations for signing in with email and password

### ISSUE THREAD

**Issue by jbahamon** [firebase/FirebaseUI-Android#901]
* Android device: Motorola G5 Plus
  * Android OS version: 7.0
  * Google Play Services version: 11.5.09
  * FirebaseUI version: 2.2.0

Using a device with Spanish (Chile) as the only language.
  
#### Steps to reproduce:

  1. Login using an email account
  2. Enter an existing email account
  3. Provide an incorrect password
  4. Press on the "Sign in" ("Acceder", in Spanish) button

  * The error text shows "The password is invalid or the user does not have a password." instead of translated text.

This might happen because the exception/error received in `WelcomeBackPasswordPrompt` is not localized, only showing the (non-localized) description from a `FirebaseAuthError`.

Additionally, the accesibility info for the password visibility toggling item (the eye icon) from the password `TextView` is not localized. This can probably be solved by setting the `app:passwordToggleContentDescription` field on the password element in `fui_register_email_layout.xml`.

**Comment by samtstern** [comment]
@jbahamon thanks for reporting this.  This is probably a server error message that we are displaying directly, which is a bad idea.  And we also appreciate the note about accesibility!

**Comment by SUPERCILEX** [comment]
@samtstern Doesn't #946 fix this?

**Comment by jstimes** [comment]
@SUPERCILEX It seems like it would, but that method does not localize the server error messages, which is what this message is. We should log these server errors and have our own (localized) strings to show the user. I can work on this.

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.2`.
