### ISSUE TITLE
Would like to remove io.fabric.apikey override from auth manifest

### ISSUE THREAD

**Issue by asfalcone** [firebase/FirebaseUI-Android#904]
In Nov 2016 an [override to the Fabric apikey](https://github.com/firebase/FirebaseUI-Android/pull/396/files/ec40c413ced3268dadd9fda933a8ca4d2eef5182#diff-72b30eb5e208275c795ce7e9fb7275ae) was added to get around a Twitter auth issue.

Twitter auth is no longer part of Fabric and the override of this key to the string value causes issues with the Fabric SDK (namely that it cannot start up because the string value it finds isn't present).

I'd like to propose removing this value from the auth AndroidManifest.

**Comment by samtstern** [comment]
@asfalcone thanks for the tip?  Do we just need to remove those lines from the `AndroidManifest.xml` or is there more to it?  If so I am happy to do it or you can send a PR to the `version-2.3.1-dev` branch.

**Comment by asfalcone** [comment]
I'll send a PR. Just wanted an open issue to reference in the PR 👍

**Comment by samtstern** [comment]
This issue has been fixed in version `2.4.0`:
https://github.com/firebase/FirebaseUI-Android/releases/tag/2.4.0
