### ISSUE TITLE
AuthUIActivity is not moving to another activity after sign-in

### ISSUE THREAD

**Issue by Soumya7391** [firebase/FirebaseUI-Android#908]
Hi, 

I have used this UI code for my app. Authenticating through phone number. Its verifying the phone-number, but after verifiying its not redirecting to the actual screen(which has to be displayed in my app after login). 
What has to be changed? Kindly help.

**Comment by samtstern** [comment]
@Soumya7391 there is not enough information here to debug, please present code/screenshots that demonstrate the problem you are having.

**Comment by Soumya7391** [comment]
@samtstern I resolved it. Now when I generate the apk and install it in other devices, I am getting error of verification.It says "This app is not authorized to use Firebase Authentication. please verify that the correct package name and SHA-1 are configured in the Firebase Console.[App validation failed]"
I have entered the SHA-1 and also package name is correct.

**Comment by samtstern** [comment]
@Soumya7391 debug and release builds have different SHA1s, make sure you have them all entered on the project you are using.

If you are getting that error message it is certain that you have entered the wrong SHA in the Firebase console or are using the wrong Firebase project

**Comment by Soumya7391** [comment]
@samtstern I checked, the key is correct. Any other issue?

**Comment by samtstern** [comment]
@Soumya7391 could you please contact [Firebase support](https://firebase.google.com/support/) for help debugging your project?

**Comment by Soumya7391** [comment]
Hey @samtstern I could solve it. Thank you so much .
