### ISSUE TITLE
Unable to set gravity of FirebaseUI.WrapperStyle elements to center

### ISSUE THREAD

**Issue by ktraghuram** [firebase/FirebaseUI-Android#909]
Respected programmers,

    I am a beginner and i am trying to develop an app with the help of FirebaseUI and android studio 2.3.3.  I seek your apologies for improper terminology that i may have used in expressing the problem.

    I implemented signing in method with the help of AuthUI.getInstance()....and tried to modify the style of FirebaseUI like below:

<style name="FirebaseUI" parent="Theme.AppCompat.DayNight.DarkActionBar">
        <item name="colorPrimary">@color/colprim</item>
        <item name="colorPrimaryDark">@color/colprimdrk</item>
        <item name="colorAccent">@color/colaccnt</item>
        <item name="android:buttonStyle">@style/FirebaseUI.Button</item>
        <item name="android:layout_gravity">center</item>
    </style>

This resulted in change of gravity of layout successfully.

[Image of Changed layout](https://drive.google.com/file/d/0B-e9WjszAI7WY2lLSm9xQ3JlMzQ/view?usp=drivesdk)

But when i am trying to change the style "FirebaseUI.WrapperStyle" as:
 <style name="FirebaseUI.WrapperStyle">
        <item name="android:layout_height">match_parent</item>
        <item name="android:layout_width">match_parent</item>
        <item name="android:paddingTop">16dp</item>
        <item name="android:layout_gravity">center</item>
        <item name="android:paddingLeft">@dimen/fui_wrapper_padding_horiz</item>
        <item name="android:paddingRight">@dimen/fui_wrapper_padding_horiz</item>
    </style>
This doesn't show any change in the gravity of layout, I tried to change even the layout "fui_check_email_layout" directly but obtained no result.

[Image of unchanged layout](https://drive.google.com/file/d/0B-e9WjszAI7WVEJqWGpTMTBNTzA/view?usp=drivesdk)

I want to place the "email field" and "next button" at the center of the screen (i.e to set the gravity of these fields to center).

Could anyone kindly suggest me how can i obtain the mentioned result. I would be very thankful for the response.

**Comment by samtstern** [comment]
@ktraghuram can you show a screenshot of what it looks like for you and then describe how you'd like to change it?

We generally don't support these kinds of UI customizations, but I want to better understand your request.

**Comment by ktraghuram** [comment]
Sir,
 i have included the images of changed and unchanged layouts for your reference.

The first image resulted by putting layout gravity to center in "FirebaseUI" style.

The second image shows no change when i included the line layout_gravity:"center" into the style  "FirebaseUI.WrapperStyle". But increasing and decreasing of "padding top" shows immediate change in the layout.

Could you kindly suggest the way to bring these elements to the center of the screen. 

Thanking you.

**Comment by samtstern** [comment]
I now see what you're trying to do.  Unfortunately we can't support this level of customization.  It's not possible for us to design a UI that works across devices if each developer is overriding element positioning.

If you are really concerned about this you could try overriding the entire XML file but remember that resource IDs are not considered part of the API and future updates will almost certainly break you.

**Comment by ktraghuram** [comment]
Thank you very much for the suggestion sir.
