### ISSUE TITLE
RuntimeException after extending FirebaseLoginBaseActivity

### ISSUE THREAD

**Issue by TienVNguyen** [firebase/FirebaseUI-Android#91]
Hi,

I followed exactly steps in FirebaseUI-Android/codelabs/chat/ to learn Firebase. It compiled successfully but error appeared when I ran app. I think there is a problem with FirebaseLoginBaseActivity. Please help to take a look on this.
1/ First error is missing or trackable class GoogleAuthProvider in FirebaseLoginDialog.getGoogleAuthProvider
2/ Second error is a fatal exception (NullPointerException)

[RelatedFiles.zip](https://github.com/firebase/FirebaseUI-Android/files/160381/RelatedFiles.zip)

Thanks & Best Regards,
Tien Nguyen

**Comment by puf** [comment]
Please provide the complete stack trace that you're getting for exceptions. Also note that I'm not likely to download a zip file: include the [minimal code that is needed to reproduce the problem](http://stackoverflow.com/help/mcve) in your issue.

An educated guess tells me that your second problem may be the same as #85

**Comment by TienVNguyen** [comment]
Hi puf,

I try to implement the same as in your suggestion but errors still appear when I ran the app.
So, I guess you have to look at my code too.

1/ I used these libraries with Android studio 1.5 - JDK 1.7
    compile 'com.firebase:firebase-client-android:2.5.0'
    compile 'com.firebaseui:firebase-ui:0.3.1'

2/ Here is the code logic which got error as I described above.
package com.training.tiennguyen.chatvn_firebase;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.TextView;

import com.firebase.client.AuthData;
import com.firebase.client.Firebase;
import com.firebase.ui.FirebaseListAdapter;
import com.firebase.ui.auth.core.AuthProviderType;
import com.firebase.ui.auth.core.FirebaseLoginBaseActivity;
import com.firebase.ui.auth.core.FirebaseLoginError;
import com.training.tiennguyen.chatvn_firebase.model.ChatMessage;

public class MainActivity extends FirebaseLoginBaseActivity {
    private Firebase mFirebaseRef;
    FirebaseListAdapter<ChatMessage> mListAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        // Initial connection between our code and its Firebase backend
        Firebase.setAndroidContext(this);

        setContentView(R.layout.activity_main);

        // Connect to the specific database
        mFirebaseRef = new Firebase("https://chatvn-firebase.firebaseio.com/");

        final EditText textEdit = (EditText) this.findViewById(R.id.text_edit);

        // Event when sendButton is click
        Button sendButton = (Button) this.findViewById(R.id.send_button);
        sendButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String text = textEdit.getText().toString();
                ChatMessage message = new ChatMessage("Android User", text);
                mFirebaseRef.push().setValue(message);
                textEdit.setText("");
            }
        });

        // If data contains records, list will appear
        final ListView listView = (ListView) this.findViewById(android.R.id.list);
        mListAdapter = new FirebaseListAdapter<ChatMessage>(this, ChatMessage.class,
                android.R.layout.two_line_list_item, mFirebaseRef) {
            @Override
            protected void populateView(View v, ChatMessage model, int position) {
                ((TextView) v.findViewById(android.R.id.text1)).setText(model.getName());
                ((TextView) v.findViewById(android.R.id.text2)).setText(model.getText());
            }
        };
        listView.setAdapter(mListAdapter);

        // Login Authentication
        Button loginButton = (Button) this.findViewById(R.id.login);
        loginButton.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                showFirebaseLoginPrompt();
            }
        });
    }

    @Override
    protected void onStart() {
        super.onStart(); // TODO: Error appears on this.
        setEnabledAuthProvider(AuthProviderType.PASSWORD);
        //showFirebaseLoginPrompt();
    }

    @Override
    public void onFirebaseLoggedOut() {    }

    @Override
    protected Firebase getFirebaseRef() {
        return null;
    }

    @Override
    protected void onFirebaseLoginProviderError(FirebaseLoginError firebaseLoginError) {    }

    @Override
    protected void onFirebaseLoginUserError(FirebaseLoginError firebaseLoginError) {    }

    @Override
    public void onFirebaseLoggedIn(AuthData authData) {    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mListAdapter.cleanup();
    }
}

2/ Here is the errors log:
03-07 15:07:55.315 7253-7253/? D/dalvikvm: Late-enabling CheckJNI
03-07 15:07:55.363 7253-7259/? D/dalvikvm: Debugger has detached; object registry had 1 entries
03-07 15:07:55.403 7253-7253/? W/dalvikvm: VFY: unable to find class referenced in signature (Landroid/view/SearchEvent;)
03-07 15:07:55.403 7253-7253/? I/dalvikvm: Could not find method android.view.Window$Callback.onSearchRequested, referenced from method android.support.v7.view.WindowCallbackWrapper.onSearchRequested
03-07 15:07:55.403 7253-7253/? W/dalvikvm: VFY: unable to resolve interface method 15063: Landroid/view/Window$Callback;.onSearchRequested (Landroid/view/SearchEvent;)Z
03-07 15:07:55.403 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
03-07 15:07:55.403 7253-7253/? I/dalvikvm: Could not find method android.view.Window$Callback.onWindowStartingActionMode, referenced from method android.support.v7.view.WindowCallbackWrapper.onWindowStartingActionMode
03-07 15:07:55.403 7253-7253/? W/dalvikvm: VFY: unable to resolve interface method 15067: Landroid/view/Window$Callback;.onWindowStartingActionMode (Landroid/view/ActionMode$Callback;I)Landroid/view/ActionMode;
03-07 15:07:55.403 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x72 at 0x0002
03-07 15:07:55.427 7253-7253/? I/dalvikvm: Could not find method android.view.ViewGroup.onRtlPropertiesChanged, referenced from method android.support.v7.widget.Toolbar.onRtlPropertiesChanged
03-07 15:07:55.427 7253-7253/? W/dalvikvm: VFY: unable to resolve virtual method 14962: Landroid/view/ViewGroup;.onRtlPropertiesChanged (I)V
03-07 15:07:55.427 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x6f at 0x0007
03-07 15:07:55.431 7253-7253/? I/dalvikvm: Could not find method android.content.res.TypedArray.getChangingConfigurations, referenced from method android.support.v7.widget.TintTypedArray.getChangingConfigurations
03-07 15:07:55.431 7253-7253/? W/dalvikvm: VFY: unable to resolve virtual method 417: Landroid/content/res/TypedArray;.getChangingConfigurations ()I
03-07 15:07:55.431 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
03-07 15:07:55.431 7253-7253/? I/dalvikvm: Could not find method android.content.res.TypedArray.getType, referenced from method android.support.v7.widget.TintTypedArray.getType
03-07 15:07:55.431 7253-7253/? W/dalvikvm: VFY: unable to resolve virtual method 439: Landroid/content/res/TypedArray;.getType (I)I
03-07 15:07:55.431 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x0002
03-07 15:07:55.455 7253-7256/? D/dalvikvm: GC_CONCURRENT freed 203K, 8% free 8154K/8839K, paused 10ms+1ms, total 16ms
03-07 15:07:55.479 7253-7253/? I/dalvikvm: Failed resolving Lcom/firebase/ui/auth/google/GoogleAuthProvider; interface 3100 'Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;'
03-07 15:07:55.479 7253-7253/? W/dalvikvm: Link of class 'Lcom/firebase/ui/auth/google/GoogleAuthProvider;' failed
03-07 15:07:55.479 7253-7253/? W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/firebase/ui/auth/google/GoogleAuthProvider;)
03-07 15:07:55.479 7253-7253/? I/dalvikvm: Failed resolving Lcom/firebase/ui/auth/google/GoogleAuthProvider; interface 3100 'Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;'
03-07 15:07:55.479 7253-7253/? W/dalvikvm: Link of class 'Lcom/firebase/ui/auth/google/GoogleAuthProvider;' failed
03-07 15:07:55.479 7253-7253/? W/dalvikvm: VFY: unable to find class referenced in signature (Lcom/firebase/ui/auth/google/GoogleAuthProvider;)
03-07 15:07:55.479 7253-7253/? I/dalvikvm: Failed resolving Lcom/firebase/ui/auth/google/GoogleAuthProvider; interface 3100 'Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;'
03-07 15:07:55.479 7253-7253/? W/dalvikvm: Link of class 'Lcom/firebase/ui/auth/google/GoogleAuthProvider;' failed
03-07 15:07:55.479 7253-7253/? I/dalvikvm: Could not find method com.firebase.ui.auth.google.GoogleAuthProvider.cleanUp, referenced from method com.firebase.ui.auth.core.FirebaseLoginDialog.cleanUp
03-07 15:07:55.479 7253-7253/? W/dalvikvm: VFY: unable to resolve virtual method 26460: Lcom/firebase/ui/auth/google/GoogleAuthProvider;.cleanUp ()V
03-07 15:07:55.479 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x6e at 0x000a
03-07 15:07:55.479 7253-7253/? I/dalvikvm: Failed resolving Lcom/firebase/ui/auth/google/GoogleAuthProvider; interface 3100 'Lcom/google/android/gms/common/api/GoogleApiClient$OnConnectionFailedListener;'
03-07 15:07:55.479 7253-7253/? W/dalvikvm: Link of class 'Lcom/firebase/ui/auth/google/GoogleAuthProvider;' failed
03-07 15:07:55.479 7253-7253/? E/dalvikvm: Could not find class 'com.firebase.ui.auth.google.GoogleAuthProvider', referenced from method com.firebase.ui.auth.core.FirebaseLoginDialog.getGoogleAuthProvider
03-07 15:07:55.479 7253-7253/? W/dalvikvm: VFY: unable to resolve check-cast 3075 (Lcom/firebase/ui/auth/google/GoogleAuthProvider;) in Lcom/firebase/ui/auth/core/FirebaseLoginDialog;
03-07 15:07:55.479 7253-7253/? D/dalvikvm: VFY: replacing opcode 0x1f at 0x0008
03-07 15:07:55.483 7253-7253/? D/AndroidRuntime: Shutting down VM
03-07 15:07:55.483 7253-7253/? W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0xa627d288)
03-07 15:07:55.483 7253-7253/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.training.tiennguyen.chatvn_firebase/com.training.tiennguyen.chatvn_firebase.MainActivity}: java.lang.NullPointerException
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2059)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                     at dalvik.system.NativeStart.main(Native Method)
                                                  Caused by: java.lang.NullPointerException
                                                     at com.firebase.ui.auth.core.FirebaseLoginBaseActivity.onStart(FirebaseLoginBaseActivity.java:151)
                                                     at com.training.tiennguyen.chatvn_firebase.MainActivity.onStart(MainActivity.java:79)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1163)
                                                     at android.app.Activity.performStart(Activity.java:5018)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2032)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084) 
                                                     at android.app.ActivityThread.access$600(ActivityThread.java:130) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                     at android.os.Looper.loop(Looper.java:137) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:4745) 
                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:511) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
                                                     at dalvik.system.NativeStart.main(Native Method) 
03-07 15:07:55.547 7253-7256/? D/dalvikvm: GC_CONCURRENT freed 236K, 9% free 8316K/9095K, paused 11ms+0ms, total 14ms
03-07 15:07:56.699 7253-7256/com.training.tiennguyen.chatvn_firebase D/dalvikvm: GC_CONCURRENT freed 385K, 10% free 8414K/9287K, paused 0ms+0ms, total 3ms
03-07 15:08:04.243 7253-7256/com.training.tiennguyen.chatvn_firebase D/dalvikvm: GC_CONCURRENT freed 364K, 10% free 8478K/9351K, paused 0ms+0ms, total 2ms

Thanks & Best Regards,
Tien Nguyen

**Comment by puf** [comment]
You're not implementing `getFirebaseRef()`:

```
@Override
protected Firebase getFirebaseRef() {
    return mFirebaseRef;
}
```

The codelab has that in https://github.com/firebase/FirebaseUI-Android/tree/master/codelabs/chat#enable-e-mailpassword-login

**Comment by TienVNguyen** [comment]
Hi puf,

You're correct. It's my bad. How silly I am :( . Thanks for your confirmation :+1: 
Nice support :+1: 

Thanks & Best Regards,
Tien Nguyen

**Comment by mugash4** [comment]
I created a firebase recyclerView  in android v 2.2.3 but it does not show it self nor does it show items from firebase database. 
someone with idea what might be the problem or what i did wrong? here is a snippet of my code

`import android.content.Context;
import android.content.Intent;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.LinearLayoutManager;
import android.support.v7.widget.RecyclerView;
import android.view.Menu;
import android.view.MenuInflater;
import android.view.MenuItem;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.ui.database.FirebaseRecyclerAdapter;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.firebase.ui.database.*;
import com.squareup.picasso.Callback;
import com.squareup.picasso.NetworkPolicy;
import com.squareup.picasso.Picasso;

public class MainActivity extends AppCompatActivity {
    private RecyclerView mBlog_list;

    private DatabaseReference mDatabase;

    private LinearLayoutManager  mLinearLayoutManager;

   private FirebaseRecyclerAdapter<Blog, BlogViewHolder> firebaseRecyclerAdapter;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        mDatabase = FirebaseDatabase.getInstance().getReference().child("Blog");

        mLinearLayoutManager = new LinearLayoutManager(this);
        mLinearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);

        mBlog_list = (RecyclerView) findViewById(R.id.blog_list);
        mBlog_list.setHasFixedSize(true);




    }

    @Override
    public void onStart() {
        super.onStart();

        //recyclerview adapter , receives data from database and sets it to the view
        firebaseRecyclerAdapter = new FirebaseRecyclerAdapter<Blog, BlogViewHolder>(

                Blog.class,
                R.layout.blog_row,
                BlogViewHolder.class,
                mDatabase

        ) {
            @Override
            protected void populateViewHolder(BlogViewHolder viewHolder, Blog model, final int position) {

                final String post_key = getRef(position).getKey();

                viewHolder.setTitle(model.getTitle());
                viewHolder.setDesc(model.getDesc());
                viewHolder.setImage(getApplicationContext(), model.getImage());


                viewHolder.mView.setOnClickListener(new View.OnClickListener() {
                    @Override
                    public void onClick(View view) {

                        Toast.makeText(MainActivity.this, post_key, Toast.LENGTH_LONG).show();

                    }
                });

            }
        };
        firebaseRecyclerAdapter.registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
            @Override
            public void onItemRangeInserted(int positionStart, int itemCount) {
                super.onItemRangeInserted(positionStart, itemCount);
                int friendlyMessageCount = firebaseRecyclerAdapter.getItemCount();
                int lastVisiblePosition =
                        mLinearLayoutManager.findLastCompletelyVisibleItemPosition();
                // If the recycler view is initially being loaded or the
                // user is at the bottom of the list, scroll to the bottom
                // of the list to show the newly added message.
                if (lastVisiblePosition == -1 ||
                        (positionStart >= (friendlyMessageCount - 1) &&
                                lastVisiblePosition == (positionStart - 1))) {
                    mBlog_list.scrollToPosition(positionStart);
                }
            }
        });

        mBlog_list.setLayoutManager(mLinearLayoutManager);
        mBlog_list.setAdapter(firebaseRecyclerAdapter);

    }

    public static class BlogViewHolder extends RecyclerView.ViewHolder {

        View mView;

        TextView post_title;
        TextView post_desc;

        ImageView post_image;

        public BlogViewHolder(View itemView) {
            super(itemView);

            mView = itemView;
            post_title = (TextView) mView.findViewById(R.id.Post_title);
            post_desc = (TextView) mView.findViewById(R.id.Post_desc);
            post_image = (ImageView) mView.findViewById(R.id.mPost_image);

        }

        public void setTitle(String title) {

            post_title.setText(title);

        }

        public void setDesc(String desc) {

            post_desc.setText(desc);

        }


        public void setImage(final Context ctx, final String image) {

            //Picasso.with(ctx).load(image).into(post_image);
            Picasso.with(ctx).load(image).networkPolicy(NetworkPolicy.OFFLINE).into(post_image, new Callback() {
                @Override
                public void onSuccess() {

                }

                @Override
                public void onError() {

                    Picasso.with(ctx).load(image).into(post_image);

                }
            });

        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        firebaseRecyclerAdapter.cleanup();
    }


    public boolean onCreateOptionsMenu(Menu menu) {
        super.onCreateOptionsMenu(menu);
        MenuInflater addBtn = getMenuInflater();
        addBtn.inflate(R.menu.main_menu, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {

        if (item.getItemId() == R.id.action_add) {
            startActivity(new Intent(MainActivity.this, PostActivity.class));
        }
        if (item.getItemId() == R.id.action_logout) {


        }

        return super.onOptionsItemSelected(item);
    }

}`

here is the custom class used to read and write objects :

`public class Blog {
    private String title;
    private String desc;
    private String image;

    public Blog(){}


    public Blog(String title, String desc, String image) {
        this.title = title;
        this.desc = desc;
        this.image = image;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDesc() {
        return desc;
    }

    public void setDesc(String desc) {
        this.desc = desc;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }
}`

and the xml for recycleView :

`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/activity_main"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context="com.weebly.gogreenenvirons.kenyasafariapp.MainActivity">

    <android.support.v7.widget.RecyclerView
        android:id="@+id/blog_list"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">

    </android.support.v7.widget.RecyclerView>
</RelativeLayout>`

any help is highly appreciated.
