### ISSUE TITLE
how to get uniqueID match position for delete  by Onclick Recyclerview

### ISSUE THREAD

**Issue by shipcake** [firebase/FirebaseUI-Android#912]
hi, i find solution and try to get the position for Recyclerview by Onclick Event. How to match uniqueID at firebase by position.
ps.getadapterposition return value 0,1,2,3... not match uniqueID at firebase

`
    private DatabaseReference databaseReference;
    FirebaseRecyclerAdapter<data_phone,ViewHolder> firebaseRecyclerAdapter;
    private RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_second_tab);

        recyclerView = (RecyclerView) findViewById(R.id.recyclearView);
        recyclerView.setLayoutManager(new LinearLayoutManager(SecondTabActivity.this));

        databaseReference = FirebaseDatabase.getInstance().getReference("PHONE");
        databaseReference.keepSynced(true);

        firebaseRecyclerAdapter = new FirebaseRecyclerAdapter<data_phone, ViewHolder>(data_phone.class, R.layout.custom_row, ViewHolder.class, databaseReference) {
            @Override
            protected void populateViewHolder(ViewHolder viewHolder, data_phone model, int position) {

                viewHolder.txtphone_view.setText(model.getTxtPhone());
                viewHolder.txtnumber_view.setText(model.getTxtNumber());

                viewHolder.uid_view.setText(model.getuId());

            }

        };

        recyclerView.setAdapter(firebaseRecyclerAdapter);

    }

    public static class ViewHolder extends RecyclerView.ViewHolder {

        TextView txtphone_view;
        TextView txtnumber_view;
        TextView uid_view;
        View view;
        DatabaseReference databaseReference;

        public ViewHolder(View itemView) {
            super(itemView);

            txtphone_view = (TextView)itemView.findViewById(R.id.txtphone_view);
            txtnumber_view=(TextView)itemView.findViewById(R.id.txtnumber_view);
            uid_view=(TextView)itemView.findViewById(R.id.uid_view);

            view = itemView;

            view.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View view) {

                    // *** HOW TO GET THE POSITION FOR DELETE CHILD  *** //

                    //databaseReference = FirebaseDatabase.getInstance().getReference("PHONE");
                    //databaseReference.child(???????).removeValue();
                    Toast.makeText(view.getContext(),"Deleted",Toast.LENGTH_SHORT).show();

                }
            });

        }

    }

**Comment by SUPERCILEX** [comment]
@shipcake use `FirebaseRecyclerAdapter#getRef(int)`:
```java
new FirebaseRecyclerAdapter<data_phone, ViewHolder>(data_phone.class, R.layout.custom_row, ViewHolder.class, databaseReference) {
    @Override
    protected void populateViewHolder(ViewHolder viewHolder, data_phone model, int position) {
        // ...
        viewHolder.databaseReference = getRef(position);
    }
}
```

**Comment by samtstern** [comment]
Thanks @SUPERCILEX

**Comment by surianmau** [comment]
getRef shows error
        @Override
        public void onBindViewHolder(@NonNull MyAdapter.MyViewHolder holder, final int position) {
            MyDataGetSet data= listArray.get(position);
            holder.MyText.setText(data.getUser_name());
            holder.MyStatus.setText(data.getUser_status());


            Picasso.with(context).load(data.getUser_thumb_image()).into(holder.MyImage);



            holder.itemView.setOnClickListener(new View.OnClickListener()
            {
                @Override
                public void onClick(View view)
                {
                    String visit_user_id =getRef().getKey();
                    Intent profileIntend = new Intent(Main2Activity.this,ProfileActivity.class);
                     profileIntend.putExtra("visit_user_id",visit_user_id);
                    startActivity(profileIntend);
                }
            });
        }

**Comment by tith-github** [comment]
``You can try to use like below.
@Override
    protected void onBindViewHolder(@NonNull myviewholder holder, int position, @NonNull Product model) {
        String id = getRef(position).getKey();
        holder.product.setText(model.getProduct());
        holder.unitprice.setText("$"+model.getUnitPrice());
        Glide.with(holder.img.getContext()).load(model.getPhoto()).into(holder.img);
        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                Intent intent = new Intent (v.getContext(), ProductDetail.class);
                Toast.makeText(v.getContext(),""+id,Toast.LENGTH_LONG).show();
                v.getContext().startActivity(intent);
            }
        });
    }
```
