### ISSUE TITLE
[Feature Request] Allow set default country code for phone auth

### ISSUE THREAD

**Issue by jhuleatt** [firebase/FirebaseUI-Android#916]
### Step 3: Describe the problem:

In [PhoneNumberUtils.java](https://github.com/firebase/FirebaseUI-Android/blob/f4494c4a5fcafc8b32351edcb02ed2834c6a32b4/auth/src/main/java/com/firebase/ui/auth/ui/phone/PhoneNumberUtils.java#L36), the default country code and locale are hardcoded as US. 

It does appear that the locale is [automatically set](https://github.com/firebase/FirebaseUI-Android/blob/f4494c4a5fcafc8b32351edcb02ed2834c6a32b4/auth/src/main/java/com/firebase/ui/auth/ui/phone/PhoneNumberUtils.java#L117) based on a user's SIM, but it would be helpful to be able to set a default locale too.

**Comment by ashfaaaa** [comment]
is it possible to remove choose country spinner and set default country code? so users from the specified country can sign up.

**Comment by SUPERCILEX** [comment]
@samtstern I believe this was fixed in FirebaseUI [`v2.4.0`](https://github.com/firebase/FirebaseUI-Android/releases/tag/2.4.0).

**Comment by SUPERCILEX** [comment]
Nevermind, that was just to prefill the phone number. I'll add this feature to #1083.

**Comment by samtstern** [comment]
This has been fixed and released in version `3.2.0`.
