### ISSUE TITLE
FirebaseRecyclerAdapter with Multiple Queries

### ISSUE THREAD

**Issue by bagintz** [firebase/FirebaseUI-Android#920]
I have 2+ queries that pull from the same source that I would like to appear in my FirebaseRecyclerAdapter.  I have been banging my head against this particular issue for a bit and I wanted to ask if I was missing something or if the FirebaseRecyclerAdapter only works with single queries.

I know I can roll my own if I need to, but I really like this implementation :)

**Comment by SUPERCILEX** [comment]
You could create several `FirebaseArray`s and forward those events to your own custom `ObservableSnapshotArray` which you can then pass into the adapter. Not really sure what you're trying to do though...

**Comment by bagintz** [comment]
I think that is what I am doing.  Essentially, I have, in RTDB, this structure:

chats {
"uid1": [chat1],
"uid2": [chat2],
"uid3": [chat3],
"uid4": [chat4]
}

and then

users {
"user1": {
"chats": {
 "uid1" : "active".
 "uid2" : "pending",
 "uid4" : "archived"
}
}
}

And I want to get all the chats that are active or pending but not archived.  And I want those to show up in one recyclerview.  Currently I am trying to create my own instance of ObservableSnapshotArray and get all the snapshots that match that into one array to pass to FirebaseREcyclerAdapter, but I was hoping there was some magic way to just pass multiple queries in.

**Comment by bagintz** [comment]
@SUPERCILEX I was able to get it to query like I wanted creating my own instance of ObservableSnapshotArray, but I lose the "listener" portion that comes automatically using the FirebaseArray.  Can you explain what you mean by creating several FirebaseArrays and forwarding them to my own ObservableSnapshotArray?

**Comment by samtstern** [comment]
I believe what you're looking for is the `FirebaseIndexRecylerAdapter`, there's a section on this in the `database/README.md`

**Comment by bagintz** [comment]
@samtstern that I can tell, it only works with one query

**Comment by SUPERCILEX** [comment]
@bagintz We're working on some API improvements internally so we're probably going to accidentally screw you over (sorry! 😁), but for now, you can use our existing callbacks. In `OSA#onCreate()`, you'll want to add your listeners to the various `FirebaseArray`s and then remove them in `OSA#onDestroy()`. Whenever you're ready to send an update, you'll use the `OSA#notify[ChangeEvent/OnDataChanged/OnCancelled]` methods and the `ObservableSnapshotArray` will dispatch those events to its attached listeners.

TBH, the Firebase Realtime Database is best suited for data duplication so you'd probably be better off having an `activeMessages` ref or something similar with all the messages you need for this query in one place.

**Comment by bagintz** [comment]
@SUPERCILEX Thank you, that is what I ended up doing.  The transition from SQL to NoSQL has been.....challenging.  Thank you for the great library!!

**Comment by girotomas** [comment]
is there any new way of solving this problem?

**Comment by apexkid** [comment]
I am facing a similar problem. I want to show the list of chats for a user along with profile pictures for each user and last message. So my database design looks something like this:

```
users:
   userid1:
       name: MyName
       profilePicUrl: <here>

userchats:
       userid1:
               chatgrp1
               chatgrp2

chatgroups:
    chatgrp1:
         participants: <list>
         lastMessage: "This..."

```

I can use indexed query to get list of chatgroups for a user and then contents for each. But i also need the name and profile pic for the participants. I am not able to figure out how to do that with firebaseUI. Any help is highly appreciated.

**Comment by mahbub90** [comment]
apexkid: you can do a .get() on a seperate CollectionReference (your "Users" collection) for each uid, inside the onbindviewholder method. That way you'll get the name and any other information stored under each user.
