### ISSUE TITLE
FirebaseUI-Android: Why not translate network error message ?

### ISSUE THREAD

**Issue by lmdic** [firebase/FirebaseUI-Android#924]
1. Select language Romanian
2. Start FirebaseUI-Android
3. Text is correct translate on screen

Here screenshot:

![firebase_1](https://user-images.githubusercontent.com/303539/30872490-eccaadb2-a2f2-11e7-9706-90587d94b187.png)

4. I turn off network (e.g. WiFi)
5. Enter phone number and press next
6. Show error message on English

Here screenshot:

![firebase_error_message](https://user-images.githubusercontent.com/303539/30872497-f84eb098-a2f2-11e7-9c84-10e6dd65c2a5.png)

Why this error message is not translated?

**Comment by samtstern** [comment]
@lmdic thanks for reporting this, I am going to close this and move discussion to #901 which is basically the same issue.  We need to never return errors directly from the server.
