### ISSUE TITLE
How to get unique  key of  an object generated while it is created in recyclerview adapter?

### ISSUE THREAD

**Issue by aqelkp** [firebase/FirebaseUI-Android#93]

**Comment by puf** [comment]
The `FirebaseRecyclerAdapter` does not create items, so I'm not really sure what you mean. Can you give an example code snippet of what you're trying to accomplish?

**Comment by aqelkp** [comment]
I achieved what i wanted by                
 mAdapter.getRef(position)
Closing the issue
