### ISSUE TITLE
FacebookSDK.setWebDialogTheme(...) method moved in Facebook SDK 4.27.0

### ISSUE THREAD

**Issue by FrancoSabadini** [firebase/FirebaseUI-Android#933]
The `setWebDialogTheme(...)` method has been moved from `FacebookSDK` to `WebDialog` in version 4.27.0 of the Facebook SDK (see https://developers.facebook.com/docs/android/change-log-4x/), and this makes FirebaseUI crash because this method is used in `FacebookProvider`.

The `FacebookProvider` class should be updated to use the new API.

**Comment by FrancoSabadini** [comment]
I just realized that this was fixed in branch `version-3.0.0-dev` so closing this issue.

**Comment by yash59** [comment]
i am using version 3.0.0 and it;s not working showing error... 


  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/WebDialog;
  at com.firebase.ui.auth.provider.FacebookProvider.<init>(FacebookProvider.java:67)

**Comment by SUPERCILEX** [comment]
@yash59 Upgrade your Facebook dependency from `facebook-android-sdk:x` to `facebook-login:4.27.0`.

@samtstern We should probably mention in the release notes that `v3.0` requires Facebook `v4.27`.

**Comment by samtstern** [comment]
@SUPERCILEX will add to release notes

**Comment by cutiko** [comment]
Hello
Can you please add this in some part of the docs please
Thanks :)

**Comment by samtstern** [comment]
I just updated auth/README.md to reflect the 4.27 verison

**Comment by cutiko** [comment]
@samtstern thanks a lot :) One question though, the initial recommendation and what you have added to docs now both worked for me:

- `compile('com.facebook.android:facebook-login:4.27.0')` this works
- `compile('com.facebook.android:facebook-android-sdk:4.27.0')` this also works

Any difference we should be aware, is one more correct than the other?

**Comment by cutiko** [comment]
@samtstern sorry if I'm spamming here but maybe I found something, according to the docs [suggested](https://developers.facebook.com/docs/android/componentsdks) initially, Facebook move the SDK to separate modules. So it will be less heavy to add only the Facebook login module, however, I'm not sure if the ui library is doing something else.

I recently had to implement some Google login with custom permissions, which is out of the scope of this library, so I didn't use it. Maybe the same logic could be applied here. If the login is the only thing is needed then just the Facebook login library, but if there is anything else needed by the developer, then the developer is whom should customize it.

**Comment by SUPERCILEX** [comment]
@cutiko Yep, see #967

**Comment by cutiko** [comment]
@SUPERCILEX thanks for the clarification, and again, sorry if I was too anxious

**Comment by SUPERCILEX** [comment]
@cutiko NP, you could have used `facebook-android-sdk`, but it includes a bunch of unnecessary stuff and would have bloated your APK. `facebook-login` is actually [reasonably small compared to the whole thing](https://github.com/facebook/facebook-android-sdk#structure).
