### ISSUE TITLE
FirebaseRecyclerAdapter but Failed to convert value of type java.util.HashMap to String?

### ISSUE THREAD

**Issue by saddamuwejan** [firebase/FirebaseUI-Android#934]
Hi ,
Trying to create FirebaseRecyclerAdapter that retrieve data all data from object class , but i get the error "Failed to convert value of type java.util.HashMap to String"
here is my code :

```java
public class Match {
   private String name; 
   private String desc;



   public Match() {
   }

   public String getName() {
      return name;
   }

   String getDesc() {
      return desc;
   }
}
```
```java
public class MatchHolder extends RecyclerView.ViewHolder {
    private final TextView mNameField;
    private final TextView mMessageField;

    public MatchHolder(View itemView) {
        super(itemView);
        mNameField = (TextView) itemView.findViewById(android.R.id.text1);
        mMessageField = (TextView) itemView.findViewById(android.R.id.text2);
    }

    public void setName(String name) {
        mNameField.setText(name);
    }

    public void setDesc(String desc) {
        mMessageField.setText(desc);
    }
}
```
```java
public class SportActivity extends AppCompatActivity {

    final FirebaseDatabase database = FirebaseDatabase.getInstance();



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_sport);

        DatabaseReference ref = database.getReference();

         RecyclerView matches = (RecyclerView) findViewById(recycle_viewer);
        matches.setHasFixedSize(true);
       matches.setLayoutManager(new LinearLayoutManager(this));


        FirebaseRecyclerAdapter<Match, MatchHolder> mAdapter = new FirebaseRecyclerAdapter<Match, MatchHolder>(
                Match.class,
                android.R.layout.two_line_list_item,
                MatchHolder.class,
                ref) {
            @Override
            public void populateViewHolder(MatchHolder holder, Match match, int position) {
                holder.setName(match.getName());
                holder.setDesc(match.getDesc());
            }
        };

        matches.setAdapter(mAdapter);



    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        FirebaseRecyclerAdapter mAdapter = null;
        mAdapter.cleanup();
    }


    }
```

my db screenshot 
![screenshot from 2017-09-30 02-59-27](https://user-images.githubusercontent.com/20250935/31040043-8607ca7e-a58b-11e7-87eb-be8a5d9ee553.png)

**Comment by samtstern** [comment]
Change this:

```
DatabaseReference ref = database.getReference();
```

to this:

```
DatabaseReference ref = database.getReference().getChild('Match');
```

Closing this issue as it's not a library bug.  In the future please post these kinds of questions to StackOverflow.

**Comment by saddamuwejan** [comment]
Thanks , next time will consider your advice about posting on StackOverflow , however the change did not work ,now i get this error "can not resolve method .getChild(java.lang.string).

**Comment by samtstern** [comment]
@saddamuwejan I updated my answer.  It's just child().

The concept you're missing is that if you want to show a list of matches, you need to give the library a reference to the database path containing the matches.  Your current implementation passes a path to the database root.

**Comment by puf** [comment]
Please be respectful when you post a question/issue and indicate when you cross-post: https://github.com/firebase/FirebaseUI-Android/issues/934

**Comment by saddamuwejan** [comment]
@puf why would you through such words ?. I have thanked Mr. @samtstern worked by thiere advice by posting on Stackoverflow .thiere reply here was no help to me so i replied on them so they know it was not working.Now Your words are verry bossy and unacceptable especially in such professional site!
