### ISSUE TITLE
Having trouble getting com.firebaseui:firebase-ui-firestore:3.0.0

### ISSUE THREAD

**Issue by bagintz** [firebase/FirebaseUI-Android#941]
When trying to use
`compile "com.firebaseui:firebase-ui:3.0.0"`
I get 
Error:Failed to resolve: firebaseui-android:common:unspecified

After trying to refresh gradle dependencies, I can see this too

Error:Failed to resolve: com.firebaseui:firebase-ui-firestore:3.0.0

Either way, I can't get it to work :(

**Comment by bagintz** [comment]
https://jcenter.bintray.com/com/firebaseui/

Doesn't show the Firestore dir

**Comment by samtstern** [comment]
D'oh!  There are a few things here.  First of all, I need to remove the dep on common from the POM.

Second, I forgot that because this is a new lib I have to get permission to add to jCenter.  Should be resolved by the end of the day.  For now I think this should work:

```groovy
repositories {
    maven {
      url 'https://dl.bintray.com/firebaseui/firebase-ui'
    }
}
```

**Comment by samtstern** [comment]
Also @bagintz we really don't recommend ever using the combined target, use `-auth`, `-storage`, etc to get just the bits you need!

**Comment by bagintz** [comment]
@samtstern will do, thank you!!

**Comment by SUPERCILEX** [comment]
Yep, I'm on it.

**Comment by SUPERCILEX** [comment]
Whoops, GitHub didn't update. Closing the PR.

**Comment by bagintz** [comment]
@SUPERCILEX and @samtstern I am still getting 
`Error:Failed to resolve: firebaseui-android:common:unspecified`
with 3.0.0, both the combined target and separate

I tried both with the 
```
repositories {
    maven {
      url 'https://dl.bintray.com/firebaseui/firebase-ui'
    }
}
```
and without.  Any ideas?

**Comment by samtstern** [comment]
@bagintz running this from my project root seemed to fix it for me:

```
./gradlew --refresh-dependencies clean cleanBuildCache
```

**Comment by bagintz** [comment]
sigh, still not working for me :(, going to try a few different things

**Comment by bagintz** [comment]
@samtstern ok, finally got it, had to clear out my .gradle folders

**Comment by simmyy** [comment]
I used       compile "com.google.firebaseui:firebase-ui:3.0.0" and 
I'm getting
Error:Failed to resolve: com.google.firebaseui:firebase-ui:3.0.0

**Comment by samtstern** [comment]
@simmyy it's `com.firebaseui` not `com.google.firebaseui`
