### ISSUE TITLE
Unable to find Resources to use FirebaseRecyclerAdapter with Firestore

### ISSUE THREAD

**Issue by CeJienAJPC** [firebase/FirebaseUI-Android#945]
### Step 2: Describe your environment

  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.0.0
  
### Step 3: Describe the problem:
Just trying my hand with the new Firestore. Unfortunately, I am unable to find relevant information relating RecyclerView, Firebaserecycleradapter and the new Firestore.

When trying to update the **Firebase dependencies to 11.4.2** and the **Firebase-UI dependencies to 3.0.0** the following error is getting displayed where I have been using FireaseRecyclerAdaper

`populateViewHolder does not override from its superclass`

Any relevant information and links to available resources with be appreciated.

Thanks.

**Comment by SUPERCILEX** [comment]
@CeJienAJPC `populateViewHolder` is no longer a thing, make sure to take a look at the [upgrade guide](https://github.com/firebase/FirebaseUI-Android/blob/master/docs/upgrade-to-3.0.md#realtime-database) and [Firestore docs](https://github.com/firebase/FirebaseUI-Android/blob/master/firestore/README.md#using-the-firestorerecycleradapter).

**Comment by CeJienAJPC** [comment]
I am sorry. I missed the information. Thanks again

**Comment by SUPERCILEX** [comment]
NP! 😄
