### ISSUE TITLE
RecyclerView +  DataSetObserver

### ISSUE THREAD

**Issue by borjaruiz** [firebase/FirebaseUI-Android#95]
I'm developing an app with a chat Fragment.
I want to scroll to bottom whenever the chat has new messages.
When I used a listView, this worked perfectly.

```
adapter = new ChatListAdapter(ref.orderByChild(Constants.FB_SERVERTIME), getActivity());

        listView.setAdapter(adapter);
        adapter.registerDataSetObserver(new DataSetObserver() {
            @Override
            public void onChanged() {
                super.onChanged();
                listView.setSelection(adapter.getCount() - 1);
            }
        });
```

My recyclerView has setStackFromEnd = "true".

In the FirebaseUi example I can't see any code to do what I want.

This is not working neither:

```
android:stackFromBottom="true"
android:transcriptMode="alwaysScroll"
```

## UPDATED:

I finally pass the recyclerView as parameter to the adapter. And then I do this. I think this is not correct. Can anyone tell its opinion please?

 ```
mSnapshots.setOnChangedListener(new FirebaseArray.OnChangedListener() {
            @Override
            public void onChanged(EventType type, int index, int oldIndex) {
                switch (type) {
                    case Added:
                        notifyItemInserted(index);
                        notifyDataSetChanged();
                        recyclerView.scrollToPosition(index);
                        break;
                    case Changed:
                        notifyItemChanged(index);
                        break;
                    case Removed:
                        notifyItemRemoved(index);
                        break;
                    case Moved:
                        notifyItemMoved(oldIndex, index);
                        break;
                    default:
                        throw new IllegalStateException("Incomplete case statement");
                }
            }
        });
```

**Comment by puf** [comment]
See #90 . Note that StackOverflow is probably a better place for fairly general Android questions such as this one. It's where I found the answer to the issue I linked. :-)

**Comment by borjaruiz** [comment]
The link doesn't solve my problem, I saw that post before asking, and I tried but it doesn't work for me.

After testing again the link code, I realize that it only scrolls to lastPosition when recyclerView items don't fit all the screen (recycler view can't scroll).

So, in my opinion, that link doesn't solve the problem.

Thanks for your reply Frank
