### ISSUE TITLE
phone auth is not working

### ISSUE THREAD

**Issue by yash59** [firebase/FirebaseUI-Android#952]
when i am using phone auth provider it's showing alert dialog...
there is no user record corresponding to this identifier. the user may have been deleted. firebase phone auth.
i am using latest version 3.0.0.
here is screenshot.
![screenshot_2017-10-07-21-12-12-071_com yashnagda kkb](https://user-images.githubusercontent.com/27333071/31309518-079f5222-aba5-11e7-86e9-e93e2e305e0f.png)

**Comment by samtstern** [comment]
@yash59 that's strange ... do you see this with every phone number or only some?

**Comment by yash59** [comment]
with every phone number.

**Comment by isaisachen** [comment]
@yash59 You are probably having Google Play services v11.7 on your testing device. Yes, there's a bug going on there. We will get this fixed by EOD 10/10 PST. In the meantime, you can test on a device without Google Play services public beta.  Sorry for the inconvenience.

**Comment by yash59** [comment]
thanks..  @isaisachen

**Comment by samtstern** [comment]
Thanks @isaiachen for swooping in!  Closing since there's nothing we can do with FirebaseUI.
