### ISSUE TITLE
FirebaseIndexRecyclerAdapter not found

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-Android#955]
Hi All,

This may seem like a silly question. However I'm trying to use FirebaseIndexRecyclerAdapter however this is not coming as an option.

I"m using compile 'com.firebaseui:firebase-ui-database:3.0.0' and I can use the normal FirebaseRecyclerAdapter but not the Index adapter. 

Am I missing something here.

**Comment by SUPERCILEX** [comment]
Yep, we killed that in favor of the builder. See the [migration guide](https://github.com/firebase/FirebaseUI-Android/blob/master/docs/upgrade-to-3.0.md#realtime-database) which explains that you can now use `setIndexQuery()` on the builder to get the index adapter.

**Comment by joemerritt** [comment]
Thank you for you help Alex, I see how this is easier. However, this no longer accepts a query. Is there any way to do this?

Joe

**Comment by SUPERCILEX** [comment]
@joemerritt Not sure what you're looking at, but it should still accept a query. See this example:
https://github.com/firebase/FirebaseUI-Android/blob/7d72ddb96e274200a89ceef550aa33337b6fed4a/app/src/main/java/com/firebase/uidemo/database/realtime/RealtimeDbChatIndexActivity.java#L25-L30

**Comment by samtstern** [comment]
@joemerritt closing this issue since @SUPERCILEX has pointed you in the right direction but feel free to keep asking questions on this thread if you don't get it working.
