### ISSUE TITLE
firebase recycler adapter showing empty rows

### ISSUE THREAD

**Issue by yash59** [firebase/FirebaseUI-Android#956]
i am using firebase database ui 3.0.0. it works fine and load the data but problem is that when i am scrolling the recylerview it's showing empty rows.
take a look..
https://stackoverflow.com/questions/46631826/firebase-recycler-adapter-showing-empty-rows

**Comment by samtstern** [comment]
@yash59 please don't double post.  StackOverflow is the better place for this question, so closing it here.

**Comment by yash59** [comment]
but it's very strange values are there and nothing in logs.. take a look at this video.. https://drive.google.com/open?id=0B4RAgG7rnTMcOWo1SUJ5d0w5bEk
