### ISSUE TITLE
Blank pop up in phone auth when the theme is dark

### ISSUE THREAD

**Issue by syrop** [firebase/FirebaseUI-Android#957]
I set the theme to dark. I had phone verification disabled in Firebase console, deliberately to invoke the pop up. This is what appeared (screenshot). The text should say "This operation is not allowed. Enable sign-in method in the Authentication tab of the Firebase console".

This is caused by the setting
`<item name="android:textColor">@color/text_default_material_dark_primary</item>`
in dark theme. The white text color is applied to the pop up, rendering the pop up blank.

To fix it I suggest using ContextThemeWrapper in class PhoneVerificationActivity, method showAlertDialog, while AlertDialog.Builder is created.

![device-2017-10-09-150026](https://user-images.githubusercontent.com/19635111/31339342-e48c3c5a-ad02-11e7-9586-e063ae44f804.png)

**Comment by SUPERCILEX** [comment]
@syrop Yeah, those are just developer errors that we should really just be logging anyway. I'll get rid of them soon. Either way, see https://github.com/firebase/FirebaseUI-Android/issues/958#issuecomment-335279357 which fixes the dark mode bugs.

Thanks!

**Comment by syrop** [comment]
Confirmed. Works well with the newest commit.

**Comment by samtstern** [comment]
@syrop thanks for confirming!
