### ISSUE TITLE
FirebaseRecyclerAdapter has overly strong cast

### ISSUE THREAD

**Issue by ScottCypher** [firebase/FirebaseUI-Android#96]
`onCreateViewHolder` casts the inflated `View` to a `ViewGroup` which causes a crash if your layout is simple (e.g. a `TextView` with no `ViewGroup` around it).  The constructor for `RecyclerView.ViewHolder` only requires a `View`, so this cast seems unnecessary.

**Comment by puf** [comment]
Thanks for entering Scott! As discussed at Droidcon today, we'll need to find a way that keeps the simple model we have for the most common use-case today, while adding support for this use-case too.

**Comment by SUPERCILEX** [comment]
This issue should now be fixed in #307.

**Comment by samtstern** [comment]
@SUPERCILEX good catch
