### ISSUE TITLE
Remove field asking for First & last name in email signup

### ISSUE THREAD

**Issue by ryandailey100** [firebase/FirebaseUI-Android#960]
Is it possible to not ask for the First & last name of the user when signing up through email? I would like it to only be email, password, and confirm password (if possible). Please get back to me asap. Thanks!

**Comment by SUPERCILEX** [comment]
Nope, unfortunately not. See #806 and duplicate #467.

**Comment by samtstern** [comment]
Closing as duplicate of #806 and #467

**Comment by markoars** [comment]
it is possible now:
