### ISSUE TITLE
Glide Offline Cache

### ISSUE THREAD

**Issue by dovahkiin98** [firebase/FirebaseUI-Android#961]
* Android device: Xperia M5
  * Android OS version: 6.0.0
  * Google Play Services version: Latest
  * Firebase/Play Services SDK version: 14.2.0
  * FirebaseUI version: 3.0.0
  

```java
val imageReference = FireBaseUtils.Storage.child("$name.jpg")

        GlideApp.with(this)
                .load(imageReference)
                .transition(DrawableTransitionOptions.withCrossFade())
                .into(mDeviceImage)
```

Using this code, the app loads and saves the image in cache.
What I don't want is the image saved in cache even after the application closes. When I restart the app Glide automatically loads the image from the offline cache.

How can I disable offline cache? I want Glide to cache the images in runtime, but clear it after the app is closed.

**Comment by SUPERCILEX** [comment]
@dovahkiin98 This is a Glide question, not FirebaseUI. Google should always be the first step, but here's [documentation](http://bumptech.github.io/glide/doc/caching.html#skipping-the-cache). BTW, why would you want to disable cache? That's going to hurt your users.

**Comment by samtstern** [comment]
@dovahkiin98 I agree with @SUPERCILEX , this is a Glide question not a FirebaseUI question.
