### ISSUE TITLE
setindexquery return key not found

### ISSUE THREAD

**Issue by joemerritt** [firebase/FirebaseUI-Android#964]
Hi Guys,

Quick question: when using setindexquery, is there a way to return any keys that were not found at the reference position. A notification comes in the log cat:

W/FirebaseIndexArray: Key not found at ref: https://myapp.firebaseio.com/Adverts/-Kw2dwycOR0kZ64mIB3E

and I would like to store this key.

Thank you for your help.

Joe

**Comment by SUPERCILEX** [comment]
@joemerritt Nope, see duplicate #441.

**Comment by samtstern** [comment]
Closing as duplicate.
