### ISSUE TITLE
Dependency issues using new 3.0.0

### ISSUE THREAD

**Issue by CyberpunkPsychonaut** [firebase/FirebaseUI-Android#965]
Hello, I am having issues with FirebaseUI 3.0.0.

[I made a gist of the relevant details](https://gist.github.com/CyberpunkPsychonaut/db5ebc03c986e844d65b50bacbb06056), let me know if any more are needed.

For some reason android is pulling in firebase 9.0.0 from the
classpath 'com.google.gms:google-services:3.1.1' plugin

and the newer 11.4.2 version from firebaseui.

Any suggestions?

**Comment by samtstern** [comment]
@CyberpunkPsychonaut can you show your `app/build.gradle` file?  Do you have any Firebase or Play services dependencies in it?

This may be solved if you just add:
```groovy
compile 'com.google.firebase:firebase-auth:11.4.2'
```

I chose `firebase-auth` above since I assume you are using FirebaseUI for Auth, but if that's not the case choose a different Firebase dependency.

**Comment by CyberpunkPsychonaut** [comment]
Sam, I included the app/build.gradle in the gist. I didn't have the firebase-auth dependency but now I don't know what I did. I tried fidgeting with the gradle files and somehow now they haven't changed by my error has changed. I have made a new [gist](https://gist.github.com/CyberpunkPsychonaut/9019c4be3c9d365f0b2021a2851e0943)

**Comment by CyberpunkPsychonaut** [comment]
If you can see this, I don't know what is wrong with GitHub but my last comment and the gist I made keep appearing/disappearing randomly with page refreshes in Chrome.

**Comment by samtstern** [comment]
@CyberpunkPsychonaut thanks for the gist.  Your new error has something to do with `Observable` which is totally unrelated to FirebaseUI.

**Comment by CyberpunkPsychonaut** [comment]
Thats the thing... I'm not using observables anywhere... The error is appearing on the Firestore call

**Comment by samtstern** [comment]
@CyberpunkPsychonaut looking at the error I see this:

```
at com.google.firebase.firestore.DocumentReference.set(Unknown Source:5)
at <APP_ID>.util.DatabaseUtil.uploadBackpack(DatabaseUtil.java:54)
```

And then farther up the stack I see thinks about method reflection, which reveals that this is an error in data mapping from a Java object to a Firestore object.

Could you show me the Java class that you're passing to `set()` in your `uploadBackpack` class?  I assume it's a `Backpack` class or similar.

**Comment by CyberpunkPsychonaut** [comment]
`import android.os.Parcel;
import android.os.Parcelable;

import io.realm.RealmObject;

public class Backpack extends RealmObject implements Parcelable {

    public String id;
    public String ownerId;
    public String name;
    public double packWeightKg;

    public Backpack() { }

    public Backpack(String id, String ownerId, String name, double packWeightKg) {
        this.id = id;
        this.name = name;
        this.packWeightKg = packWeightKg;
    }


    @Override public int describeContents() {
        return 0;
    }

    @Override public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(this.id);
        dest.writeString(this.ownerId);
        dest.writeString(this.name);
        dest.writeDouble(this.packWeightKg);
    }

    protected Backpack(Parcel in) {
        this.id = in.readString();
        this.ownerId = in.readString();
        this.name = in.readString();
        this.packWeightKg = in.readDouble();
    }

    public static final Creator<Backpack> CREATOR = new Creator<Backpack>() {
        @Override public Backpack createFromParcel(Parcel source) { return new Backpack(source); }
        @Override public Backpack[] newArray(int size) { return new Backpack[size]; }
    };
}
`

**Comment by SUPERCILEX** [comment]
I would guess that extending `RealmObject` is breaking things. Any reason to be using both Realm and Firebase? Seems like a weird combo. 😄

**Comment by samtstern** [comment]
Yeah that's definitely it, Realm must be using observable somewhere which is breaking us.  Not sure waht you can do besides create another plain object class like `BackpackPOJO` or something.

**Comment by CyberpunkPsychonaut** [comment]
I could probably create an inner pojo class and have a toPojo() method. Pretty much all of the user data doesn't need to be online and I like realm's interface for handling local database operations. I like the ecosystem Firebase offers but it, like all interfaces of its scale, naturally lacks in agility. I try to make the most of both technologies.

**Comment by samtstern** [comment]
@CyberpunkPsychonaut sounds good to me.  Going to close this issue since there's nothing we can do in `FirebaseUI-Android` but feel free to keep posting here if something goes wrong.
