### ISSUE TITLE
FirestoreRecyclerAdapter not working with LifecycleOwner

### ISSUE THREAD

**Issue by ChanSek** [firebase/FirebaseUI-Android#972]
* Android device: Moto G5s Plus
  * Android OS version: Android N 7.1.1
  * Google Play Services version: 3.1.0
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.0.0
  
Trying to use FirestoreRecyclerAdapter but getting ClassCastException if trying to use it with Architecture Components. Seems like it was working with previous versions of SDK.

Below is the code in my Activity class:

val query = FirebaseFirestore.getInstance().collection("<collection>")
            .document("<docId>")
            .collection("<subcollection>")
            .whereEqualTo("id", "<someId>")

val options = FirestoreRecyclerOptions.Builder<Pojo>().setQuery(query, Pojo::class.java)
            .setLifecycleOwner(this)
            .build()

recyclerView.adapter = MyAdapter(options, R.layout.some_xml)

But I am getting below exception:

`java.lang.ClassCastException: com.firebase.ui.firestore.FirestoreRecyclerAdapter_LifecycleAdapter cannot be cast to android.arch.lifecycle.GeneratedAdapter
                                                                                      at android.arch.lifecycle.Lifecycling.a(Lifecycling.java:79)
                                                                                      at android.arch.lifecycle.Lifecycling.a(Lifecycling.java:62)
                                                                                      at android.arch.lifecycle.LifecycleRegistry$ObserverWithState.<init>(LifecycleRegistry.java:319)
                                                                                      at android.arch.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:145)
                                                                                      at com.firebase.ui.firestore.FirestoreRecyclerAdapter.<init>(FirestoreRecyclerAdapter.java:37)`

This only happens when we do `setLifecycleOwner(this)` on FirestoreRecyclerOptions. Seems like in previous versions it was working fine.

**Comment by brezinajn** [comment]
Set your lifecycle dependency to beta1 `annotationProcessor "android.arch.lifecycle:compiler:1.0.0-beta1"` beta2 conflicts.

**Comment by ChanSek** [comment]
Does that mean, I have to use beta1 with Firestore?

**Comment by brezinajn** [comment]
Yes.

**Comment by TheCraftKid** [comment]
The library currently uses version 1.0.0-beta1 of Android Architecture Components and version 26.1.0 of the Android Support Libraries which implement the `LifecycleOwner` interfaces used in `setLifecycleOwner()`. Make sure you're using version 26.1.0 of the support libraries.

**Comment by SUPERCILEX** [comment]
Hmmm, we'll need to recompile the db modules—I thought Google was supposed to stop breaking stuff at beta. 😆 Anyway, if you're up to [setting up JitPack](https://jitpack.io/), you can add a custom version of FirebaseUI that I built until we release an official version with `beta2` bundled:
```groovy
implementation 'com.github.SUPERCILEX.FirebaseUI-Android:firebase-ui-firestore:9cc77708bd'
```

**Comment by samtstern** [comment]
Thanks all for helping to debug this.  I am going to close this issue since it can be fixed with different dependencies, thanks!

**Comment by b95505017** [comment]
I copied FirestoreRecyclerAdapter out to my project and let it implement [DefaultLifecycleObserver](https://developer.android.com/reference/android/arch/lifecycle/DefaultLifecycleObserver.html) so that I could use arch `1.0.0-rc1` & java8 env.

**Comment by SUPERCILEX** [comment]
@b95505017 Yeah, I'd like to somehow get FUI on Java 8, but I remember a failed experiment with @samtstern on EasyPermissions where we had to revert to Java 7 to support devs who haven't upgraded yet.

@samtstern what do you think our policy should be with Java 8? Should we wait until AGP 3.1 is released and then say everyone has to support Java 8? Or is everything already being compiled to Java 7 bytecode anyway and it should work now?

**Comment by samtstern** [comment]
@SUPERCILEX last time I tried what I learned (or what I think I learned) is that as soon as I set my source compatibility level to 8 I am mandating that folks who consume this library do the same.  If that's the case I'd say I have no plans to update to java 8 for years ... If I had to put my money on where the community will go I'd bet that we see a split into two main camps: Java 7 and Kotlin.

There's a chance though that there's a way for us to use Java 8 and allow Java 7 devs to consume the library.  If that's the case, sign me up.

**Comment by SUPERCILEX** [comment]
@samtstern Well crud, I thought you might have some magic solution up your sleeve... guess not. 😆

Prep for a great plug 😄: _speaking of Kotlin..._ are you open to that? I know you weren't so sure before, but I've been using Kotlin for a while now and I can tell you it's definitely worth it. I think it's far too late the refactor PR, but once that's done I'd like to add the dependency and convert our `ExtraConstants` file or something small like that to Kotlin. If you're worried about Java interop, I've got you covered—I'm very familiar with the bytecode decompiler so I know how most of Kotlin's syntactic sugar gets translated into Java. What do you think?

**Comment by samtstern** [comment]
I am certainly open to Kotlin in the project, and it's awesome that you have the knowledge because I am a n00b.

I'm excited to see the recording of the "Building Libraries in Kotlin" talk at Kotlinconf:
https://blog.jetbrains.com/kotlin/2017/09/kotlinconf-new-workshop-and-community-event-by-jetbrains-and-realm/

But in general I agree, Kotlin is great and we should use it where we can.

**Comment by SUPERCILEX** [comment]
@samtstern AWESOME!!! 😆 Cool talk BTW, that's when I wish I could live in SF. Hopefully Realm will record some of it.
