### ISSUE TITLE
Facebook SDK 4.27.0 Issue - WebDialog

### ISSUE THREAD

**Issue by kalehv** [firebase/FirebaseUI-Android#976]
### Environment
  * Android device: Emulator
  * Android OS version: 8.0.0
  * Google Play Services version: 11.5.09 (on Emulator)
  * Firebase/Play Services SDK version: 11.4.2
  * FirebaseUI version: 3.0.0
  * Facebook SDK Version: 4.27.0
  
I upgraded my firebase-ui dependency to 3.0.0 and Facebook-SDK to 4.27.0
``` gradle
    // Firebase UI
    implementation "com.firebaseui:firebase-ui-database:3.0.0"
    implementation "com.firebaseui:firebase-ui-auth:3.0.0"

    // Facebook Login
    implementation "com.facebook.android:facebook-android-sdk:4.27.0"
```
I looked into the `FacebookProvider.java` class and it does have updated code from https://github.com/firebase/FirebaseUI-Android/pull/929
``` java
WebDialog.setWebDialogTheme(theme);
```
Not sure what I need to do. Please help.
  
#### Observed Results:

```
java.lang.NoSuchMethodError: No static method setWebDialogTheme(I)V in class Lcom/facebook/internal/WebDialog; or its super classes
```
  
#### Expected Results:

  * App compiles and runs without this error

**Comment by kalehv** [comment]
I placed a breakpoint in `FacebookProvider.java` and seems it's consuming new code now. No other action was necessary.

**Comment by lalo2302** [comment]
Hi! I am having this exact problem. Could you give more details about your solution?

Thank you.

**Comment by SUPERCILEX** [comment]
@lalo2302 make sure to be using FirebaseUI 3.1 and `com.facebook.android:`**`facebook-login`**`:4.27.0`. Also try cleaning your cache.

**Comment by lalo2302** [comment]
I was using an outdated version of firebase ui. Thank you very much.
