### ISSUE TITLE
How to define property in json which is inconsistent, Android

### ISSUE THREAD

**Issue by SahajRana** [firebase/FirebaseUI-Android#99]
I was trying to use firebaseuiRecyclerView in which the property of json is inconsistent ie It keeps on changing for each user, so i wanted to know is there any way to define property which can change (n ya it would be in database.)

The situation is that property UserID is inconsistent as it would be differnt for every user

`public class FriendsData {`
`String picurl;`
`String userNAME;`
`String status;`
`String sahaj;`
`String UserID;`
`Map<String, Boolean> emails = new HashMap<>();`
`public String getSahaj() {`
 `   return sahaj;`
`}`
`public void setSahaj(String sahaj) {`
`    this.sahaj = sahaj;`
`}`
`public Map<String, Boolean> getEmails() {`
    `return emails;`
`}`

`public void setEmails(Map<String, Boolean> emails) {`
   ` this.emails = emails;`
`}`

`public FriendsData(){`
    `emails.put("sahaj9917730102@gmail", true);`
`}`

`public String getPicurl() {
    return picurl;
}`

`public void setPicurl(String picurl) {
    this.picurl = picurl;
}`

`public String getUserNAME() {
    return userNAME;
}`

`public void setUserNAME(String userNAME) {
    this.userNAME = userNAME;
}`

`public String getStatus() {
    return status;
}`

`public void setStatus(String status) {
    this.status = status;`
`}`

`}`

It's like this
` { "randomlygeneratedKeyname0" : "some-  value",
  "randomlygeneratedKeyname1": {
   "randomlygeneratedKeyname2" : {
       "randomlygeneratedKeyname3":         "some-value",
       "randomlygeneratedKeyname4": "some-value"
   },
   "randomlygeneratedKeyname5": {
       "randomlygeneratedKeyname6": "some-value",
       "randomlygeneratedKeyname7":           "some-value"
   }
} `

Notes that I don't know the name of randomlygeneratedKeyname and their naming convention is inconsistent so I could not create my corresponding Java field/variable names.

So how to define the Inconsistent variable in friendsData class

**Comment by puf** [comment]
Cross-post from http://stackoverflow.com/questions/36227295/, where it is better suited.
