### ISSUE TITLE
How Can join two table in Firebase Ui

### ISSUE THREAD

**Issue by junoprima** [firebase/FirebaseUI-Android#990]
![image](https://user-images.githubusercontent.com/29189180/31852878-f0baf3b2-b6a9-11e7-9bcf-fda15e1812c2.png)

From this photo i'm query report and get all but on rp_author i need get user_fname from table User

and i see try FirebaseIndexRecyclerAdapter i dont understand this can someone show me a sample how to do like this

**Comment by samtstern** [comment]
@junoprima this activity has an example of how to use indexed data:
https://github.com/firebase/FirebaseUI-Android/blob/master/app/src/main/java/com/firebase/uidemo/database/realtime/RealtimeDbChatIndexActivity.java

And this section of the docs describes it as well:
https://github.com/firebase/FirebaseUI-Android/tree/master/database#using-firebaseui-with-indexed-data

**Comment by junoprima** [comment]
In this case why i cant use FirebaseRecyclerOption  it cant import and anything

**Comment by samtstern** [comment]
@junoprima make sure you're using version `3.0.0` or higher of the FirebaseUI libraries.

**Comment by junoprima** [comment]
@samtstern  Thx a lot sir i got this

**Comment by samtstern** [comment]
@junoprima glad you solved it! Closing this issue.

**Comment by rushapushp** [comment]
похуй
