### ISSUE TITLE
FirebaseListOption

### ISSUE THREAD

**Issue by CuspMe** [firebase/FirebaseUI-Android#995]
https://stackoverflow.com/questions/46912532/android-using-firebaseui-with-firebaselistoptions-to-populate-a-listview-doesnt

**Comment by SUPERCILEX** [comment]
See https://stackoverflow.com/a/46997383/4548500

**Comment by samtstern** [comment]
I believe @SUPERCILEX has answered this on StackOverflow, closing here.
