### ISSUE TITLE
Build fail after migration to plugin 3.0.0 and supportversion 27.0.0

### ISSUE THREAD

**Issue by Hypercruse** [firebase/FirebaseUI-Android#996]
Since i changed to Android Studio 3.0, Gradle Plugin Version 3.0.0 and supportLibraryVersion 27.0.0 my build keeps failing because some style attributes are not found. Im using compileSdkVersion 27, buildToolsVersion 27.0.0 and minSdkVersion 17.
Error in Messages:
![unbenannt](https://user-images.githubusercontent.com/29468072/32147985-341e58fa-bcf0-11e7-8de1-95f4c20409b7.JPG)
Repositories:
![unbenannt](https://user-images.githubusercontent.com/29468072/32147897-cf18ca4a-bcee-11e7-9ab2-e76c010a6c98.JPG)
Versions:
![unbenannt](https://user-images.githubusercontent.com/29468072/32147899-e8a4a9de-bcee-11e7-93f5-ad66d25ce642.JPG)
Implementations:
![unbenannt](https://user-images.githubusercontent.com/29468072/32147914-287b1796-bcef-11e7-8830-2319c7479783.JPG)

If i jump to the source of the first error i jump into some firebaseui values file but i cant figure out what to change to be able to build the project again. I really hope that im at the right place to ask for help here. I tried to solve the problem myself for quite some time but didnt find anything that helped. Thanks in advance!

**Comment by SUPERCILEX** [comment]
I have no problems with 27 and 3.0. Try deleting the `.gradle` folder in your project's directory to force a full cache refresh (`./gradlew clean` doesn't always fix things from my experience).

**Comment by Hypercruse** [comment]
Nope that didnt help either. Same problems as before

**Comment by SUPERCILEX** [comment]
Oh wait, actually it's probably because you're excluding `support-v4`. I don't think you should be doing that.

**Comment by Hypercruse** [comment]
Thats from one of my tries to fix it (read it in some stackoverflow thread), just removed it and there are still the same problems

**Comment by SUPERCILEX** [comment]
Hmmm, ok that's really weird. Could you try using my custom fork insead?
```groovy
implementation "com.github.SUPERCILEX.FirebaseUI-Android:firebase-ui-auth:08a7a28219"
```

I swear I didn't change anything, but if my fork works I'll have to figure what changed from master.

**Comment by Hypercruse** [comment]
Im really sorry but that doesnt work either. Same problems, just another filename at the top of the problem stack

**Comment by SUPERCILEX** [comment]
Huh, I'm not sure what to say. Something has gone very wrong somewhere along the line. I would just copy your project, delete all the `build` folders, the `.gradle` folder, and the `.idea` folder, then re-import it into Android Studio since it doesn't appear to be a FirebaseUI issue.

**Comment by Hypercruse** [comment]
Well that didnt help, but i just used an old version and didnt upgrade it to 3.0 gradle then its working again, weird. But thanks for your time anyway!
