### ISSUE TITLE
Signout from Fragment or non-activity class

### ISSUE THREAD

**Issue by kidokimo** [firebase/FirebaseUI-Android#997]
Hi There, 

I am trying to use this sign out method just to be able to add an OnCompleteListener to the sign out process But it asks for a FragmentActivity and i am calling it from inside a fragment (this fragment is called by an AppCompatAcivity).. Here is the code

     AuthUI.getInstance() .signOut(getActivity()) // this is the issue
                            .addOnCompleteListener(new OnCompleteListener<Void>() {
                                public void onComplete(@NonNull Task<Void> task) {
                                    // user is now signed out
                                  
                                }
                            });

All what i need is one of the following:
1. How to pass the correct context knowing that i am calling this method inside a Fragment (this fragment is called by an AppCompatActivity)
2. is there any other method to have an OnCompleteListener to the sign out process from inside a fragment or a non-activity class ?

Thanks in advance

**Comment by SUPERCILEX** [comment]
`AppCompatActvity` actually extends `FragmentActivity` so everything should compile just fine. Is something not working?

**Comment by SUPERCILEX** [comment]
@samtstern @kidokimo This is fixed in FUI `v3.1.1`. Enjoy!
